package com.acuteterror233.mite.datagen;

import com.acuteterror233.mite.block.AtBlocks;
import com.acuteterror233.mite.registry.tag.AtTags;
import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricTagProvider;
import net.minecraft.block.Blocks;
import net.minecraft.registry.RegistryWrapper;
import net.minecraft.registry.tag.BlockTags;

import java.util.concurrent.CompletableFuture;

public class BlockTagProvider extends FabricTagProvider.BlockTagProvider {
    public BlockTagProvider(FabricDataOutput output, CompletableFuture<RegistryWrapper.WrapperLookup> registriesFuture) {
        super(output, registriesFuture);
    }

    @Override
    protected void configure(RegistryWrapper.WrapperLookup wrapperLookup) {
        getOrCreateTagBuilder(BlockTags.DOORS)
                .add(AtBlocks.GOLDEN_DOOR)
                .add(AtBlocks.SILVER_DOOR)
                .add(AtBlocks.MITHRIL_DOOR)
                .add(AtBlocks.ANCIENT_METAL_DOOR)
                .add(AtBlocks.ADAMANTIUM_DOOR);
        getOrCreateTagBuilder(AtTags.GLASS)
                .add(Blocks.GLASS)
                .add(Blocks.WHITE_STAINED_GLASS)
                .add(Blocks.ORANGE_STAINED_GLASS)
                .add(Blocks.MAGENTA_STAINED_GLASS)
                .add(Blocks.LIGHT_BLUE_STAINED_GLASS)
                .add(Blocks.YELLOW_STAINED_GLASS)
                .add(Blocks.LIME_STAINED_GLASS)
                .add(Blocks.PINK_STAINED_GLASS)
                .add(Blocks.GRAY_STAINED_GLASS)
                .add(Blocks.LIGHT_GRAY_STAINED_GLASS)
                .add(Blocks.CYAN_STAINED_GLASS)
                .add(Blocks.PURPLE_STAINED_GLASS)
                .add(Blocks.BLUE_STAINED_GLASS)
                .add(Blocks.BROWN_STAINED_GLASS)
                .add(Blocks.GREEN_STAINED_GLASS)
                .add(Blocks.RED_STAINED_GLASS)
                .add(Blocks.BLACK_STAINED_GLASS)
                .add(Blocks.TINTED_GLASS);
        getOrCreateTagBuilder(AtTags.GLASS_PANE)
                .add(Blocks.GLASS_PANE)
                .add(Blocks.WHITE_STAINED_GLASS_PANE)
                .add(Blocks.ORANGE_STAINED_GLASS_PANE)
                .add(Blocks.MAGENTA_STAINED_GLASS_PANE)
                .add(Blocks.LIGHT_BLUE_STAINED_GLASS_PANE)
                .add(Blocks.YELLOW_STAINED_GLASS_PANE)
                .add(Blocks.LIME_STAINED_GLASS_PANE)
                .add(Blocks.PINK_STAINED_GLASS_PANE)
                .add(Blocks.GRAY_STAINED_GLASS_PANE)
                .add(Blocks.LIGHT_GRAY_STAINED_GLASS_PANE)
                .add(Blocks.CYAN_STAINED_GLASS_PANE)
                .add(Blocks.PURPLE_STAINED_GLASS_PANE)
                .add(Blocks.BLUE_STAINED_GLASS_PANE)
                .add(Blocks.BROWN_STAINED_GLASS_PANE)
                .add(Blocks.GREEN_STAINED_GLASS_PANE)
                .add(Blocks.RED_STAINED_GLASS_PANE)
                .add(Blocks.BLACK_STAINED_GLASS_PANE);
        getOrCreateTagBuilder(AtTags.BARS)
                .add(Blocks.IRON_BARS)
                .add(AtBlocks.ADAMANTIUM_BARS)
                .add(AtBlocks.ANCIENT_METAL_BARS)
                .add(AtBlocks.GOLDEN_BARS)
                .add(AtBlocks.MITHRIL_BARS)
                .add(AtBlocks.SILVER_BARS)
                .add(AtBlocks.COPPER_BARS);
        getOrCreateTagBuilder(BlockTags.ANVIL)
                .add(AtBlocks.ADAMANTIUM_ANVIL)
                .add(AtBlocks.CHIPPED_ADAMANTIUM_ANVIL)
                .add(AtBlocks.DAMAGED_ADAMANTIUM_ANVIL)
                .add(AtBlocks.MITHRIL_ANVIL)
                .add(AtBlocks.CHIPPED_MITHRIL_ANVIL)
                .add(AtBlocks.DAMAGED_MITHRIL_ANVIL)
                .add(AtBlocks.ANCIENT_METAL_ANVIL)
                .add(AtBlocks.CHIPPED_ANCIENT_METAL_ANVIL)
                .add(AtBlocks.DAMAGED_ANCIENT_METAL_ANVIL)
                .add(AtBlocks.SILVER_ANVIL)
                .add(AtBlocks.CHIPPED_SILVER_ANVIL)
                .add(AtBlocks.DAMAGED_SILVER_ANVIL)
                .add(AtBlocks.GOLDEN_ANVIL)
                .add(AtBlocks.CHIPPED_GOLDEN_ANVIL)
                .add(AtBlocks.DAMAGED_GOLDEN_ANVIL)
                .add(AtBlocks.COPPER_ANVIL)
                .add(AtBlocks.CHIPPED_COPPER_ANVIL)
                .add(AtBlocks.DAMAGED_COPPER_ANVIL);
        getOrCreateTagBuilder(AtTags.INTACT_ANVIL)
                .add(AtBlocks.ADAMANTIUM_ANVIL)
                .add(AtBlocks.MITHRIL_ANVIL)
                .add(AtBlocks.ANCIENT_METAL_ANVIL)
                .add(AtBlocks.SILVER_ANVIL)
                .add(AtBlocks.GOLDEN_ANVIL)
                .add(AtBlocks.COPPER_ANVIL);
        getOrCreateTagBuilder(AtTags.CHIPPED_ANVIL)
                .add(AtBlocks.CHIPPED_ADAMANTIUM_ANVIL)
                .add(AtBlocks.CHIPPED_MITHRIL_ANVIL)
                .add(AtBlocks.CHIPPED_ANCIENT_METAL_ANVIL)
                .add(AtBlocks.CHIPPED_SILVER_ANVIL)
                .add(AtBlocks.CHIPPED_GOLDEN_ANVIL)
                .add(AtBlocks.CHIPPED_COPPER_ANVIL);
        getOrCreateTagBuilder(AtTags.DAMAGED_ANVIL)
                .add(AtBlocks.DAMAGED_ADAMANTIUM_ANVIL)
                .add(AtBlocks.DAMAGED_MITHRIL_ANVIL)
                .add(AtBlocks.DAMAGED_ANCIENT_METAL_ANVIL)
                .add(AtBlocks.DAMAGED_SILVER_ANVIL)
                .add(AtBlocks.DAMAGED_GOLDEN_ANVIL)
                .add(AtBlocks.DAMAGED_COPPER_ANVIL);
        getOrCreateTagBuilder(AtTags.ADAMANTIUM_ANVIL)
                .add(AtBlocks.ADAMANTIUM_ANVIL)
                .add(AtBlocks.CHIPPED_ADAMANTIUM_ANVIL)
                .add(AtBlocks.DAMAGED_ADAMANTIUM_ANVIL);
        getOrCreateTagBuilder(AtTags.MITHRIL_ANVIL)
                .add(AtBlocks.MITHRIL_ANVIL)
                .add(AtBlocks.CHIPPED_MITHRIL_ANVIL)
                .add(AtBlocks.DAMAGED_MITHRIL_ANVIL);
        getOrCreateTagBuilder(AtTags.ANCIENT_METAL_ANVIL)
                .add(AtBlocks.ANCIENT_METAL_ANVIL)
                .add(AtBlocks.CHIPPED_ANCIENT_METAL_ANVIL)
                .add(AtBlocks.DAMAGED_ANCIENT_METAL_ANVIL);
        getOrCreateTagBuilder(AtTags.SILVER_ANVIL)
                .add(AtBlocks.SILVER_ANVIL)
                .add(AtBlocks.CHIPPED_SILVER_ANVIL)
                .add(AtBlocks.DAMAGED_SILVER_ANVIL);
        getOrCreateTagBuilder(AtTags.GOLDEN_ANVIL)
                .add(AtBlocks.GOLDEN_ANVIL)
                .add(AtBlocks.CHIPPED_GOLDEN_ANVIL)
                .add(AtBlocks.DAMAGED_GOLDEN_ANVIL);
        getOrCreateTagBuilder(AtTags.COPPER_ANVIL)
                .add(AtBlocks.COPPER_ANVIL)
                .add(AtBlocks.CHIPPED_COPPER_ANVIL)
                .add(AtBlocks.DAMAGED_COPPER_ANVIL);
        getOrCreateTagBuilder(AtTags.IRON_ANVIL)
                .add(Blocks.ANVIL)
                .add(Blocks.CHIPPED_ANVIL)
                .add(Blocks.DAMAGED_ANVIL);
        getOrCreateTagBuilder(AtTags.PORTAL)
                .add(AtBlocks.UNDERGROUND_PORTAL)
                .add(AtBlocks.HOME_PORTAL)
                .add(AtBlocks.RUNE_PORTAL)
                .add(Blocks.NETHER_PORTAL);
        getOrCreateTagBuilder(AtTags.MITHRIL_RUNESTORE)
                .add(AtBlocks.MITHRIL_NUL_RUNESTORE)
                .add(AtBlocks.MITHRIL_QUAS_RUNESTORE)
                .add(AtBlocks.MITHRIL_POR_RUNESTORE)
                .add(AtBlocks.MITHRIL_AN_RUNESTORE)
                .add(AtBlocks.MITHRIL_NOX_RUNESTORE)
                .add(AtBlocks.MITHRIL_FLAM_RUNESTORE)
                .add(AtBlocks.MITHRIL_VAS_RUNESTORE)
                .add(AtBlocks.MITHRIL_DES_RUNESTORE)
                .add(AtBlocks.MITHRIL_ORT_RUNESTORE)
                .add(AtBlocks.MITHRIL_TYM_RUNESTORE)
                .add(AtBlocks.MITHRIL_CORP_RUNESTORE)
                .add(AtBlocks.MITHRIL_LOR_RUNESTORE)
                .add(AtBlocks.MITHRIL_MANI_RUNESTORE)
                .add(AtBlocks.MITHRIL_JUX_RUNESTORE)
                .add(AtBlocks.MITHRIL_YLEM_RUNESTORE)
                .add(AtBlocks.MITHRIL_SANCT_RUNESTORE);
        getOrCreateTagBuilder(AtTags.ADAMANTIUM_RUNESTORE)
                .add(AtBlocks.ADAMANTIUM_NUL_RUNESTORE)
                .add(AtBlocks.ADAMANTIUM_QUAS_RUNESTORE)
                .add(AtBlocks.ADAMANTIUM_POR_RUNESTORE)
                .add(AtBlocks.ADAMANTIUM_AN_RUNESTORE)
                .add(AtBlocks.ADAMANTIUM_NOX_RUNESTORE)
                .add(AtBlocks.ADAMANTIUM_FLAM_RUNESTORE)
                .add(AtBlocks.ADAMANTIUM_VAS_RUNESTORE)
                .add(AtBlocks.ADAMANTIUM_DES_RUNESTORE)
                .add(AtBlocks.ADAMANTIUM_ORT_RUNESTORE)
                .add(AtBlocks.ADAMANTIUM_TYM_RUNESTORE)
                .add(AtBlocks.ADAMANTIUM_CORP_RUNESTORE)
                .add(AtBlocks.ADAMANTIUM_LOR_RUNESTORE)
                .add(AtBlocks.ADAMANTIUM_MANI_RUNESTORE)
                .add(AtBlocks.ADAMANTIUM_JUX_RUNESTORE)
                .add(AtBlocks.ADAMANTIUM_YLEM_RUNESTORE)
                .add(AtBlocks.ADAMANTIUM_SANCT_RUNESTORE);
        getOrCreateTagBuilder(AtTags.RUNESTORE)
                .forceAddTag(AtTags.ADAMANTIUM_RUNESTORE)
                .forceAddTag(AtTags.MITHRIL_RUNESTORE);
        getOrCreateTagBuilder(AtTags.CRAFTING_TABLE)
                .add(AtBlocks.ADAMANTIUM_CRAFTING_TABLE)
                .add(AtBlocks.MITHRIL_CRAFTING_TABLE)
                .add(AtBlocks.ANCIENT_METAL_CRAFTING_TABLE)
                .add(AtBlocks.IRON_CRAFTING_TABLE)
                .add(AtBlocks.GOLD_CRAFTING_TABLE)
                .add(AtBlocks.SILVER_CRAFTING_TABLE)
                .add(AtBlocks.COPPER_CRAFTING_TABLE)
                .add(AtBlocks.OBSIDIAN_CRAFTING_TABLE)
                .add(AtBlocks.FLINT_CRAFTING_TABLE);

        getOrCreateTagBuilder(AtTags.NEEDS_ADAMANTIUM_TOOL)
                .add(Blocks.ANCIENT_DEBRIS)
                .add(Blocks.NETHERITE_BLOCK)
                .add(AtBlocks.ADAMANTIUM_BLOCK)
                .add(AtBlocks.ADAMANTIUM_BARS)
                .add(AtBlocks.ADAMANTIUM_DOOR);
        getOrCreateTagBuilder(AtTags.NEEDS_MITHRIL_TOOL)
                .add(AtBlocks.MITHRIL_BLOCK)
                .add(AtBlocks.MITHRIL_BARS)
                .add(AtBlocks.MITHRIL_DOOR)
                .add(AtBlocks.ADAMANTIUM_ORE)
                .add(AtBlocks.DEEPSLATE_ADAMANTIUM_ORE);
        getOrCreateTagBuilder(AtTags.NEEDS_ANCIENT_METAL_TOOL)
                .add(AtBlocks.ANCIENT_METAL_BLOCK)
                .add(AtBlocks.ANCIENT_METAL_BARS);
        getOrCreateTagBuilder(BlockTags.NEEDS_IRON_TOOL)
                .add(AtBlocks.MITHRIL_ORE)
                .add(AtBlocks.DEEPSLATE_MITHRIL_ORE);
        getOrCreateTagBuilder(AtTags.NEEDS_SILVER_OR_COPPER_TOOL)
                .add(AtBlocks.SILVER_BLOCK)
                .add(AtBlocks.SILVER_BARS)
                .add(AtBlocks.SILVER_DOOR)
                .add(Blocks.COPPER_BLOCK)
                .add(AtBlocks.COPPER_BARS)
                .forceAddTag(BlockTags.COPPER_ORES);

        getOrCreateTagBuilder(AtTags.INCORRECT_FOR_FLINT_OR_OBSIDIAN_TOOL)
                .forceAddTag(AtTags.NEEDS_SILVER_OR_COPPER_TOOL)
                .forceAddTag(AtTags.NEEDS_ANCIENT_METAL_TOOL)
                .forceAddTag(AtTags.NEEDS_MITHRIL_TOOL)
                .forceAddTag(AtTags.NEEDS_ADAMANTIUM_TOOL)
                .forceAddTag(BlockTags.NEEDS_DIAMOND_TOOL)
                .forceAddTag(BlockTags.NEEDS_IRON_TOOL)
                .forceAddTag(BlockTags.NEEDS_STONE_TOOL);
        getOrCreateTagBuilder(AtTags.INCORRECT_FOR_COPPER_OR_SILVER_TOOL)
                .forceAddTag(BlockTags.NEEDS_IRON_TOOL)
                .forceAddTag(BlockTags.NEEDS_DIAMOND_TOOL)
                .forceAddTag(AtTags.NEEDS_ANCIENT_METAL_TOOL)
                .forceAddTag(AtTags.NEEDS_MITHRIL_TOOL)
                .forceAddTag(AtTags.NEEDS_ADAMANTIUM_TOOL);
        getOrCreateTagBuilder(AtTags.INCORRECT_FOR_RUSTED_IRON_TOOL)
                .forceAddTag(AtTags.NEEDS_ANCIENT_METAL_TOOL)
                .forceAddTag(AtTags.NEEDS_MITHRIL_TOOL)
                .forceAddTag(AtTags.NEEDS_ADAMANTIUM_TOOL);
        getOrCreateTagBuilder(AtTags.INCORRECT_FOR_ANCIENT_METAL_TOOL)
                .forceAddTag(AtTags.NEEDS_MITHRIL_TOOL)
                .forceAddTag(AtTags.NEEDS_ADAMANTIUM_TOOL);
        getOrCreateTagBuilder(AtTags.INCORRECT_FOR_MITHRIL_TOOL)
                .forceAddTag(AtTags.NEEDS_ADAMANTIUM_TOOL);
        getOrCreateTagBuilder(AtTags.INCORRECT_FOR_ADAMANTIUM_TOOL);

        getOrCreateTagBuilder(BlockTags.PICKAXE_MINEABLE)
                .add(AtBlocks.ADAMANTIUM_ORE)
                .add(AtBlocks.DEEPSLATE_ADAMANTIUM_ORE)
                .add(AtBlocks.MITHRIL_ORE)
                .add(AtBlocks.DEEPSLATE_MITHRIL_ORE)
                .add(AtBlocks.SILVER_ORE)
                .add(AtBlocks.DEEPSLATE_SILVER_ORE)
                .add(AtBlocks.ADAMANTIUM_BARS)
                .add(AtBlocks.MITHRIL_BARS)
                .add(AtBlocks.ANCIENT_METAL_BARS)
                .add(AtBlocks.GOLDEN_BARS)
                .add(AtBlocks.SILVER_BARS)
                .add(AtBlocks.COPPER_BARS)
                .add(AtBlocks.ADAMANTIUM_BLOCK)
                .add(AtBlocks.ANCIENT_METAL_BLOCK)
                .add(AtBlocks.MITHRIL_BLOCK)
                .add(AtBlocks.SILVER_BLOCK)
                .add(AtBlocks.ADAMANTIUM_DOOR)
                .add(AtBlocks.ANCIENT_METAL_DOOR)
                .add(AtBlocks.MITHRIL_DOOR)
                .add(AtBlocks.SILVER_DOOR)
                .add(AtBlocks.GOLDEN_DOOR);
    }
}
