package com.acuteterror233.mite.datagen;

import com.acuteterror233.mite.item.At_Items;
import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricLanguageProvider;
import net.minecraft.registry.RegistryWrapper;

import java.util.concurrent.CompletableFuture;

public class En_usLanguageProvider extends FabricLanguageProvider {

    public En_usLanguageProvider(FabricDataOutput dataOutput, CompletableFuture<RegistryWrapper.WrapperLookup> registryLookup) {
        super(dataOutput, "en_us", registryLookup);
    }

    @Override
    public void generateTranslations(RegistryWrapper.WrapperLookup registryLookup, TranslationBuilder translationBuilder) {
        translationBuilder.add("itemGroup.at_mite.item_group","Minecraft is too easy!");
        translationBuilder.add(At_Items.ADAMANTIUM_HELMET,"Adamantium Helmet");
        translationBuilder.add(At_Items.ADAMANTIUM_CHESTPLATE,"Adamantium Chestplate");
        translationBuilder.add(At_Items.ADAMANTIUM_LEGGINGS,"Adamantium Leggings");
        translationBuilder.add(At_Items.ADAMANTIUM_BOOTS,"Adamantium Boots");
        translationBuilder.add(At_Items.ADAMANTIUM_CHAINMAIL_HELMET,"Adamantium Chainmail Helmet");
        translationBuilder.add(At_Items.ADAMANTIUM_CHAINMAIL_CHESTPLATE,"Adamantium Chainmail Chestplate");
        translationBuilder.add(At_Items.ADAMANTIUM_CHAINMAIL_LEGGINGS,"Adamantium Chainmail Leggings");
        translationBuilder.add(At_Items.ADAMANTIUM_CHAINMAIL_BOOTS,"Adamantium Chainmail Boots");
        translationBuilder.add(At_Items.ANCIENT_METAL_HELMET,"Ancient Metal Helmet");
        translationBuilder.add(At_Items.ANCIENT_METAL_CHESTPLATE,"Ancient Metal Chestplate");
        translationBuilder.add(At_Items.ANCIENT_METAL_LEGGINGS,"Ancient Metal Leggings");
        translationBuilder.add(At_Items.ANCIENT_METAL_BOOTS,"Ancient Metal Boots");
        translationBuilder.add(At_Items.ANCIENT_METAL_CHAINMAIL_HELMET,"Ancient Metal Chainmail Helmet");
        translationBuilder.add(At_Items.ANCIENT_METAL_CHAINMAIL_CHESTPLATE,"Ancient Metal Chainmail Chestplate");
        translationBuilder.add(At_Items.ANCIENT_METAL_CHAINMAIL_LEGGINGS,"Ancient Metal Chainmail Leggings");
        translationBuilder.add(At_Items.ANCIENT_METAL_CHAINMAIL_BOOTS,"Ancient Metal Chainmail Boots");
        translationBuilder.add(At_Items.COPPER_HELMET,"Copper Helmet");
        translationBuilder.add(At_Items.COPPER_CHESTPLATE,"Copper Chestplate");
        translationBuilder.add(At_Items.COPPER_LEGGINGS,"Copper Leggings");
        translationBuilder.add(At_Items.COPPER_BOOTS,"Copper Boots");
        translationBuilder.add(At_Items.COPPER_CHAINMAIL_HELMET,"Copper Chainmail Helmet");
        translationBuilder.add(At_Items.COPPER_CHAINMAIL_CHESTPLATE,"Copper Chainmail Chestplate");
        translationBuilder.add(At_Items.COPPER_CHAINMAIL_LEGGINGS,"Copper Chainmail Leggings");
        translationBuilder.add(At_Items.MITHRIL_HELMET, "Mithril Helmet");
        translationBuilder.add(At_Items.MITHRIL_CHESTPLATE, "Mithril Chestplate");
        translationBuilder.add(At_Items.MITHRIL_LEGGINGS, "Mithril Leggings");
        translationBuilder.add(At_Items.MITHRIL_BOOTS, "Mithril Boots");
        translationBuilder.add(At_Items.MITHRIL_CHAINMAIL_HELMET, "Mithril Chainmail Helmet");
        translationBuilder.add(At_Items.MITHRIL_CHAINMAIL_CHESTPLATE, "Mithril Chainmail Chestplate");
        translationBuilder.add(At_Items.MITHRIL_CHAINMAIL_LEGGINGS, "Mithril Chainmail Leggings");
        translationBuilder.add(At_Items.MITHRIL_CHAINMAIL_BOOTS, "Mithril Chainmail Boots");
        translationBuilder.add(At_Items.RUSTED_IRON_HELMET, "Rusted Iron Helmet");
        translationBuilder.add(At_Items.RUSTED_IRON_CHESTPLATE, "Rusted Iron Chestplate");
        translationBuilder.add(At_Items.RUSTED_IRON_LEGGINGS, "Rusted Iron Leggings");
        translationBuilder.add(At_Items.RUSTED_IRON_BOOTS, "Rusted Iron Boots");
        translationBuilder.add(At_Items.RUSTED_IRON_CHAINMAIL_HELMET, "Rusted Iron Chainmail Helmet");
        translationBuilder.add(At_Items.RUSTED_IRON_CHAINMAIL_CHESTPLATE, "Rusted Iron Chainmail Chestplate");
        translationBuilder.add(At_Items.RUSTED_IRON_CHAINMAIL_LEGGINGS, "Rusted Iron Chainmail Leggings");
        translationBuilder.add(At_Items.RUSTED_IRON_CHAINMAIL_BOOTS, "Rusted Iron Chainmail Boots");
        translationBuilder.add(At_Items.SILVER_HELMET, "Silver Helmet");
        translationBuilder.add(At_Items.SILVER_CHESTPLATE, "Silver Chestplate");
        translationBuilder.add(At_Items.SILVER_LEGGINGS, "Silver Leggings");
        translationBuilder.add(At_Items.SILVER_BOOTS, "Silver Boots");
        translationBuilder.add(At_Items.SILVER_CHAINMAIL_HELMET, "Silver Chainmail Helmet");
        translationBuilder.add(At_Items.SILVER_CHAINMAIL_CHESTPLATE, "Silver Chainmail Chestplate");
        translationBuilder.add(At_Items.SILVER_CHAINMAIL_LEGGINGS, "Silver Chainmail Leggings");
        translationBuilder.add(At_Items.SILVER_CHAINMAIL_BOOTS, "Silver Chainmail Boots");

        translationBuilder.add(At_Items.BANANA, "Banana");
        translationBuilder.add(At_Items.BLUEBERRIE, "Blueberry");
        translationBuilder.add(At_Items.CHEESE, "Cheese");
        translationBuilder.add(At_Items.CHOCOLATE, "Chocolate");
        translationBuilder.add(At_Items.DOUGH, "Dough");
        translationBuilder.add(At_Items.ONION, "Onion");
        translationBuilder.add(At_Items.LEMON, "Lemon");
        translationBuilder.add(At_Items.ORANGE, "Orange");
        translationBuilder.add(At_Items.WORM_COOKED, "Worm Cooked");
        translationBuilder.add(At_Items.WORM_RAW, "Worm Raw");
        translationBuilder.add(At_Items.BEEF_STEW, "Beef Stew");
        translationBuilder.add(At_Items.BOWL_MILK, "Bowl of Milk");
        translationBuilder.add(At_Items.BOWL_SALAD, "Bowl of Salad");
        translationBuilder.add(At_Items.BOWL_WATER, "Bowl of Water");
        translationBuilder.add(At_Items.CEREAL, "Cereal");
        translationBuilder.add(At_Items.CHICKEN_SOUP, "Chicken Soup");
        translationBuilder.add(At_Items.CREAM_OF_MUSHROOM_SOUP, "Cream of Mushroom Soup");
        translationBuilder.add(At_Items.CREAM_OF_VEGETABLE_SOUP, "Cream of Vegetable Soup");
        translationBuilder.add(At_Items.ICE_CREAM, "Ice Cream");
        translationBuilder.add(At_Items.MASHED_POTATO, "Mashed Potato");
        translationBuilder.add(At_Items.MUSHROOM_STEW, "Mushroom Stew");
        translationBuilder.add(At_Items.PORRIDGE, "Porridge");
        translationBuilder.add(At_Items.PUMPKIN_SOUP, "Pumpkin Soup");
        translationBuilder.add(At_Items.SORBET, "Sorbet");
        translationBuilder.add(At_Items.VEGETABLE_SOUP, "Vegetable Soup");

        translationBuilder.add(At_Items.ADAMANTIUM_ARROW, "Adamantium Arrow");
        translationBuilder.add(At_Items.ANCIENT_METAL_ARROW, "Ancient Metal Arrow");
        translationBuilder.add(At_Items.COPPER_ARROW, "Copper Arrow");
        translationBuilder.add(At_Items.MITHRIL_ARROW, "Mithril Arrow");
        translationBuilder.add(At_Items.RUSTED_IRON_ARROW, "Rusted Iron Arrow");
        translationBuilder.add(At_Items.SILVER_ARROW, "Silver Arrow");
        translationBuilder.add(At_Items.FLINT_ARROW, "Flint Arrow");
        translationBuilder.add(At_Items.GOLD_ARROW, "Gold Arrow");
        translationBuilder.add(At_Items.IRON_ARROW, "Iron Arrow");
        translationBuilder.add(At_Items.OBSIDIAN_ARROW, "Obsidian Arrow");
        translationBuilder.add(At_Items.ADAMANTIUM_CHAINS, "Adamantium Chains");
        translationBuilder.add(At_Items.ANCIENT_METAL_CHAINS, "Ancient Metal Chains");
        translationBuilder.add(At_Items.COPPER_CHAINS, "Copper Chains");
        translationBuilder.add(At_Items.MITHRIL_CHAINS, "Mithril Chains");
        translationBuilder.add(At_Items.RUSTED_IRON_CHAINS, "Rusted Iron Chains");
        translationBuilder.add(At_Items.SILVER_CHAINS, "Silver Chains");
        translationBuilder.add(At_Items.GOLD_CHAINS, "Steel Chains");
        translationBuilder.add(At_Items.IRON_CHAINS, "Tin Chains");
        translationBuilder.add(At_Items.ADAMANTIUM_COINS, "Adamantium Coins");
        translationBuilder.add(At_Items.ANCIENT_METAL_COINS, "Ancient Metal Coins");
        translationBuilder.add(At_Items.COPPER_COINS, "Copper Coins");
        translationBuilder.add(At_Items.MITHRIL_COINS, "Mithril Coins");
        translationBuilder.add(At_Items.GOLD_COINS, "Rusted Iron Coins");
        translationBuilder.add(At_Items.SILVER_COINS, "Silver Coins");
        translationBuilder.add(At_Items.IRON_COINS, "Iron Coins");

        translationBuilder.add(At_Items.ADAMANTIUM_AXE, "Adamantium Axe");
        translationBuilder.add(At_Items.ADAMANTIUM_BATTLE_AXE, "Adamantium Battle Axe");
        translationBuilder.add(At_Items.ADAMANTIUM_DAGGER, "Adamantium Dagger");
        translationBuilder.add(At_Items.ADAMANTIUM_HATCHET, "Adamantium Hatchet");
        translationBuilder.add(At_Items.ADAMANTIUM_HOE, "Adamantium Hoe");
        translationBuilder.add(At_Items.ADAMANTIUM_KNIFE, "Adamantium Knife");
        translationBuilder.add(At_Items.ADAMANTIUM_MATTOCK, "Adamantium Mattock");
        translationBuilder.add(At_Items.ADAMANTIUM_PICKAXE, "Adamantium Pickaxe");
        translationBuilder.add(At_Items.ADAMANTIUM_SCYTHE, "Adamantium Scythe");
        translationBuilder.add(At_Items.ADAMANTIUM_SHEARS, "Adamantium Shears");
        translationBuilder.add(At_Items.ADAMANTIUM_SHOVEL, "Adamantium Shovel");
        translationBuilder.add(At_Items.ADAMANTIUM_SWORD, "Adamantium Sword");
        translationBuilder.add(At_Items.ADAMANTIUM_WAR_HAMMER, "Adamantium War Hammer");
        translationBuilder.add(At_Items.ANCIENT_METAL_AXE, "Ancient Metal Axe");
        translationBuilder.add(At_Items.ANCIENT_METAL_BATTLE_AXE, "Ancient Metal Battle Axe");
        translationBuilder.add(At_Items.ANCIENT_METAL_DAGGER, "Ancient Metal Dagger");
        translationBuilder.add(At_Items.ANCIENT_METAL_HATCHET, "Ancient Metal Hatchet");
        translationBuilder.add(At_Items.ANCIENT_METAL_HOE, "Ancient Metal Hoe");
        translationBuilder.add(At_Items.ANCIENT_METAL_KNIFE, "Ancient Metal Knife");
        translationBuilder.add(At_Items.ANCIENT_METAL_MATTOCK, "Ancient Metal Mattock");
        translationBuilder.add(At_Items.ANCIENT_METAL_PICKAXE, "Ancient Metal Pickaxe");
        translationBuilder.add(At_Items.ANCIENT_METAL_SCYTHE, "Ancient Metal Scythe");
        translationBuilder.add(At_Items.ANCIENT_METAL_SHEARS, "Ancient Metal Shears");
        translationBuilder.add(At_Items.ANCIENT_METAL_SHOVEL, "Ancient Metal Shovel");
        translationBuilder.add(At_Items.ANCIENT_METAL_SWORD, "Ancient Metal Sword");
        translationBuilder.add(At_Items.ANCIENT_METAL_WAR_HAMMER, "Ancient Metal War Hammer");
        translationBuilder.add(At_Items.COPPER_AXE, "Copper Axe");
        translationBuilder.add(At_Items.COPPER_BATTLE_AXE, "Copper Battle Axe");
        translationBuilder.add(At_Items.COPPER_DAGGER, "Copper Dagger");
        translationBuilder.add(At_Items.COPPER_HATCHET, "Copper Hatchet");
        translationBuilder.add(At_Items.COPPER_HOE, "Copper Hoe");
        translationBuilder.add(At_Items.COPPER_KNIFE, "Copper Knife");
        translationBuilder.add(At_Items.COPPER_MATTOCK, "Copper Mattock");
        translationBuilder.add(At_Items.COPPER_PICKAXE, "Copper Pickaxe");
        translationBuilder.add(At_Items.COPPER_SCYTHE, "Copper Scythe");
        translationBuilder.add(At_Items.COPPER_SHEARS, "Copper Shears");
        translationBuilder.add(At_Items.COPPER_SHOVEL, "Copper Shovel");
        translationBuilder.add(At_Items.COPPER_SWORD, "Copper Sword");
        translationBuilder.add(At_Items.COPPER_WAR_HAMMER, "Copper War Hammer");
        translationBuilder.add(At_Items.FLINT_AXE, "Flint Axe");
        translationBuilder.add(At_Items.FLINT_HATCHET, "Flint Hatchet");
        translationBuilder.add(At_Items.FLINT_KNIFE, "Flint Knife");
        translationBuilder.add(At_Items.FLINT_SHOVEL, "Flint Shovel");
        translationBuilder.add(At_Items.GOLD_AXE, "Gold Axe");
        translationBuilder.add(At_Items.GOLD_BATTLE_AXE, "Gold Battle Axe");
        translationBuilder.add(At_Items.GOLD_DAGGER, "Gold Dagger");
        translationBuilder.add(At_Items.GOLD_HATCHET, "Gold Hatchet");
        translationBuilder.add(At_Items.GOLD_HOE, "Gold Hoe");
        translationBuilder.add(At_Items.GOLD_KNIFE, "Gold Knife");
        translationBuilder.add(At_Items.GOLD_MATTOCK, "Gold Mattock");
        translationBuilder.add(At_Items.GOLD_PICKAXE, "Gold Pickaxe");
        translationBuilder.add(At_Items.GOLD_SCYTHE, "Gold Scythe");
        translationBuilder.add(At_Items.GOLD_SHEARS, "Gold Shears");
        translationBuilder.add(At_Items.GOLD_SHOVEL, "Gold Shovel");
        translationBuilder.add(At_Items.GOLD_SWORD, "Gold Sword");
        translationBuilder.add(At_Items.GOLD_WAR_HAMMER, "Gold War Hammer");
        translationBuilder.add(At_Items.IRON_BATTLE_AXE, "Iron Battle Axe");
        translationBuilder.add(At_Items.IRON_DAGGER, "Iron Dagger");
        translationBuilder.add(At_Items.IRON_HATCHET, "Iron Hatchet");
        translationBuilder.add(At_Items.IRON_KNIFE, "Iron Knife");
        translationBuilder.add(At_Items.IRON_MATTOCK, "Iron Mattock");
        translationBuilder.add(At_Items.IRON_SCYTHE, "Iron Scythe");
        translationBuilder.add(At_Items.IRON_WAR_HAMMER, "Iron War Hammer");
        translationBuilder.add(At_Items.MITHRIL_AXE, "Mithril Axe");
        translationBuilder.add(At_Items.MITHRIL_BATTLE_AXE, "Mithril Battle Axe");
        translationBuilder.add(At_Items.MITHRIL_DAGGER, "Mithril Dagger");
        translationBuilder.add(At_Items.MITHRIL_HATCHET, "Mithril Hatchet");
        translationBuilder.add(At_Items.MITHRIL_HOE, "Mithril Hoe");
        translationBuilder.add(At_Items.MITHRIL_KNIFE, "Mithril Knife");
        translationBuilder.add(At_Items.MITHRIL_MATTOCK, "Mithril Mattock");
        translationBuilder.add(At_Items.MITHRIL_PICKAXE, "Mithril Pickaxe");
        translationBuilder.add(At_Items.MITHRIL_SCYTHE, "Mithril Scythe");
        translationBuilder.add(At_Items.MITHRIL_SHEARS, "Mithril Shears");
        translationBuilder.add(At_Items.MITHRIL_SHOVEL, "Mithril Shovel");
        translationBuilder.add(At_Items.MITHRIL_SWORD, "Mithril Sword");
        translationBuilder.add(At_Items.MITHRIL_WAR_HAMMER, "Mithril War Hammer");
        translationBuilder.add(At_Items.OBSIDIAN_AXE, "Obsidian Axe");
        translationBuilder.add(At_Items.OBSIDIAN_HATCHET, "Obsidian Hatchet");
        translationBuilder.add(At_Items.OBSIDIAN_KNIFE, "Obsidian Knife");
        translationBuilder.add(At_Items.OBSIDIAN_SHOVEL, "Obsidian Shovel");
        translationBuilder.add(At_Items.RUSTED_IRON_AXE, "Rusted Iron Axe");
        translationBuilder.add(At_Items.RUSTED_IRON_BATTLE_AXE, "Rusted Iron Battle Axe");
        translationBuilder.add(At_Items.RUSTED_IRON_DAGGER, "Rusted Iron Dagger");
        translationBuilder.add(At_Items.RUSTED_IRON_HATCHET, "Rusted Iron Hatchet");
        translationBuilder.add(At_Items.RUSTED_IRON_HOE, "Rusted Iron Hoe");
        translationBuilder.add(At_Items.RUSTED_IRON_KNIFE, "Rusted Iron Knife");
        translationBuilder.add(At_Items.RUSTED_IRON_MATTOCK, "Rusted Iron Mattock");
        translationBuilder.add(At_Items.RUSTED_IRON_PICKAXE, "Rusted Iron Pickaxe");
        translationBuilder.add(At_Items.RUSTED_IRON_SCYTHE, "Rusted Iron Scythe");
        translationBuilder.add(At_Items.RUSTED_IRON_SHEARS, "Rusted Iron Shears");
        translationBuilder.add(At_Items.RUSTED_IRON_SHOVEL, "Rusted Iron Shovel");
        translationBuilder.add(At_Items.RUSTED_IRON_SWORD, "Rusted Iron Sword");
        translationBuilder.add(At_Items.RUSTED_IRON_WAR_HAMMER, "Rusted Iron War Hammer");
        translationBuilder.add(At_Items.SILVER_AXE, "Silver Axe");
        translationBuilder.add(At_Items.SILVER_BATTLE_AXE, "Silver Battle Axe");
        translationBuilder.add(At_Items.SILVER_DAGGER, "Silver Dagger");
        translationBuilder.add(At_Items.SILVER_HATCHET, "Silver Hatchet");
        translationBuilder.add(At_Items.SILVER_HOE, "Silver Hoe");
        translationBuilder.add(At_Items.SILVER_KNIFE, "Silver Knife");
        translationBuilder.add(At_Items.SILVER_MATTOCK, "Silver Mattock");
        translationBuilder.add(At_Items.SILVER_PICKAXE, "Silver Pickaxe");
        translationBuilder.add(At_Items.SILVER_SCYTHE, "Silver Scythe");
        translationBuilder.add(At_Items.SILVER_SHEARS, "Silver Shears");
        translationBuilder.add(At_Items.SILVER_SHOVEL, "Silver Shovel");
        translationBuilder.add(At_Items.SILVER_SWORD, "Silver Sword");
        translationBuilder.add(At_Items.SILVER_WAR_HAMMER, "Silver War Hammer");
        translationBuilder.add(At_Items.STONE_DAGGER, "Stone Dagger");
        translationBuilder.add(At_Items.WOOD_CLUB, "Wood Club");
        translationBuilder.add(At_Items.WOOD_CUDGEL, "Wood Cudgel ");
    }
}
