package com.acuteterror233.mite.datagen;

import com.acuteterror233.mite.block.AtBlocks;
import com.acuteterror233.mite.item.AtItems;
import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricLanguageProvider;
import net.minecraft.registry.RegistryWrapper;

import java.util.concurrent.CompletableFuture;

public class En_usLanguageProvider extends FabricLanguageProvider {

    public En_usLanguageProvider(FabricDataOutput dataOutput, CompletableFuture<RegistryWrapper.WrapperLookup> registryLookup) {
        super(dataOutput, "en_us", registryLookup);
    }

    @Override
    public void generateTranslations(RegistryWrapper.WrapperLookup registryLookup, TranslationBuilder translationBuilder) {
        translationBuilder.add("itemGroup.mme.item_group","Make Minecraft easier!");
        translationBuilder.add("mme.craftingTable.noAllowedCrafting","§cThis item cannot be crafted§r");
        translationBuilder.add("mme.gradefurnac.fuelnotavailable", "§cThis furnace cannot burn this fuel§r");
        translationBuilder.add(AtItems.ADAMANTIUM_HELMET,"Adamantium Helmet");
        translationBuilder.add(AtItems.ADAMANTIUM_CHESTPLATE,"Adamantium Chestplate");
        translationBuilder.add(AtItems.ADAMANTIUM_LEGGINGS,"Adamantium Leggings");
        translationBuilder.add(AtItems.ADAMANTIUM_BOOTS,"Adamantium Boots");
        translationBuilder.add(AtItems.ADAMANTIUM_CHAINMAIL_HELMET,"Adamantium Chainmail Helmet");
        translationBuilder.add(AtItems.ADAMANTIUM_CHAINMAIL_CHESTPLATE,"Adamantium Chainmail Chestplate");
        translationBuilder.add(AtItems.ADAMANTIUM_CHAINMAIL_LEGGINGS,"Adamantium Chainmail Leggings");
        translationBuilder.add(AtItems.ADAMANTIUM_CHAINMAIL_BOOTS,"Adamantium Chainmail Boots");
        translationBuilder.add(AtItems.ANCIENT_METAL_HELMET,"Ancient Metal Helmet");
        translationBuilder.add(AtItems.ANCIENT_METAL_CHESTPLATE,"Ancient Metal Chestplate");
        translationBuilder.add(AtItems.ANCIENT_METAL_LEGGINGS,"Ancient Metal Leggings");
        translationBuilder.add(AtItems.ANCIENT_METAL_BOOTS,"Ancient Metal Boots");
        translationBuilder.add(AtItems.ANCIENT_METAL_CHAINMAIL_HELMET,"Ancient Metal Chainmail Helmet");
        translationBuilder.add(AtItems.ANCIENT_METAL_CHAINMAIL_CHESTPLATE,"Ancient Metal Chainmail Chestplate");
        translationBuilder.add(AtItems.ANCIENT_METAL_CHAINMAIL_LEGGINGS,"Ancient Metal Chainmail Leggings");
        translationBuilder.add(AtItems.ANCIENT_METAL_CHAINMAIL_BOOTS,"Ancient Metal Chainmail Boots");
        translationBuilder.add(AtItems.COPPER_HELMET,"Copper Helmet");
        translationBuilder.add(AtItems.COPPER_CHESTPLATE,"Copper Chestplate");
        translationBuilder.add(AtItems.COPPER_LEGGINGS,"Copper Leggings");
        translationBuilder.add(AtItems.COPPER_BOOTS,"Copper Boots");
        translationBuilder.add(AtItems.COPPER_CHAINMAIL_BOOTS,"Copper Chainmail boots");
        translationBuilder.add(AtItems.COPPER_CHAINMAIL_HELMET,"Copper Chainmail Helmet");
        translationBuilder.add(AtItems.COPPER_CHAINMAIL_CHESTPLATE,"Copper Chainmail Chestplate");
        translationBuilder.add(AtItems.COPPER_CHAINMAIL_LEGGINGS,"Copper Chainmail Leggings");
        translationBuilder.add(AtItems.MITHRIL_HELMET, "Mithril Helmet");
        translationBuilder.add(AtItems.MITHRIL_CHESTPLATE, "Mithril Chestplate");
        translationBuilder.add(AtItems.MITHRIL_LEGGINGS, "Mithril Leggings");
        translationBuilder.add(AtItems.MITHRIL_BOOTS, "Mithril Boots");
        translationBuilder.add(AtItems.MITHRIL_CHAINMAIL_HELMET, "Mithril Chainmail Helmet");
        translationBuilder.add(AtItems.MITHRIL_CHAINMAIL_CHESTPLATE, "Mithril Chainmail Chestplate");
        translationBuilder.add(AtItems.MITHRIL_CHAINMAIL_LEGGINGS, "Mithril Chainmail Leggings");
        translationBuilder.add(AtItems.MITHRIL_CHAINMAIL_BOOTS, "Mithril Chainmail Boots");
        translationBuilder.add(AtItems.RUSTED_IRON_HELMET, "Rusted Iron Helmet");
        translationBuilder.add(AtItems.RUSTED_IRON_CHESTPLATE, "Rusted Iron Chestplate");
        translationBuilder.add(AtItems.RUSTED_IRON_LEGGINGS, "Rusted Iron Leggings");
        translationBuilder.add(AtItems.RUSTED_IRON_BOOTS, "Rusted Iron Boots");
        translationBuilder.add(AtItems.RUSTED_IRON_CHAINMAIL_HELMET, "Rusted Iron Chainmail Helmet");
        translationBuilder.add(AtItems.RUSTED_IRON_CHAINMAIL_CHESTPLATE, "Rusted Iron Chainmail Chestplate");
        translationBuilder.add(AtItems.RUSTED_IRON_CHAINMAIL_LEGGINGS, "Rusted Iron Chainmail Leggings");
        translationBuilder.add(AtItems.RUSTED_IRON_CHAINMAIL_BOOTS, "Rusted Iron Chainmail Boots");
        translationBuilder.add(AtItems.SILVER_HELMET, "Silver Helmet");
        translationBuilder.add(AtItems.SILVER_CHESTPLATE, "Silver Chestplate");
        translationBuilder.add(AtItems.SILVER_LEGGINGS, "Silver Leggings");
        translationBuilder.add(AtItems.SILVER_BOOTS, "Silver Boots");
        translationBuilder.add(AtItems.SILVER_CHAINMAIL_HELMET, "Silver Chainmail Helmet");
        translationBuilder.add(AtItems.SILVER_CHAINMAIL_CHESTPLATE, "Silver Chainmail Chestplate");
        translationBuilder.add(AtItems.SILVER_CHAINMAIL_LEGGINGS, "Silver Chainmail Leggings");
        translationBuilder.add(AtItems.SILVER_CHAINMAIL_BOOTS, "Silver Chainmail Boots");

        translationBuilder.add(AtItems.BANANA, "Banana");
        translationBuilder.add(AtItems.BLUEBERRIE, "Blueberry");
        translationBuilder.add(AtItems.CHEESE, "Cheese");
        translationBuilder.add(AtItems.CHOCOLATE, "Chocolate");
        translationBuilder.add(AtItems.DOUGH, "Dough");
        translationBuilder.add(AtItems.ONION, "Onion");
        translationBuilder.add(AtItems.LEMON, "Lemon");
        translationBuilder.add(AtItems.ORANGE, "Orange");
        translationBuilder.add(AtItems.WORM_COOKED, "Worm Cooked");
        translationBuilder.add(AtItems.WORM_RAW, "Worm Raw");
        translationBuilder.add(AtItems.FLOUR, "Flour");
        translationBuilder.add(AtItems.BEEF_STEW, "Beef Stew");
        translationBuilder.add(AtItems.BOWL_MILK, "Bowl of Milk");
        translationBuilder.add(AtItems.BOWL_SALAD, "Bowl of Salad");
        translationBuilder.add(AtItems.BOWL_WATER, "Bowl of Water");
        translationBuilder.add(AtItems.CEREAL, "Cereal");
        translationBuilder.add(AtItems.CHICKEN_SOUP, "Chicken Soup");
        translationBuilder.add(AtItems.CREAM_OF_MUSHROOM_SOUP, "Cream of Mushroom Soup");
        translationBuilder.add(AtItems.CREAM_OF_VEGETABLE_SOUP, "Cream of Vegetable Soup");
        translationBuilder.add(AtItems.ICE_CREAM, "Ice Cream");
        translationBuilder.add(AtItems.MASHED_POTATO, "Mashed Potato");
        translationBuilder.add(AtItems.MUSHROOM_STEW, "Mushroom Stew");
        translationBuilder.add(AtItems.PORRIDGE, "Blueberry Porridge");
        translationBuilder.add(AtItems.PUMPKIN_SOUP, "Pumpkin Soup");
        translationBuilder.add(AtItems.SORBET, "Sorbet");
        translationBuilder.add(AtItems.VEGETABLE_SOUP, "Vegetable Soup");

        translationBuilder.add(AtItems.ADAMANTIUM_ARROW, "Adamantium Arrow");
        translationBuilder.add(AtItems.ANCIENT_METAL_ARROW, "Ancient Metal Arrow");
        translationBuilder.add(AtItems.COPPER_ARROW, "Copper Arrow");
        translationBuilder.add(AtItems.MITHRIL_ARROW, "Mithril Arrow");
        translationBuilder.add(AtItems.RUSTED_IRON_ARROW, "Rusted Iron Arrow");
        translationBuilder.add(AtItems.SILVER_ARROW, "Silver Arrow");
        translationBuilder.add(AtItems.FLINT_ARROW, "Flint Arrow");
        translationBuilder.add(AtItems.GOLDEN_ARROW, "Gold Arrow");
        translationBuilder.add(AtItems.IRON_ARROW, "Iron Arrow");
        translationBuilder.add(AtItems.OBSIDIAN_ARROW, "Obsidian Arrow");
        translationBuilder.add(AtItems.ADAMANTIUM_CHAINS, "Adamantium Chains");
        translationBuilder.add(AtItems.ANCIENT_METAL_CHAINS, "Ancient Metal Chains");
        translationBuilder.add(AtItems.COPPER_CHAINS, "Copper Chains");
        translationBuilder.add(AtItems.MITHRIL_CHAINS, "Mithril Chains");
        translationBuilder.add(AtItems.RUSTED_IRON_CHAINS, "Rusted Iron Chains");
        translationBuilder.add(AtItems.SILVER_CHAINS, "Silver Chains");
        translationBuilder.add(AtItems.GOLDEN_CHAINS, "Steel Chains");
        translationBuilder.add(AtItems.IRON_CHAINS, "Tin Chains");
        translationBuilder.add(AtItems.ADAMANTIUM_COINS, "Adamantium Coins");
        translationBuilder.add(AtItems.ANCIENT_METAL_COINS, "Ancient Metal Coins");
        translationBuilder.add(AtItems.COPPER_COINS, "Copper Coins");
        translationBuilder.add(AtItems.MITHRIL_COINS, "Mithril Coins");
        translationBuilder.add(AtItems.GOLDEN_COINS, "Rusted Iron Coins");
        translationBuilder.add(AtItems.SILVER_COINS, "Silver Coins");
        translationBuilder.add(AtItems.IRON_COINS, "Iron Coins");

        translationBuilder.add(AtItems.ADAMANTIUM_AXE, "Adamantium Axe");
        translationBuilder.add(AtItems.ADAMANTIUM_BATTLE_AXE, "Adamantium Battle Axe");
        translationBuilder.add(AtItems.ADAMANTIUM_DAGGER, "Adamantium Dagger");
        translationBuilder.add(AtItems.ADAMANTIUM_HATCHET, "Adamantium Hatchet");
        translationBuilder.add(AtItems.ADAMANTIUM_HOE, "Adamantium Hoe");
        translationBuilder.add(AtItems.ADAMANTIUM_KNIFE, "Adamantium Knife");
        translationBuilder.add(AtItems.ADAMANTIUM_MATTOCK, "Adamantium Mattock");
        translationBuilder.add(AtItems.ADAMANTIUM_PICKAXE, "Adamantium Pickaxe");
        translationBuilder.add(AtItems.ADAMANTIUM_SCYTHE, "Adamantium Scythe");
        translationBuilder.add(AtItems.ADAMANTIUM_SHEARS, "Adamantium Shears");
        translationBuilder.add(AtItems.ADAMANTIUM_SHOVEL, "Adamantium Shovel");
        translationBuilder.add(AtItems.ADAMANTIUM_SWORD, "Adamantium Sword");
        translationBuilder.add(AtItems.ADAMANTIUM_WAR_HAMMER, "Adamantium War Hammer");
        translationBuilder.add(AtItems.ANCIENT_METAL_AXE, "Ancient Metal Axe");
        translationBuilder.add(AtItems.ANCIENT_METAL_BATTLE_AXE, "Ancient Metal Battle Axe");
        translationBuilder.add(AtItems.ANCIENT_METAL_DAGGER, "Ancient Metal Dagger");
        translationBuilder.add(AtItems.ANCIENT_METAL_HATCHET, "Ancient Metal Hatchet");
        translationBuilder.add(AtItems.ANCIENT_METAL_HOE, "Ancient Metal Hoe");
        translationBuilder.add(AtItems.ANCIENT_METAL_KNIFE, "Ancient Metal Knife");
        translationBuilder.add(AtItems.ANCIENT_METAL_MATTOCK, "Ancient Metal Mattock");
        translationBuilder.add(AtItems.ANCIENT_METAL_PICKAXE, "Ancient Metal Pickaxe");
        translationBuilder.add(AtItems.ANCIENT_METAL_SCYTHE, "Ancient Metal Scythe");
        translationBuilder.add(AtItems.ANCIENT_METAL_SHEARS, "Ancient Metal Shears");
        translationBuilder.add(AtItems.ANCIENT_METAL_SHOVEL, "Ancient Metal Shovel");
        translationBuilder.add(AtItems.ANCIENT_METAL_SWORD, "Ancient Metal Sword");
        translationBuilder.add(AtItems.ANCIENT_METAL_WAR_HAMMER, "Ancient Metal War Hammer");
        translationBuilder.add(AtItems.COPPER_AXE, "Copper Axe");
        translationBuilder.add(AtItems.COPPER_BATTLE_AXE, "Copper Battle Axe");
        translationBuilder.add(AtItems.COPPER_DAGGER, "Copper Dagger");
        translationBuilder.add(AtItems.COPPER_HATCHET, "Copper Hatchet");
        translationBuilder.add(AtItems.COPPER_HOE, "Copper Hoe");
        translationBuilder.add(AtItems.COPPER_KNIFE, "Copper Knife");
        translationBuilder.add(AtItems.COPPER_MATTOCK, "Copper Mattock");
        translationBuilder.add(AtItems.COPPER_PICKAXE, "Copper Pickaxe");
        translationBuilder.add(AtItems.COPPER_SCYTHE, "Copper Scythe");
        translationBuilder.add(AtItems.COPPER_SHEARS, "Copper Shears");
        translationBuilder.add(AtItems.COPPER_SHOVEL, "Copper Shovel");
        translationBuilder.add(AtItems.COPPER_SWORD, "Copper Sword");
        translationBuilder.add(AtItems.COPPER_WAR_HAMMER, "Copper War Hammer");
        translationBuilder.add(AtItems.FLINT_AXE, "Flint Axe");
        translationBuilder.add(AtItems.FLINT_HATCHET, "Flint Hatchet");
        translationBuilder.add(AtItems.FLINT_KNIFE, "Flint Knife");
        translationBuilder.add(AtItems.FLINT_SHOVEL, "Flint Shovel");
        translationBuilder.add(AtItems.GOLDEN_BATTLE_AXE, "Gold Battle Axe");
        translationBuilder.add(AtItems.GOLDEN_DAGGER, "Gold Dagger");
        translationBuilder.add(AtItems.GOLDEN_HATCHET, "Gold Hatchet");
        translationBuilder.add(AtItems.GOLDEN_KNIFE, "Gold Knife");
        translationBuilder.add(AtItems.GOLDEN_MATTOCK, "Gold Mattock");
        translationBuilder.add(AtItems.GOLDEN_SCYTHE, "Gold Scythe");
        translationBuilder.add(AtItems.GOLDEN_SHEARS, "Gold Shears");
        translationBuilder.add(AtItems.GOLDEN_WAR_HAMMER, "Gold War Hammer");
        translationBuilder.add(AtItems.IRON_BATTLE_AXE, "Iron Battle Axe");
        translationBuilder.add(AtItems.IRON_DAGGER, "Iron Dagger");
        translationBuilder.add(AtItems.IRON_HATCHET, "Iron Hatchet");
        translationBuilder.add(AtItems.IRON_KNIFE, "Iron Knife");
        translationBuilder.add(AtItems.IRON_MATTOCK, "Iron Mattock");
        translationBuilder.add(AtItems.IRON_SCYTHE, "Iron Scythe");
        translationBuilder.add(AtItems.IRON_WAR_HAMMER, "Iron War Hammer");
        translationBuilder.add(AtItems.MITHRIL_AXE, "Mithril Axe");
        translationBuilder.add(AtItems.MITHRIL_BATTLE_AXE, "Mithril Battle Axe");
        translationBuilder.add(AtItems.MITHRIL_DAGGER, "Mithril Dagger");
        translationBuilder.add(AtItems.MITHRIL_HATCHET, "Mithril Hatchet");
        translationBuilder.add(AtItems.MITHRIL_HOE, "Mithril Hoe");
        translationBuilder.add(AtItems.MITHRIL_KNIFE, "Mithril Knife");
        translationBuilder.add(AtItems.MITHRIL_MATTOCK, "Mithril Mattock");
        translationBuilder.add(AtItems.MITHRIL_PICKAXE, "Mithril Pickaxe");
        translationBuilder.add(AtItems.MITHRIL_SCYTHE, "Mithril Scythe");
        translationBuilder.add(AtItems.MITHRIL_SHEARS, "Mithril Shears");
        translationBuilder.add(AtItems.MITHRIL_SHOVEL, "Mithril Shovel");
        translationBuilder.add(AtItems.MITHRIL_SWORD, "Mithril Sword");
        translationBuilder.add(AtItems.MITHRIL_WAR_HAMMER, "Mithril War Hammer");
        translationBuilder.add(AtItems.OBSIDIAN_AXE, "Obsidian Axe");
        translationBuilder.add(AtItems.OBSIDIAN_HATCHET, "Obsidian Hatchet");
        translationBuilder.add(AtItems.OBSIDIAN_KNIFE, "Obsidian Knife");
        translationBuilder.add(AtItems.OBSIDIAN_SHOVEL, "Obsidian Shovel");
        translationBuilder.add(AtItems.RUSTED_IRON_AXE, "Rusted Iron Axe");
        translationBuilder.add(AtItems.RUSTED_IRON_BATTLE_AXE, "Rusted Iron Battle Axe");
        translationBuilder.add(AtItems.RUSTED_IRON_DAGGER, "Rusted Iron Dagger");
        translationBuilder.add(AtItems.RUSTED_IRON_HATCHET, "Rusted Iron Hatchet");
        translationBuilder.add(AtItems.RUSTED_IRON_HOE, "Rusted Iron Hoe");
        translationBuilder.add(AtItems.RUSTED_IRON_KNIFE, "Rusted Iron Knife");
        translationBuilder.add(AtItems.RUSTED_IRON_MATTOCK, "Rusted Iron Mattock");
        translationBuilder.add(AtItems.RUSTED_IRON_PICKAXE, "Rusted Iron Pickaxe");
        translationBuilder.add(AtItems.RUSTED_IRON_SCYTHE, "Rusted Iron Scythe");
        translationBuilder.add(AtItems.RUSTED_IRON_SHEARS, "Rusted Iron Shears");
        translationBuilder.add(AtItems.RUSTED_IRON_SHOVEL, "Rusted Iron Shovel");
        translationBuilder.add(AtItems.RUSTED_IRON_SWORD, "Rusted Iron Sword");
        translationBuilder.add(AtItems.RUSTED_IRON_WAR_HAMMER, "Rusted Iron War Hammer");
        translationBuilder.add(AtItems.SILVER_AXE, "Silver Axe");
        translationBuilder.add(AtItems.SILVER_BATTLE_AXE, "Silver Battle Axe");
        translationBuilder.add(AtItems.SILVER_DAGGER, "Silver Dagger");
        translationBuilder.add(AtItems.SILVER_HATCHET, "Silver Hatchet");
        translationBuilder.add(AtItems.SILVER_HOE, "Silver Hoe");
        translationBuilder.add(AtItems.SILVER_KNIFE, "Silver Knife");
        translationBuilder.add(AtItems.SILVER_MATTOCK, "Silver Mattock");
        translationBuilder.add(AtItems.SILVER_PICKAXE, "Silver Pickaxe");
        translationBuilder.add(AtItems.SILVER_SCYTHE, "Silver Scythe");
        translationBuilder.add(AtItems.SILVER_SHEARS, "Silver Shears");
        translationBuilder.add(AtItems.SILVER_SHOVEL, "Silver Shovel");
        translationBuilder.add(AtItems.SILVER_SWORD, "Silver Sword");
        translationBuilder.add(AtItems.SILVER_WAR_HAMMER, "Silver War Hammer");
        translationBuilder.add(AtItems.STONE_DAGGER, "Stone Dagger");
        translationBuilder.add(AtItems.WOOD_CLUB, "Wood Club");
        translationBuilder.add(AtItems.WOOD_CUDGEL, "Wood Cudgel ");

        translationBuilder.add(AtBlocks.ADAMANTIUM_ORE, "Adamantium Ore");
        translationBuilder.add(AtBlocks.ADAMANTIUM_BARS, "Adamantium Bars");
        translationBuilder.add(AtBlocks.ADAMANTIUM_BLOCK, "Adamantium Block");
        translationBuilder.add(AtBlocks.ANCIENT_METAL_BARS, "Ancient Metal Bars");
        translationBuilder.add(AtBlocks.ANCIENT_METAL_BLOCK, "Ancient Metal Block");
        translationBuilder.add(AtBlocks.GOLDEN_BARS, "Gold Bars");
        translationBuilder.add(AtBlocks.MITHRIL_BARS, "Mithril Bars");
        translationBuilder.add(AtBlocks.MITHRIL_BLOCK, "Mithril Block");
        translationBuilder.add(AtBlocks.MITHRIL_ORE, "Mithril Ore");
        translationBuilder.add(AtBlocks.SILVER_BARS, "Silver BARS");
        translationBuilder.add(AtBlocks.SILVER_BLOCK, "Silver Block");
        translationBuilder.add(AtBlocks.SILVER_ORE, "Silver Ore");
        translationBuilder.add(AtBlocks.MANTLE, "Mantle");
        translationBuilder.add(AtBlocks.COPPER_BARS, "Copper BARS");

        translationBuilder.add(AtItems.ADAMANTIUM_BUCKET,"Adamantium Bucket");
        translationBuilder.add(AtItems.LAVA_ADAMANTIUM_BUCKET, "Adamantium Bucket of Lava");
        translationBuilder.add(AtItems.WATER_ADAMANTIUM_BUCKET, "Adamantium of Water Bucket");
        translationBuilder.add(AtItems.POWDER_SNOW_ADAMANTIUM_BUCKET, "Adamantium Bucket of Powder Snow");
        translationBuilder.add(AtItems.MILK_ADAMANTIUM_BUCKET, "Adamantium Bucket of Milk");
        translationBuilder.add(AtItems.PUFFERFISH_ADAMANTIUM_BUCKET, "Adamantium Bucket of Pufferfish");
        translationBuilder.add(AtItems.SALMON_ADAMANTIUM_BUCKET, "Adamantium Bucket of Salmon");
        translationBuilder.add(AtItems.COD_ADAMANTIUM_BUCKET, "Adamantium Bucket of Cod");
        translationBuilder.add(AtItems.TROPICAL_FISH_ADAMANTIUM_BUCKET, "Adamantium Bucket of Tropical Fish");
        translationBuilder.add(AtItems.AXOLOTL_ADAMANTIUM_BUCKET, "Adamantium Bucket of Axolotl");
        translationBuilder.add(AtItems.TADPOLE_ADAMANTIUM_BUCKET, "Adamantium Bucket of Tadpole");

        translationBuilder.add(AtItems.ANCIENT_METAL_BUCKET,"Ancient Metal bucket");
        translationBuilder.add(AtItems.LAVA_ANCIENT_METAL_BUCKET, "Ancient Metal Bucket of Lava");
        translationBuilder.add(AtItems.WATER_ANCIENT_METAL_BUCKET, "Ancient Metal of Water Bucket");
        translationBuilder.add(AtItems.POWDER_SNOW_ANCIENT_METAL_BUCKET, "Ancient Metal Bucket of Powder Snow");
        translationBuilder.add(AtItems.MILK_ANCIENT_METAL_BUCKET, "Ancient Metal Bucket of Milk");
        translationBuilder.add(AtItems.PUFFERFISH_ANCIENT_METAL_BUCKET, "Ancient Metal Bucket of Pufferfish");
        translationBuilder.add(AtItems.SALMON_ANCIENT_METAL_BUCKET, "Ancient Metal Bucket of Salmon");
        translationBuilder.add(AtItems.COD_ANCIENT_METAL_BUCKET, "Ancient Metal Bucket of Cod");
        translationBuilder.add(AtItems.TROPICAL_FISH_ANCIENT_METAL_BUCKET, "Ancient Metal Bucket of Tropical Fish");
        translationBuilder.add(AtItems.AXOLOTL_ANCIENT_METAL_BUCKET, "Ancient Metal Bucket of Axolotl");
        translationBuilder.add(AtItems.TADPOLE_ANCIENT_METAL_BUCKET, "Ancient Metal Bucket of Tadpole");

        translationBuilder.add(AtItems.COPPER_BUCKET,"Copper bucket");
        translationBuilder.add(AtItems.LAVA_COPPER_BUCKET, "Copper Bucket of Lava");
        translationBuilder.add(AtItems.WATER_COPPER_BUCKET, "Copper of Water Bucket");
        translationBuilder.add(AtItems.POWDER_SNOW_COPPER_BUCKET, "Copper Bucket of Powder Snow");
        translationBuilder.add(AtItems.MILK_COPPER_BUCKET, "Copper Bucket of Milk");
        translationBuilder.add(AtItems.PUFFERFISH_COPPER_BUCKET, "Copper Bucket of Pufferfish");
        translationBuilder.add(AtItems.SALMON_COPPER_BUCKET, "Copper Bucket of Salmon");
        translationBuilder.add(AtItems.COD_COPPER_BUCKET, "Copper Bucket of Cod");
        translationBuilder.add(AtItems.TROPICAL_FISH_COPPER_BUCKET, "Copper Bucket of Tropical Fish");
        translationBuilder.add(AtItems.AXOLOTL_COPPER_BUCKET, "Copper Bucket of Axolotl");
        translationBuilder.add(AtItems.TADPOLE_COPPER_BUCKET, "Copper Bucket of Tadpole");

        translationBuilder.add(AtItems.GOLD_BUCKET,"Gold bucket");
        translationBuilder.add(AtItems.LAVA_GOLD_BUCKET, "Gold Bucket of Lava");
        translationBuilder.add(AtItems.WATER_GOLD_BUCKET, "Gold of Water Bucket");
        translationBuilder.add(AtItems.POWDER_SNOW_GOLD_BUCKET, "Gold Bucket of Powder Snow");
        translationBuilder.add(AtItems.MILK_GOLD_BUCKET, "Gold Bucket of Milk");
        translationBuilder.add(AtItems.PUFFERFISH_GOLD_BUCKET, "Gold Bucket of Pufferfish");
        translationBuilder.add(AtItems.SALMON_GOLD_BUCKET, "Gold Bucket of Salmon");
        translationBuilder.add(AtItems.COD_GOLD_BUCKET, "Gold Bucket of Cod");
        translationBuilder.add(AtItems.TROPICAL_FISH_GOLD_BUCKET, "Gold Bucket of Tropical Fish");
        translationBuilder.add(AtItems.AXOLOTL_GOLD_BUCKET, "Gold Bucket of Axolotl");
        translationBuilder.add(AtItems.TADPOLE_GOLD_BUCKET, "Gold Bucket of Tadpole");

        translationBuilder.add(AtItems.MITHRIL_BUCKET,"Mithril bucket");
        translationBuilder.add(AtItems.LAVA_MITHRIL_BUCKET, "Mithril Bucket of Lava");
        translationBuilder.add(AtItems.WATER_MITHRIL_BUCKET, "Mithril of Water Bucket");
        translationBuilder.add(AtItems.POWDER_SNOW_MITHRIL_BUCKET, "Mithril Bucket of Powder Snow");
        translationBuilder.add(AtItems.MILK_MITHRIL_BUCKET, "Mithril Bucket of Milk");
        translationBuilder.add(AtItems.PUFFERFISH_MITHRIL_BUCKET, "Mithril Bucket of Pufferfish");
        translationBuilder.add(AtItems.SALMON_MITHRIL_BUCKET, "Mithril Bucket of Salmon");
        translationBuilder.add(AtItems.COD_MITHRIL_BUCKET, "Mithril Bucket of Cod");
        translationBuilder.add(AtItems.TROPICAL_FISH_MITHRIL_BUCKET, "Mithril Bucket of Tropical Fish");
        translationBuilder.add(AtItems.AXOLOTL_MITHRIL_BUCKET, "Mithril Bucket of Axolotl");
        translationBuilder.add(AtItems.TADPOLE_MITHRIL_BUCKET, "Mithril Bucket of Tadpole");

        translationBuilder.add(AtItems.SILVER_BUCKET,"Silver bucket");
        translationBuilder.add(AtItems.LAVA_SILVER_BUCKET, "Silver Bucket of Lava");
        translationBuilder.add(AtItems.WATER_SILVER_BUCKET, "Silver of Water Bucket");
        translationBuilder.add(AtItems.POWDER_SNOW_SILVER_BUCKET, "Silver Bucket of Powder Snow");
        translationBuilder.add(AtItems.MILK_SILVER_BUCKET, "Silver Bucket of Milk");
        translationBuilder.add(AtItems.PUFFERFISH_SILVER_BUCKET, "Silver Bucket of Pufferfish");
        translationBuilder.add(AtItems.SALMON_SILVER_BUCKET, "Silver Bucket of Salmon");
        translationBuilder.add(AtItems.COD_SILVER_BUCKET, "Silver Bucket of Cod");
        translationBuilder.add(AtItems.TROPICAL_FISH_SILVER_BUCKET, "Silver Bucket of Tropical Fish");
        translationBuilder.add(AtItems.AXOLOTL_SILVER_BUCKET, "Silver Bucket of Axolotl");
        translationBuilder.add(AtItems.TADPOLE_SILVER_BUCKET, "Silver Bucket of Tadpole");

        translationBuilder.add(AtItems.NETHERITE_BUCKET,"Netherite bucket");
        translationBuilder.add(AtItems.LAVA_NETHERITE_BUCKET, "Netherite Bucket of Lava");
        translationBuilder.add(AtItems.WATER_NETHERITE_BUCKET, "Netherite of Water Bucket");
        translationBuilder.add(AtItems.POWDER_SNOW_NETHERITE_BUCKET, "Netherite Bucket of Powder Snow");
        translationBuilder.add(AtItems.MILK_NETHERITE_BUCKET, "Netherite Bucket of Milk");
        translationBuilder.add(AtItems.PUFFERFISH_NETHERITE_BUCKET, "Netherite Bucket of Pufferfish");
        translationBuilder.add(AtItems.SALMON_NETHERITE_BUCKET, "Netherite Bucket of Salmon");
        translationBuilder.add(AtItems.COD_NETHERITE_BUCKET, "Netherite Bucket of Cod");
        translationBuilder.add(AtItems.TROPICAL_FISH_NETHERITE_BUCKET, "Netherite Bucket of Tropical Fish");
        translationBuilder.add(AtItems.AXOLOTL_NETHERITE_BUCKET, "Netherite Bucket of Axolotl");
        translationBuilder.add(AtItems.TADPOLE_NETHERITE_BUCKET, "Netherite Bucket of Tadpole");

        translationBuilder.add(AtItems.MITHRIL_BOW,"Mithril Bow");
        translationBuilder.add(AtItems.ANCIENT_METAL_BOW,"Ancient Metal Bow");

        translationBuilder.add(AtBlocks.ADAMANTIUM_DOOR, "Adamantium Door");
        translationBuilder.add(AtBlocks.ANCIENT_METAL_DOOR, "Ancient Metal Door");
        translationBuilder.add(AtBlocks.MITHRIL_DOOR, "Mithril Door");
        translationBuilder.add(AtBlocks.SILVER_DOOR, "Silver Door");
        translationBuilder.add(AtBlocks.GOLDEN_DOOR, "Gold Door");

        translationBuilder.add(AtItems.ADAMANTIUM_FISHING_ROD, "Adamantium Fishing Rod");
        translationBuilder.add(AtItems.ANCIENT_METAL_FISHING_ROD, "Ancient Metal Fishing Rod");
        translationBuilder.add(AtItems.MITHRIL_FISHING_ROD, "Mithril Fishing Rod");
        translationBuilder.add(AtItems.SILVER_FISHING_ROD, "Silver Fishing Rod");
        translationBuilder.add(AtItems.GOLDEN_FISHING_ROD, "Gold Fishing Rod");
        translationBuilder.add(AtItems.COPPER_FISHING_ROD, "Copper Fishing Rod");
        translationBuilder.add(AtItems.IRON_FISHING_ROD, "Iron Fishing Rod");
        translationBuilder.add(AtItems.FLINT_FISHING_ROD, "Flint Fishing Rod");
        translationBuilder.add(AtItems.OBSIDIAN_FISHING_ROD, "Obsidian Fishing Rod");

        translationBuilder.add(AtItems.RAW_ADAMANTIUM, "Raw Adamantium");
        translationBuilder.add(AtItems.RAW_MITHRIL, "Raw Mithril");
        translationBuilder.add(AtItems.RAW_SILVER, "Raw Silver");

        translationBuilder.add(AtItems.ADAMANTIUM_INGOT, "Adamantium Ingot");
        translationBuilder.add(AtItems.ANCIENT_METAL_INGOT, "Ancient Metal Ingot");
        translationBuilder.add(AtItems.MITHRIL_INGOT, "Mithril Ingot");
        translationBuilder.add(AtItems.SILVER_INGOT, "Silver Ingot");

        translationBuilder.add(AtItems.ADAMANTIUM_NUGGET, "Adamantium Nugget");
        translationBuilder.add(AtItems.ANCIENT_METAL_NUGGET, "Ancient Metal Nugget");
        translationBuilder.add(AtItems.MITHRIL_NUGGET, "Mithril Nugget");
        translationBuilder.add(AtItems.SILVER_NUGGET, "Silver Nugget");
        translationBuilder.add(AtItems.COPPER_NUGGET, "Copper Nugget");

        translationBuilder.add(AtItems.DIAMOND_SHARD, "Diamond Shard");
        translationBuilder.add(AtItems.EMERALD_SHARD, "Emerald Shard");
        translationBuilder.add(AtItems.FLINT_SHARD, "Flint Shard");
        translationBuilder.add(AtItems.GLASS_SHARD, "Glass Shard");
        translationBuilder.add(AtItems.OBSIDIAN_SHARD, "Obsidian Shard");
        translationBuilder.add(AtItems.QUARTZ_SHARD, "Quartz Shard");

        translationBuilder.add(AtBlocks.ADAMANTIUM_ANVIL,"Adamantium Anvil");
        translationBuilder.add(AtBlocks.CHIPPED_ADAMANTIUM_ANVIL,"Chipped Adamantium Anvil");
        translationBuilder.add(AtBlocks.DAMAGED_ADAMANTIUM_ANVIL,"Damaged Adamantium Anvil");
        translationBuilder.add(AtBlocks.MITHRIL_ANVIL,"Mithril Anvil");
        translationBuilder.add(AtBlocks.CHIPPED_MITHRIL_ANVIL,"Chipped Mithril Anvil");
        translationBuilder.add(AtBlocks.DAMAGED_MITHRIL_ANVIL,"Damaged Mithril Anvil");
        translationBuilder.add(AtBlocks.ANCIENT_METAL_ANVIL,"Ancient Metal Anvil");
        translationBuilder.add(AtBlocks.CHIPPED_ANCIENT_METAL_ANVIL,"Chipped Ancient Metal Anvil");
        translationBuilder.add(AtBlocks.DAMAGED_ANCIENT_METAL_ANVIL,"Damaged Ancient Metal Anvil");
        translationBuilder.add(AtBlocks.SILVER_ANVIL,"Silver Anvil");
        translationBuilder.add(AtBlocks.CHIPPED_SILVER_ANVIL,"chipped Silver Anvil");
        translationBuilder.add(AtBlocks.DAMAGED_SILVER_ANVIL,"damaged Silver Anvil");
        translationBuilder.add(AtBlocks.GOLDEN_ANVIL,"Gold Anvil");
        translationBuilder.add(AtBlocks.CHIPPED_GOLDEN_ANVIL,"Chipped Gold Anvil");
        translationBuilder.add(AtBlocks.DAMAGED_GOLDEN_ANVIL,"Damaged Gold Anvil");
        translationBuilder.add(AtBlocks.COPPER_ANVIL,"Copper Anvil");
        translationBuilder.add(AtBlocks.CHIPPED_COPPER_ANVIL,"Chipped Copper Anvil");
        translationBuilder.add(AtBlocks.DAMAGED_COPPER_ANVIL,"Damaged Copper Anvil");
        
        translationBuilder.add(AtBlocks.MITHRIL_NUL_RUNESTORE, "Mithril Nul Runestone");
        translationBuilder.add(AtBlocks.MITHRIL_QUAS_RUNESTORE, "Mithril Quas Runestone");
        translationBuilder.add(AtBlocks.MITHRIL_POR_RUNESTORE, "Mithril Por Runestone");
        translationBuilder.add(AtBlocks.MITHRIL_AN_RUNESTORE, "Mithril An Runestone");
        translationBuilder.add(AtBlocks.MITHRIL_NOX_RUNESTORE, "Mithril Nox Runestone");
        translationBuilder.add(AtBlocks.MITHRIL_FLAM_RUNESTORE, "Mithril Flam Runestone");
        translationBuilder.add(AtBlocks.MITHRIL_VAS_RUNESTORE, "Mithril Vas Runestone");
        translationBuilder.add(AtBlocks.MITHRIL_DES_RUNESTORE, "Mithril Des Runestone");
        translationBuilder.add(AtBlocks.MITHRIL_ORT_RUNESTORE, "Mithril Ort Runestone");
        translationBuilder.add(AtBlocks.MITHRIL_TYM_RUNESTORE, "Mithril Typ Runestone");
        translationBuilder.add(AtBlocks.MITHRIL_CORP_RUNESTORE, "Mithril Corp Runestone");
        translationBuilder.add(AtBlocks.MITHRIL_LOR_RUNESTORE, "Mithril Lor Runestone");
        translationBuilder.add(AtBlocks.MITHRIL_MANI_RUNESTORE, "Mithril Mani Runestone");
        translationBuilder.add(AtBlocks.MITHRIL_JUX_RUNESTORE, "Mithril Jux Runestone");
        translationBuilder.add(AtBlocks.MITHRIL_YLEM_RUNESTORE, "Mithril Ylem Runestone");
        translationBuilder.add(AtBlocks.MITHRIL_SANCT_RUNESTORE, "Mithril Sanct Runestone");
        
        translationBuilder.add(AtBlocks.ADAMANTIUM_NUL_RUNESTORE, "Adamantium Nul Runestone");
        translationBuilder.add(AtBlocks.ADAMANTIUM_QUAS_RUNESTORE, "Adamantium Quas Runestone");
        translationBuilder.add(AtBlocks.ADAMANTIUM_POR_RUNESTORE, "Adamantium Por Runestone");
        translationBuilder.add(AtBlocks.ADAMANTIUM_AN_RUNESTORE, "Adamantium An Runestone");
        translationBuilder.add(AtBlocks.ADAMANTIUM_NOX_RUNESTORE, "Adamantium Nox Runestone");
        translationBuilder.add(AtBlocks.ADAMANTIUM_FLAM_RUNESTORE, "Adamantium Flam Runestone");
        translationBuilder.add(AtBlocks.ADAMANTIUM_VAS_RUNESTORE, "Adamantium Vas Runestone");
        translationBuilder.add(AtBlocks.ADAMANTIUM_DES_RUNESTORE, "Adamantium Des Runestone");
        translationBuilder.add(AtBlocks.ADAMANTIUM_ORT_RUNESTORE, "Adamantium Ort Runestone");
        translationBuilder.add(AtBlocks.ADAMANTIUM_TYM_RUNESTORE, "Adamantium Typ Runestone");
        translationBuilder.add(AtBlocks.ADAMANTIUM_CORP_RUNESTORE, "Adamantium Corp Runestone");
        translationBuilder.add(AtBlocks.ADAMANTIUM_LOR_RUNESTORE, "Adamantium Lor Runestone");
        translationBuilder.add(AtBlocks.ADAMANTIUM_MANI_RUNESTORE, "Adamantium Mani Runestone");
        translationBuilder.add(AtBlocks.ADAMANTIUM_JUX_RUNESTORE, "Adamantium Jux Runestone");
        translationBuilder.add(AtBlocks.ADAMANTIUM_YLEM_RUNESTORE, "Adamantium Ylem Runestone");
        translationBuilder.add(AtBlocks.ADAMANTIUM_SANCT_RUNESTORE, "Adamantium Sanct Runestone");

        translationBuilder.add(AtBlocks.ADAMANTIUM_CRAFTING_TABLE, "Adamantium Crafting Table");
        translationBuilder.add(AtBlocks.ANCIENT_METAL_CRAFTING_TABLE, "Ancient Metal Crafting Table");
        translationBuilder.add(AtBlocks.COPPER_CRAFTING_TABLE, "Copper Crafting Table");
        translationBuilder.add(AtBlocks.GOLD_CRAFTING_TABLE, "Gold Crafting Table");
        translationBuilder.add(AtBlocks.IRON_CRAFTING_TABLE, "Iron Crafting Table");
        translationBuilder.add(AtBlocks.MITHRIL_CRAFTING_TABLE, "Mithril Crafting Table");
        translationBuilder.add(AtBlocks.SILVER_CRAFTING_TABLE, "Silver Crafting Table");
        translationBuilder.add(AtBlocks.FLINT_CRAFTING_TABLE, "Flint Crafting Table");
        translationBuilder.add(AtBlocks.OBSIDIAN_CRAFTING_TABLE, "Obsidian Crafting Table");

        translationBuilder.add(AtBlocks.CLAY_FURNACE, "Clay Furnace");
        translationBuilder.add(AtBlocks.HARDENED_CLAY_FURNACE, "Hardened Clay Furnace");
        translationBuilder.add(AtBlocks.NETHERRACK_FURNACE, "Netherrack Furnace");
        translationBuilder.add(AtBlocks.OBSIDIAN_FURNACE, "Obsidian Furnace");
        translationBuilder.add(AtBlocks.SANDSTONE_FURNACE, "Sandstone Furnace");

        translationBuilder.add(AtItems.SINEW, "Leather Thread");
    }
}
