package com.acuteterror233.mite.datagen;

import com.acuteterror233.mite.item.AtItems;
import com.acuteterror233.mite.registry.tag.AtTags;
import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricTagProvider;
import net.minecraft.item.Items;
import net.minecraft.registry.RegistryWrapper;
import net.minecraft.registry.tag.ItemTags;

import java.util.concurrent.CompletableFuture;

public class ItemTagProvider extends FabricTagProvider.ItemTagProvider {
    public ItemTagProvider(FabricDataOutput output, CompletableFuture<RegistryWrapper.WrapperLookup> completableFuture) {
        super(output, completableFuture);
    }

    @Override
    protected void configure(RegistryWrapper.WrapperLookup wrapperLookup) {
        getOrCreateTagBuilder(ItemTags.HEAD_ARMOR)
                .add(AtItems.ADAMANTIUM_HELMET)
                .add(AtItems.ADAMANTIUM_CHAINMAIL_HELMET)
                .add(AtItems.ANCIENT_METAL_HELMET)
                .add(AtItems.ANCIENT_METAL_CHAINMAIL_HELMET)
                .add(AtItems.COPPER_HELMET)
                .add(AtItems.COPPER_CHAINMAIL_HELMET)
                .add(AtItems.MITHRIL_HELMET)
                .add(AtItems.MITHRIL_CHAINMAIL_HELMET)
                .add(AtItems.RUSTED_IRON_HELMET)
                .add(AtItems.RUSTED_IRON_CHAINMAIL_HELMET)
                .add(AtItems.SILVER_HELMET)
                .add(AtItems.SILVER_CHAINMAIL_HELMET)
                .add(AtItems.GOLD_CHAINMAIL_HELMET);
        getOrCreateTagBuilder(ItemTags.CHEST_ARMOR)
                .add(AtItems.ADAMANTIUM_CHESTPLATE)
                .add(AtItems.ADAMANTIUM_CHAINMAIL_CHESTPLATE)
                .add(AtItems.ANCIENT_METAL_CHESTPLATE)
                .add(AtItems.ANCIENT_METAL_CHAINMAIL_CHESTPLATE)
                .add(AtItems.COPPER_CHESTPLATE)
                .add(AtItems.COPPER_CHAINMAIL_CHESTPLATE)
                .add(AtItems.MITHRIL_CHESTPLATE)
                .add(AtItems.MITHRIL_CHAINMAIL_CHESTPLATE)
                .add(AtItems.RUSTED_IRON_CHESTPLATE)
                .add(AtItems.RUSTED_IRON_CHAINMAIL_CHESTPLATE)
                .add(AtItems.SILVER_CHESTPLATE)
                .add(AtItems.SILVER_CHAINMAIL_CHESTPLATE)
                .add(AtItems.GOLD_CHAINMAIL_CHESTPLATE);
        getOrCreateTagBuilder(ItemTags.LEG_ARMOR)
                .add(AtItems.ADAMANTIUM_LEGGINGS)
                .add(AtItems.ADAMANTIUM_CHAINMAIL_LEGGINGS)
                .add(AtItems.ANCIENT_METAL_LEGGINGS)
                .add(AtItems.ANCIENT_METAL_CHAINMAIL_LEGGINGS)
                .add(AtItems.COPPER_LEGGINGS)
                .add(AtItems.COPPER_CHAINMAIL_LEGGINGS)
                .add(AtItems.MITHRIL_LEGGINGS)
                .add(AtItems.MITHRIL_CHAINMAIL_LEGGINGS)
                .add(AtItems.RUSTED_IRON_LEGGINGS)
                .add(AtItems.RUSTED_IRON_CHAINMAIL_LEGGINGS)
                .add(AtItems.SILVER_LEGGINGS)
                .add(AtItems.SILVER_CHAINMAIL_LEGGINGS)
                .add(AtItems.GOLD_CHAINMAIL_LEGGINGS);
        getOrCreateTagBuilder(ItemTags.FOOT_ARMOR)
                .add(AtItems.ADAMANTIUM_BOOTS)
                .add(AtItems.ADAMANTIUM_CHAINMAIL_BOOTS)
                .add(AtItems.ANCIENT_METAL_BOOTS)
                .add(AtItems.ANCIENT_METAL_CHAINMAIL_BOOTS)
                .add(AtItems.COPPER_BOOTS)
                .add(AtItems.COPPER_CHAINMAIL_BOOTS)
                .add(AtItems.MITHRIL_BOOTS)
                .add(AtItems.MITHRIL_CHAINMAIL_BOOTS)
                .add(AtItems.RUSTED_IRON_BOOTS)
                .add(AtItems.RUSTED_IRON_CHAINMAIL_BOOTS)
                .add(AtItems.SILVER_BOOTS)
                .add(AtItems.SILVER_CHAINMAIL_BOOTS)
                .add(AtItems.GOLD_CHAINMAIL_BOOTS);
        getOrCreateTagBuilder(AtTags.WATER_BUCKET)
                .add(AtItems.WATER_ADAMANTIUM_BUCKET)
                .add(AtItems.WATER_ANCIENT_METAL_BUCKET)
                .add(AtItems.WATER_COPPER_BUCKET)
                .add(AtItems.WATER_GOLD_BUCKET)
                .add(AtItems.WATER_MITHRIL_BUCKET)
                .add(AtItems.WATER_SILVER_BUCKET)
                .add(AtItems.WATER_NETHERITE_BUCKET)
                .add(Items.WATER_BUCKET);
        getOrCreateTagBuilder(AtTags.FISHING_RODS)
                .add(AtItems.ADAMANTIUM_FISHING_ROD)
                .add(AtItems.ANCIENT_METAL_FISHING_ROD)
                .add(AtItems.COPPER_FISHING_ROD)
                .add(AtItems.MITHRIL_FISHING_ROD)
                .add(AtItems.GOLD_FISHING_ROD)
                .add(AtItems.IRON_FISHING_ROD)
                .add(AtItems.SILVER_FISHING_ROD)
                .add(AtItems.FLINT_FISHING_ROD)
                .add(AtItems.OBSIDIAN_FISHING_ROD)
                .add(Items.FISHING_ROD);
        getOrCreateTagBuilder(AtTags.NUGGET)
                .add(Items.IRON_NUGGET)
                .add(Items.GOLD_NUGGET)
                .add(AtItems.ADAMANTIUM_NUGGET)
                .add(AtItems.ANCIENT_METAL_NUGGET)
                .add(AtItems.MITHRIL_NUGGET)
                .add(AtItems.SILVER_NUGGET);
        getOrCreateTagBuilder(AtTags.SHARD)
                .add(AtItems.DIAMOND_SHARD)
                .add(AtItems.EMERALD_SHARD)
                .add(AtItems.FLINT_SHARD)
                .add(AtItems.GLASS_SHARD)
                .add(AtItems.OBSIDIAN_SHARD)
                .add(AtItems.QUARTZ_SHARD);
        getOrCreateTagBuilder(AtTags.INGOT)
                .add(Items.IRON_INGOT)
                .add(Items.GOLD_INGOT)
                .add(Items.NETHERITE_INGOT)
                .add(Items.COPPER_INGOT)
                .add(AtItems.ADAMANTIUM_INGOT)
                .add(AtItems.ANCIENT_METAL_INGOT)
                .add(AtItems.MITHRIL_INGOT)
                .add(AtItems.SILVER_INGOT);
        getOrCreateTagBuilder(ItemTags.ARROWS)
                .add(AtItems.ADAMANTIUM_ARROW)
                .add(AtItems.ANCIENT_METAL_ARROW)
                .add(AtItems.COPPER_ARROW)
                .add(AtItems.MITHRIL_ARROW)
                .add(AtItems.RUSTED_IRON_ARROW)
                .add(AtItems.SILVER_ARROW)
                .add(AtItems.GOLD_ARROW)
                .add(AtItems.IRON_ARROW)
                .add(AtItems.FLINT_ARROW)
                .add(AtItems.OBSIDIAN_ARROW);
        getOrCreateTagBuilder(AtTags.CHAINS)
                .add(AtItems.ADAMANTIUM_CHAINS)
                .add(AtItems.ANCIENT_METAL_CHAINS)
                .add(AtItems.COPPER_CHAINS)
                .add(AtItems.MITHRIL_CHAINS)
                .add(AtItems.RUSTED_IRON_CHAINS)
                .add(AtItems.SILVER_CHAINS)
                .add(AtItems.GOLD_CHAINS)
                .add(AtItems.IRON_CHAINS);
        getOrCreateTagBuilder(AtTags.COINS)
                .add(AtItems.ADAMANTIUM_COINS)
                .add(AtItems.ANCIENT_METAL_COINS)
                .add(AtItems.COPPER_COINS)
                .add(AtItems.MITHRIL_COINS)
                .add(AtItems.GOLD_COINS)
                .add(AtItems.SILVER_COINS)
                .add(AtItems.IRON_COINS);
        getOrCreateTagBuilder(AtTags.ITEM_COUNT_1)
                .add(Items.NETHER_STAR)
                .add(Items.HEART_OF_THE_SEA)
                .add(Items.DRAGON_BREATH)
                .add(Items.DRAGON_EGG)
                .add(Items.COMPASS)
                .add(Items.RECOVERY_COMPASS)
                .add(Items.CLOCK);
        getOrCreateTagBuilder(AtTags.ITEM_COUNT_8)
                .add(Items.FLINT)
                .add(Items.LEATHER)
                .add(Items.INK_SAC)
                .add(Items.GLOW_INK_SAC)
                .add(Items.TURTLE_SCUTE)
                .add(Items.ARMADILLO_SCUTE)
                .add(Items.RABBIT_HIDE)
                .add(Items.ITEM_FRAME)
                .add(Items.GLOW_ITEM_FRAME)
                .add(Items.SUGAR);
        getOrCreateTagBuilder(AtTags.ITEM_COUNT_16)
                .add(Items.COAL)
                .add(Items.CHARCOAL)
                .add(Items.EMERALD)
                .add(Items.AMETHYST_SHARD)
                .add(Items.NETHERITE_SCRAP)
                .add(Items.WHEAT)
                .add(Items.BONE)
                .add(Items.CLAY_BALL)
                .add(Items.GOLDEN_CARROT)
                .add(Items.GHAST_TEAR)
                .add(Items.EXPERIENCE_BOTTLE)
                .add(Items.TORCH)
                .add(Items.SOUL_TORCH)
                .add(Items.REDSTONE_TORCH)
                .add(Items.LANTERN)
                .add(Items.SOUL_LANTERN)
                .add(Items.CHAIN)
                .add(Items.ENDER_EYE)
                .add(Items.FEATHER)
                .add(Items.APPLE)
                .add(Items.GOLDEN_APPLE)
                .add(Items.ENCHANTED_GOLDEN_APPLE)
                .addTag(ItemTags.ARROWS)
                .addTag(AtTags.COINS)
                .addTag(AtTags.CHAINS);
        getOrCreateTagBuilder(AtTags.ITEM_COUNT_32)
                .add(Items.LAPIS_LAZULI)
                .add(Items.QUARTZ)
                .add(Items.STICK)
                .add(Items.BONE_MEAL)
                .add(Items.STRING)
                .add(Items.REDSTONE)
                .add(Items.GLOWSTONE_DUST)
                .add(Items.GUNPOWDER)
                .add(Items.MELON_SLICE)
                .addTag(AtTags.NUGGET)
                .addTag(AtTags.SHARD);
        getOrCreateTagBuilder(AtTags.ADAMANTIUM_SERIES_REPAIRABLE)
                .add(AtItems.ADAMANTIUM_AXE)
                .add(AtItems.ADAMANTIUM_HATCHET)
                .add(AtItems.ADAMANTIUM_PICKAXE)
                .add(AtItems.ADAMANTIUM_SHOVEL)
                .add(AtItems.ADAMANTIUM_HOE)
                .add(AtItems.ADAMANTIUM_MATTOCK)
                .add(AtItems.ADAMANTIUM_SCYTHE)
                .add(AtItems.ADAMANTIUM_SHEARS)
                .add(AtItems.ADAMANTIUM_FISHING_ROD)
                .add(AtItems.ADAMANTIUM_DAGGER)
                .add(AtItems.ADAMANTIUM_SWORD)
                .add(AtItems.ADAMANTIUM_WAR_HAMMER)
                .add(AtItems.ADAMANTIUM_BATTLE_AXE)
                .add(AtItems.ADAMANTIUM_HELMET)
                .add(AtItems.ADAMANTIUM_CHAINMAIL_HELMET)
                .add(AtItems.ADAMANTIUM_CHESTPLATE)
                .add(AtItems.ADAMANTIUM_CHAINMAIL_CHESTPLATE)
                .add(AtItems.ADAMANTIUM_LEGGINGS)
                .add(AtItems.ADAMANTIUM_CHAINMAIL_LEGGINGS)
                .add(AtItems.ADAMANTIUM_BOOTS)
                .add(AtItems.ADAMANTIUM_CHAINMAIL_BOOTS);
        getOrCreateTagBuilder(AtTags.MITHRIL_SERIES_REPAIRABLE)
                .add(AtItems.MITHRIL_AXE)
                .add(AtItems.MITHRIL_HATCHET)
                .add(AtItems.MITHRIL_PICKAXE)
                .add(AtItems.MITHRIL_SHOVEL)
                .add(AtItems.MITHRIL_HOE)
                .add(AtItems.MITHRIL_MATTOCK)
                .add(AtItems.MITHRIL_SCYTHE)
                .add(AtItems.MITHRIL_SHEARS)
                .add(AtItems.MITHRIL_FISHING_ROD)
                .add(AtItems.MITHRIL_DAGGER)
                .add(AtItems.MITHRIL_SWORD)
                .add(AtItems.MITHRIL_WAR_HAMMER)
                .add(AtItems.MITHRIL_BATTLE_AXE)
                .add(AtItems.MITHRIL_HELMET)
                .add(AtItems.MITHRIL_CHAINMAIL_HELMET)
                .add(AtItems.MITHRIL_CHESTPLATE)
                .add(AtItems.MITHRIL_CHAINMAIL_CHESTPLATE)
                .add(AtItems.MITHRIL_LEGGINGS)
                .add(AtItems.MITHRIL_CHAINMAIL_LEGGINGS)
                .add(AtItems.MITHRIL_BOOTS)
                .add(AtItems.MITHRIL_CHAINMAIL_BOOTS);
        getOrCreateTagBuilder(AtTags.ANCIENT_METAL_SERIES_REPAIRABLE)
                .add(AtItems.ANCIENT_METAL_AXE)
                .add(AtItems.ANCIENT_METAL_HATCHET)
                .add(AtItems.ANCIENT_METAL_PICKAXE)
                .add(AtItems.ANCIENT_METAL_SHOVEL)
                .add(AtItems.ANCIENT_METAL_HOE)
                .add(AtItems.ANCIENT_METAL_MATTOCK)
                .add(AtItems.ANCIENT_METAL_SCYTHE)
                .add(AtItems.ANCIENT_METAL_SHEARS)
                .add(AtItems.ANCIENT_METAL_FISHING_ROD)
                .add(AtItems.ANCIENT_METAL_DAGGER)
                .add(AtItems.ANCIENT_METAL_SWORD)
                .add(AtItems.ANCIENT_METAL_WAR_HAMMER)
                .add(AtItems.ANCIENT_METAL_BATTLE_AXE)
                .add(AtItems.ANCIENT_METAL_HELMET)
                .add(AtItems.ANCIENT_METAL_CHAINMAIL_HELMET)
                .add(AtItems.ANCIENT_METAL_CHESTPLATE)
                .add(AtItems.ANCIENT_METAL_CHAINMAIL_CHESTPLATE)
                .add(AtItems.ANCIENT_METAL_LEGGINGS)
                .add(AtItems.ANCIENT_METAL_CHAINMAIL_LEGGINGS)
                .add(AtItems.ANCIENT_METAL_BOOTS)
                .add(AtItems.ANCIENT_METAL_CHAINMAIL_BOOTS);
//        getOrCreateTagBuilder(AtTags.GOLD_SERIES_REPAIRABLE)
//                .add(AtItems.GOLD_AXE)
//                .add(AtItems.GOLD_HATCHET)
//                .add(AtItems.GOLD_PICKAXE)
//                .add(AtItems.GOLD_SHOVEL)
//                .add(AtItems.GOLD_HOE)
//                .add(AtItems.GOLD_MATTOCK)
//                .add(AtItems.GOLD_SCYTHE)
//                .add(AtItems.GOLD_SHEARS)
//                .add(AtItems.GOLD_FISHING_ROD)
//                .add(AtItems.GOLD_DAGGER)
//                .add(AtItems.GOLD_SWORD)
//                .add(AtItems.GOLD_WAR_HAMMER)
//                .add(AtItems.GOLD_BATTLE_AXE)
//                .add(AtItems.GOLD_HELMET)
//                .add(AtItems.GOLD_CHAINMAIL_HELMET)
//                .add(AtItems.GOLD_CHESTPLATE)
//                .add(AtItems.GOLD_CHAINMAIL_CHESTPLATE)
//                .add(AtItems.GOLD_LEGGINGS)
//                .add(AtItems.GOLD_CHAINMAIL_LEGGINGS)
//                .add(AtItems.GOLD_BOOTS)
//                .add(AtItems.GOLD_CHAINMAIL_BOOTS);
    }
}
