package com.acuteterror233.mite.datagen;

import com.acuteterror233.mite.block.MMEBlocks;
import com.acuteterror233.mite.registry.tag.MMETags;
import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricTagProvider;
import net.minecraft.core.HolderLookup;
import net.minecraft.tags.BlockTags;
import net.minecraft.world.level.block.Blocks;

import java.util.concurrent.CompletableFuture;

public class MMEBlockTagProvider extends FabricTagProvider.BlockTagProvider {
    public MMEBlockTagProvider(FabricDataOutput output, CompletableFuture<HolderLookup.Provider> registriesFuture) {
        super(output, registriesFuture);
    }

    @Override
    protected void addTags(HolderLookup.Provider wrapperLookup) {
        this.valueLookupBuilder(BlockTags.DOORS)
                .add(MMEBlocks.GOLDEN_DOOR)
                .add(MMEBlocks.SILVER_DOOR)
                .add(MMEBlocks.MITHRIL_DOOR)
                .add(MMEBlocks.ANCIENT_METAL_DOOR)
                .add(MMEBlocks.ADAMANTIUM_DOOR);
        this.valueLookupBuilder(MMETags.GLASS)
                .add(Blocks.GLASS)
                .add(Blocks.WHITE_STAINED_GLASS)
                .add(Blocks.ORANGE_STAINED_GLASS)
                .add(Blocks.MAGENTA_STAINED_GLASS)
                .add(Blocks.LIGHT_BLUE_STAINED_GLASS)
                .add(Blocks.YELLOW_STAINED_GLASS)
                .add(Blocks.LIME_STAINED_GLASS)
                .add(Blocks.PINK_STAINED_GLASS)
                .add(Blocks.GRAY_STAINED_GLASS)
                .add(Blocks.LIGHT_GRAY_STAINED_GLASS)
                .add(Blocks.CYAN_STAINED_GLASS)
                .add(Blocks.PURPLE_STAINED_GLASS)
                .add(Blocks.BLUE_STAINED_GLASS)
                .add(Blocks.BROWN_STAINED_GLASS)
                .add(Blocks.GREEN_STAINED_GLASS)
                .add(Blocks.RED_STAINED_GLASS)
                .add(Blocks.BLACK_STAINED_GLASS)
                .add(Blocks.TINTED_GLASS);
        this.valueLookupBuilder(MMETags.GLASS_PANE)
                .add(Blocks.GLASS_PANE)
                .add(Blocks.WHITE_STAINED_GLASS_PANE)
                .add(Blocks.ORANGE_STAINED_GLASS_PANE)
                .add(Blocks.MAGENTA_STAINED_GLASS_PANE)
                .add(Blocks.LIGHT_BLUE_STAINED_GLASS_PANE)
                .add(Blocks.YELLOW_STAINED_GLASS_PANE)
                .add(Blocks.LIME_STAINED_GLASS_PANE)
                .add(Blocks.PINK_STAINED_GLASS_PANE)
                .add(Blocks.GRAY_STAINED_GLASS_PANE)
                .add(Blocks.LIGHT_GRAY_STAINED_GLASS_PANE)
                .add(Blocks.CYAN_STAINED_GLASS_PANE)
                .add(Blocks.PURPLE_STAINED_GLASS_PANE)
                .add(Blocks.BLUE_STAINED_GLASS_PANE)
                .add(Blocks.BROWN_STAINED_GLASS_PANE)
                .add(Blocks.GREEN_STAINED_GLASS_PANE)
                .add(Blocks.RED_STAINED_GLASS_PANE)
                .add(Blocks.BLACK_STAINED_GLASS_PANE);
        this.valueLookupBuilder(MMETags.BARS)
                .add(Blocks.IRON_BARS)
                .add(MMEBlocks.ADAMANTIUM_BARS)
                .add(MMEBlocks.ANCIENT_METAL_BARS)
                .add(MMEBlocks.GOLDEN_BARS)
                .add(MMEBlocks.MITHRIL_BARS)
                .add(MMEBlocks.SILVER_BARS)
                .add(MMEBlocks.COPPER_BARS);
        this.valueLookupBuilder(BlockTags.ANVIL)
                .add(MMEBlocks.NETHERITE_ANVIL)
                .add(MMEBlocks.CHIPPED_NETHERITE_ANVIL)
                .add(MMEBlocks.DAMAGED_NETHERITE_ANVIL)
                .add(MMEBlocks.ADAMANTIUM_ANVIL)
                .add(MMEBlocks.CHIPPED_ADAMANTIUM_ANVIL)
                .add(MMEBlocks.DAMAGED_ADAMANTIUM_ANVIL)
                .add(MMEBlocks.MITHRIL_ANVIL)
                .add(MMEBlocks.CHIPPED_MITHRIL_ANVIL)
                .add(MMEBlocks.DAMAGED_MITHRIL_ANVIL)
                .add(MMEBlocks.ANCIENT_METAL_ANVIL)
                .add(MMEBlocks.CHIPPED_ANCIENT_METAL_ANVIL)
                .add(MMEBlocks.DAMAGED_ANCIENT_METAL_ANVIL)
                .add(MMEBlocks.SILVER_ANVIL)
                .add(MMEBlocks.CHIPPED_SILVER_ANVIL)
                .add(MMEBlocks.DAMAGED_SILVER_ANVIL)
                .add(MMEBlocks.GOLDEN_ANVIL)
                .add(MMEBlocks.CHIPPED_GOLDEN_ANVIL)
                .add(MMEBlocks.DAMAGED_GOLDEN_ANVIL)
                .add(MMEBlocks.COPPER_ANVIL)
                .add(MMEBlocks.CHIPPED_COPPER_ANVIL)
                .add(MMEBlocks.DAMAGED_COPPER_ANVIL);
        this.valueLookupBuilder(MMETags.INTACT_ANVIL)
                .add(MMEBlocks.NETHERITE_ANVIL)
                .add(MMEBlocks.ADAMANTIUM_ANVIL)
                .add(MMEBlocks.MITHRIL_ANVIL)
                .add(MMEBlocks.ANCIENT_METAL_ANVIL)
                .add(MMEBlocks.SILVER_ANVIL)
                .add(MMEBlocks.GOLDEN_ANVIL)
                .add(MMEBlocks.COPPER_ANVIL);
        this.valueLookupBuilder(MMETags.CHIPPED_ANVIL)
                .add(MMEBlocks.CHIPPED_NETHERITE_ANVIL)
                .add(MMEBlocks.CHIPPED_ADAMANTIUM_ANVIL)
                .add(MMEBlocks.CHIPPED_MITHRIL_ANVIL)
                .add(MMEBlocks.CHIPPED_ANCIENT_METAL_ANVIL)
                .add(MMEBlocks.CHIPPED_SILVER_ANVIL)
                .add(MMEBlocks.CHIPPED_GOLDEN_ANVIL)
                .add(MMEBlocks.CHIPPED_COPPER_ANVIL);
        this.valueLookupBuilder(MMETags.DAMAGED_ANVIL)
                .add(MMEBlocks.DAMAGED_NETHERITE_ANVIL)
                .add(MMEBlocks.DAMAGED_ADAMANTIUM_ANVIL)
                .add(MMEBlocks.DAMAGED_MITHRIL_ANVIL)
                .add(MMEBlocks.DAMAGED_ANCIENT_METAL_ANVIL)
                .add(MMEBlocks.DAMAGED_SILVER_ANVIL)
                .add(MMEBlocks.DAMAGED_GOLDEN_ANVIL)
                .add(MMEBlocks.DAMAGED_COPPER_ANVIL);
        this.valueLookupBuilder(MMETags.NETHERITE_ANVIL)
                .add(MMEBlocks.NETHERITE_ANVIL)
                .add(MMEBlocks.CHIPPED_NETHERITE_ANVIL)
                .add(MMEBlocks.DAMAGED_NETHERITE_ANVIL);
        this.valueLookupBuilder(MMETags.ADAMANTIUM_ANVIL)
                .add(MMEBlocks.ADAMANTIUM_ANVIL)
                .add(MMEBlocks.CHIPPED_ADAMANTIUM_ANVIL)
                .add(MMEBlocks.DAMAGED_ADAMANTIUM_ANVIL);
        this.valueLookupBuilder(MMETags.MITHRIL_ANVIL)
                .add(MMEBlocks.MITHRIL_ANVIL)
                .add(MMEBlocks.CHIPPED_MITHRIL_ANVIL)
                .add(MMEBlocks.DAMAGED_MITHRIL_ANVIL);
        this.valueLookupBuilder(MMETags.ANCIENT_METAL_ANVIL)
                .add(MMEBlocks.ANCIENT_METAL_ANVIL)
                .add(MMEBlocks.CHIPPED_ANCIENT_METAL_ANVIL)
                .add(MMEBlocks.DAMAGED_ANCIENT_METAL_ANVIL);
        this.valueLookupBuilder(MMETags.SILVER_ANVIL)
                .add(MMEBlocks.SILVER_ANVIL)
                .add(MMEBlocks.CHIPPED_SILVER_ANVIL)
                .add(MMEBlocks.DAMAGED_SILVER_ANVIL);
        this.valueLookupBuilder(MMETags.GOLDEN_ANVIL)
                .add(MMEBlocks.GOLDEN_ANVIL)
                .add(MMEBlocks.CHIPPED_GOLDEN_ANVIL)
                .add(MMEBlocks.DAMAGED_GOLDEN_ANVIL);
        this.valueLookupBuilder(MMETags.COPPER_ANVIL)
                .add(MMEBlocks.COPPER_ANVIL)
                .add(MMEBlocks.CHIPPED_COPPER_ANVIL)
                .add(MMEBlocks.DAMAGED_COPPER_ANVIL);
        this.valueLookupBuilder(MMETags.IRON_ANVIL)
                .add(Blocks.ANVIL)
                .add(Blocks.CHIPPED_ANVIL)
                .add(Blocks.DAMAGED_ANVIL);
        this.valueLookupBuilder(MMETags.PORTAL)
                .add(MMEBlocks.UNDERGROUND_PORTAL)
                .add(MMEBlocks.HOME_PORTAL)
                .add(MMEBlocks.RUNE_PORTAL)
                .add(Blocks.NETHER_PORTAL);
        this.valueLookupBuilder(MMETags.MITHRIL_RUNESTORE)
                .add(MMEBlocks.MITHRIL_NUL_RUNESTORE)
                .add(MMEBlocks.MITHRIL_QUAS_RUNESTORE)
                .add(MMEBlocks.MITHRIL_POR_RUNESTORE)
                .add(MMEBlocks.MITHRIL_AN_RUNESTORE)
                .add(MMEBlocks.MITHRIL_NOX_RUNESTORE)
                .add(MMEBlocks.MITHRIL_FLAM_RUNESTORE)
                .add(MMEBlocks.MITHRIL_VAS_RUNESTORE)
                .add(MMEBlocks.MITHRIL_DES_RUNESTORE)
                .add(MMEBlocks.MITHRIL_ORT_RUNESTORE)
                .add(MMEBlocks.MITHRIL_TYM_RUNESTORE)
                .add(MMEBlocks.MITHRIL_CORP_RUNESTORE)
                .add(MMEBlocks.MITHRIL_LOR_RUNESTORE)
                .add(MMEBlocks.MITHRIL_MANI_RUNESTORE)
                .add(MMEBlocks.MITHRIL_JUX_RUNESTORE)
                .add(MMEBlocks.MITHRIL_YLEM_RUNESTORE)
                .add(MMEBlocks.MITHRIL_SANCT_RUNESTORE);
        this.valueLookupBuilder(MMETags.ADAMANTIUM_RUNESTORE)
                .add(MMEBlocks.ADAMANTIUM_NUL_RUNESTORE)
                .add(MMEBlocks.ADAMANTIUM_QUAS_RUNESTORE)
                .add(MMEBlocks.ADAMANTIUM_POR_RUNESTORE)
                .add(MMEBlocks.ADAMANTIUM_AN_RUNESTORE)
                .add(MMEBlocks.ADAMANTIUM_NOX_RUNESTORE)
                .add(MMEBlocks.ADAMANTIUM_FLAM_RUNESTORE)
                .add(MMEBlocks.ADAMANTIUM_VAS_RUNESTORE)
                .add(MMEBlocks.ADAMANTIUM_DES_RUNESTORE)
                .add(MMEBlocks.ADAMANTIUM_ORT_RUNESTORE)
                .add(MMEBlocks.ADAMANTIUM_TYM_RUNESTORE)
                .add(MMEBlocks.ADAMANTIUM_CORP_RUNESTORE)
                .add(MMEBlocks.ADAMANTIUM_LOR_RUNESTORE)
                .add(MMEBlocks.ADAMANTIUM_MANI_RUNESTORE)
                .add(MMEBlocks.ADAMANTIUM_JUX_RUNESTORE)
                .add(MMEBlocks.ADAMANTIUM_YLEM_RUNESTORE)
                .add(MMEBlocks.ADAMANTIUM_SANCT_RUNESTORE);
        this.valueLookupBuilder(MMETags.RUNESTORE)
                .forceAddTag(MMETags.ADAMANTIUM_RUNESTORE)
                .forceAddTag(MMETags.MITHRIL_RUNESTORE);
        this.valueLookupBuilder(MMETags.CRAFTING_TABLE)
                .add(MMEBlocks.ADAMANTIUM_CRAFTING_TABLE)
                .add(MMEBlocks.MITHRIL_CRAFTING_TABLE)
                .add(MMEBlocks.ANCIENT_METAL_CRAFTING_TABLE)
                .add(MMEBlocks.IRON_CRAFTING_TABLE)
                .add(MMEBlocks.GOLD_CRAFTING_TABLE)
                .add(MMEBlocks.SILVER_CRAFTING_TABLE)
                .add(MMEBlocks.COPPER_CRAFTING_TABLE)
                .add(MMEBlocks.OBSIDIAN_CRAFTING_TABLE)
                .add(MMEBlocks.FLINT_CRAFTING_TABLE);
        this.valueLookupBuilder(MMETags.ENCHANTING_TABLE)
                .add(Blocks.ENCHANTING_TABLE)
                .add(MMEBlocks.EMERALD_ENCHANTING_TABLE);
        this.valueLookupBuilder(MMETags.MINEABLE_WITH_MATTOCK)
                .forceAddTag(BlockTags.MINEABLE_WITH_HOE)
                .forceAddTag(BlockTags.MINEABLE_WITH_SHOVEL);

        this.valueLookupBuilder(MMETags.NEEDS_ADAMANTIUM_TOOL)
                .add(Blocks.ANCIENT_DEBRIS)
                .add(Blocks.NETHERITE_BLOCK)
                .add(MMEBlocks.ADAMANTIUM_BLOCK)
                .add(MMEBlocks.ADAMANTIUM_BARS)
                .add(MMEBlocks.ADAMANTIUM_DOOR);
        this.valueLookupBuilder(MMETags.NEEDS_MITHRIL_TOOL)
                .add(MMEBlocks.MITHRIL_BLOCK)
                .add(MMEBlocks.MITHRIL_BARS)
                .add(MMEBlocks.MITHRIL_DOOR)
                .add(MMEBlocks.ADAMANTIUM_ORE)
                .add(MMEBlocks.DEEPSLATE_ADAMANTIUM_ORE);
        this.valueLookupBuilder(MMETags.NEEDS_ANCIENT_METAL_TOOL)
                .add(MMEBlocks.ANCIENT_METAL_BLOCK)
                .add(MMEBlocks.ANCIENT_METAL_BARS);
        this.valueLookupBuilder(BlockTags.NEEDS_IRON_TOOL)
                .add(MMEBlocks.MITHRIL_ORE)
                .add(MMEBlocks.DEEPSLATE_MITHRIL_ORE);
        this.valueLookupBuilder(MMETags.NEEDS_SILVER_OR_COPPER_TOOL)
                .add(MMEBlocks.SILVER_BLOCK)
                .add(MMEBlocks.SILVER_BARS)
                .add(MMEBlocks.SILVER_DOOR)
                .add(Blocks.COPPER_BLOCK)
                .add(MMEBlocks.COPPER_BARS)
                .forceAddTag(BlockTags.COPPER_ORES);

        this.valueLookupBuilder(MMETags.INCORRECT_FOR_FLINT_OR_OBSIDIAN_TOOL)
                .forceAddTag(MMETags.NEEDS_SILVER_OR_COPPER_TOOL)
                .forceAddTag(MMETags.NEEDS_ANCIENT_METAL_TOOL)
                .forceAddTag(MMETags.NEEDS_MITHRIL_TOOL)
                .forceAddTag(MMETags.NEEDS_ADAMANTIUM_TOOL)
                .forceAddTag(BlockTags.NEEDS_DIAMOND_TOOL)
                .forceAddTag(BlockTags.NEEDS_IRON_TOOL)
                .forceAddTag(BlockTags.NEEDS_STONE_TOOL);
        this.valueLookupBuilder(MMETags.INCORRECT_FOR_COPPER_OR_SILVER_TOOL)
                .forceAddTag(BlockTags.NEEDS_IRON_TOOL)
                .forceAddTag(BlockTags.NEEDS_DIAMOND_TOOL)
                .forceAddTag(MMETags.NEEDS_ANCIENT_METAL_TOOL)
                .forceAddTag(MMETags.NEEDS_MITHRIL_TOOL)
                .forceAddTag(MMETags.NEEDS_ADAMANTIUM_TOOL);
        this.valueLookupBuilder(MMETags.INCORRECT_FOR_RUSTED_IRON_TOOL)
                .forceAddTag(MMETags.NEEDS_ANCIENT_METAL_TOOL)
                .forceAddTag(MMETags.NEEDS_MITHRIL_TOOL)
                .forceAddTag(MMETags.NEEDS_ADAMANTIUM_TOOL);
        this.valueLookupBuilder(MMETags.INCORRECT_FOR_ANCIENT_METAL_TOOL)
                .forceAddTag(MMETags.NEEDS_MITHRIL_TOOL)
                .forceAddTag(MMETags.NEEDS_ADAMANTIUM_TOOL);
        this.valueLookupBuilder(MMETags.INCORRECT_FOR_MITHRIL_TOOL)
                .forceAddTag(MMETags.NEEDS_ADAMANTIUM_TOOL);
        this.valueLookupBuilder(MMETags.INCORRECT_FOR_ADAMANTIUM_TOOL);

        this.valueLookupBuilder(BlockTags.MINEABLE_WITH_PICKAXE)
                .add(MMEBlocks.ADAMANTIUM_ORE)
                .add(MMEBlocks.DEEPSLATE_ADAMANTIUM_ORE)
                .add(MMEBlocks.MITHRIL_ORE)
                .add(MMEBlocks.DEEPSLATE_MITHRIL_ORE)
                .add(MMEBlocks.SILVER_ORE)
                .add(MMEBlocks.DEEPSLATE_SILVER_ORE)
                .add(MMEBlocks.ADAMANTIUM_BARS)
                .add(MMEBlocks.MITHRIL_BARS)
                .add(MMEBlocks.ANCIENT_METAL_BARS)
                .add(MMEBlocks.GOLDEN_BARS)
                .add(MMEBlocks.SILVER_BARS)
                .add(MMEBlocks.COPPER_BARS)
                .add(MMEBlocks.ADAMANTIUM_BLOCK)
                .add(MMEBlocks.ANCIENT_METAL_BLOCK)
                .add(MMEBlocks.MITHRIL_BLOCK)
                .add(MMEBlocks.SILVER_BLOCK)
                .add(MMEBlocks.ADAMANTIUM_DOOR)
                .add(MMEBlocks.ANCIENT_METAL_DOOR)
                .add(MMEBlocks.MITHRIL_DOOR)
                .add(MMEBlocks.SILVER_DOOR)
                .add(MMEBlocks.GOLDEN_DOOR);
    }
}
