package com.acuteterror233.mite.datagen;

import com.acuteterror233.mite.block.MMEBlocks;
import com.acuteterror233.mite.item.MMEItems;
import com.acuteterror233.mite.item.enchantment.MMEEnchantments;
import com.acuteterror233.mite.world.effect.MMEMobEffects;
import com.acuteterror233.mite.world.entity.MMEEntityTypes;
import net.fabricmc.fabric.api.datagen.v1.FabricPackOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricLanguageProvider;
import net.minecraft.core.HolderLookup;
import org.jspecify.annotations.NonNull;

import java.util.concurrent.CompletableFuture;

public class MMELanguageProvider {
    /**
     * 英文语言文件生成器。
     * 为 MME 模组物品/方块生成英文翻译键值对。
     */
    public static class En_us extends FabricLanguageProvider {

        public En_us(FabricPackOutput dataOutput, CompletableFuture<HolderLookup.Provider> registryLookup) {
            super(dataOutput, "en_us", registryLookup);
        }

        @Override
        public void generateTranslations(HolderLookup.@NonNull Provider registryLookup, TranslationBuilder translationBuilder) {
            translationBuilder.add("itemGroup.mme.item_group", "Might Makes Everything");
            translationBuilder.add("mme.craftingTable.noAllowedCrafting", "§cThis item cannot be crafted§r");
            translationBuilder.add("mme.gradefurnac.fuelnotavailable", "§cThis furnace cannot burn this fuel§r");
            translationBuilder.add("mme.nugget.tooltip", "Right-click to make coins and store %dXP");
            translationBuilder.add("mme.coins.tooltip", "%d XP per use");
            translationBuilder.add("mme.nutrition.tooltip", "%s Current nutritional status:{fiber:%f, protein:%f, sugar:%f}");

            translationBuilder.add("mme.advancements.story.root.description", "Where the dream begins");
            translationBuilder.add("mme.advancements.story.wheat_seeds.title", "Scavenger");
            translationBuilder.add("mme.advancements.story.wheat_seeds.description", "Better than starving");
            translationBuilder.add("mme.advancements.story.egg.title", "Eat an Egg");
            translationBuilder.add("mme.advancements.story.egg.description", "Better than nothing");
            translationBuilder.add("mme.advancements.story.clay_furnace.title", "Clay Crafting");
            translationBuilder.add("mme.advancements.story.clay_furnace.description", "The simplest furnace");
            translationBuilder.add("mme.advancements.story.torch.title", "Let It Shine");
            translationBuilder.add("mme.advancements.story.torch.description", "Acquire a torch");
            translationBuilder.add("mme.advancements.story.flint.title", "Flint Seeker");
            translationBuilder.add("mme.advancements.story.flint.description", "The beginning of all tools");
            translationBuilder.add("mme.advancements.story.flint_hatchet.title", "Here's Johnny");
            translationBuilder.add("mme.advancements.story.flint_hatchet.description", "Unlock wood");
            translationBuilder.add("mme.advancements.story.log.title", "Get Wood");
            translationBuilder.add("mme.advancements.story.log.description", "Don't forget to replant saplings");
            translationBuilder.add("mme.advancements.story.crafting_table.title", "Is This? A Crafting Table!");
            translationBuilder.add("mme.advancements.story.crafting_table.description", "Unlock 3×3 crafting");
            translationBuilder.add("mme.advancements.story.flint_axe.title", "Lumberjack");
            translationBuilder.add("mme.advancements.story.flint_axe.description", "Axe pro max");
            translationBuilder.add("mme.advancements.story.flint_shovel.title", "Explore the Surface");
            translationBuilder.add("mme.advancements.story.flint_shovel.description", "Dig, dig, dig");
            translationBuilder.add("mme.advancements.story.cudgel.title", "Time to Fight");
            translationBuilder.add("mme.advancements.story.cudgel.description", "Maybe only good against skeletons");
            translationBuilder.add("mme.advancements.story.monster_hunter.title", "Monster Hunter");
            translationBuilder.add("mme.advancements.story.monster_hunter.description", "Kill a hostile mob");
            translationBuilder.add("mme.advancements.story.copper_nugget.title", "Precious Metal");
            translationBuilder.add("mme.advancements.story.copper_nugget.description", "So valuable");
            translationBuilder.add("mme.advancements.story.metal_crafting_table.title", "Metal Crafting Table");
            translationBuilder.add("mme.advancements.story.metal_crafting_table.description", "Doesn't seem to speed up crafting");
            translationBuilder.add("mme.advancements.story.better_armor.title", "Better Armor");
            translationBuilder.add("mme.advancements.story.better_armor.description", "Cold and shiny");
            translationBuilder.add("mme.advancements.story.pickaxe.title", "Time to Mine!");
            translationBuilder.add("mme.advancements.story.pickaxe.description", "Finally made it out");
            translationBuilder.add("mme.advancements.story.mine_stone.title", "The Lowest Grade Ore");
            translationBuilder.add("mme.advancements.story.mine_stone.description", "Acquire copper and silver ores");
            translationBuilder.add("mme.advancements.story.leather.title", "Matador");
            translationBuilder.add("mme.advancements.story.leather.description", "Acquire leather");
            translationBuilder.add("mme.advancements.story.leather_armor.title", "Stop Streaking!");
            translationBuilder.add("mme.advancements.story.leather_armor.description", "Acquire leather armor");
            translationBuilder.add("mme.advancements.story.fishing_go.title", "Time to Fish");
            translationBuilder.add("mme.advancements.story.fishing_go.description", "Acquire a fishing rod");
            translationBuilder.add("mme.advancements.story.delicious_fish.title", "Delicious Fish");
            translationBuilder.add("mme.advancements.story.delicious_fish.description", "Acquire a cooked fish");
            translationBuilder.add("mme.advancements.story.mithril.title", "Acquire Mithril");
            translationBuilder.add("mme.advancements.story.mithril.description", "Blue and shiny silver");
            translationBuilder.add("mme.advancements.story.shiny_gear.title", "Mithril Armor");
            translationBuilder.add("mme.advancements.story.shiny_gear.description", "Mithril armor can save your life");
            translationBuilder.add("mme.advancements.story.enter_the_underground.title", "Enter the Underground");
            translationBuilder.add("mme.advancements.story.enter_the_underground.description", "Deep and dark");

            translationBuilder.add("mme.advancements.underground.root.title", "Underground");
            translationBuilder.add("mme.advancements.underground.root.description", "Can't see your hand in front of your face");
            translationBuilder.add("mme.advancements.underground.find_mithril.title", "The Azure Legend");
            translationBuilder.add("mme.advancements.underground.find_mithril.description", "Acquire mithril ore");
            translationBuilder.add("mme.advancements.underground.smelt_mithril.title", "Blue-Silver Transformation");
            translationBuilder.add("mme.advancements.underground.smelt_mithril.description", "Smelt a mithril ingot");
            translationBuilder.add("mme.advancements.underground.find_ancient_metal.title", "Ancient Gift");
            translationBuilder.add("mme.advancements.underground.find_ancient_metal.description", "Acquire an ancient metal ingot");
            translationBuilder.add("mme.advancements.underground.ancient_metal_crafting_table.title", "Ancient Craft");
            translationBuilder.add("mme.advancements.underground.ancient_metal_crafting_table.description", "Acquire an ancient metal crafting table");
            translationBuilder.add("mme.advancements.underground.mithril_tool.title", "Mithril Forging");
            translationBuilder.add("mme.advancements.underground.mithril_tool.description", "Acquire a mithril tool");
            translationBuilder.add("mme.advancements.underground.find_adamantium.title", "Indestructible");
            translationBuilder.add("mme.advancements.underground.find_adamantium.description", "Acquire adamantium ore");
            translationBuilder.add("mme.advancements.underground.smelt_adamantium.title", "Forged by Fire");
            translationBuilder.add("mme.advancements.underground.smelt_adamantium.description", "Smelt an adamantium ingot");
            translationBuilder.add("mme.advancements.underground.adamantium_tool.title", "Power of Adamantium");
            translationBuilder.add("mme.advancements.underground.adamantium_tool.description", "Acquire an adamantium tool");
            translationBuilder.add("mme.advancements.underground.adamantium_armor.title", "Ultimate Armor");
            translationBuilder.add("mme.advancements.underground.adamantium_armor.description", "Acquire a piece of adamantium armor");
            translationBuilder.add("mme.advancements.underground.enter_ancient_city.title", "City of Silence");
            translationBuilder.add("mme.advancements.underground.enter_ancient_city.description", "Enter an ancient city in the underground");
            translationBuilder.add("mme.advancements.underground.deep_down.title", "Deep Down");
            translationBuilder.add("mme.advancements.underground.deep_down.description", "Reach Y=-60 or below in the underground");
            translationBuilder.add("mme.advancements.underground.mantle_portal.title", "Gate to Hell");
            translationBuilder.add("mme.advancements.underground.mantle_portal.description", "Light a portal on mantle to enter the Nether");

            translationBuilder.add(MMEItems.ADAMANTIUM_HELMET, "Adamantium Helmet");
            translationBuilder.add(MMEItems.ADAMANTIUM_CHESTPLATE, "Adamantium Chestplate");
            translationBuilder.add(MMEItems.ADAMANTIUM_LEGGINGS, "Adamantium Leggings");
            translationBuilder.add(MMEItems.ADAMANTIUM_BOOTS, "Adamantium Boots");
            translationBuilder.add(MMEItems.ADAMANTIUM_CHAINMAIL_HELMET, "Adamantium Chainmail Helmet");
            translationBuilder.add(MMEItems.ADAMANTIUM_CHAINMAIL_CHESTPLATE, "Adamantium Chainmail Chestplate");
            translationBuilder.add(MMEItems.ADAMANTIUM_CHAINMAIL_LEGGINGS, "Adamantium Chainmail Leggings");
            translationBuilder.add(MMEItems.ADAMANTIUM_CHAINMAIL_BOOTS, "Adamantium Chainmail Boots");
            translationBuilder.add(MMEItems.MITHRIL_HELMET, "Mithril Helmet");
            translationBuilder.add(MMEItems.MITHRIL_CHESTPLATE, "Mithril Chestplate");
            translationBuilder.add(MMEItems.MITHRIL_LEGGINGS, "Mithril Leggings");
            translationBuilder.add(MMEItems.MITHRIL_BOOTS, "Mithril Boots");
            translationBuilder.add(MMEItems.MITHRIL_CHAINMAIL_HELMET, "Mithril Chainmail Helmet");
            translationBuilder.add(MMEItems.MITHRIL_CHAINMAIL_CHESTPLATE, "Mithril Chainmail Chestplate");
            translationBuilder.add(MMEItems.MITHRIL_CHAINMAIL_LEGGINGS, "Mithril Chainmail Leggings");
            translationBuilder.add(MMEItems.MITHRIL_CHAINMAIL_BOOTS, "Mithril Chainmail Boots");
            translationBuilder.add(MMEItems.ANCIENT_METAL_HELMET, "Ancient Metal Helmet");
            translationBuilder.add(MMEItems.ANCIENT_METAL_CHESTPLATE, "Ancient Metal Chestplate");
            translationBuilder.add(MMEItems.ANCIENT_METAL_LEGGINGS, "Ancient Metal Leggings");
            translationBuilder.add(MMEItems.ANCIENT_METAL_BOOTS, "Ancient Metal Boots");
            translationBuilder.add(MMEItems.ANCIENT_METAL_CHAINMAIL_HELMET, "Ancient Metal Chainmail Helmet");
            translationBuilder.add(MMEItems.ANCIENT_METAL_CHAINMAIL_CHESTPLATE, "Ancient Metal Chainmail Chestplate");
            translationBuilder.add(MMEItems.ANCIENT_METAL_CHAINMAIL_LEGGINGS, "Ancient Metal Chainmail Leggings");
            translationBuilder.add(MMEItems.ANCIENT_METAL_CHAINMAIL_BOOTS, "Ancient Metal Chainmail Boots");
            translationBuilder.add(MMEItems.RUSTED_IRON_HELMET, "Rusted Iron Helmet");
            translationBuilder.add(MMEItems.RUSTED_IRON_CHESTPLATE, "Rusted Iron Chestplate");
            translationBuilder.add(MMEItems.RUSTED_IRON_LEGGINGS, "Rusted Iron Leggings");
            translationBuilder.add(MMEItems.RUSTED_IRON_BOOTS, "Rusted Iron Boots");
            translationBuilder.add(MMEItems.RUSTED_IRON_CHAINMAIL_HELMET, "Rusted Iron Chainmail Helmet");
            translationBuilder.add(MMEItems.RUSTED_IRON_CHAINMAIL_CHESTPLATE, "Rusted Iron Chainmail Chestplate");
            translationBuilder.add(MMEItems.RUSTED_IRON_CHAINMAIL_LEGGINGS, "Rusted Iron Chainmail Leggings");
            translationBuilder.add(MMEItems.RUSTED_IRON_CHAINMAIL_BOOTS, "Rusted Iron Chainmail Boots");
            translationBuilder.add(MMEItems.COPPER_CHAINMAIL_HELMET, "Copper Chainmail Helmet");
            translationBuilder.add(MMEItems.COPPER_CHAINMAIL_CHESTPLATE, "Copper Chainmail Chestplate");
            translationBuilder.add(MMEItems.COPPER_CHAINMAIL_LEGGINGS, "Copper Chainmail Leggings");
            translationBuilder.add(MMEItems.COPPER_CHAINMAIL_BOOTS, "Copper Chainmail Boots");
            translationBuilder.add(MMEItems.SILVER_HELMET, "Silver Helmet");
            translationBuilder.add(MMEItems.SILVER_CHESTPLATE, "Silver Chestplate");
            translationBuilder.add(MMEItems.SILVER_LEGGINGS, "Silver Leggings");
            translationBuilder.add(MMEItems.SILVER_BOOTS, "Silver Boots");
            translationBuilder.add(MMEItems.SILVER_CHAINMAIL_HELMET, "Silver Chainmail Helmet");
            translationBuilder.add(MMEItems.SILVER_CHAINMAIL_CHESTPLATE, "Silver Chainmail Chestplate");
            translationBuilder.add(MMEItems.SILVER_CHAINMAIL_LEGGINGS, "Silver Chainmail Leggings");
            translationBuilder.add(MMEItems.SILVER_CHAINMAIL_BOOTS, "Silver Chainmail Boots");
            translationBuilder.add(MMEItems.GOLDEN_CHAINMAIL_HELMET, "Golden Chainmail Helmet");
            translationBuilder.add(MMEItems.GOLDEN_CHAINMAIL_CHESTPLATE, "Golden Chainmail Chestplate");
            translationBuilder.add(MMEItems.GOLDEN_CHAINMAIL_LEGGINGS, "Golden Chainmail Leggings");
            translationBuilder.add(MMEItems.GOLDEN_CHAINMAIL_BOOTS, "Golden Chainmail Boots");

            translationBuilder.add(MMEItems.BANANA, "Banana");
            translationBuilder.add(MMEItems.BLUE_BERRIE, "Blueberry");
            translationBuilder.add(MMEItems.CHEESE, "Cheese");
            translationBuilder.add(MMEItems.CHOCOLATE, "Chocolate");
            translationBuilder.add(MMEItems.DOUGH, "Dough");
            translationBuilder.add(MMEItems.ONION, "Onion");
            translationBuilder.add(MMEItems.LEMON, "Lemon");
            translationBuilder.add(MMEItems.ORANGE, "Orange");
            translationBuilder.add(MMEItems.WORM_COOKED, "Roasted Worm");
            translationBuilder.add(MMEItems.WORM_RAW, "Raw Worm");
            translationBuilder.add(MMEItems.BEEF_STEW, "Beef Stew");
            translationBuilder.add(MMEItems.FLOUR, "Flour");
            translationBuilder.add(MMEItems.BOWL_MILK, "Bowl of Milk");
            translationBuilder.add(MMEItems.BOWL_SALAD, "Bowl of Salad");
            translationBuilder.add(MMEItems.BOWL_WATER, "Bowl of Water");
            translationBuilder.add(MMEItems.CEREAL, "Cereal Porridge");
            translationBuilder.add(MMEItems.CHICKEN_SOUP, "Chicken Soup");
            translationBuilder.add(MMEItems.CREAM_OF_MUSHROOM_SOUP, "Cream of Mushroom Soup");
            translationBuilder.add(MMEItems.CREAM_OF_VEGETABLE_SOUP, "Cream of Vegetable Soup");
            translationBuilder.add(MMEItems.ICE_CREAM, "Ice Cream");
            translationBuilder.add(MMEItems.MASHED_POTATO, "Mashed Potato");
            translationBuilder.add(MMEItems.PORRIDGE, "Blueberry Porridge");
            translationBuilder.add(MMEItems.PUMPKIN_SOUP, "Pumpkin Soup");
            translationBuilder.add(MMEItems.SORBET, "Sorbet");
            translationBuilder.add(MMEItems.VEGETABLE_SOUP, "Vegetable Soup");

            translationBuilder.add(MMEItems.ADAMANTIUM_CHAINS, "Adamantium Chains");
            translationBuilder.add(MMEItems.ANCIENT_METAL_CHAINS, "Ancient Metal Chains");
            translationBuilder.add(MMEItems.COPPER_CHAINS, "Copper Chains");
            translationBuilder.add(MMEItems.MITHRIL_CHAINS, "Mithril Chains");
            translationBuilder.add(MMEItems.RUSTED_IRON_CHAINS, "Rusted Iron Chains");
            translationBuilder.add(MMEItems.SILVER_CHAINS, "Silver Chains");
            translationBuilder.add(MMEItems.GOLDEN_CHAINS, "Golden Chains");
            translationBuilder.add(MMEItems.IRON_CHAINS, "Iron Chains");
            translationBuilder.add(MMEItems.NETHERITE_COINS, "Netherite Coins");
            translationBuilder.add(MMEItems.ADAMANTIUM_COINS, "Adamantium Coins");
            translationBuilder.add(MMEItems.ANCIENT_METAL_COINS, "Ancient Metal Coins");
            translationBuilder.add(MMEItems.COPPER_COINS, "Copper Coins");
            translationBuilder.add(MMEItems.MITHRIL_COINS, "Mithril Coins");
            translationBuilder.add(MMEItems.GOLDEN_COINS, "Golden Coins");
            translationBuilder.add(MMEItems.SILVER_COINS, "Silver Coins");
            translationBuilder.add(MMEItems.IRON_COINS, "Iron Coins");

            translationBuilder.add(MMEItems.NETHERITE_BATTLE_AXE, "Netherite Battle Axe");
            translationBuilder.add(MMEItems.NETHERITE_DAGGER, "Netherite Dagger");
            translationBuilder.add(MMEItems.NETHERITE_HATCHET, "Netherite Hatchet");
            translationBuilder.add(MMEItems.NETHERITE_KNIFE, "Netherite Knife");
            translationBuilder.add(MMEItems.NETHERITE_MATTOCK, "Netherite Mattock");
            translationBuilder.add(MMEItems.NETHERITE_SCYTHE, "Netherite Scythe");
            translationBuilder.add(MMEItems.NETHERITE_SHEARS, "Netherite Shears");
            translationBuilder.add(MMEItems.NETHERITE_WAR_HAMMER, "Netherite War Hammer");
            translationBuilder.add(MMEItems.ADAMANTIUM_AXE, "Adamantium Axe");
            translationBuilder.add(MMEItems.ADAMANTIUM_BATTLE_AXE, "Adamantium Battle Axe");
            translationBuilder.add(MMEItems.ADAMANTIUM_DAGGER, "Adamantium Dagger");
            translationBuilder.add(MMEItems.ADAMANTIUM_HATCHET, "Adamantium Hatchet");
            translationBuilder.add(MMEItems.ADAMANTIUM_HOE, "Adamantium Hoe");
            translationBuilder.add(MMEItems.ADAMANTIUM_KNIFE, "Adamantium Knife");
            translationBuilder.add(MMEItems.ADAMANTIUM_MATTOCK, "Adamantium Mattock");
            translationBuilder.add(MMEItems.ADAMANTIUM_PICKAXE, "Adamantium Pickaxe");
            translationBuilder.add(MMEItems.ADAMANTIUM_SCYTHE, "Adamantium Scythe");
            translationBuilder.add(MMEItems.ADAMANTIUM_SHEARS, "Adamantium Shears");
            translationBuilder.add(MMEItems.ADAMANTIUM_SHOVEL, "Adamantium Shovel");
            translationBuilder.add(MMEItems.ADAMANTIUM_SWORD, "Adamantium Sword");
            translationBuilder.add(MMEItems.ADAMANTIUM_WAR_HAMMER, "Adamantium War Hammer");
            translationBuilder.add(MMEItems.ADAMANTIUM_SPEAR, "Adamantium Spear");
            translationBuilder.add(MMEItems.MITHRIL_AXE, "Mithril Axe");
            translationBuilder.add(MMEItems.MITHRIL_BATTLE_AXE, "Mithril Battle Axe");
            translationBuilder.add(MMEItems.MITHRIL_DAGGER, "Mithril Dagger");
            translationBuilder.add(MMEItems.MITHRIL_HATCHET, "Mithril Hatchet");
            translationBuilder.add(MMEItems.MITHRIL_HOE, "Mithril Hoe");
            translationBuilder.add(MMEItems.MITHRIL_KNIFE, "Mithril Knife");
            translationBuilder.add(MMEItems.MITHRIL_MATTOCK, "Mithril Mattock");
            translationBuilder.add(MMEItems.MITHRIL_PICKAXE, "Mithril Pickaxe");
            translationBuilder.add(MMEItems.MITHRIL_SCYTHE, "Mithril Scythe");
            translationBuilder.add(MMEItems.MITHRIL_SHEARS, "Mithril Shears");
            translationBuilder.add(MMEItems.MITHRIL_SHOVEL, "Mithril Shovel");
            translationBuilder.add(MMEItems.MITHRIL_SWORD, "Mithril Sword");
            translationBuilder.add(MMEItems.MITHRIL_WAR_HAMMER, "Mithril War Hammer");
            translationBuilder.add(MMEItems.MITHRIL_SPEAR, "Mithril Spear");
            translationBuilder.add(MMEItems.ANCIENT_METAL_AXE, "Ancient Metal Axe");
            translationBuilder.add(MMEItems.ANCIENT_METAL_BATTLE_AXE, "Ancient Metal Battle Axe");
            translationBuilder.add(MMEItems.ANCIENT_METAL_DAGGER, "Ancient Metal Dagger");
            translationBuilder.add(MMEItems.ANCIENT_METAL_HATCHET, "Ancient Metal Hatchet");
            translationBuilder.add(MMEItems.ANCIENT_METAL_HOE, "Ancient Metal Hoe");
            translationBuilder.add(MMEItems.ANCIENT_METAL_KNIFE, "Ancient Metal Knife");
            translationBuilder.add(MMEItems.ANCIENT_METAL_MATTOCK, "Ancient Metal Mattock");
            translationBuilder.add(MMEItems.ANCIENT_METAL_PICKAXE, "Ancient Metal Pickaxe");
            translationBuilder.add(MMEItems.ANCIENT_METAL_SCYTHE, "Ancient Metal Scythe");
            translationBuilder.add(MMEItems.ANCIENT_METAL_SHEARS, "Ancient Metal Shears");
            translationBuilder.add(MMEItems.ANCIENT_METAL_SHOVEL, "Ancient Metal Shovel");
            translationBuilder.add(MMEItems.ANCIENT_METAL_SWORD, "Ancient Metal Sword");
            translationBuilder.add(MMEItems.ANCIENT_METAL_WAR_HAMMER, "Ancient Metal War Hammer");
            translationBuilder.add(MMEItems.ANCIENT_METAL_SPEAR, "Ancient Metal Spear");
            translationBuilder.add(MMEItems.IRON_BATTLE_AXE, "Iron Battle Axe");
            translationBuilder.add(MMEItems.IRON_DAGGER, "Iron Dagger");
            translationBuilder.add(MMEItems.IRON_HATCHET, "Iron Hatchet");
            translationBuilder.add(MMEItems.IRON_KNIFE, "Iron Knife");
            translationBuilder.add(MMEItems.IRON_MATTOCK, "Iron Mattock");
            translationBuilder.add(MMEItems.IRON_SCYTHE, "Iron Scythe");
            translationBuilder.add(MMEItems.IRON_WAR_HAMMER, "Iron War Hammer");
            translationBuilder.add(MMEItems.RUSTED_IRON_AXE, "Rusted Iron Axe");
            translationBuilder.add(MMEItems.RUSTED_IRON_BATTLE_AXE, "Rusted Iron Battle Axe");
            translationBuilder.add(MMEItems.RUSTED_IRON_DAGGER, "Rusted Iron Dagger");
            translationBuilder.add(MMEItems.RUSTED_IRON_HATCHET, "Rusted Iron Hatchet");
            translationBuilder.add(MMEItems.RUSTED_IRON_HOE, "Rusted Iron Hoe");
            translationBuilder.add(MMEItems.RUSTED_IRON_KNIFE, "Rusted Iron Knife");
            translationBuilder.add(MMEItems.RUSTED_IRON_MATTOCK, "Rusted Iron Mattock");
            translationBuilder.add(MMEItems.RUSTED_IRON_PICKAXE, "Rusted Iron Pickaxe");
            translationBuilder.add(MMEItems.RUSTED_IRON_SCYTHE, "Rusted Iron Scythe");
            translationBuilder.add(MMEItems.RUSTED_IRON_SHEARS, "Rusted Iron Shears");
            translationBuilder.add(MMEItems.RUSTED_IRON_SHOVEL, "Rusted Iron Shovel");
            translationBuilder.add(MMEItems.RUSTED_IRON_SWORD, "Rusted Iron Sword");
            translationBuilder.add(MMEItems.RUSTED_IRON_WAR_HAMMER, "Rusted Iron War Hammer");
            translationBuilder.add(MMEItems.RUSTED_IRON_SPEAR, "Rusted Iron Spear");
            translationBuilder.add(MMEItems.COPPER_BATTLE_AXE, "Copper Battle Axe");
            translationBuilder.add(MMEItems.COPPER_DAGGER, "Copper Dagger");
            translationBuilder.add(MMEItems.COPPER_HATCHET, "Copper Hatchet");
            translationBuilder.add(MMEItems.COPPER_KNIFE, "Copper Knife");
            translationBuilder.add(MMEItems.COPPER_MATTOCK, "Copper Mattock");
            translationBuilder.add(MMEItems.COPPER_SCYTHE, "Copper Scythe");
            translationBuilder.add(MMEItems.COPPER_SHEARS, "Copper Shears");
            translationBuilder.add(MMEItems.COPPER_WAR_HAMMER, "Copper War Hammer");
            translationBuilder.add(MMEItems.SILVER_AXE, "Silver Axe");
            translationBuilder.add(MMEItems.SILVER_BATTLE_AXE, "Silver Battle Axe");
            translationBuilder.add(MMEItems.SILVER_DAGGER, "Silver Dagger");
            translationBuilder.add(MMEItems.SILVER_HATCHET, "Silver Hatchet");
            translationBuilder.add(MMEItems.SILVER_HOE, "Silver Hoe");
            translationBuilder.add(MMEItems.SILVER_KNIFE, "Silver Knife");
            translationBuilder.add(MMEItems.SILVER_MATTOCK, "Silver Mattock");
            translationBuilder.add(MMEItems.SILVER_PICKAXE, "Silver Pickaxe");
            translationBuilder.add(MMEItems.SILVER_SCYTHE, "Silver Scythe");
            translationBuilder.add(MMEItems.SILVER_SHEARS, "Silver Shears");
            translationBuilder.add(MMEItems.SILVER_SHOVEL, "Silver Shovel");
            translationBuilder.add(MMEItems.SILVER_SWORD, "Silver Sword");
            translationBuilder.add(MMEItems.SILVER_WAR_HAMMER, "Silver War Hammer");
            translationBuilder.add(MMEItems.SILVER_SPEAR, "Silver Spear");
            translationBuilder.add(MMEItems.GOLDEN_BATTLE_AXE, "Golden Battle Axe");
            translationBuilder.add(MMEItems.GOLDEN_DAGGER, "Golden Dagger");
            translationBuilder.add(MMEItems.GOLDEN_HATCHET, "Golden Hatchet");
            translationBuilder.add(MMEItems.GOLDEN_KNIFE, "Golden Knife");
            translationBuilder.add(MMEItems.GOLDEN_MATTOCK, "Golden Mattock");
            translationBuilder.add(MMEItems.GOLDEN_SCYTHE, "Golden Scythe");
            translationBuilder.add(MMEItems.GOLDEN_SHEARS, "Golden Shears");
            translationBuilder.add(MMEItems.GOLDEN_WAR_HAMMER, "Golden War Hammer");
            translationBuilder.add(MMEItems.FLINT_AXE, "Flint Axe");
            translationBuilder.add(MMEItems.FLINT_HATCHET, "Flint Hatchet");
            translationBuilder.add(MMEItems.FLINT_KNIFE, "Flint Knife");
            translationBuilder.add(MMEItems.FLINT_SHOVEL, "Flint Shovel");
            translationBuilder.add(MMEItems.FLINT_SPEAR, "Flint Spear");
            translationBuilder.add(MMEItems.OBSIDIAN_AXE, "Obsidian Axe");
            translationBuilder.add(MMEItems.OBSIDIAN_HATCHET, "Obsidian Hatchet");
            translationBuilder.add(MMEItems.OBSIDIAN_KNIFE, "Obsidian Knife");
            translationBuilder.add(MMEItems.OBSIDIAN_SHOVEL, "Obsidian Shovel");
            translationBuilder.add(MMEItems.WOODEN_CLUB, "Wooden Club");
            translationBuilder.add(MMEItems.WOODEN_CUDGEL, "Small Wooden Club");

            translationBuilder.add(MMEBlocks.ADAMANTIUM_ORE, "Adamantium Ore");
            translationBuilder.add(MMEBlocks.ADAMANTIUM_BLOCK, "Adamantium Block");
            translationBuilder.add(MMEBlocks.ANCIENT_METAL_BLOCK, "Ancient Metal Block");
            translationBuilder.add(MMEBlocks.MITHRIL_BLOCK, "Mithril Block");
            translationBuilder.add(MMEBlocks.MITHRIL_ORE, "Mithril Ore");
            translationBuilder.add(MMEBlocks.SILVER_BLOCK, "Silver Block");
            translationBuilder.add(MMEBlocks.SILVER_ORE, "Silver Ore");
            translationBuilder.add(MMEBlocks.MANTLE, "Mantle");

            translationBuilder.add(MMEItems.NETHERITE_BUCKET, "Netherite Bucket");
            translationBuilder.add(MMEItems.LAVA_NETHERITE_BUCKET, "Netherite Bucket of Lava");
            translationBuilder.add(MMEItems.WATER_NETHERITE_BUCKET, "Netherite Water Bucket");
            translationBuilder.add(MMEItems.POWDER_SNOW_NETHERITE_BUCKET, "Netherite Bucket of Powder Snow");
            translationBuilder.add(MMEItems.MILK_NETHERITE_BUCKET, "Netherite Bucket of Milk");
            translationBuilder.add(MMEItems.PUFFERFISH_NETHERITE_BUCKET, "Netherite Bucket of Pufferfish");
            translationBuilder.add(MMEItems.SALMON_NETHERITE_BUCKET, "Netherite Bucket of Salmon");
            translationBuilder.add(MMEItems.COD_NETHERITE_BUCKET, "Netherite Bucket of Cod");
            translationBuilder.add(MMEItems.TROPICAL_FISH_NETHERITE_BUCKET, "Netherite Bucket of Tropical Fish");
            translationBuilder.add(MMEItems.AXOLOTL_NETHERITE_BUCKET, "Netherite Bucket of Axolotl");
            translationBuilder.add(MMEItems.TADPOLE_NETHERITE_BUCKET, "Netherite Bucket of Tadpole");

            translationBuilder.add(MMEItems.ADAMANTIUM_BUCKET, "Adamantium Bucket");
            translationBuilder.add(MMEItems.LAVA_ADAMANTIUM_BUCKET, "Adamantium Bucket of Lava");
            translationBuilder.add(MMEItems.WATER_ADAMANTIUM_BUCKET, "Adamantium Water Bucket");
            translationBuilder.add(MMEItems.POWDER_SNOW_ADAMANTIUM_BUCKET, "Adamantium Bucket of Powder Snow");
            translationBuilder.add(MMEItems.MILK_ADAMANTIUM_BUCKET, "Adamantium Bucket of Milk");
            translationBuilder.add(MMEItems.PUFFERFISH_ADAMANTIUM_BUCKET, "Adamantium Bucket of Pufferfish");
            translationBuilder.add(MMEItems.SALMON_ADAMANTIUM_BUCKET, "Adamantium Bucket of Salmon");
            translationBuilder.add(MMEItems.COD_ADAMANTIUM_BUCKET, "Adamantium Bucket of Cod");
            translationBuilder.add(MMEItems.TROPICAL_FISH_ADAMANTIUM_BUCKET, "Adamantium Bucket of Tropical Fish");
            translationBuilder.add(MMEItems.AXOLOTL_ADAMANTIUM_BUCKET, "Adamantium Bucket of Axolotl");
            translationBuilder.add(MMEItems.TADPOLE_ADAMANTIUM_BUCKET, "Adamantium Bucket of Tadpole");

            translationBuilder.add(MMEItems.MITHRIL_BUCKET, "Mithril Bucket");
            translationBuilder.add(MMEItems.LAVA_MITHRIL_BUCKET, "Mithril Bucket of Lava");
            translationBuilder.add(MMEItems.WATER_MITHRIL_BUCKET, "Mithril Water Bucket");
            translationBuilder.add(MMEItems.POWDER_SNOW_MITHRIL_BUCKET, "Mithril Bucket of Powder Snow");
            translationBuilder.add(MMEItems.MILK_MITHRIL_BUCKET, "Mithril Bucket of Milk");
            translationBuilder.add(MMEItems.PUFFERFISH_MITHRIL_BUCKET, "Mithril Bucket of Pufferfish");
            translationBuilder.add(MMEItems.SALMON_MITHRIL_BUCKET, "Mithril Bucket of Salmon");
            translationBuilder.add(MMEItems.COD_MITHRIL_BUCKET, "Mithril Bucket of Cod");
            translationBuilder.add(MMEItems.TROPICAL_FISH_MITHRIL_BUCKET, "Mithril Bucket of Tropical Fish");
            translationBuilder.add(MMEItems.AXOLOTL_MITHRIL_BUCKET, "Mithril Bucket of Axolotl");
            translationBuilder.add(MMEItems.TADPOLE_MITHRIL_BUCKET, "Mithril Bucket of Tadpole");

            translationBuilder.add(MMEItems.ANCIENT_METAL_BUCKET, "Ancient Metal Bucket");
            translationBuilder.add(MMEItems.LAVA_ANCIENT_METAL_BUCKET, "Ancient Metal Bucket of Lava");
            translationBuilder.add(MMEItems.WATER_ANCIENT_METAL_BUCKET, "Ancient Metal Water Bucket");
            translationBuilder.add(MMEItems.POWDER_SNOW_ANCIENT_METAL_BUCKET, "Ancient Metal Bucket of Powder Snow");
            translationBuilder.add(MMEItems.MILK_ANCIENT_METAL_BUCKET, "Ancient Metal Bucket of Milk");
            translationBuilder.add(MMEItems.PUFFERFISH_ANCIENT_METAL_BUCKET, "Ancient Metal Bucket of Pufferfish");
            translationBuilder.add(MMEItems.SALMON_ANCIENT_METAL_BUCKET, "Ancient Metal Bucket of Salmon");
            translationBuilder.add(MMEItems.COD_ANCIENT_METAL_BUCKET, "Ancient Metal Bucket of Cod");
            translationBuilder.add(MMEItems.TROPICAL_FISH_ANCIENT_METAL_BUCKET, "Ancient Metal Bucket of Tropical Fish");
            translationBuilder.add(MMEItems.AXOLOTL_ANCIENT_METAL_BUCKET, "Ancient Metal Bucket of Axolotl");
            translationBuilder.add(MMEItems.TADPOLE_ANCIENT_METAL_BUCKET, "Ancient Metal Bucket of Tadpole");

            translationBuilder.add(MMEItems.SILVER_BUCKET, "Silver Bucket");
            translationBuilder.add(MMEItems.LAVA_SILVER_BUCKET, "Silver Bucket of Lava");
            translationBuilder.add(MMEItems.WATER_SILVER_BUCKET, "Silver Water Bucket");
            translationBuilder.add(MMEItems.POWDER_SNOW_SILVER_BUCKET, "Silver Bucket of Powder Snow");
            translationBuilder.add(MMEItems.MILK_SILVER_BUCKET, "Silver Bucket of Milk");
            translationBuilder.add(MMEItems.PUFFERFISH_SILVER_BUCKET, "Silver Bucket of Pufferfish");
            translationBuilder.add(MMEItems.SALMON_SILVER_BUCKET, "Silver Bucket of Salmon");
            translationBuilder.add(MMEItems.COD_SILVER_BUCKET, "Silver Bucket of Cod");
            translationBuilder.add(MMEItems.TROPICAL_FISH_SILVER_BUCKET, "Silver Bucket of Tropical Fish");
            translationBuilder.add(MMEItems.AXOLOTL_SILVER_BUCKET, "Silver Bucket of Axolotl");
            translationBuilder.add(MMEItems.TADPOLE_SILVER_BUCKET, "Silver Bucket of Tadpole");

            translationBuilder.add(MMEItems.COPPER_BUCKET, "Copper Bucket");
            translationBuilder.add(MMEItems.LAVA_COPPER_BUCKET, "Copper Bucket of Lava");
            translationBuilder.add(MMEItems.WATER_COPPER_BUCKET, "Copper Water Bucket");
            translationBuilder.add(MMEItems.POWDER_SNOW_COPPER_BUCKET, "Copper Bucket of Powder Snow");
            translationBuilder.add(MMEItems.MILK_COPPER_BUCKET, "Copper Bucket of Milk");
            translationBuilder.add(MMEItems.PUFFERFISH_COPPER_BUCKET, "Copper Bucket of Pufferfish");
            translationBuilder.add(MMEItems.SALMON_COPPER_BUCKET, "Copper Bucket of Salmon");
            translationBuilder.add(MMEItems.COD_COPPER_BUCKET, "Copper Bucket of Cod");
            translationBuilder.add(MMEItems.TROPICAL_FISH_COPPER_BUCKET, "Copper Bucket of Tropical Fish");
            translationBuilder.add(MMEItems.AXOLOTL_COPPER_BUCKET, "Copper Bucket of Axolotl");
            translationBuilder.add(MMEItems.TADPOLE_COPPER_BUCKET, "Copper Bucket of Tadpole");

            translationBuilder.add(MMEItems.GOLD_BUCKET, "Golden Bucket");
            translationBuilder.add(MMEItems.LAVA_GOLD_BUCKET, "Golden Bucket of Lava");
            translationBuilder.add(MMEItems.WATER_GOLD_BUCKET, "Golden Water Bucket");
            translationBuilder.add(MMEItems.POWDER_SNOW_GOLD_BUCKET, "Golden Bucket of Powder Snow");
            translationBuilder.add(MMEItems.MILK_GOLD_BUCKET, "Golden Bucket of Milk");
            translationBuilder.add(MMEItems.PUFFERFISH_GOLD_BUCKET, "Golden Bucket of Pufferfish");
            translationBuilder.add(MMEItems.SALMON_GOLD_BUCKET, "Golden Bucket of Salmon");
            translationBuilder.add(MMEItems.COD_GOLD_BUCKET, "Golden Bucket of Cod");
            translationBuilder.add(MMEItems.TROPICAL_FISH_GOLD_BUCKET, "Golden Bucket of Tropical Fish");
            translationBuilder.add(MMEItems.AXOLOTL_GOLD_BUCKET, "Golden Bucket of Axolotl");
            translationBuilder.add(MMEItems.TADPOLE_GOLD_BUCKET, "Golden Bucket of Tadpole");

            translationBuilder.add(MMEItems.NETHERITE_FISHING_ROD, "Netherite Fishing Rod");
            translationBuilder.add(MMEItems.ADAMANTIUM_FISHING_ROD, "Adamantium Fishing Rod");
            translationBuilder.add(MMEItems.ANCIENT_METAL_FISHING_ROD, "Ancient Metal Fishing Rod");
            translationBuilder.add(MMEItems.MITHRIL_FISHING_ROD, "Mithril Fishing Rod");
            translationBuilder.add(MMEItems.SILVER_FISHING_ROD, "Silver Fishing Rod");
            translationBuilder.add(MMEItems.GOLDEN_FISHING_ROD, "Golden Fishing Rod");
            translationBuilder.add(MMEItems.COPPER_FISHING_ROD, "Copper Fishing Rod");
            translationBuilder.add(MMEItems.IRON_FISHING_ROD, "Iron Fishing Rod");
            translationBuilder.add(MMEItems.FLINT_FISHING_ROD, "Flint Fishing Rod");
            translationBuilder.add(MMEItems.OBSIDIAN_FISHING_ROD, "Obsidian Fishing Rod");

            translationBuilder.add(MMEItems.RAW_ADAMANTIUM, "Raw Adamantium");
            translationBuilder.add(MMEItems.RAW_MITHRIL, "Raw Mithril");
            translationBuilder.add(MMEItems.RAW_SILVER, "Raw Silver");

            translationBuilder.add(MMEItems.ADAMANTIUM_INGOT, "Adamantium Ingot");
            translationBuilder.add(MMEItems.ANCIENT_METAL_INGOT, "Ancient Metal Ingot");
            translationBuilder.add(MMEItems.MITHRIL_INGOT, "Mithril Ingot");
            translationBuilder.add(MMEItems.SILVER_INGOT, "Silver Ingot");

            translationBuilder.add(MMEItems.NETHERITE_NUGGET, "Netherite Nugget");
            translationBuilder.add(MMEItems.ADAMANTIUM_NUGGET, "Adamantium Nugget");
            translationBuilder.add(MMEItems.ANCIENT_METAL_NUGGET, "Ancient Metal Nugget");
            translationBuilder.add(MMEItems.MITHRIL_NUGGET, "Mithril Nugget");
            translationBuilder.add(MMEItems.SILVER_NUGGET, "Silver Nugget");

            translationBuilder.add(MMEItems.FLINT_SHARD, "Flint Shard");
            translationBuilder.add(MMEItems.OBSIDIAN_SHARD, "Obsidian Shard");

            translationBuilder.add(MMEBlocks.NETHERITE_ANVIL, "Netherite Anvil");
            translationBuilder.add(MMEBlocks.CHIPPED_NETHERITE_ANVIL, "Chipped Netherite Anvil");
            translationBuilder.add(MMEBlocks.DAMAGED_NETHERITE_ANVIL, "Damaged Netherite Anvil");
            translationBuilder.add(MMEBlocks.ADAMANTIUM_ANVIL, "Adamantium Anvil");
            translationBuilder.add(MMEBlocks.CHIPPED_ADAMANTIUM_ANVIL, "Chipped Adamantium Anvil");
            translationBuilder.add(MMEBlocks.DAMAGED_ADAMANTIUM_ANVIL, "Damaged Adamantium Anvil");
            translationBuilder.add(MMEBlocks.MITHRIL_ANVIL, "Mithril Anvil");
            translationBuilder.add(MMEBlocks.CHIPPED_MITHRIL_ANVIL, "Chipped Mithril Anvil");
            translationBuilder.add(MMEBlocks.DAMAGED_MITHRIL_ANVIL, "Damaged Mithril Anvil");
            translationBuilder.add(MMEBlocks.ANCIENT_METAL_ANVIL, "Ancient Metal Anvil");
            translationBuilder.add(MMEBlocks.CHIPPED_ANCIENT_METAL_ANVIL, "Chipped Ancient Metal Anvil");
            translationBuilder.add(MMEBlocks.DAMAGED_ANCIENT_METAL_ANVIL, "Damaged Ancient Metal Anvil");
            translationBuilder.add(MMEBlocks.SILVER_ANVIL, "Silver Anvil");
            translationBuilder.add(MMEBlocks.CHIPPED_SILVER_ANVIL, "Chipped Silver Anvil");
            translationBuilder.add(MMEBlocks.DAMAGED_SILVER_ANVIL, "Damaged Silver Anvil");
            translationBuilder.add(MMEBlocks.GOLDEN_ANVIL, "Golden Anvil");
            translationBuilder.add(MMEBlocks.CHIPPED_GOLDEN_ANVIL, "Chipped Golden Anvil");
            translationBuilder.add(MMEBlocks.DAMAGED_GOLDEN_ANVIL, "Damaged Golden Anvil");
            translationBuilder.add(MMEBlocks.COPPER_ANVIL, "Copper Anvil");
            translationBuilder.add(MMEBlocks.CHIPPED_COPPER_ANVIL, "Chipped Copper Anvil");
            translationBuilder.add(MMEBlocks.DAMAGED_COPPER_ANVIL, "Damaged Copper Anvil");

            translationBuilder.add(MMEBlocks.MITHRIL_NUL_RUNESTORE, "Mithril Nul Runestone");
            translationBuilder.add(MMEBlocks.MITHRIL_QUAS_RUNESTORE, "Mithril Quas Runestone");
            translationBuilder.add(MMEBlocks.MITHRIL_POR_RUNESTORE, "Mithril Por Runestone");
            translationBuilder.add(MMEBlocks.MITHRIL_AN_RUNESTORE, "Mithril An Runestone");
            translationBuilder.add(MMEBlocks.MITHRIL_NOX_RUNESTORE, "Mithril Nox Runestone");
            translationBuilder.add(MMEBlocks.MITHRIL_FLAM_RUNESTORE, "Mithril Flam Runestone");
            translationBuilder.add(MMEBlocks.MITHRIL_VAS_RUNESTORE, "Mithril Vas Runestone");
            translationBuilder.add(MMEBlocks.MITHRIL_DES_RUNESTORE, "Mithril Des Runestone");
            translationBuilder.add(MMEBlocks.MITHRIL_ORT_RUNESTORE, "Mithril Ort Runestone");
            translationBuilder.add(MMEBlocks.MITHRIL_TYM_RUNESTORE, "Mithril Tym Runestone");
            translationBuilder.add(MMEBlocks.MITHRIL_CORP_RUNESTORE, "Mithril Corp Runestone");
            translationBuilder.add(MMEBlocks.MITHRIL_LOR_RUNESTORE, "Mithril Lor Runestone");
            translationBuilder.add(MMEBlocks.MITHRIL_MANI_RUNESTORE, "Mithril Mani Runestone");
            translationBuilder.add(MMEBlocks.MITHRIL_JUX_RUNESTORE, "Mithril Jux Runestone");
            translationBuilder.add(MMEBlocks.MITHRIL_YLEM_RUNESTORE, "Mithril Ylem Runestone");
            translationBuilder.add(MMEBlocks.MITHRIL_SANCT_RUNESTORE, "Mithril Sanct Runestone");

            translationBuilder.add(MMEBlocks.ADAMANTIUM_NUL_RUNESTORE, "Adamantium Nul Runestone");
            translationBuilder.add(MMEBlocks.ADAMANTIUM_QUAS_RUNESTORE, "Adamantium Quas Runestone");
            translationBuilder.add(MMEBlocks.ADAMANTIUM_POR_RUNESTORE, "Adamantium Por Runestone");
            translationBuilder.add(MMEBlocks.ADAMANTIUM_AN_RUNESTORE, "Adamantium An Runestone");
            translationBuilder.add(MMEBlocks.ADAMANTIUM_NOX_RUNESTORE, "Adamantium Nox Runestone");
            translationBuilder.add(MMEBlocks.ADAMANTIUM_FLAM_RUNESTORE, "Adamantium Flam Runestone");
            translationBuilder.add(MMEBlocks.ADAMANTIUM_VAS_RUNESTORE, "Adamantium Vas Runestone");
            translationBuilder.add(MMEBlocks.ADAMANTIUM_DES_RUNESTORE, "Adamantium Des Runestone");
            translationBuilder.add(MMEBlocks.ADAMANTIUM_ORT_RUNESTORE, "Adamantium Ort Runestone");
            translationBuilder.add(MMEBlocks.ADAMANTIUM_TYM_RUNESTORE, "Adamantium Tym Runestone");
            translationBuilder.add(MMEBlocks.ADAMANTIUM_CORP_RUNESTORE, "Adamantium Corp Runestone");
            translationBuilder.add(MMEBlocks.ADAMANTIUM_LOR_RUNESTORE, "Adamantium Lor Runestone");
            translationBuilder.add(MMEBlocks.ADAMANTIUM_MANI_RUNESTORE, "Adamantium Mani Runestone");
            translationBuilder.add(MMEBlocks.ADAMANTIUM_JUX_RUNESTORE, "Adamantium Jux Runestone");
            translationBuilder.add(MMEBlocks.ADAMANTIUM_YLEM_RUNESTORE, "Adamantium Ylem Runestone");
            translationBuilder.add(MMEBlocks.ADAMANTIUM_SANCT_RUNESTORE, "Adamantium Sanct Runestone");

            translationBuilder.add(MMEBlocks.ADAMANTIUM_CRAFTING_TABLE, "Adamantium Crafting Table");
            translationBuilder.add(MMEBlocks.ANCIENT_METAL_CRAFTING_TABLE, "Ancient Metal Crafting Table");
            translationBuilder.add(MMEBlocks.COPPER_CRAFTING_TABLE, "Copper Crafting Table");
            translationBuilder.add(MMEBlocks.GOLD_CRAFTING_TABLE, "Golden Crafting Table");
            translationBuilder.add(MMEBlocks.IRON_CRAFTING_TABLE, "Iron Crafting Table");
            translationBuilder.add(MMEBlocks.MITHRIL_CRAFTING_TABLE, "Mithril Crafting Table");
            translationBuilder.add(MMEBlocks.SILVER_CRAFTING_TABLE, "Silver Crafting Table");
            translationBuilder.add(MMEBlocks.FLINT_CRAFTING_TABLE, "Flint Crafting Table");
            translationBuilder.add(MMEBlocks.OBSIDIAN_CRAFTING_TABLE, "Obsidian Crafting Table");

            translationBuilder.add(MMEBlocks.CLAY_FURNACE, "Clay Furnace");
            translationBuilder.add(MMEBlocks.HARDENED_CLAY_FURNACE, "Hardened Clay Furnace");
            translationBuilder.add(MMEBlocks.NETHERRACK_FURNACE, "Netherrack Furnace");
            translationBuilder.add(MMEBlocks.OBSIDIAN_FURNACE, "Obsidian Furnace");
            translationBuilder.add(MMEBlocks.SANDSTONE_FURNACE, "Sandstone Furnace");

            translationBuilder.add(MMEBlocks.DEEPSLATE_ADAMANTIUM_ORE, "Deepslate Adamantium Ore");
            translationBuilder.add(MMEBlocks.DEEPSLATE_MITHRIL_ORE, "Deepslate Mithril Ore");
            translationBuilder.add(MMEBlocks.DEEPSLATE_SILVER_ORE, "Deepslate Silver Ore");

            translationBuilder.add(MMEBlocks.EMERALD_ENCHANTING_TABLE, "Emerald Enchanting Table");

            translationBuilder.add(MMEItems.SINEW, "Leather Thread");
            translationBuilder.add(MMEItems.MANURE, "Manure");
            translationBuilder.add(MMEItems.GHOUL_SPAWN_EGG, "Ghoul Spawn Egg");
            translationBuilder.add(MMEEntityTypes.GHOUL, "Ghoul");
            translationBuilder.add(MMEItems.SHADOW_SPAWN_EGG, "Shadow Spawn Egg");
            translationBuilder.add(MMEEntityTypes.SHADOW, "Shadow");
            translationBuilder.add(MMEItems.WIGHT_SPAWN_EGG, "Wight Spawn Egg");
            translationBuilder.add(MMEEntityTypes.WIGHT, "Wight");
            translationBuilder.add(MMEItems.INVISIBLE_STALKER_SPAWN_EGG, "Invisible Stalker Spawn Egg");
            translationBuilder.add(MMEEntityTypes.INVISIBLE_STALKER, "Invisible Stalker");
            translationBuilder.add(MMEItems.DEMON_SPIDER_SPAWN_EGG, "Demon Spider Spawn Egg");
            translationBuilder.add(MMEEntityTypes.DEMON_SPIDER, "Demon Spider");
            translationBuilder.add(MMEItems.PHASE_SPIDER_SPAWN_EGG, "Phase Spider Spawn Egg");
            translationBuilder.add(MMEEntityTypes.PHASE_SPIDER, "Phase Spider");
            translationBuilder.add(MMEItems.INFERNAL_CREEPER_SPAWN_EGG, "Infernal Creeper Spawn Egg");
            translationBuilder.add(MMEEntityTypes.INFERNAL_CREEPER, "Infernal Creeper");
            translationBuilder.add(MMEItems.FIRE_ELEMENTAL_SPAWN_EGG, "Fire Elemental Spawn Egg");
            translationBuilder.add(MMEEntityTypes.FIRE_ELEMENTAL, "Fire Elemental");
            translationBuilder.add(MMEItems.VAMPIRE_BAT_SPAWN_EGG, "Vampire Bat Spawn Egg");
            translationBuilder.add(MMEEntityTypes.VAMPIRE_BAT, "Vampire Bat");
            translationBuilder.add(MMEItems.NIGHTWING_SPAWN_EGG, "Nightwing Spawn Egg");
            translationBuilder.add(MMEEntityTypes.NIGHTWING, "Nightwing");
            translationBuilder.add(MMEItems.GIANT_VAMPIRE_BAT_SPAWN_EGG, "Giant Vampire Bat Spawn Egg");
            translationBuilder.add(MMEEntityTypes.GIANT_VAMPIRE_BAT, "Giant Vampire Bat");

            translationBuilder.add(MMEMobEffects.INSULIN_RESISTANCE.value(), "Diabetes");
            translationBuilder.add(MMEMobEffects.MALNUTRITION.value(), "Malnutrition");

            translationBuilder.addEnchantment(MMEEnchantments.BUTCHERING, "Butchering");
            translationBuilder.addEnchantment(MMEEnchantments.CLEAVING, "Cleaving");
            translationBuilder.addEnchantment(MMEEnchantments.HARVESTING, "Harvesting");
            translationBuilder.addEnchantment(MMEEnchantments.FERTILITY, "Fertility");
            translationBuilder.addEnchantment(MMEEnchantments.UPGRADE, "Infuse");
            translationBuilder.add("container.enchant.upgrade_target", "§7Enchant → %s");

            translationBuilder.add("painting.mme.abyss.title", "abyss");
            translationBuilder.add("painting.mme.abyss.author", "Avernite");
            translationBuilder.add("painting.mme.baron_almric.title", "baron_almric");
            translationBuilder.add("painting.mme.baron_almric.author", "Avernite");
            translationBuilder.add("painting.mme.boat.title", "boat");
            translationBuilder.add("painting.mme.boat.author", "Avernite");
            translationBuilder.add("painting.mme.castle.title", "castle");
            translationBuilder.add("painting.mme.castle.author", "Avernite");
            translationBuilder.add("painting.mme.castle_britannia.title", "castle_britannia");
            translationBuilder.add("painting.mme.castle_britannia.author", "Avernite");
            translationBuilder.add("painting.mme.darklands.title", "darklands");
            translationBuilder.add("painting.mme.darklands.author", "Avernite");
            translationBuilder.add("painting.mme.deathtrap_dungeon.title", "deathtrap_dungeon");
            translationBuilder.add("painting.mme.deathtrap_dungeon.author", "Avernite");
            translationBuilder.add("painting.mme.dnd_basic.title", "dnd_basic");
            translationBuilder.add("painting.mme.dnd_basic.author", "Avernite");
            translationBuilder.add("painting.mme.draracle.title", "draracle");
            translationBuilder.add("painting.mme.draracle.author", "Avernite");
            translationBuilder.add("painting.mme.elden_grove.title", "elden_grove");
            translationBuilder.add("painting.mme.elden_grove.author", "Avernite");
            translationBuilder.add("painting.mme.fair_day.title", "fair_day");
            translationBuilder.add("painting.mme.fair_day.author", "Avernite");
            translationBuilder.add("painting.mme.fallen_bridge.title", "fallen_bridge");
            translationBuilder.add("painting.mme.fallen_bridge.author", "Avernite");
            translationBuilder.add("painting.mme.gate_closing.title", "gate_closing");
            translationBuilder.add("painting.mme.gate_closing.author", "Avernite");
            translationBuilder.add("painting.mme.ghoul.title", "ghoul");
            translationBuilder.add("painting.mme.ghoul.author", "Avernite");
            translationBuilder.add("painting.mme.gladstone_keep.title", "gladstone_keep");
            translationBuilder.add("painting.mme.gladstone_keep.author", "Avernite");
            translationBuilder.add("painting.mme.graves.title", "graves");
            translationBuilder.add("painting.mme.graves.author", "Avernite");
            translationBuilder.add("painting.mme.king_richard.title", "king_richard");
            translationBuilder.add("painting.mme.king_richard.author", "Avernite");
            translationBuilder.add("painting.mme.messenger.title", "messenger");
            translationBuilder.add("painting.mme.messenger.author", "Avernite");
            translationBuilder.add("painting.mme.mountains.title", "mountains");
            translationBuilder.add("painting.mme.mountains.author", "Avernite");
            translationBuilder.add("painting.mme.rolands_manor.title", "rolands_manor");
            translationBuilder.add("painting.mme.rolands_manor.author", "Avernite");
            translationBuilder.add("painting.mme.scotia.title", "scotia");
            translationBuilder.add("painting.mme.scotia.author", "Avernite");
            translationBuilder.add("painting.mme.ship.title", "ship");
            translationBuilder.add("painting.mme.ship.author", "Avernite");
            translationBuilder.add("painting.mme.sunlight.title", "sunlight");
            translationBuilder.add("painting.mme.sunlight.author", "Avernite");
            translationBuilder.add("painting.mme.titan.title", "titan");
            translationBuilder.add("painting.mme.titan.author", "Avernite");
            translationBuilder.add("painting.mme.wolves.title", "wolves");
            translationBuilder.add("painting.mme.wolves.author", "Avernite");
        }
    }

    /**
     * 中文语言文件生成器。
     * 为 MME 模组物品/方块生成简体中文翻译键值对。
     */
    public static class Zh_cn extends FabricLanguageProvider {

        public Zh_cn(FabricPackOutput dataOutput, CompletableFuture<HolderLookup.Provider> registryLookup) {
            super(dataOutput, "zh_cn", registryLookup);
        }

        @Override
        public void generateTranslations(HolderLookup.@NonNull Provider wrapperLookup, TranslationBuilder translationBuilder) {
            translationBuilder.add("itemGroup.mme.item_group", "唯力是尊");
            translationBuilder.add("mme.craftingTable.noAllowedCrafting", "§c无法制作此物品§r");
            translationBuilder.add("mme.gradefurnac.fuelnotavailable", "§c无法燃烧这个燃料§r");
            translationBuilder.add("mme.nugget.tooltip", "右键做成币储存%dXP");
            translationBuilder.add("mme.coins.tooltip", "每个+%dXP");
            translationBuilder.add("mme.nutrition.tooltip", "%s当前营养状态:{fiber:%f, protein:%f, sugar:%f}");

            translationBuilder.add("mme.advancements.story.root.description", "梦开始的地方");
            translationBuilder.add("mme.advancements.story.wheat_seeds.title", "拾荒者");
            translationBuilder.add("mme.advancements.story.wheat_seeds.description", "总比饿死好");
            translationBuilder.add("mme.advancements.story.egg.title", "吃鸡蛋");
            translationBuilder.add("mme.advancements.story.egg.description", "好过没有");
            translationBuilder.add("mme.advancements.story.clay_furnace.title", "黏土工艺");
            translationBuilder.add("mme.advancements.story.clay_furnace.description", "最简单的熔炉");
            translationBuilder.add("mme.advancements.story.torch.title", "都亮起来");
            translationBuilder.add("mme.advancements.story.torch.description", "获得火把");
            translationBuilder.add("mme.advancements.story.flint.title", "燧石寻找者");
            translationBuilder.add("mme.advancements.story.flint.description", "一切工具的开端");
            translationBuilder.add("mme.advancements.story.flint_hatchet.title", "Here's Johnny");
            translationBuilder.add("mme.advancements.story.flint_hatchet.description", "解锁木头");
            translationBuilder.add("mme.advancements.story.log.title", "获得木头");
            translationBuilder.add("mme.advancements.story.log.description", "记得补种树苗奥");
            translationBuilder.add("mme.advancements.story.crafting_table.title", "这是? 工作台!");
            translationBuilder.add("mme.advancements.story.crafting_table.description", "解锁3*3");
            translationBuilder.add("mme.advancements.story.flint_axe.title", "伐木工");
            translationBuilder.add("mme.advancements.story.flint_axe.description", "斧头 pro max");
            translationBuilder.add("mme.advancements.story.flint_shovel.title", "探索地表");
            translationBuilder.add("mme.advancements.story.flint_shovel.description", "铲铲铲");
            translationBuilder.add("mme.advancements.story.cudgel.title", "出击时间到");
            translationBuilder.add("mme.advancements.story.cudgel.description", "好像也就只能欺负欺负小白");
            translationBuilder.add("mme.advancements.story.copper_nugget.title", "贵金属");
            translationBuilder.add("mme.advancements.story.copper_nugget.description", "太贵重了");
            translationBuilder.add("mme.advancements.story.metal_crafting_table.title", "金属工作台");
            translationBuilder.add("mme.advancements.story.metal_crafting_table.description", "似乎不会增加制作速度");
            translationBuilder.add("mme.advancements.story.better_armor.title", "更好的护甲");
            translationBuilder.add("mme.advancements.story.better_armor.description", "冷冷的");
            translationBuilder.add("mme.advancements.story.pickaxe.title", "下矿时间到!");
            translationBuilder.add("mme.advancements.story.pickaxe.description", "终于熬出头了");
            translationBuilder.add("mme.advancements.story.mine_stone.title", "最低级的矿物");
            translationBuilder.add("mme.advancements.story.mine_stone.description", "获取铜和银的矿石");
            translationBuilder.add("mme.advancements.story.leather.title", "斗牛士");
            translationBuilder.add("mme.advancements.story.leather.description", "获得皮革");
            translationBuilder.add("mme.advancements.story.leather_armor.title", "别在裸奔了!");
            translationBuilder.add("mme.advancements.story.leather_armor.description", "获得皮革装备");
            translationBuilder.add("mme.advancements.story.fishing_go.title", "该钓鱼了");
            translationBuilder.add("mme.advancements.story.fishing_go.description", "获得钓鱼竿");
            translationBuilder.add("mme.advancements.story.delicious_fish.title", "美味的鱼儿");
            translationBuilder.add("mme.advancements.story.delicious_fish.description", "获得烤熟的鱼");
            translationBuilder.add("mme.advancements.story.mithril.title", "获得秘银");
            translationBuilder.add("mme.advancements.story.mithril.description", "蓝蓝的银");
            translationBuilder.add("mme.advancements.story.shiny_gear.title", "秘银护体");
            translationBuilder.add("mme.advancements.story.shiny_gear.description", "秘银盔甲能救人");
            translationBuilder.add("mme.advancements.story.enter_the_underground.title", "进入地底");
            translationBuilder.add("mme.advancements.story.enter_the_underground.description", "深邃的黑");

            translationBuilder.add("mme.advancements.underground.root.title", "地底");
            translationBuilder.add("mme.advancements.underground.root.description", "伸手不见五指");
            translationBuilder.add("mme.advancements.underground.find_mithril.title", "蔚蓝的传说");
            translationBuilder.add("mme.advancements.underground.find_mithril.description", "获得秘银矿石");
            translationBuilder.add("mme.advancements.underground.smelt_mithril.title", "蓝银蜕变");
            translationBuilder.add("mme.advancements.underground.smelt_mithril.description", "冶炼出秘银锭");
            translationBuilder.add("mme.advancements.underground.find_ancient_metal.title", "远古的馈赠");
            translationBuilder.add("mme.advancements.underground.find_ancient_metal.description", "获得远古金属锭");
            translationBuilder.add("mme.advancements.underground.ancient_metal_crafting_table.title", "远古工艺");
            translationBuilder.add("mme.advancements.underground.ancient_metal_crafting_table.description", "获得远古金属工作台");
            translationBuilder.add("mme.advancements.underground.mithril_tool.title", "秘银锻造");
            translationBuilder.add("mme.advancements.underground.mithril_tool.description", "获得一件秘银工具");
            translationBuilder.add("mme.advancements.underground.find_adamantium.title", "坚不可摧");
            translationBuilder.add("mme.advancements.underground.find_adamantium.description", "获得艾德曼矿石");
            translationBuilder.add("mme.advancements.underground.smelt_adamantium.title", "万锻成钢");
            translationBuilder.add("mme.advancements.underground.smelt_adamantium.description", "冶炼出艾德曼锭");
            translationBuilder.add("mme.advancements.underground.adamantium_tool.title", "艾德曼之力");
            translationBuilder.add("mme.advancements.underground.adamantium_tool.description", "获得一件艾德曼工具");
            translationBuilder.add("mme.advancements.underground.adamantium_armor.title", "终极护甲");
            translationBuilder.add("mme.advancements.underground.adamantium_armor.description", "获得一件艾德曼装备");
            translationBuilder.add("mme.advancements.underground.enter_ancient_city.title", "寂静之城");
            translationBuilder.add("mme.advancements.underground.enter_ancient_city.description", "进入地底的远古城市");
            translationBuilder.add("mme.advancements.underground.deep_down.title", "深入地心");
            translationBuilder.add("mme.advancements.underground.deep_down.description", "到达地底Y=-60以下的深度");
            translationBuilder.add("mme.advancements.underground.mantle_portal.title", "地狱之门");
            translationBuilder.add("mme.advancements.underground.mantle_portal.description", "在地幔上点燃传送门进入下界");

            translationBuilder.add(MMEItems.ADAMANTIUM_HELMET, "艾德曼头盔");
            translationBuilder.add(MMEItems.ADAMANTIUM_CHESTPLATE, "艾德曼胸甲");
            translationBuilder.add(MMEItems.ADAMANTIUM_LEGGINGS, "艾德曼护腿");
            translationBuilder.add(MMEItems.ADAMANTIUM_BOOTS, "艾德曼靴子");
            translationBuilder.add(MMEItems.ADAMANTIUM_CHAINMAIL_HELMET, "艾德曼锁链头盔");
            translationBuilder.add(MMEItems.ADAMANTIUM_CHAINMAIL_CHESTPLATE, "艾德曼锁链胸甲");
            translationBuilder.add(MMEItems.ADAMANTIUM_CHAINMAIL_LEGGINGS, "艾德曼锁链护腿");
            translationBuilder.add(MMEItems.ADAMANTIUM_CHAINMAIL_BOOTS, "艾德曼锁链靴子");
            translationBuilder.add(MMEItems.MITHRIL_HELMET, "秘银头盔");
            translationBuilder.add(MMEItems.MITHRIL_CHESTPLATE, "秘银胸甲");
            translationBuilder.add(MMEItems.MITHRIL_LEGGINGS, "秘银护腿");
            translationBuilder.add(MMEItems.MITHRIL_BOOTS, "秘银靴子");
            translationBuilder.add(MMEItems.MITHRIL_CHAINMAIL_HELMET, "秘银锁链头盔");
            translationBuilder.add(MMEItems.MITHRIL_CHAINMAIL_CHESTPLATE, "秘银锁链胸甲");
            translationBuilder.add(MMEItems.MITHRIL_CHAINMAIL_LEGGINGS, "秘银锁链护腿");
            translationBuilder.add(MMEItems.MITHRIL_CHAINMAIL_BOOTS, "秘银锁链靴子");
            translationBuilder.add(MMEItems.ANCIENT_METAL_HELMET, "远古金属头盔");
            translationBuilder.add(MMEItems.ANCIENT_METAL_CHESTPLATE, "远古金属胸甲");
            translationBuilder.add(MMEItems.ANCIENT_METAL_LEGGINGS, "远古金属护腿");
            translationBuilder.add(MMEItems.ANCIENT_METAL_BOOTS, "远古金属靴子");
            translationBuilder.add(MMEItems.ANCIENT_METAL_CHAINMAIL_HELMET, "远古金属锁链头盔");
            translationBuilder.add(MMEItems.ANCIENT_METAL_CHAINMAIL_CHESTPLATE, "远古金属锁链胸甲");
            translationBuilder.add(MMEItems.ANCIENT_METAL_CHAINMAIL_LEGGINGS, "远古金属锁链护腿");
            translationBuilder.add(MMEItems.ANCIENT_METAL_CHAINMAIL_BOOTS, "远古金属锁链靴子");
            translationBuilder.add(MMEItems.RUSTED_IRON_HELMET, "锈铁头盔");
            translationBuilder.add(MMEItems.RUSTED_IRON_CHESTPLATE, "锈铁胸甲");
            translationBuilder.add(MMEItems.RUSTED_IRON_LEGGINGS, "锈铁护腿");
            translationBuilder.add(MMEItems.RUSTED_IRON_BOOTS, "锈铁靴子");
            translationBuilder.add(MMEItems.RUSTED_IRON_CHAINMAIL_HELMET, "锈铁锁链头盔");
            translationBuilder.add(MMEItems.RUSTED_IRON_CHAINMAIL_CHESTPLATE, "锈铁锁链胸甲");
            translationBuilder.add(MMEItems.RUSTED_IRON_CHAINMAIL_LEGGINGS, "锈铁锁链护腿");
            translationBuilder.add(MMEItems.RUSTED_IRON_CHAINMAIL_BOOTS, "锈铁锁链靴子");
            translationBuilder.add(MMEItems.COPPER_CHAINMAIL_HELMET, "铜锁链头盔");
            translationBuilder.add(MMEItems.COPPER_CHAINMAIL_CHESTPLATE, "铜锁链胸甲");
            translationBuilder.add(MMEItems.COPPER_CHAINMAIL_LEGGINGS, "铜锁链护腿");
            translationBuilder.add(MMEItems.COPPER_CHAINMAIL_BOOTS, "铜锁链靴子");
            translationBuilder.add(MMEItems.SILVER_HELMET, "银头盔");
            translationBuilder.add(MMEItems.SILVER_CHESTPLATE, "银胸甲");
            translationBuilder.add(MMEItems.SILVER_LEGGINGS, "银护腿");
            translationBuilder.add(MMEItems.SILVER_BOOTS, "银靴子");
            translationBuilder.add(MMEItems.SILVER_CHAINMAIL_HELMET, "银锁链头盔");
            translationBuilder.add(MMEItems.SILVER_CHAINMAIL_CHESTPLATE, "银锁链胸甲");
            translationBuilder.add(MMEItems.SILVER_CHAINMAIL_LEGGINGS, "银锁链护腿");
            translationBuilder.add(MMEItems.SILVER_CHAINMAIL_BOOTS, "银锁链靴子");
            translationBuilder.add(MMEItems.GOLDEN_CHAINMAIL_HELMET, "金锁链头盔");
            translationBuilder.add(MMEItems.GOLDEN_CHAINMAIL_CHESTPLATE, "金锁链胸甲");
            translationBuilder.add(MMEItems.GOLDEN_CHAINMAIL_LEGGINGS, "金锁链护腿");
            translationBuilder.add(MMEItems.GOLDEN_CHAINMAIL_BOOTS, "金锁链靴子");

            translationBuilder.add(MMEItems.BANANA, "香蕉");
            translationBuilder.add(MMEItems.BLUE_BERRIE, "蓝莓");
            translationBuilder.add(MMEItems.CHEESE, "奶酪");
            translationBuilder.add(MMEItems.CHOCOLATE, "巧克力");
            translationBuilder.add(MMEItems.DOUGH, "面团");
            translationBuilder.add(MMEItems.ONION, "洋葱");
            translationBuilder.add(MMEItems.LEMON, "柠檬");
            translationBuilder.add(MMEItems.ORANGE, "橘子");
            translationBuilder.add(MMEItems.WORM_COOKED, "烤熟的虫子");
            translationBuilder.add(MMEItems.WORM_RAW, "生的虫子");
            translationBuilder.add(MMEItems.BEEF_STEW, "炖牛肉");
            translationBuilder.add(MMEItems.FLOUR, "面粉");
            translationBuilder.add(MMEItems.BOWL_MILK, "一碗牛奶");
            translationBuilder.add(MMEItems.BOWL_SALAD, "一碗沙拉");
            translationBuilder.add(MMEItems.BOWL_WATER, "一碗水");
            translationBuilder.add(MMEItems.CEREAL, "麦片粥");
            translationBuilder.add(MMEItems.CHICKEN_SOUP, "鸡汤");
            translationBuilder.add(MMEItems.CREAM_OF_MUSHROOM_SOUP, "奶油蘑菇汤");
            translationBuilder.add(MMEItems.CREAM_OF_VEGETABLE_SOUP, "奶油蔬菜汤");
            translationBuilder.add(MMEItems.ICE_CREAM, "冰淇淋");
            translationBuilder.add(MMEItems.MASHED_POTATO, "土豆泥");
            translationBuilder.add(MMEItems.PORRIDGE, "蓝莓粥");
            translationBuilder.add(MMEItems.PUMPKIN_SOUP, "南瓜汤");
            translationBuilder.add(MMEItems.SORBET, "雪糕");
            translationBuilder.add(MMEItems.VEGETABLE_SOUP, "蔬菜汤");

            translationBuilder.add(MMEItems.ADAMANTIUM_CHAINS, "艾德曼链");
            translationBuilder.add(MMEItems.ANCIENT_METAL_CHAINS, "远古金属链");
            translationBuilder.add(MMEItems.COPPER_CHAINS, "铜链");
            translationBuilder.add(MMEItems.MITHRIL_CHAINS, "秘银链");
            translationBuilder.add(MMEItems.RUSTED_IRON_CHAINS, "锈铁链");
            translationBuilder.add(MMEItems.SILVER_CHAINS, "银链");
            translationBuilder.add(MMEItems.GOLDEN_CHAINS, "金链");
            translationBuilder.add(MMEItems.IRON_CHAINS, "铁链");
            translationBuilder.add(MMEItems.NETHERITE_COINS, "下界合金币");
            translationBuilder.add(MMEItems.ADAMANTIUM_COINS, "艾德曼币");
            translationBuilder.add(MMEItems.ANCIENT_METAL_COINS, "远古金属币");
            translationBuilder.add(MMEItems.COPPER_COINS, "铜币");
            translationBuilder.add(MMEItems.MITHRIL_COINS, "秘银币");
            translationBuilder.add(MMEItems.GOLDEN_COINS, "金币");
            translationBuilder.add(MMEItems.SILVER_COINS, "银币");
            translationBuilder.add(MMEItems.IRON_COINS, "铁币");

            translationBuilder.add(MMEItems.NETHERITE_BATTLE_AXE, "下界合金战斧");
            translationBuilder.add(MMEItems.NETHERITE_DAGGER, "下界合金短剑");
            translationBuilder.add(MMEItems.NETHERITE_HATCHET, "下界合金短斧");
            translationBuilder.add(MMEItems.NETHERITE_KNIFE, "下界合金小刀");
            translationBuilder.add(MMEItems.NETHERITE_MATTOCK, "下界合金鹤嘴锄");
            translationBuilder.add(MMEItems.NETHERITE_SCYTHE, "下界合金镰刀");
            translationBuilder.add(MMEItems.NETHERITE_SHEARS, "下界合金剪刀");
            translationBuilder.add(MMEItems.NETHERITE_WAR_HAMMER, "下界合金锤");
            translationBuilder.add(MMEItems.ADAMANTIUM_AXE, "艾德曼斧");
            translationBuilder.add(MMEItems.ADAMANTIUM_BATTLE_AXE, "艾德曼战斧");
            translationBuilder.add(MMEItems.ADAMANTIUM_DAGGER, "艾德曼短剑");
            translationBuilder.add(MMEItems.ADAMANTIUM_HATCHET, "艾德曼短斧");
            translationBuilder.add(MMEItems.ADAMANTIUM_HOE, "艾德曼锄");
            translationBuilder.add(MMEItems.ADAMANTIUM_KNIFE, "艾德曼小刀");
            translationBuilder.add(MMEItems.ADAMANTIUM_MATTOCK, "艾德曼鹤嘴锄");
            translationBuilder.add(MMEItems.ADAMANTIUM_PICKAXE, "艾德曼镐");
            translationBuilder.add(MMEItems.ADAMANTIUM_SCYTHE, "艾德曼镰刀");
            translationBuilder.add(MMEItems.ADAMANTIUM_SHEARS, "艾德曼剪刀");
            translationBuilder.add(MMEItems.ADAMANTIUM_SHOVEL, "艾德曼铲");
            translationBuilder.add(MMEItems.ADAMANTIUM_SWORD, "艾德曼剑");
            translationBuilder.add(MMEItems.ADAMANTIUM_WAR_HAMMER, "艾德曼锤");
            translationBuilder.add(MMEItems.ADAMANTIUM_SPEAR, "艾德曼矛");
            translationBuilder.add(MMEItems.MITHRIL_AXE, "秘银斧");
            translationBuilder.add(MMEItems.MITHRIL_BATTLE_AXE, "秘银战斧");
            translationBuilder.add(MMEItems.MITHRIL_DAGGER, "秘银短剑");
            translationBuilder.add(MMEItems.MITHRIL_HATCHET, "秘银短斧");
            translationBuilder.add(MMEItems.MITHRIL_HOE, "秘银锄");
            translationBuilder.add(MMEItems.MITHRIL_KNIFE, "秘银小刀");
            translationBuilder.add(MMEItems.MITHRIL_MATTOCK, "秘银鹤嘴锄");
            translationBuilder.add(MMEItems.MITHRIL_PICKAXE, "秘银镐");
            translationBuilder.add(MMEItems.MITHRIL_SCYTHE, "秘银镰刀");
            translationBuilder.add(MMEItems.MITHRIL_SHEARS, "秘银剪刀");
            translationBuilder.add(MMEItems.MITHRIL_SHOVEL, "秘银铲");
            translationBuilder.add(MMEItems.MITHRIL_SWORD, "秘银剑");
            translationBuilder.add(MMEItems.MITHRIL_WAR_HAMMER, "秘银锤");
            translationBuilder.add(MMEItems.MITHRIL_SPEAR, "秘银矛");
            translationBuilder.add(MMEItems.ANCIENT_METAL_AXE, "远古金属斧");
            translationBuilder.add(MMEItems.ANCIENT_METAL_BATTLE_AXE, "远古金属战斧");
            translationBuilder.add(MMEItems.ANCIENT_METAL_DAGGER, "远古金属短剑");
            translationBuilder.add(MMEItems.ANCIENT_METAL_HATCHET, "远古金属短斧");
            translationBuilder.add(MMEItems.ANCIENT_METAL_HOE, "远古金属锄");
            translationBuilder.add(MMEItems.ANCIENT_METAL_KNIFE, "远古金属小刀");
            translationBuilder.add(MMEItems.ANCIENT_METAL_MATTOCK, "远古金属鹤嘴锄");
            translationBuilder.add(MMEItems.ANCIENT_METAL_PICKAXE, "远古金属镐");
            translationBuilder.add(MMEItems.ANCIENT_METAL_SCYTHE, "远古金属镰刀");
            translationBuilder.add(MMEItems.ANCIENT_METAL_SHEARS, "远古金属剪刀");
            translationBuilder.add(MMEItems.ANCIENT_METAL_SHOVEL, "远古金属铲");
            translationBuilder.add(MMEItems.ANCIENT_METAL_SWORD, "远古金属剑");
            translationBuilder.add(MMEItems.ANCIENT_METAL_WAR_HAMMER, "远古金属锤");
            translationBuilder.add(MMEItems.ANCIENT_METAL_SPEAR, "远古金属矛");
            translationBuilder.add(MMEItems.IRON_BATTLE_AXE, "铁战斧");
            translationBuilder.add(MMEItems.IRON_DAGGER, "铁短剑");
            translationBuilder.add(MMEItems.IRON_HATCHET, "铁短斧");
            translationBuilder.add(MMEItems.IRON_KNIFE, "铁小刀");
            translationBuilder.add(MMEItems.IRON_MATTOCK, "铁鹤嘴锄");
            translationBuilder.add(MMEItems.IRON_SCYTHE, "铁镰刀");
            translationBuilder.add(MMEItems.IRON_WAR_HAMMER, "铁锤");
            translationBuilder.add(MMEItems.RUSTED_IRON_AXE, "锈铁斧");
            translationBuilder.add(MMEItems.RUSTED_IRON_BATTLE_AXE, "锈铁战斧");
            translationBuilder.add(MMEItems.RUSTED_IRON_DAGGER, "锈铁短剑");
            translationBuilder.add(MMEItems.RUSTED_IRON_HATCHET, "锈铁短斧");
            translationBuilder.add(MMEItems.RUSTED_IRON_HOE, "锈铁锄");
            translationBuilder.add(MMEItems.RUSTED_IRON_KNIFE, "锈铁小刀");
            translationBuilder.add(MMEItems.RUSTED_IRON_MATTOCK, "锈铁鹤嘴锄");
            translationBuilder.add(MMEItems.RUSTED_IRON_PICKAXE, "锈铁镐");
            translationBuilder.add(MMEItems.RUSTED_IRON_SCYTHE, "锈铁镰刀");
            translationBuilder.add(MMEItems.RUSTED_IRON_SHEARS, "锈铁剪刀");
            translationBuilder.add(MMEItems.RUSTED_IRON_SHOVEL, "锈铁铲");
            translationBuilder.add(MMEItems.RUSTED_IRON_SWORD, "锈铁剑");
            translationBuilder.add(MMEItems.RUSTED_IRON_WAR_HAMMER, "锈铁锤");
            translationBuilder.add(MMEItems.RUSTED_IRON_SPEAR, "锈铁矛");
            translationBuilder.add(MMEItems.COPPER_BATTLE_AXE, "铜战斧");
            translationBuilder.add(MMEItems.COPPER_DAGGER, "铜短剑");
            translationBuilder.add(MMEItems.COPPER_HATCHET, "铜短斧");
            translationBuilder.add(MMEItems.COPPER_KNIFE, "铜小刀");
            translationBuilder.add(MMEItems.COPPER_MATTOCK, "铜鹤嘴锄");
            translationBuilder.add(MMEItems.COPPER_SCYTHE, "铜镰刀");
            translationBuilder.add(MMEItems.COPPER_SHEARS, "铜剪刀");
            translationBuilder.add(MMEItems.COPPER_WAR_HAMMER, "铜锤");
            translationBuilder.add(MMEItems.SILVER_AXE, "银斧");
            translationBuilder.add(MMEItems.SILVER_BATTLE_AXE, "银战斧");
            translationBuilder.add(MMEItems.SILVER_DAGGER, "银短剑");
            translationBuilder.add(MMEItems.SILVER_HATCHET, "银短斧");
            translationBuilder.add(MMEItems.SILVER_HOE, "银锄");
            translationBuilder.add(MMEItems.SILVER_KNIFE, "银小刀");
            translationBuilder.add(MMEItems.SILVER_MATTOCK, "银鹤嘴锄");
            translationBuilder.add(MMEItems.SILVER_PICKAXE, "银镐");
            translationBuilder.add(MMEItems.SILVER_SCYTHE, "银镰刀");
            translationBuilder.add(MMEItems.SILVER_SHEARS, "银剪刀");
            translationBuilder.add(MMEItems.SILVER_SHOVEL, "银铲");
            translationBuilder.add(MMEItems.SILVER_SWORD, "银剑");
            translationBuilder.add(MMEItems.SILVER_WAR_HAMMER, "银锤");
            translationBuilder.add(MMEItems.SILVER_SPEAR, "银矛");
            translationBuilder.add(MMEItems.GOLDEN_BATTLE_AXE, "金战斧");
            translationBuilder.add(MMEItems.GOLDEN_DAGGER, "金短剑");
            translationBuilder.add(MMEItems.GOLDEN_HATCHET, "金短斧");
            translationBuilder.add(MMEItems.GOLDEN_KNIFE, "金小刀");
            translationBuilder.add(MMEItems.GOLDEN_MATTOCK, "金鹤嘴锄");
            translationBuilder.add(MMEItems.GOLDEN_SCYTHE, "金镰刀");
            translationBuilder.add(MMEItems.GOLDEN_SHEARS, "金剪刀");
            translationBuilder.add(MMEItems.GOLDEN_WAR_HAMMER, "金锤");
            translationBuilder.add(MMEItems.FLINT_AXE, "燧石斧");
            translationBuilder.add(MMEItems.FLINT_HATCHET, "燧石短斧");
            translationBuilder.add(MMEItems.FLINT_KNIFE, "燧石小刀");
            translationBuilder.add(MMEItems.FLINT_SHOVEL, "燧石铲");
            translationBuilder.add(MMEItems.FLINT_SPEAR, "燧石矛");
            translationBuilder.add(MMEItems.OBSIDIAN_AXE, "黑曜石斧");
            translationBuilder.add(MMEItems.OBSIDIAN_HATCHET, "黑曜石短斧");
            translationBuilder.add(MMEItems.OBSIDIAN_KNIFE, "黑曜石小刀");
            translationBuilder.add(MMEItems.OBSIDIAN_SHOVEL, "黑曜石铲");
            translationBuilder.add(MMEItems.WOODEN_CLUB, "木棒");
            translationBuilder.add(MMEItems.WOODEN_CUDGEL, "小木棒");

            translationBuilder.add(MMEBlocks.ADAMANTIUM_ORE, "艾德曼矿");
            translationBuilder.add(MMEBlocks.ADAMANTIUM_BLOCK, "艾德曼块");
            translationBuilder.add(MMEBlocks.ANCIENT_METAL_BLOCK, "古代金属块");
            translationBuilder.add(MMEBlocks.MITHRIL_BLOCK, "秘银块");
            translationBuilder.add(MMEBlocks.MITHRIL_ORE, "秘银矿");
            translationBuilder.add(MMEBlocks.SILVER_BLOCK, "银块");
            translationBuilder.add(MMEBlocks.SILVER_ORE, "银矿");
            translationBuilder.add(MMEBlocks.MANTLE, "地幔");

            translationBuilder.add(MMEItems.NETHERITE_BUCKET, "下界合金桶");
            translationBuilder.add(MMEItems.LAVA_NETHERITE_BUCKET, "装满熔岩的下界合金桶");
            translationBuilder.add(MMEItems.WATER_NETHERITE_BUCKET, "装满水的下界合金桶");
            translationBuilder.add(MMEItems.POWDER_SNOW_NETHERITE_BUCKET, "装满细雪的下界合金桶");
            translationBuilder.add(MMEItems.MILK_NETHERITE_BUCKET, "装满牛奶的下界合金桶");
            translationBuilder.add(MMEItems.PUFFERFISH_NETHERITE_BUCKET, "装有河豚的下界合金桶");
            translationBuilder.add(MMEItems.SALMON_NETHERITE_BUCKET, "装有鲑鱼的下界合金桶");
            translationBuilder.add(MMEItems.COD_NETHERITE_BUCKET, "装有鳕鱼的下界合金桶");
            translationBuilder.add(MMEItems.TROPICAL_FISH_NETHERITE_BUCKET, "装有热带鱼的下界合金桶");
            translationBuilder.add(MMEItems.AXOLOTL_NETHERITE_BUCKET, "装有美西螈的下界合金桶");
            translationBuilder.add(MMEItems.TADPOLE_NETHERITE_BUCKET, "装有蝌蚪的下界合金桶");

            translationBuilder.add(MMEItems.ADAMANTIUM_BUCKET, "艾德曼桶");
            translationBuilder.add(MMEItems.LAVA_ADAMANTIUM_BUCKET, "装满熔岩的艾德曼桶");
            translationBuilder.add(MMEItems.WATER_ADAMANTIUM_BUCKET, "装满水的艾德曼桶");
            translationBuilder.add(MMEItems.POWDER_SNOW_ADAMANTIUM_BUCKET, "装满细雪的艾德曼桶");
            translationBuilder.add(MMEItems.MILK_ADAMANTIUM_BUCKET, "装满牛奶的艾德曼桶");
            translationBuilder.add(MMEItems.PUFFERFISH_ADAMANTIUM_BUCKET, "装有河豚的艾德曼桶");
            translationBuilder.add(MMEItems.SALMON_ADAMANTIUM_BUCKET, "装有鲑鱼的艾德曼桶");
            translationBuilder.add(MMEItems.COD_ADAMANTIUM_BUCKET, "装有鳕鱼的艾德曼桶");
            translationBuilder.add(MMEItems.TROPICAL_FISH_ADAMANTIUM_BUCKET, "装有热带鱼的艾德曼桶");
            translationBuilder.add(MMEItems.AXOLOTL_ADAMANTIUM_BUCKET, "装有美西螈的艾德曼桶");
            translationBuilder.add(MMEItems.TADPOLE_ADAMANTIUM_BUCKET, "装有蝌蚪的艾德曼桶");

            translationBuilder.add(MMEItems.MITHRIL_BUCKET, "秘银桶");
            translationBuilder.add(MMEItems.LAVA_MITHRIL_BUCKET, "装满熔岩的秘银桶");
            translationBuilder.add(MMEItems.WATER_MITHRIL_BUCKET, "装满水的秘银桶");
            translationBuilder.add(MMEItems.POWDER_SNOW_MITHRIL_BUCKET, "装满细雪的秘银桶");
            translationBuilder.add(MMEItems.MILK_MITHRIL_BUCKET, "装满牛奶的秘银桶");
            translationBuilder.add(MMEItems.PUFFERFISH_MITHRIL_BUCKET, "装有河豚的秘银桶");
            translationBuilder.add(MMEItems.SALMON_MITHRIL_BUCKET, "装有鲑鱼的秘银桶");
            translationBuilder.add(MMEItems.COD_MITHRIL_BUCKET, "装有鳕鱼的秘银桶");
            translationBuilder.add(MMEItems.TROPICAL_FISH_MITHRIL_BUCKET, "装有热带鱼的秘银桶");
            translationBuilder.add(MMEItems.AXOLOTL_MITHRIL_BUCKET, "装有美西螈的秘银桶");
            translationBuilder.add(MMEItems.TADPOLE_MITHRIL_BUCKET, "装有蝌蚪的秘银桶");

            translationBuilder.add(MMEItems.ANCIENT_METAL_BUCKET, "远古金属桶");
            translationBuilder.add(MMEItems.LAVA_ANCIENT_METAL_BUCKET, "装满熔岩的远古金属桶");
            translationBuilder.add(MMEItems.WATER_ANCIENT_METAL_BUCKET, "装满水的远古金属桶");
            translationBuilder.add(MMEItems.POWDER_SNOW_ANCIENT_METAL_BUCKET, "装满细雪的远古金属桶");
            translationBuilder.add(MMEItems.MILK_ANCIENT_METAL_BUCKET, "装满牛奶的远古金属桶");
            translationBuilder.add(MMEItems.PUFFERFISH_ANCIENT_METAL_BUCKET, "装有河豚的远古金属桶");
            translationBuilder.add(MMEItems.SALMON_ANCIENT_METAL_BUCKET, "装有鲑鱼的远古金属桶");
            translationBuilder.add(MMEItems.COD_ANCIENT_METAL_BUCKET, "装有鳕鱼的远古金属桶");
            translationBuilder.add(MMEItems.TROPICAL_FISH_ANCIENT_METAL_BUCKET, "装有热带鱼的远古金属桶");
            translationBuilder.add(MMEItems.AXOLOTL_ANCIENT_METAL_BUCKET, "装有美西螈的远古金属桶");
            translationBuilder.add(MMEItems.TADPOLE_ANCIENT_METAL_BUCKET, "装有蝌蚪的远古金属桶");

            translationBuilder.add(MMEItems.SILVER_BUCKET, "银桶");
            translationBuilder.add(MMEItems.LAVA_SILVER_BUCKET, "装满熔岩的银桶");
            translationBuilder.add(MMEItems.WATER_SILVER_BUCKET, "装满水的银桶");
            translationBuilder.add(MMEItems.POWDER_SNOW_SILVER_BUCKET, "装满细雪的银桶");
            translationBuilder.add(MMEItems.MILK_SILVER_BUCKET, "装满牛奶的银桶");
            translationBuilder.add(MMEItems.PUFFERFISH_SILVER_BUCKET, "装有河豚的银桶");
            translationBuilder.add(MMEItems.SALMON_SILVER_BUCKET, "装有鲑鱼的银桶");
            translationBuilder.add(MMEItems.COD_SILVER_BUCKET, "装有鳕鱼的银桶");
            translationBuilder.add(MMEItems.TROPICAL_FISH_SILVER_BUCKET, "装有热带鱼的银桶");
            translationBuilder.add(MMEItems.AXOLOTL_SILVER_BUCKET, "装有美西螈的银桶");
            translationBuilder.add(MMEItems.TADPOLE_SILVER_BUCKET, "装有蝌蚪的银桶");

            translationBuilder.add(MMEItems.COPPER_BUCKET, "铜桶");
            translationBuilder.add(MMEItems.LAVA_COPPER_BUCKET, "装满熔岩的铜桶");
            translationBuilder.add(MMEItems.WATER_COPPER_BUCKET, "装满水的铜桶");
            translationBuilder.add(MMEItems.POWDER_SNOW_COPPER_BUCKET, "装满细雪的铜桶");
            translationBuilder.add(MMEItems.MILK_COPPER_BUCKET, "装满牛奶的铜桶");
            translationBuilder.add(MMEItems.PUFFERFISH_COPPER_BUCKET, "装有河豚的铜桶");
            translationBuilder.add(MMEItems.SALMON_COPPER_BUCKET, "装有鲑鱼的铜桶");
            translationBuilder.add(MMEItems.COD_COPPER_BUCKET, "装有鳕鱼的铜桶");
            translationBuilder.add(MMEItems.TROPICAL_FISH_COPPER_BUCKET, "装有热带鱼的铜桶");
            translationBuilder.add(MMEItems.AXOLOTL_COPPER_BUCKET, "装有美西螈的铜桶");
            translationBuilder.add(MMEItems.TADPOLE_COPPER_BUCKET, "装有蝌蚪的铜桶");

            translationBuilder.add(MMEItems.GOLD_BUCKET, "金桶");
            translationBuilder.add(MMEItems.LAVA_GOLD_BUCKET, "装满熔岩的金桶");
            translationBuilder.add(MMEItems.WATER_GOLD_BUCKET, "装满水的金桶");
            translationBuilder.add(MMEItems.POWDER_SNOW_GOLD_BUCKET, "装满细雪的金桶");
            translationBuilder.add(MMEItems.MILK_GOLD_BUCKET, "装满牛奶的金桶");
            translationBuilder.add(MMEItems.PUFFERFISH_GOLD_BUCKET, "装有河豚的金桶");
            translationBuilder.add(MMEItems.SALMON_GOLD_BUCKET, "装有鲑鱼的金桶");
            translationBuilder.add(MMEItems.COD_GOLD_BUCKET, "装有鳕鱼的金桶");
            translationBuilder.add(MMEItems.TROPICAL_FISH_GOLD_BUCKET, "装有热带鱼的金桶");
            translationBuilder.add(MMEItems.AXOLOTL_GOLD_BUCKET, "装有美西螈的金桶");
            translationBuilder.add(MMEItems.TADPOLE_GOLD_BUCKET, "装有蝌蚪的金桶");

            translationBuilder.add(MMEItems.NETHERITE_FISHING_ROD, "下界合金鱼竿");
            translationBuilder.add(MMEItems.ADAMANTIUM_FISHING_ROD, "艾德曼鱼竿");
            translationBuilder.add(MMEItems.ANCIENT_METAL_FISHING_ROD, "远古金属鱼竿");
            translationBuilder.add(MMEItems.MITHRIL_FISHING_ROD, "秘银鱼竿");
            translationBuilder.add(MMEItems.SILVER_FISHING_ROD, "银鱼竿");
            translationBuilder.add(MMEItems.GOLDEN_FISHING_ROD, "金鱼竿");
            translationBuilder.add(MMEItems.COPPER_FISHING_ROD, "铜鱼竿");
            translationBuilder.add(MMEItems.IRON_FISHING_ROD, "铁鱼竿");
            translationBuilder.add(MMEItems.FLINT_FISHING_ROD, "燧石鱼竿");
            translationBuilder.add(MMEItems.OBSIDIAN_FISHING_ROD, "黑曜石鱼竿");

            translationBuilder.add(MMEItems.RAW_ADAMANTIUM, "粗艾德曼");
            translationBuilder.add(MMEItems.RAW_MITHRIL, "粗秘银");
            translationBuilder.add(MMEItems.RAW_SILVER, "粗银");

            translationBuilder.add(MMEItems.ADAMANTIUM_INGOT, "艾德曼锭");
            translationBuilder.add(MMEItems.ANCIENT_METAL_INGOT, "远古金属锭");
            translationBuilder.add(MMEItems.MITHRIL_INGOT, "秘银锭");
            translationBuilder.add(MMEItems.SILVER_INGOT, "银锭");

            translationBuilder.add(MMEItems.NETHERITE_NUGGET, "下界合金粒");
            translationBuilder.add(MMEItems.ADAMANTIUM_NUGGET, "艾德曼粒");
            translationBuilder.add(MMEItems.ANCIENT_METAL_NUGGET, "远古金属粒");
            translationBuilder.add(MMEItems.MITHRIL_NUGGET, "秘银粒");
            translationBuilder.add(MMEItems.SILVER_NUGGET, "银粒");

            translationBuilder.add(MMEItems.FLINT_SHARD, "燧石碎片");
            translationBuilder.add(MMEItems.OBSIDIAN_SHARD, "黑曜石碎片");

            translationBuilder.add(MMEBlocks.NETHERITE_ANVIL, "下界合金砧");
            translationBuilder.add(MMEBlocks.CHIPPED_NETHERITE_ANVIL, "开裂的下界合金砧");
            translationBuilder.add(MMEBlocks.DAMAGED_NETHERITE_ANVIL, "损坏的下界合金砧");
            translationBuilder.add(MMEBlocks.ADAMANTIUM_ANVIL, "艾德曼砧");
            translationBuilder.add(MMEBlocks.CHIPPED_ADAMANTIUM_ANVIL, "开裂的艾德曼砧");
            translationBuilder.add(MMEBlocks.DAMAGED_ADAMANTIUM_ANVIL, "损坏的艾德曼砧");
            translationBuilder.add(MMEBlocks.MITHRIL_ANVIL, "秘银砧");
            translationBuilder.add(MMEBlocks.CHIPPED_MITHRIL_ANVIL, "开裂的秘银砧");
            translationBuilder.add(MMEBlocks.DAMAGED_MITHRIL_ANVIL, "损坏的秘银砧");
            translationBuilder.add(MMEBlocks.ANCIENT_METAL_ANVIL, "远古金属砧");
            translationBuilder.add(MMEBlocks.CHIPPED_ANCIENT_METAL_ANVIL, "开裂的远古金属砧");
            translationBuilder.add(MMEBlocks.DAMAGED_ANCIENT_METAL_ANVIL, "损坏的远古金属砧");
            translationBuilder.add(MMEBlocks.SILVER_ANVIL, "银砧");
            translationBuilder.add(MMEBlocks.CHIPPED_SILVER_ANVIL, "开裂的银砧");
            translationBuilder.add(MMEBlocks.DAMAGED_SILVER_ANVIL, "损坏的银砧");
            translationBuilder.add(MMEBlocks.GOLDEN_ANVIL, "金砧");
            translationBuilder.add(MMEBlocks.CHIPPED_GOLDEN_ANVIL, "开裂的金砧");
            translationBuilder.add(MMEBlocks.DAMAGED_GOLDEN_ANVIL, "损坏的金砧");
            translationBuilder.add(MMEBlocks.COPPER_ANVIL, "铜砧");
            translationBuilder.add(MMEBlocks.CHIPPED_COPPER_ANVIL, "开裂的铜砧");
            translationBuilder.add(MMEBlocks.DAMAGED_COPPER_ANVIL, "损坏的铜砧");

            translationBuilder.add(MMEBlocks.MITHRIL_NUL_RUNESTORE, "秘银符文石");
            translationBuilder.add(MMEBlocks.MITHRIL_QUAS_RUNESTORE, "秘银符文石");
            translationBuilder.add(MMEBlocks.MITHRIL_POR_RUNESTORE, "秘银符文石");
            translationBuilder.add(MMEBlocks.MITHRIL_AN_RUNESTORE, "秘银符文石");
            translationBuilder.add(MMEBlocks.MITHRIL_NOX_RUNESTORE, "秘银符文石");
            translationBuilder.add(MMEBlocks.MITHRIL_FLAM_RUNESTORE, "秘银符文石");
            translationBuilder.add(MMEBlocks.MITHRIL_VAS_RUNESTORE, "秘银符文石");
            translationBuilder.add(MMEBlocks.MITHRIL_DES_RUNESTORE, "秘银符文石");
            translationBuilder.add(MMEBlocks.MITHRIL_ORT_RUNESTORE, "秘银符文石");
            translationBuilder.add(MMEBlocks.MITHRIL_TYM_RUNESTORE, "秘银符文石");
            translationBuilder.add(MMEBlocks.MITHRIL_CORP_RUNESTORE, "秘银符文石");
            translationBuilder.add(MMEBlocks.MITHRIL_LOR_RUNESTORE, "秘银符文石");
            translationBuilder.add(MMEBlocks.MITHRIL_MANI_RUNESTORE, "秘银符文石");
            translationBuilder.add(MMEBlocks.MITHRIL_JUX_RUNESTORE, "秘银符文石");
            translationBuilder.add(MMEBlocks.MITHRIL_YLEM_RUNESTORE, "秘银符文石");
            translationBuilder.add(MMEBlocks.MITHRIL_SANCT_RUNESTORE, "秘银符文石");

            translationBuilder.add(MMEBlocks.ADAMANTIUM_NUL_RUNESTORE, "艾德曼符文石");
            translationBuilder.add(MMEBlocks.ADAMANTIUM_QUAS_RUNESTORE, "艾德曼符文石");
            translationBuilder.add(MMEBlocks.ADAMANTIUM_POR_RUNESTORE, "艾德曼符文石");
            translationBuilder.add(MMEBlocks.ADAMANTIUM_AN_RUNESTORE, "艾德曼符文石");
            translationBuilder.add(MMEBlocks.ADAMANTIUM_NOX_RUNESTORE, "艾德曼符文石");
            translationBuilder.add(MMEBlocks.ADAMANTIUM_FLAM_RUNESTORE, "艾德曼符文石");
            translationBuilder.add(MMEBlocks.ADAMANTIUM_VAS_RUNESTORE, "艾德曼符文石");
            translationBuilder.add(MMEBlocks.ADAMANTIUM_DES_RUNESTORE, "艾德曼符文石");
            translationBuilder.add(MMEBlocks.ADAMANTIUM_ORT_RUNESTORE, "艾德曼符文石");
            translationBuilder.add(MMEBlocks.ADAMANTIUM_TYM_RUNESTORE, "艾德曼符文石");
            translationBuilder.add(MMEBlocks.ADAMANTIUM_CORP_RUNESTORE, "艾德曼符文石");
            translationBuilder.add(MMEBlocks.ADAMANTIUM_LOR_RUNESTORE, "艾德曼符文石");
            translationBuilder.add(MMEBlocks.ADAMANTIUM_MANI_RUNESTORE, "艾德曼符文石");
            translationBuilder.add(MMEBlocks.ADAMANTIUM_JUX_RUNESTORE, "艾德曼符文石");
            translationBuilder.add(MMEBlocks.ADAMANTIUM_YLEM_RUNESTORE, "艾德曼符文石");
            translationBuilder.add(MMEBlocks.ADAMANTIUM_SANCT_RUNESTORE, "艾德曼符文石");

            translationBuilder.add(MMEBlocks.ADAMANTIUM_CRAFTING_TABLE, "艾德曼工作台");
            translationBuilder.add(MMEBlocks.ANCIENT_METAL_CRAFTING_TABLE, "远古金属工作台");
            translationBuilder.add(MMEBlocks.COPPER_CRAFTING_TABLE, "铜工作台");
            translationBuilder.add(MMEBlocks.GOLD_CRAFTING_TABLE, "金工作台");
            translationBuilder.add(MMEBlocks.IRON_CRAFTING_TABLE, "铁工作台");
            translationBuilder.add(MMEBlocks.MITHRIL_CRAFTING_TABLE, "秘银工作台");
            translationBuilder.add(MMEBlocks.SILVER_CRAFTING_TABLE, "银工作台");
            translationBuilder.add(MMEBlocks.FLINT_CRAFTING_TABLE, "燧石工作台");
            translationBuilder.add(MMEBlocks.OBSIDIAN_CRAFTING_TABLE, "黑曜石工作台");

            translationBuilder.add(MMEBlocks.CLAY_FURNACE, "黏土熔炉");
            translationBuilder.add(MMEBlocks.HARDENED_CLAY_FURNACE, "硬化黏土熔炉");
            translationBuilder.add(MMEBlocks.NETHERRACK_FURNACE, "下界岩熔炉");
            translationBuilder.add(MMEBlocks.OBSIDIAN_FURNACE, "黑曜石熔炉");
            translationBuilder.add(MMEBlocks.SANDSTONE_FURNACE, "砂岩熔炉");

            translationBuilder.add(MMEBlocks.DEEPSLATE_ADAMANTIUM_ORE, "深层艾德曼矿石");
            translationBuilder.add(MMEBlocks.DEEPSLATE_MITHRIL_ORE, "深层秘银矿石");
            translationBuilder.add(MMEBlocks.DEEPSLATE_SILVER_ORE, "深层银矿石");

            translationBuilder.add(MMEBlocks.EMERALD_ENCHANTING_TABLE, "绿宝石附魔台");

            translationBuilder.add(MMEItems.SINEW, "皮革线");
            translationBuilder.add(MMEItems.MANURE, "粪便");
            translationBuilder.add(MMEItems.GHOUL_SPAWN_EGG, "食尸鬼刷怪蛋");
            translationBuilder.add(MMEEntityTypes.GHOUL, "食尸鬼");
            translationBuilder.add(MMEItems.SHADOW_SPAWN_EGG, "黑色食尸鬼刷怪蛋");
            translationBuilder.add(MMEEntityTypes.SHADOW, "黑色食尸鬼");
            translationBuilder.add(MMEItems.WIGHT_SPAWN_EGG, "白色食尸鬼刷怪蛋");
            translationBuilder.add(MMEEntityTypes.WIGHT, "白色食尸鬼");
            translationBuilder.add(MMEItems.INVISIBLE_STALKER_SPAWN_EGG, "影子潜伏者刷怪蛋");
            translationBuilder.add(MMEEntityTypes.INVISIBLE_STALKER, "影子潜伏者");
            translationBuilder.add(MMEItems.DEMON_SPIDER_SPAWN_EGG, "恶魔蜘蛛刷怪蛋");
            translationBuilder.add(MMEEntityTypes.DEMON_SPIDER, "恶魔蜘蛛");
            translationBuilder.add(MMEItems.PHASE_SPIDER_SPAWN_EGG, "相位蜘蛛刷怪蛋");
            translationBuilder.add(MMEEntityTypes.PHASE_SPIDER, "相位蜘蛛");
            translationBuilder.add(MMEItems.INFERNAL_CREEPER_SPAWN_EGG, "地狱爬行者刷怪蛋");
            translationBuilder.add(MMEEntityTypes.INFERNAL_CREEPER, "地狱爬行者");
            translationBuilder.add(MMEItems.FIRE_ELEMENTAL_SPAWN_EGG, "火元素刷怪蛋");
            translationBuilder.add(MMEEntityTypes.FIRE_ELEMENTAL, "火元素");
            translationBuilder.add(MMEItems.VAMPIRE_BAT_SPAWN_EGG, "吸血蝙蝠刷怪蛋");
            translationBuilder.add(MMEEntityTypes.VAMPIRE_BAT, "吸血蝙蝠");
            translationBuilder.add(MMEItems.NIGHTWING_SPAWN_EGG, "暗影蝙蝠刷怪蛋");
            translationBuilder.add(MMEEntityTypes.NIGHTWING, "暗影蝙蝠");
            translationBuilder.add(MMEItems.GIANT_VAMPIRE_BAT_SPAWN_EGG, "吸血巨蝠刷怪蛋");
            translationBuilder.add(MMEEntityTypes.GIANT_VAMPIRE_BAT, "吸血巨蝠");

            translationBuilder.add(MMEMobEffects.INSULIN_RESISTANCE.value(), "糖尿病");
            translationBuilder.add(MMEMobEffects.MALNUTRITION.value(), "营养不良");

            translationBuilder.addEnchantment(MMEEnchantments.BUTCHERING, "屠宰");
            translationBuilder.addEnchantment(MMEEnchantments.CLEAVING, "劈裂");
            translationBuilder.addEnchantment(MMEEnchantments.HARVESTING, "收获");
            translationBuilder.addEnchantment(MMEEnchantments.FERTILITY, "肥沃");
            translationBuilder.addEnchantment(MMEEnchantments.UPGRADE, "灌注");
            translationBuilder.add("container.enchant.upgrade_target", "§7附魔 → %s");
        }
    }
}
