package com.acuteterror233.mite.datagen;

import com.acuteterror233.mite.MME;
import com.acuteterror233.mite.atinterface.BlockModelGeneratorsExtension;
import com.acuteterror233.mite.atinterface.ItemModelGeneratorsExtension;
import com.acuteterror233.mite.block.AtBlocks;
import com.acuteterror233.mite.item.MMEItems;
import com.acuteterror233.mite.item.armor.MMEArmorMaterials;
import net.fabricmc.fabric.api.client.datagen.v1.provider.FabricModelProvider;
import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.minecraft.client.data.models.BlockModelGenerators;
import net.minecraft.client.data.models.ItemModelGenerators;
import net.minecraft.client.data.models.model.ModelTemplates;
import net.minecraft.client.data.models.model.TexturedModel;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.Items;


public class MMEModelProvider extends FabricModelProvider {
    public MMEModelProvider(FabricDataOutput output) {
        super(output);
    }

    @Override
    public void generateBlockStateModels(BlockModelGenerators blockStateModelGenerator) {
        blockStateModelGenerator.createTrivialCube(AtBlocks.ADAMANTIUM_ORE);
        ((BlockModelGeneratorsExtension)blockStateModelGenerator).MME$registerBars(AtBlocks.ADAMANTIUM_BARS);
        blockStateModelGenerator.createTrivialCube(AtBlocks.ADAMANTIUM_BLOCK);
        ((BlockModelGeneratorsExtension)blockStateModelGenerator).MME$registerBars(AtBlocks.MITHRIL_BARS);
        blockStateModelGenerator.createTrivialCube(AtBlocks.MITHRIL_BLOCK);
        ((BlockModelGeneratorsExtension)blockStateModelGenerator).MME$registerBars(AtBlocks.SILVER_BARS);
        blockStateModelGenerator.createTrivialCube(AtBlocks.SILVER_BLOCK);
        ((BlockModelGeneratorsExtension)blockStateModelGenerator).MME$registerBars(AtBlocks.ANCIENT_METAL_BARS);
        blockStateModelGenerator.createTrivialCube(AtBlocks.ANCIENT_METAL_BLOCK);
        ((BlockModelGeneratorsExtension)blockStateModelGenerator).MME$registerBars(AtBlocks.GOLDEN_BARS);
        blockStateModelGenerator.createTrivialCube(AtBlocks.MANTLE);
        blockStateModelGenerator.createTrivialCube(AtBlocks.MITHRIL_ORE);
        blockStateModelGenerator.createTrivialCube(AtBlocks.SILVER_ORE);
        ((BlockModelGeneratorsExtension) blockStateModelGenerator).MME$registerBars(AtBlocks.COPPER_BARS);

        blockStateModelGenerator.createDoor(AtBlocks.ADAMANTIUM_DOOR);
        blockStateModelGenerator.createDoor(AtBlocks.GOLDEN_DOOR);
        blockStateModelGenerator.createDoor(AtBlocks.SILVER_DOOR);
        blockStateModelGenerator.createDoor(AtBlocks.ANCIENT_METAL_DOOR);
        blockStateModelGenerator.createDoor(AtBlocks.MITHRIL_DOOR);
        ((BlockModelGeneratorsExtension) blockStateModelGenerator).MME$registerAnvil(AtBlocks.ADAMANTIUM_ANVIL, AtBlocks.CHIPPED_ADAMANTIUM_ANVIL, AtBlocks.DAMAGED_ADAMANTIUM_ANVIL);
        ((BlockModelGeneratorsExtension) blockStateModelGenerator).MME$registerAnvil(AtBlocks.MITHRIL_ANVIL, AtBlocks.CHIPPED_MITHRIL_ANVIL, AtBlocks.DAMAGED_MITHRIL_ANVIL);
        ((BlockModelGeneratorsExtension) blockStateModelGenerator).MME$registerAnvil(AtBlocks.ANCIENT_METAL_ANVIL, AtBlocks.CHIPPED_ANCIENT_METAL_ANVIL, AtBlocks.DAMAGED_ANCIENT_METAL_ANVIL);
        ((BlockModelGeneratorsExtension) blockStateModelGenerator).MME$registerAnvil(AtBlocks.GOLDEN_ANVIL, AtBlocks.CHIPPED_GOLDEN_ANVIL, AtBlocks.DAMAGED_GOLDEN_ANVIL);
        ((BlockModelGeneratorsExtension) blockStateModelGenerator).MME$registerAnvil(AtBlocks.SILVER_ANVIL, AtBlocks.CHIPPED_SILVER_ANVIL, AtBlocks.DAMAGED_SILVER_ANVIL);
        ((BlockModelGeneratorsExtension) blockStateModelGenerator).MME$registerAnvil(AtBlocks.COPPER_ANVIL, AtBlocks.CHIPPED_COPPER_ANVIL, AtBlocks.DAMAGED_COPPER_ANVIL);
        
        blockStateModelGenerator.createFurnace(AtBlocks.CLAY_FURNACE, TexturedModel.ORIENTABLE_ONLY_TOP);
        blockStateModelGenerator.createFurnace(AtBlocks.HARDENED_CLAY_FURNACE, TexturedModel.ORIENTABLE_ONLY_TOP);
        blockStateModelGenerator.createFurnace(AtBlocks.NETHERRACK_FURNACE, TexturedModel.ORIENTABLE_ONLY_TOP);
        blockStateModelGenerator.createFurnace(AtBlocks.OBSIDIAN_FURNACE, TexturedModel.ORIENTABLE_ONLY_TOP);
        blockStateModelGenerator.createFurnace(AtBlocks.SANDSTONE_FURNACE, TexturedModel.ORIENTABLE_ONLY_TOP);

        blockStateModelGenerator.createTrivialCube(AtBlocks.DEEPSLATE_ADAMANTIUM_ORE);
        blockStateModelGenerator.createTrivialCube(AtBlocks.DEEPSLATE_MITHRIL_ORE);
        blockStateModelGenerator.createTrivialCube(AtBlocks.DEEPSLATE_SILVER_ORE);

//        blockStateModelGenerator.registerSimpleCubeAll(AtBlocks.MITHRIL_NUL_RUNESTORE);
//        blockStateModelGenerator.registerSimpleCubeAll(AtBlocks.MITHRIL_QUAS_RUNESTORE);
//        blockStateModelGenerator.registerSimpleCubeAll(AtBlocks.MITHRIL_POR_RUNESTORE);
//        blockStateModelGenerator.registerSimpleCubeAll(AtBlocks.MITHRIL_AN_RUNESTORE);
//        blockStateModelGenerator.registerSimpleCubeAll(AtBlocks.MITHRIL_NOX_RUNESTORE);
//        blockStateModelGenerator.registerSimpleCubeAll(AtBlocks.MITHRIL_FLAM_RUNESTORE);
//        blockStateModelGenerator.registerSimpleCubeAll(AtBlocks.MITHRIL_VAS_RUNESTORE);
//        blockStateModelGenerator.registerSimpleCubeAll(AtBlocks.MITHRIL_DES_RUNESTORE);
//        blockStateModelGenerator.registerSimpleCubeAll(AtBlocks.MITHRIL_ORT_RUNESTORE);
//        blockStateModelGenerator.registerSimpleCubeAll(AtBlocks.MITHRIL_TYM_RUNESTORE);
//        blockStateModelGenerator.registerSimpleCubeAll(AtBlocks.MITHRIL_CORP_RUNESTORE);
//        blockStateModelGenerator.registerSimpleCubeAll(AtBlocks.MITHRIL_LOR_RUNESTORE);
//        blockStateModelGenerator.registerSimpleCubeAll(AtBlocks.MITHRIL_MANI_RUNESTORE);
//        blockStateModelGenerator.registerSimpleCubeAll(AtBlocks.MITHRIL_JUX_RUNESTORE);
//        blockStateModelGenerator.registerSimpleCubeAll(AtBlocks.MITHRIL_YLEM_RUNESTORE);
//        blockStateModelGenerator.registerSimpleCubeAll(AtBlocks.MITHRIL_SANCT_RUNESTORE);
//
//        blockStateModelGenerator.registerSimpleCubeAll(AtBlocks.ADAMANTIUM_NUL_RUNESTORE);
//        blockStateModelGenerator.registerSimpleCubeAll(AtBlocks.ADAMANTIUM_QUAS_RUNESTORE);
//        blockStateModelGenerator.registerSimpleCubeAll(AtBlocks.ADAMANTIUM_POR_RUNESTORE);
//        blockStateModelGenerator.registerSimpleCubeAll(AtBlocks.ADAMANTIUM_AN_RUNESTORE);
//        blockStateModelGenerator.registerSimpleCubeAll(AtBlocks.ADAMANTIUM_NOX_RUNESTORE);
//        blockStateModelGenerator.registerSimpleCubeAll(AtBlocks.ADAMANTIUM_FLAM_RUNESTORE);
//        blockStateModelGenerator.registerSimpleCubeAll(AtBlocks.ADAMANTIUM_VAS_RUNESTORE);
//        blockStateModelGenerator.registerSimpleCubeAll(AtBlocks.ADAMANTIUM_DES_RUNESTORE);
//        blockStateModelGenerator.registerSimpleCubeAll(AtBlocks.ADAMANTIUM_ORT_RUNESTORE);
//        blockStateModelGenerator.registerSimpleCubeAll(AtBlocks.ADAMANTIUM_TYM_RUNESTORE);
//        blockStateModelGenerator.registerSimpleCubeAll(AtBlocks.ADAMANTIUM_CORP_RUNESTORE);
//        blockStateModelGenerator.registerSimpleCubeAll(AtBlocks.ADAMANTIUM_LOR_RUNESTORE);
//        blockStateModelGenerator.registerSimpleCubeAll(AtBlocks.ADAMANTIUM_MANI_RUNESTORE);
//        blockStateModelGenerator.registerSimpleCubeAll(AtBlocks.ADAMANTIUM_JUX_RUNESTORE);
//        blockStateModelGenerator.registerSimpleCubeAll(AtBlocks.ADAMANTIUM_YLEM_RUNESTORE);
//        blockStateModelGenerator.registerSimpleCubeAll(AtBlocks.ADAMANTIUM_SANCT_RUNESTORE);
    }

    @Override
    public void generateItemModels(ItemModelGenerators itemModelGenerator) {
        ItemModelGeneratorsExtension extendedAccessor = (ItemModelGeneratorsExtension) itemModelGenerator;
        //装备部分
        itemModelGenerator.generateTrimmableItem(MMEItems.ADAMANTIUM_HELMET, MMEArmorMaterials.ADAMANTIUM_MATERIAL_KEY, ItemModelGenerators.TRIM_PREFIX_HELMET, false);
        itemModelGenerator.generateTrimmableItem(MMEItems.ADAMANTIUM_CHESTPLATE, MMEArmorMaterials.ADAMANTIUM_MATERIAL_KEY, ItemModelGenerators.TRIM_PREFIX_CHESTPLATE, false);
        itemModelGenerator.generateTrimmableItem(MMEItems.ADAMANTIUM_LEGGINGS, MMEArmorMaterials.ADAMANTIUM_MATERIAL_KEY, ItemModelGenerators.TRIM_PREFIX_LEGGINGS, false);
        itemModelGenerator.generateTrimmableItem(MMEItems.ADAMANTIUM_BOOTS, MMEArmorMaterials.ADAMANTIUM_MATERIAL_KEY, ItemModelGenerators.TRIM_PREFIX_BOOTS, false);
        itemModelGenerator.generateTrimmableItem(MMEItems.ADAMANTIUM_CHAINMAIL_HELMET, MMEArmorMaterials.ADAMANTIUM_CHAINMAIL_MATERIAL_KEY, ItemModelGenerators.TRIM_PREFIX_HELMET, false);
        itemModelGenerator.generateTrimmableItem(MMEItems.ADAMANTIUM_CHAINMAIL_CHESTPLATE, MMEArmorMaterials.ADAMANTIUM_CHAINMAIL_MATERIAL_KEY, ItemModelGenerators.TRIM_PREFIX_CHESTPLATE, false);
        itemModelGenerator.generateTrimmableItem(MMEItems.ADAMANTIUM_CHAINMAIL_LEGGINGS, MMEArmorMaterials.ADAMANTIUM_CHAINMAIL_MATERIAL_KEY, ItemModelGenerators.TRIM_PREFIX_LEGGINGS, false);
        itemModelGenerator.generateTrimmableItem(MMEItems.ADAMANTIUM_CHAINMAIL_BOOTS, MMEArmorMaterials.ADAMANTIUM_CHAINMAIL_MATERIAL_KEY, ItemModelGenerators.TRIM_PREFIX_BOOTS, false);
        itemModelGenerator.generateTrimmableItem(MMEItems.ANCIENT_METAL_HELMET, MMEArmorMaterials.ANCIENT_METAL_MATERIAL_KEY, ItemModelGenerators.TRIM_PREFIX_HELMET, false);
        itemModelGenerator.generateTrimmableItem(MMEItems.ANCIENT_METAL_CHESTPLATE, MMEArmorMaterials.ANCIENT_METAL_MATERIAL_KEY, ItemModelGenerators.TRIM_PREFIX_CHESTPLATE, false);
        itemModelGenerator.generateTrimmableItem(MMEItems.ANCIENT_METAL_LEGGINGS, MMEArmorMaterials.ANCIENT_METAL_MATERIAL_KEY, ItemModelGenerators.TRIM_PREFIX_LEGGINGS, false);
        itemModelGenerator.generateTrimmableItem(MMEItems.ANCIENT_METAL_BOOTS, MMEArmorMaterials.ANCIENT_METAL_MATERIAL_KEY, ItemModelGenerators.TRIM_PREFIX_BOOTS, false);
        itemModelGenerator.generateTrimmableItem(MMEItems.ANCIENT_METAL_CHAINMAIL_HELMET, MMEArmorMaterials.ANCIENT_METAL_CHAINMAIL_MATERIAL_KEY, ItemModelGenerators.TRIM_PREFIX_HELMET, false);
        itemModelGenerator.generateTrimmableItem(MMEItems.ANCIENT_METAL_CHAINMAIL_CHESTPLATE, MMEArmorMaterials.ANCIENT_METAL_CHAINMAIL_MATERIAL_KEY, ItemModelGenerators.TRIM_PREFIX_CHESTPLATE, false);
        itemModelGenerator.generateTrimmableItem(MMEItems.ANCIENT_METAL_CHAINMAIL_LEGGINGS, MMEArmorMaterials.ANCIENT_METAL_CHAINMAIL_MATERIAL_KEY, ItemModelGenerators.TRIM_PREFIX_LEGGINGS, false);
        itemModelGenerator.generateTrimmableItem(MMEItems.ANCIENT_METAL_CHAINMAIL_BOOTS, MMEArmorMaterials.ANCIENT_METAL_CHAINMAIL_MATERIAL_KEY, ItemModelGenerators.TRIM_PREFIX_BOOTS, false);
        itemModelGenerator.generateTrimmableItem(MMEItems.COPPER_HELMET, MMEArmorMaterials.COPPER_MATERIAL_KEY, ItemModelGenerators.TRIM_PREFIX_HELMET, false);
        itemModelGenerator.generateTrimmableItem(MMEItems.COPPER_CHESTPLATE, MMEArmorMaterials.COPPER_MATERIAL_KEY, ItemModelGenerators.TRIM_PREFIX_CHESTPLATE, false);
        itemModelGenerator.generateTrimmableItem(MMEItems.COPPER_LEGGINGS, MMEArmorMaterials.COPPER_MATERIAL_KEY, ItemModelGenerators.TRIM_PREFIX_LEGGINGS, false);
        itemModelGenerator.generateTrimmableItem(MMEItems.COPPER_BOOTS, MMEArmorMaterials.COPPER_MATERIAL_KEY, ItemModelGenerators.TRIM_PREFIX_BOOTS, false);
        itemModelGenerator.generateTrimmableItem(MMEItems.COPPER_CHAINMAIL_HELMET, MMEArmorMaterials.COPPER_CHAINMAIL_MATERIAL_KEY, ItemModelGenerators.TRIM_PREFIX_HELMET, false);
        itemModelGenerator.generateTrimmableItem(MMEItems.COPPER_CHAINMAIL_CHESTPLATE, MMEArmorMaterials.COPPER_CHAINMAIL_MATERIAL_KEY, ItemModelGenerators.TRIM_PREFIX_CHESTPLATE, false);
        itemModelGenerator.generateTrimmableItem(MMEItems.COPPER_CHAINMAIL_LEGGINGS, MMEArmorMaterials.COPPER_CHAINMAIL_MATERIAL_KEY, ItemModelGenerators.TRIM_PREFIX_LEGGINGS, false);
        itemModelGenerator.generateTrimmableItem(MMEItems.COPPER_CHAINMAIL_BOOTS, MMEArmorMaterials.COPPER_CHAINMAIL_MATERIAL_KEY, ItemModelGenerators.TRIM_PREFIX_BOOTS, false);
        itemModelGenerator.generateTrimmableItem(MMEItems.MITHRIL_HELMET, MMEArmorMaterials.MITHRIL_MATERIAL_KEY, ItemModelGenerators.TRIM_PREFIX_HELMET, false);
        itemModelGenerator.generateTrimmableItem(MMEItems.MITHRIL_CHESTPLATE, MMEArmorMaterials.MITHRIL_MATERIAL_KEY, ItemModelGenerators.TRIM_PREFIX_CHESTPLATE, false);
        itemModelGenerator.generateTrimmableItem(MMEItems.MITHRIL_LEGGINGS, MMEArmorMaterials.MITHRIL_MATERIAL_KEY, ItemModelGenerators.TRIM_PREFIX_LEGGINGS, false);
        itemModelGenerator.generateTrimmableItem(MMEItems.MITHRIL_BOOTS, MMEArmorMaterials.MITHRIL_MATERIAL_KEY, ItemModelGenerators.TRIM_PREFIX_BOOTS, false);
        itemModelGenerator.generateTrimmableItem(MMEItems.MITHRIL_CHAINMAIL_HELMET, MMEArmorMaterials.MITHRIL_CHAINMAIL_MATERIAL_KEY, ItemModelGenerators.TRIM_PREFIX_HELMET, false);
        itemModelGenerator.generateTrimmableItem(MMEItems.MITHRIL_CHAINMAIL_CHESTPLATE, MMEArmorMaterials.MITHRIL_CHAINMAIL_MATERIAL_KEY, ItemModelGenerators.TRIM_PREFIX_CHESTPLATE, false);
        itemModelGenerator.generateTrimmableItem(MMEItems.MITHRIL_CHAINMAIL_LEGGINGS, MMEArmorMaterials.MITHRIL_CHAINMAIL_MATERIAL_KEY, ItemModelGenerators.TRIM_PREFIX_LEGGINGS, false);
        itemModelGenerator.generateTrimmableItem(MMEItems.MITHRIL_CHAINMAIL_BOOTS, MMEArmorMaterials.MITHRIL_CHAINMAIL_MATERIAL_KEY, ItemModelGenerators.TRIM_PREFIX_BOOTS, false);
        itemModelGenerator.generateTrimmableItem(MMEItems.RUSTED_IRON_HELMET, MMEArmorMaterials.RUSTED_IRON_MATERIAL_KEY, ItemModelGenerators.TRIM_PREFIX_HELMET, false);
        itemModelGenerator.generateTrimmableItem(MMEItems.RUSTED_IRON_CHESTPLATE, MMEArmorMaterials.RUSTED_IRON_MATERIAL_KEY, ItemModelGenerators.TRIM_PREFIX_CHESTPLATE, false);
        itemModelGenerator.generateTrimmableItem(MMEItems.RUSTED_IRON_LEGGINGS, MMEArmorMaterials.RUSTED_IRON_MATERIAL_KEY, ItemModelGenerators.TRIM_PREFIX_LEGGINGS, false);
        itemModelGenerator.generateTrimmableItem(MMEItems.RUSTED_IRON_BOOTS, MMEArmorMaterials.RUSTED_IRON_MATERIAL_KEY, ItemModelGenerators.TRIM_PREFIX_BOOTS, false);
        itemModelGenerator.generateTrimmableItem(MMEItems.RUSTED_IRON_CHAINMAIL_HELMET, MMEArmorMaterials.RUSTED_IRON_CHAINMAIL_MATERIAL_KEY, ItemModelGenerators.TRIM_PREFIX_HELMET, false);
        itemModelGenerator.generateTrimmableItem(MMEItems.RUSTED_IRON_CHAINMAIL_CHESTPLATE, MMEArmorMaterials.RUSTED_IRON_CHAINMAIL_MATERIAL_KEY, ItemModelGenerators.TRIM_PREFIX_CHESTPLATE, false);
        itemModelGenerator.generateTrimmableItem(MMEItems.RUSTED_IRON_CHAINMAIL_LEGGINGS, MMEArmorMaterials.RUSTED_IRON_CHAINMAIL_MATERIAL_KEY, ItemModelGenerators.TRIM_PREFIX_LEGGINGS, false);
        itemModelGenerator.generateTrimmableItem(MMEItems.RUSTED_IRON_CHAINMAIL_BOOTS, MMEArmorMaterials.RUSTED_IRON_CHAINMAIL_MATERIAL_KEY, ItemModelGenerators.TRIM_PREFIX_BOOTS, false);
        itemModelGenerator.generateTrimmableItem(MMEItems.SILVER_HELMET, MMEArmorMaterials.SILVER_MATERIAL_KEY, ItemModelGenerators.TRIM_PREFIX_HELMET, false);
        itemModelGenerator.generateTrimmableItem(MMEItems.SILVER_CHESTPLATE, MMEArmorMaterials.SILVER_MATERIAL_KEY, ItemModelGenerators.TRIM_PREFIX_CHESTPLATE, false);
        itemModelGenerator.generateTrimmableItem(MMEItems.SILVER_LEGGINGS, MMEArmorMaterials.SILVER_MATERIAL_KEY, ItemModelGenerators.TRIM_PREFIX_LEGGINGS, false);
        itemModelGenerator.generateTrimmableItem(MMEItems.SILVER_BOOTS, MMEArmorMaterials.SILVER_MATERIAL_KEY, ItemModelGenerators.TRIM_PREFIX_BOOTS, false);
        itemModelGenerator.generateTrimmableItem(MMEItems.SILVER_CHAINMAIL_HELMET, MMEArmorMaterials.SILVER_CHAINMAIL_MATERIAL_KEY, ItemModelGenerators.TRIM_PREFIX_HELMET, false);
        itemModelGenerator.generateTrimmableItem(MMEItems.SILVER_CHAINMAIL_CHESTPLATE, MMEArmorMaterials.SILVER_CHAINMAIL_MATERIAL_KEY, ItemModelGenerators.TRIM_PREFIX_CHESTPLATE, false);
        itemModelGenerator.generateTrimmableItem(MMEItems.SILVER_CHAINMAIL_LEGGINGS, MMEArmorMaterials.SILVER_CHAINMAIL_MATERIAL_KEY, ItemModelGenerators.TRIM_PREFIX_LEGGINGS, false);
        itemModelGenerator.generateTrimmableItem(MMEItems.SILVER_CHAINMAIL_BOOTS, MMEArmorMaterials.SILVER_CHAINMAIL_MATERIAL_KEY, ItemModelGenerators.TRIM_PREFIX_BOOTS, false);
        itemModelGenerator.generateTrimmableItem(MMEItems.GOLDEN_CHAINMAIL_HELMET, MMEArmorMaterials.GOLD_MATERIAL_KEY, ItemModelGenerators.TRIM_PREFIX_HELMET, false);
        itemModelGenerator.generateTrimmableItem(MMEItems.GOLDEN_CHAINMAIL_CHESTPLATE, MMEArmorMaterials.GOLD_MATERIAL_KEY, ItemModelGenerators.TRIM_PREFIX_CHESTPLATE, false);
        itemModelGenerator.generateTrimmableItem(MMEItems.GOLDEN_CHAINMAIL_LEGGINGS, MMEArmorMaterials.GOLD_MATERIAL_KEY, ItemModelGenerators.TRIM_PREFIX_LEGGINGS, false);
        itemModelGenerator.generateTrimmableItem(MMEItems.GOLDEN_CHAINMAIL_BOOTS, MMEArmorMaterials.GOLD_MATERIAL_KEY, ItemModelGenerators.TRIM_PREFIX_BOOTS, false);

        //食物部分
        itemModelGenerator.generateFlatItem(MMEItems.BANANA, ModelTemplates.FLAT_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.BLUEBERRIE, ModelTemplates.FLAT_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.CHEESE, ModelTemplates.FLAT_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.CHOCOLATE, ModelTemplates.FLAT_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.DOUGH, ModelTemplates.FLAT_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.LEMON, ModelTemplates.FLAT_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.ONION, ModelTemplates.FLAT_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.ORANGE, ModelTemplates.FLAT_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.WORM_COOKED, ModelTemplates.FLAT_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.WORM_RAW, ModelTemplates.FLAT_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.BEEF_STEW, ModelTemplates.FLAT_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.BOWL_MILK, ModelTemplates.FLAT_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.BOWL_SALAD, ModelTemplates.FLAT_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.BOWL_WATER, ModelTemplates.FLAT_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.FLOUR, ModelTemplates.FLAT_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.CEREAL, ModelTemplates.FLAT_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.CHICKEN_SOUP, ModelTemplates.FLAT_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.CREAM_OF_MUSHROOM_SOUP, ModelTemplates.FLAT_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.CREAM_OF_VEGETABLE_SOUP, ModelTemplates.FLAT_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.ICE_CREAM, ModelTemplates.FLAT_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.MASHED_POTATO, ModelTemplates.FLAT_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.MUSHROOM_STEW, ModelTemplates.FLAT_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.PORRIDGE, ModelTemplates.FLAT_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.PUMPKIN_SOUP, ModelTemplates.FLAT_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.SORBET, ModelTemplates.FLAT_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.VEGETABLE_SOUP, ModelTemplates.FLAT_ITEM);

        //币,锁链和箭
        itemModelGenerator.generateFlatItem(MMEItems.ADAMANTIUM_ARROW, ModelTemplates.FLAT_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.ANCIENT_METAL_ARROW, ModelTemplates.FLAT_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.COPPER_ARROW, ModelTemplates.FLAT_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.MITHRIL_ARROW, ModelTemplates.FLAT_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.RUSTED_IRON_ARROW, ModelTemplates.FLAT_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.SILVER_ARROW, ModelTemplates.FLAT_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.FLINT_ARROW, ModelTemplates.FLAT_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.GOLDEN_ARROW, ModelTemplates.FLAT_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.IRON_ARROW, ModelTemplates.FLAT_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.OBSIDIAN_ARROW, ModelTemplates.FLAT_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.ADAMANTIUM_CHAINS, ModelTemplates.FLAT_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.ANCIENT_METAL_CHAINS, ModelTemplates.FLAT_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.COPPER_CHAINS, ModelTemplates.FLAT_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.MITHRIL_CHAINS, ModelTemplates.FLAT_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.RUSTED_IRON_CHAINS, ModelTemplates.FLAT_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.SILVER_CHAINS, ModelTemplates.FLAT_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.GOLDEN_CHAINS, ModelTemplates.FLAT_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.IRON_CHAINS, ModelTemplates.FLAT_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.ADAMANTIUM_COINS, ModelTemplates.FLAT_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.ANCIENT_METAL_COINS, ModelTemplates.FLAT_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.COPPER_COINS, ModelTemplates.FLAT_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.MITHRIL_COINS, ModelTemplates.FLAT_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.GOLD_COINS, ModelTemplates.FLAT_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.SILVER_COINS, ModelTemplates.FLAT_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.IRON_COINS, ModelTemplates.FLAT_ITEM);

        //工具,武器
        itemModelGenerator.generateFlatItem(MMEItems.NETHERITE_BATTLE_AXE, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.NETHERITE_DAGGER, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.NETHERITE_HATCHET, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.NETHERITE_KNIFE, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.NETHERITE_MATTOCK, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.NETHERITE_SCYTHE, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.NETHERITE_SHEARS, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.NETHERITE_WAR_HAMMER, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.ADAMANTIUM_AXE, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.ADAMANTIUM_BATTLE_AXE, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.ADAMANTIUM_DAGGER, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.ADAMANTIUM_HATCHET, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.ADAMANTIUM_HOE, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.ADAMANTIUM_KNIFE, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.ADAMANTIUM_MATTOCK, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.ADAMANTIUM_PICKAXE, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.ADAMANTIUM_SCYTHE, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.ADAMANTIUM_SHEARS, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.ADAMANTIUM_SHOVEL, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.ADAMANTIUM_SWORD, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.ADAMANTIUM_WAR_HAMMER, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.MITHRIL_AXE, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.MITHRIL_BATTLE_AXE, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.MITHRIL_DAGGER, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.MITHRIL_HATCHET, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.MITHRIL_HOE, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.MITHRIL_KNIFE, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.MITHRIL_MATTOCK, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.MITHRIL_PICKAXE, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.MITHRIL_SCYTHE, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.MITHRIL_SHEARS, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.MITHRIL_SHOVEL, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.MITHRIL_SWORD, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.MITHRIL_WAR_HAMMER, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.ANCIENT_METAL_AXE, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.ANCIENT_METAL_BATTLE_AXE, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.ANCIENT_METAL_DAGGER, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.ANCIENT_METAL_HATCHET, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.ANCIENT_METAL_HOE, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.ANCIENT_METAL_KNIFE, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.ANCIENT_METAL_MATTOCK, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.ANCIENT_METAL_PICKAXE, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.ANCIENT_METAL_SCYTHE, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.ANCIENT_METAL_SHEARS, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.ANCIENT_METAL_SHOVEL, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.ANCIENT_METAL_SWORD, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.ANCIENT_METAL_WAR_HAMMER, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.IRON_BATTLE_AXE, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.IRON_DAGGER, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.IRON_HATCHET, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.IRON_KNIFE, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.IRON_MATTOCK, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.IRON_SCYTHE, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.IRON_WAR_HAMMER, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.RUSTED_IRON_AXE, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.RUSTED_IRON_BATTLE_AXE, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.RUSTED_IRON_DAGGER, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.RUSTED_IRON_HATCHET, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.RUSTED_IRON_HOE, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.RUSTED_IRON_KNIFE, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.RUSTED_IRON_MATTOCK, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.RUSTED_IRON_PICKAXE, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.RUSTED_IRON_SCYTHE, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.RUSTED_IRON_SHEARS, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.RUSTED_IRON_SHOVEL, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.RUSTED_IRON_SWORD, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.RUSTED_IRON_WAR_HAMMER, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.COPPER_AXE, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.COPPER_BATTLE_AXE, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.COPPER_DAGGER, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.COPPER_HATCHET, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.COPPER_HOE, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.COPPER_KNIFE, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.COPPER_MATTOCK, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.COPPER_PICKAXE, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.COPPER_SCYTHE, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.COPPER_SHEARS, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.COPPER_SHOVEL, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.COPPER_SWORD, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.COPPER_WAR_HAMMER, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.SILVER_AXE, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.SILVER_BATTLE_AXE, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.SILVER_DAGGER, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.SILVER_HATCHET, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.SILVER_HOE, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.SILVER_KNIFE, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.SILVER_MATTOCK, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.SILVER_PICKAXE, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.SILVER_SCYTHE, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.SILVER_SHEARS, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.SILVER_SHOVEL, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.SILVER_SWORD, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.SILVER_WAR_HAMMER, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.GOLDEN_BATTLE_AXE, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.GOLDEN_DAGGER, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.GOLDEN_HATCHET, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.GOLDEN_KNIFE, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.GOLDEN_MATTOCK, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.GOLDEN_SCYTHE, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.GOLDEN_SHEARS, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.GOLDEN_WAR_HAMMER, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.FLINT_AXE, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.FLINT_HATCHET, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.FLINT_KNIFE, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.FLINT_SHOVEL, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.OBSIDIAN_AXE, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.OBSIDIAN_HATCHET, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.OBSIDIAN_KNIFE, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.OBSIDIAN_SHOVEL, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.STONE_DAGGER, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.WOODEN_CLUB, ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.WOODEN_CUDGEL, ModelTemplates.FLAT_HANDHELD_ITEM);

        ResourceLocation AXOLOTL = ResourceLocation.fromNamespaceAndPath(MME.MOD_ID, "item/nobuckets/axolotl");
        ResourceLocation COD = ResourceLocation.fromNamespaceAndPath(MME.MOD_ID, "item/nobuckets/cod");
        ResourceLocation LAVA = ResourceLocation.fromNamespaceAndPath(MME.MOD_ID, "item/nobuckets/lava");
        ResourceLocation MILK = ResourceLocation.fromNamespaceAndPath(MME.MOD_ID, "item/nobuckets/milk");
        ResourceLocation POWDER_SNOW = ResourceLocation.fromNamespaceAndPath(MME.MOD_ID, "item/nobuckets/powder_snow");
        ResourceLocation PUFFERFISH = ResourceLocation.fromNamespaceAndPath(MME.MOD_ID, "item/nobuckets/pufferfish");
        ResourceLocation SALMON = ResourceLocation.fromNamespaceAndPath(MME.MOD_ID, "item/nobuckets/salmon");
        ResourceLocation TADPOLE = ResourceLocation.fromNamespaceAndPath(MME.MOD_ID, "item/nobuckets/tadpole");
        ResourceLocation TROPICAL_FISH = ResourceLocation.fromNamespaceAndPath(MME.MOD_ID, "item/nobuckets/tropical_fish");
        ResourceLocation WATER = ResourceLocation.fromNamespaceAndPath(MME.MOD_ID, "item/nobuckets/water");

        extendedAccessor.MME$registerBucket(MMEItems.ADAMANTIUM_BUCKET, null, MMEItems.ADAMANTIUM_BUCKET);
        extendedAccessor.MME$registerBucket(MMEItems.WATER_ADAMANTIUM_BUCKET, WATER, MMEItems.ADAMANTIUM_BUCKET);
        extendedAccessor.MME$registerBucket(MMEItems.LAVA_ADAMANTIUM_BUCKET, LAVA, MMEItems.ADAMANTIUM_BUCKET);
        extendedAccessor.MME$registerBucket(MMEItems.POWDER_SNOW_ADAMANTIUM_BUCKET, POWDER_SNOW, MMEItems.ADAMANTIUM_BUCKET);
        extendedAccessor.MME$registerBucket(MMEItems.MILK_ADAMANTIUM_BUCKET, MILK, MMEItems.ADAMANTIUM_BUCKET);
        extendedAccessor.MME$registerBucket(MMEItems.PUFFERFISH_ADAMANTIUM_BUCKET, PUFFERFISH, MMEItems.ADAMANTIUM_BUCKET);
        extendedAccessor.MME$registerBucket(MMEItems.SALMON_ADAMANTIUM_BUCKET, SALMON, MMEItems.ADAMANTIUM_BUCKET);
        extendedAccessor.MME$registerBucket(MMEItems.COD_ADAMANTIUM_BUCKET, COD, MMEItems.ADAMANTIUM_BUCKET);
        extendedAccessor.MME$registerBucket(MMEItems.TROPICAL_FISH_ADAMANTIUM_BUCKET, TROPICAL_FISH, MMEItems.ADAMANTIUM_BUCKET);
        extendedAccessor.MME$registerBucket(MMEItems.AXOLOTL_ADAMANTIUM_BUCKET, AXOLOTL, MMEItems.ADAMANTIUM_BUCKET);
        extendedAccessor.MME$registerBucket(MMEItems.TADPOLE_ADAMANTIUM_BUCKET, TADPOLE, MMEItems.ADAMANTIUM_BUCKET);

        extendedAccessor.MME$registerBucket(MMEItems.ANCIENT_METAL_BUCKET, null, MMEItems.ANCIENT_METAL_BUCKET);
        extendedAccessor.MME$registerBucket(MMEItems.WATER_ANCIENT_METAL_BUCKET, WATER, MMEItems.ANCIENT_METAL_BUCKET);
        extendedAccessor.MME$registerBucket(MMEItems.LAVA_ANCIENT_METAL_BUCKET, LAVA, MMEItems.ANCIENT_METAL_BUCKET);
        extendedAccessor.MME$registerBucket(MMEItems.POWDER_SNOW_ANCIENT_METAL_BUCKET, POWDER_SNOW, MMEItems.ANCIENT_METAL_BUCKET);
        extendedAccessor.MME$registerBucket(MMEItems.MILK_ANCIENT_METAL_BUCKET, MILK, MMEItems.ANCIENT_METAL_BUCKET);
        extendedAccessor.MME$registerBucket(MMEItems.PUFFERFISH_ANCIENT_METAL_BUCKET, PUFFERFISH, MMEItems.ANCIENT_METAL_BUCKET);
        extendedAccessor.MME$registerBucket(MMEItems.SALMON_ANCIENT_METAL_BUCKET, SALMON, MMEItems.ANCIENT_METAL_BUCKET);
        extendedAccessor.MME$registerBucket(MMEItems.COD_ANCIENT_METAL_BUCKET, COD, MMEItems.ANCIENT_METAL_BUCKET);
        extendedAccessor.MME$registerBucket(MMEItems.TROPICAL_FISH_ANCIENT_METAL_BUCKET, TROPICAL_FISH, MMEItems.ANCIENT_METAL_BUCKET);
        extendedAccessor.MME$registerBucket(MMEItems.AXOLOTL_ANCIENT_METAL_BUCKET, AXOLOTL, MMEItems.ANCIENT_METAL_BUCKET);
        extendedAccessor.MME$registerBucket(MMEItems.TADPOLE_ANCIENT_METAL_BUCKET, TADPOLE, MMEItems.ANCIENT_METAL_BUCKET);

        extendedAccessor.MME$registerBucket(MMEItems.COPPER_BUCKET, null, MMEItems.COPPER_BUCKET);
        extendedAccessor.MME$registerBucket(MMEItems.WATER_COPPER_BUCKET, WATER, MMEItems.COPPER_BUCKET);
        extendedAccessor.MME$registerBucket(MMEItems.LAVA_COPPER_BUCKET, LAVA, MMEItems.COPPER_BUCKET);
        extendedAccessor.MME$registerBucket(MMEItems.POWDER_SNOW_COPPER_BUCKET, POWDER_SNOW, MMEItems.COPPER_BUCKET);
        extendedAccessor.MME$registerBucket(MMEItems.MILK_COPPER_BUCKET, MILK, MMEItems.COPPER_BUCKET);
        extendedAccessor.MME$registerBucket(MMEItems.PUFFERFISH_COPPER_BUCKET, PUFFERFISH, MMEItems.COPPER_BUCKET);
        extendedAccessor.MME$registerBucket(MMEItems.SALMON_COPPER_BUCKET, SALMON, MMEItems.COPPER_BUCKET);
        extendedAccessor.MME$registerBucket(MMEItems.COD_COPPER_BUCKET, COD, MMEItems.COPPER_BUCKET);
        extendedAccessor.MME$registerBucket(MMEItems.TROPICAL_FISH_COPPER_BUCKET, TROPICAL_FISH, MMEItems.COPPER_BUCKET);
        extendedAccessor.MME$registerBucket(MMEItems.AXOLOTL_COPPER_BUCKET, AXOLOTL, MMEItems.COPPER_BUCKET);
        extendedAccessor.MME$registerBucket(MMEItems.TADPOLE_COPPER_BUCKET, TADPOLE, MMEItems.COPPER_BUCKET);

        extendedAccessor.MME$registerBucket(MMEItems.GOLD_BUCKET, null, MMEItems.GOLD_BUCKET);
        extendedAccessor.MME$registerBucket(MMEItems.WATER_GOLD_BUCKET, WATER, MMEItems.GOLD_BUCKET);
        extendedAccessor.MME$registerBucket(MMEItems.LAVA_GOLD_BUCKET, LAVA, MMEItems.GOLD_BUCKET);
        extendedAccessor.MME$registerBucket(MMEItems.POWDER_SNOW_GOLD_BUCKET, POWDER_SNOW, MMEItems.GOLD_BUCKET);
        extendedAccessor.MME$registerBucket(MMEItems.MILK_GOLD_BUCKET, MILK, MMEItems.GOLD_BUCKET);
        extendedAccessor.MME$registerBucket(MMEItems.PUFFERFISH_GOLD_BUCKET, PUFFERFISH, MMEItems.GOLD_BUCKET);
        extendedAccessor.MME$registerBucket(MMEItems.SALMON_GOLD_BUCKET, SALMON, MMEItems.GOLD_BUCKET);
        extendedAccessor.MME$registerBucket(MMEItems.COD_GOLD_BUCKET, COD, MMEItems.GOLD_BUCKET);
        extendedAccessor.MME$registerBucket(MMEItems.TROPICAL_FISH_GOLD_BUCKET, TROPICAL_FISH, MMEItems.GOLD_BUCKET);
        extendedAccessor.MME$registerBucket(MMEItems.AXOLOTL_GOLD_BUCKET, AXOLOTL, MMEItems.GOLD_BUCKET);
        extendedAccessor.MME$registerBucket(MMEItems.TADPOLE_GOLD_BUCKET, TADPOLE, MMEItems.GOLD_BUCKET);

        extendedAccessor.MME$registerBucket(MMEItems.MITHRIL_BUCKET, null, MMEItems.MITHRIL_BUCKET);
        extendedAccessor.MME$registerBucket(MMEItems.WATER_MITHRIL_BUCKET, WATER, MMEItems.MITHRIL_BUCKET);
        extendedAccessor.MME$registerBucket(MMEItems.LAVA_MITHRIL_BUCKET, LAVA, MMEItems.MITHRIL_BUCKET);
        extendedAccessor.MME$registerBucket(MMEItems.POWDER_SNOW_MITHRIL_BUCKET, POWDER_SNOW, MMEItems.MITHRIL_BUCKET);
        extendedAccessor.MME$registerBucket(MMEItems.MILK_MITHRIL_BUCKET, MILK, MMEItems.MITHRIL_BUCKET);
        extendedAccessor.MME$registerBucket(MMEItems.PUFFERFISH_MITHRIL_BUCKET, PUFFERFISH, MMEItems.MITHRIL_BUCKET);
        extendedAccessor.MME$registerBucket(MMEItems.SALMON_MITHRIL_BUCKET, SALMON, MMEItems.MITHRIL_BUCKET);
        extendedAccessor.MME$registerBucket(MMEItems.COD_MITHRIL_BUCKET, COD, MMEItems.MITHRIL_BUCKET);
        extendedAccessor.MME$registerBucket(MMEItems.TROPICAL_FISH_MITHRIL_BUCKET, TROPICAL_FISH, MMEItems.MITHRIL_BUCKET);
        extendedAccessor.MME$registerBucket(MMEItems.AXOLOTL_MITHRIL_BUCKET, AXOLOTL, MMEItems.MITHRIL_BUCKET);
        extendedAccessor.MME$registerBucket(MMEItems.TADPOLE_MITHRIL_BUCKET, TADPOLE, MMEItems.MITHRIL_BUCKET);

        extendedAccessor.MME$registerBucket(MMEItems.SILVER_BUCKET, null, MMEItems.SILVER_BUCKET);
        extendedAccessor.MME$registerBucket(MMEItems.WATER_SILVER_BUCKET, WATER, MMEItems.SILVER_BUCKET);
        extendedAccessor.MME$registerBucket(MMEItems.LAVA_SILVER_BUCKET, LAVA, MMEItems.SILVER_BUCKET);
        extendedAccessor.MME$registerBucket(MMEItems.POWDER_SNOW_SILVER_BUCKET, POWDER_SNOW, MMEItems.SILVER_BUCKET);
        extendedAccessor.MME$registerBucket(MMEItems.MILK_SILVER_BUCKET, MILK, MMEItems.SILVER_BUCKET);
        extendedAccessor.MME$registerBucket(MMEItems.PUFFERFISH_SILVER_BUCKET, PUFFERFISH, MMEItems.SILVER_BUCKET);
        extendedAccessor.MME$registerBucket(MMEItems.SALMON_SILVER_BUCKET, SALMON, MMEItems.SILVER_BUCKET);
        extendedAccessor.MME$registerBucket(MMEItems.COD_SILVER_BUCKET, COD, MMEItems.SILVER_BUCKET);
        extendedAccessor.MME$registerBucket(MMEItems.TROPICAL_FISH_SILVER_BUCKET, TROPICAL_FISH, MMEItems.SILVER_BUCKET);
        extendedAccessor.MME$registerBucket(MMEItems.AXOLOTL_SILVER_BUCKET, AXOLOTL, MMEItems.SILVER_BUCKET);
        extendedAccessor.MME$registerBucket(MMEItems.TADPOLE_SILVER_BUCKET, TADPOLE, MMEItems.SILVER_BUCKET);

        extendedAccessor.MME$registerBucket(MMEItems.NETHERITE_BUCKET, null, MMEItems.NETHERITE_BUCKET);
        extendedAccessor.MME$registerBucket(MMEItems.WATER_NETHERITE_BUCKET, WATER, MMEItems.NETHERITE_BUCKET);
        extendedAccessor.MME$registerBucket(MMEItems.LAVA_NETHERITE_BUCKET, LAVA, MMEItems.NETHERITE_BUCKET);
        extendedAccessor.MME$registerBucket(MMEItems.POWDER_SNOW_NETHERITE_BUCKET, POWDER_SNOW, MMEItems.NETHERITE_BUCKET);
        extendedAccessor.MME$registerBucket(MMEItems.MILK_NETHERITE_BUCKET, MILK, MMEItems.NETHERITE_BUCKET);
        extendedAccessor.MME$registerBucket(MMEItems.PUFFERFISH_NETHERITE_BUCKET, PUFFERFISH, MMEItems.NETHERITE_BUCKET);
        extendedAccessor.MME$registerBucket(MMEItems.SALMON_NETHERITE_BUCKET, SALMON, MMEItems.NETHERITE_BUCKET);
        extendedAccessor.MME$registerBucket(MMEItems.COD_NETHERITE_BUCKET, COD, MMEItems.NETHERITE_BUCKET);
        extendedAccessor.MME$registerBucket(MMEItems.TROPICAL_FISH_NETHERITE_BUCKET, TROPICAL_FISH, MMEItems.NETHERITE_BUCKET);
        extendedAccessor.MME$registerBucket(MMEItems.AXOLOTL_NETHERITE_BUCKET, AXOLOTL, MMEItems.NETHERITE_BUCKET);
        extendedAccessor.MME$registerBucket(MMEItems.TADPOLE_NETHERITE_BUCKET, TADPOLE, MMEItems.NETHERITE_BUCKET);

        itemModelGenerator.generateBow(MMEItems.MITHRIL_BOW);
        itemModelGenerator.generateBow(MMEItems.ANCIENT_METAL_BOW);

        ResourceLocation cast = itemModelGenerator.createFlatItemModel(Items.FISHING_ROD, "_cast", ModelTemplates.FLAT_HANDHELD_ROD_ITEM);
        extendedAccessor.MME$registerFishingRod(MMEItems.ADAMANTIUM_FISHING_ROD, cast);
        extendedAccessor.MME$registerFishingRod(MMEItems.MITHRIL_FISHING_ROD, cast);
        extendedAccessor.MME$registerFishingRod(MMEItems.ANCIENT_METAL_FISHING_ROD, cast);
        extendedAccessor.MME$registerFishingRod(MMEItems.SILVER_FISHING_ROD, cast);
        extendedAccessor.MME$registerFishingRod(MMEItems.COPPER_FISHING_ROD, cast);
        extendedAccessor.MME$registerFishingRod(MMEItems.GOLDEN_FISHING_ROD, cast);
        extendedAccessor.MME$registerFishingRod(MMEItems.IRON_FISHING_ROD, cast);
        extendedAccessor.MME$registerFishingRod(MMEItems.FLINT_FISHING_ROD, cast);
        extendedAccessor.MME$registerFishingRod(MMEItems.OBSIDIAN_FISHING_ROD, cast);

        itemModelGenerator.generateFlatItem(MMEItems.RAW_ADAMANTIUM, ModelTemplates.FLAT_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.RAW_MITHRIL, ModelTemplates.FLAT_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.RAW_SILVER, ModelTemplates.FLAT_ITEM);

        itemModelGenerator.generateFlatItem(MMEItems.ADAMANTIUM_INGOT, ModelTemplates.FLAT_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.MITHRIL_INGOT, ModelTemplates.FLAT_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.ANCIENT_METAL_INGOT, ModelTemplates.FLAT_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.SILVER_INGOT, ModelTemplates.FLAT_ITEM);

        itemModelGenerator.generateFlatItem(MMEItems.ADAMANTIUM_NUGGET, ModelTemplates.FLAT_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.MITHRIL_NUGGET, ModelTemplates.FLAT_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.ANCIENT_METAL_NUGGET, ModelTemplates.FLAT_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.SILVER_NUGGET, ModelTemplates.FLAT_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.COPPER_NUGGET, ModelTemplates.FLAT_ITEM);

        itemModelGenerator.generateFlatItem(MMEItems.DIAMOND_SHARD, ModelTemplates.FLAT_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.EMERALD_SHARD, ModelTemplates.FLAT_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.FLINT_SHARD, ModelTemplates.FLAT_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.GLASS_SHARD, ModelTemplates.FLAT_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.OBSIDIAN_SHARD, ModelTemplates.FLAT_ITEM);
        itemModelGenerator.generateFlatItem(MMEItems.QUARTZ_SHARD, ModelTemplates.FLAT_ITEM);

        itemModelGenerator.generateFlatItem(MMEItems.SINEW, ModelTemplates.FLAT_ITEM);
    }
}
