package com.acuteterror233.mite.datagen;

import com.acuteterror233.mite.block.MMEBlocks;
import com.acuteterror233.mite.item.MMEItems;
import com.acuteterror233.mite.item.enchantment.MMEEnchantments;
import com.acuteterror233.mite.registry.tag.MMEBlockTags;
import com.acuteterror233.mite.registry.tag.MMEEnchantmentTags;
import com.acuteterror233.mite.registry.tag.MMEEntityTypeTags;
import com.acuteterror233.mite.registry.tag.MMEItemTags;
import com.acuteterror233.mite.world.biome.MMEBiomeKeys;
import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricTagProvider;
import net.minecraft.core.HolderLookup;
import net.minecraft.core.registries.Registries;
import net.minecraft.tags.BiomeTags;
import net.minecraft.tags.BlockTags;
import net.minecraft.tags.ItemTags;
import net.minecraft.world.entity.EntityType;
import net.minecraft.world.item.Items;
import net.minecraft.world.item.enchantment.Enchantment;
import net.minecraft.world.item.enchantment.Enchantments;
import net.minecraft.world.level.biome.Biome;
import net.minecraft.world.level.block.Blocks;

import java.util.concurrent.CompletableFuture;

public class MMETagProvider {
    MMETagProvider() {

    }
    public static class EnchantmentTag extends FabricTagProvider<Enchantment>{
        public EnchantmentTag(FabricDataOutput output, CompletableFuture<HolderLookup.Provider> registriesFuture) {
            super(output, Registries.ENCHANTMENT, registriesFuture);
        }

        @Override
        protected void addTags(HolderLookup.Provider wrapperLookup) {
            tag(MMEEnchantmentTags.EQUIPMENT_DROPS_EXCLUSIVE)
                    .add(Enchantments.LOOTING)
                    .add(MMEEnchantments.BUTCHERING);
        }
    }


    public static class BiomeTag extends FabricTagProvider<Biome>{
        public BiomeTag(FabricDataOutput output, CompletableFuture<HolderLookup.Provider> registriesFuture) {
            super(output, Registries.BIOME, registriesFuture);
        }

        @Override
        protected void addTags(HolderLookup.Provider wrapperLookup) {
            tag(BiomeTags.HAS_MINESHAFT)
                    .add(MMEBiomeKeys.DEEP_DARK)
                    .add(MMEBiomeKeys.DRIPSTONE_CAVES)
                    .add(MMEBiomeKeys.LUSH_CAVES)
                    .add(MMEBiomeKeys.UNDERGROUND);
            tag(BiomeTags.HAS_RUINED_PORTAL_MOUNTAIN)
                    .add(MMEBiomeKeys.DEEP_DARK)
                    .add(MMEBiomeKeys.DRIPSTONE_CAVES)
                    .add(MMEBiomeKeys.LUSH_CAVES)
                    .add(MMEBiomeKeys.UNDERGROUND);
        }
    }

    public static class EntityTypeTag extends FabricTagProvider<EntityType<?>> {
        public EntityTypeTag(FabricDataOutput output, CompletableFuture<HolderLookup.Provider> registriesFuture) {
            super(output, Registries.ENTITY_TYPE, registriesFuture);
        }

        @Override
        protected void addTags(HolderLookup.Provider wrapperLookup) {
            getOrCreateTagBuilder(MMEEntityTypeTags.SENSITIVE_TO_BUTCHERING)
                    .add(EntityType.CHICKEN)
                    .add(EntityType.COW)
                    .add(EntityType.HOGLIN)
                    .add(EntityType.MOOSHROOM)
                    .add(EntityType.PIG)
                    .add(EntityType.SHEEP)
                    .add(EntityType.RABBIT);
            getOrCreateTagBuilder(MMEEntityTypeTags.PRODUCE_MANURE)
                    .add(EntityType.COW)
                    .add(EntityType.CAMEL)
                    .add(EntityType.DONKEY)
                    .add(EntityType.GOAT)
                    .add(EntityType.HORSE)
                    .add(EntityType.LLAMA)
                    .add(EntityType.MOOSHROOM)
                    .add(EntityType.MULE)
                    .add(EntityType.PANDA)
                    .add(EntityType.PIG)
                    .add(EntityType.POLAR_BEAR)
                    .add(EntityType.SHEEP)
                    .add(EntityType.SNIFFER)
                    .add(EntityType.TRADER_LLAMA);
        }
    }

    public static class BlockTag extends FabricTagProvider.BlockTagProvider {
        public BlockTag(FabricDataOutput output, CompletableFuture<HolderLookup.Provider> registriesFuture) {
            super(output, registriesFuture);
        }

        @Override
        protected void addTags(HolderLookup.Provider wrapperLookup) {
            getOrCreateTagBuilder(MMEBlockTags.GLASS)
                    .add(Blocks.GLASS)
                    .add(Blocks.WHITE_STAINED_GLASS)
                    .add(Blocks.ORANGE_STAINED_GLASS)
                    .add(Blocks.MAGENTA_STAINED_GLASS)
                    .add(Blocks.LIGHT_BLUE_STAINED_GLASS)
                    .add(Blocks.YELLOW_STAINED_GLASS)
                    .add(Blocks.LIME_STAINED_GLASS)
                    .add(Blocks.PINK_STAINED_GLASS)
                    .add(Blocks.GRAY_STAINED_GLASS)
                    .add(Blocks.LIGHT_GRAY_STAINED_GLASS)
                    .add(Blocks.CYAN_STAINED_GLASS)
                    .add(Blocks.PURPLE_STAINED_GLASS)
                    .add(Blocks.BLUE_STAINED_GLASS)
                    .add(Blocks.BROWN_STAINED_GLASS)
                    .add(Blocks.GREEN_STAINED_GLASS)
                    .add(Blocks.RED_STAINED_GLASS)
                    .add(Blocks.BLACK_STAINED_GLASS)
                    .add(Blocks.TINTED_GLASS);
            getOrCreateTagBuilder(MMEBlockTags.GLASS_PANE)
                    .add(Blocks.GLASS_PANE)
                    .add(Blocks.WHITE_STAINED_GLASS_PANE)
                    .add(Blocks.ORANGE_STAINED_GLASS_PANE)
                    .add(Blocks.MAGENTA_STAINED_GLASS_PANE)
                    .add(Blocks.LIGHT_BLUE_STAINED_GLASS_PANE)
                    .add(Blocks.YELLOW_STAINED_GLASS_PANE)
                    .add(Blocks.LIME_STAINED_GLASS_PANE)
                    .add(Blocks.PINK_STAINED_GLASS_PANE)
                    .add(Blocks.GRAY_STAINED_GLASS_PANE)
                    .add(Blocks.LIGHT_GRAY_STAINED_GLASS_PANE)
                    .add(Blocks.CYAN_STAINED_GLASS_PANE)
                    .add(Blocks.PURPLE_STAINED_GLASS_PANE)
                    .add(Blocks.BLUE_STAINED_GLASS_PANE)
                    .add(Blocks.BROWN_STAINED_GLASS_PANE)
                    .add(Blocks.GREEN_STAINED_GLASS_PANE)
                    .add(Blocks.RED_STAINED_GLASS_PANE)
                    .add(Blocks.BLACK_STAINED_GLASS_PANE);
            getOrCreateTagBuilder(BlockTags.ANVIL)
                    .add(MMEBlocks.NETHERITE_ANVIL)
                    .add(MMEBlocks.CHIPPED_NETHERITE_ANVIL)
                    .add(MMEBlocks.DAMAGED_NETHERITE_ANVIL)
                    .add(MMEBlocks.ADAMANTIUM_ANVIL)
                    .add(MMEBlocks.CHIPPED_ADAMANTIUM_ANVIL)
                    .add(MMEBlocks.DAMAGED_ADAMANTIUM_ANVIL)
                    .add(MMEBlocks.MITHRIL_ANVIL)
                    .add(MMEBlocks.CHIPPED_MITHRIL_ANVIL)
                    .add(MMEBlocks.DAMAGED_MITHRIL_ANVIL)
                    .add(MMEBlocks.ANCIENT_METAL_ANVIL)
                    .add(MMEBlocks.CHIPPED_ANCIENT_METAL_ANVIL)
                    .add(MMEBlocks.DAMAGED_ANCIENT_METAL_ANVIL)
                    .add(MMEBlocks.SILVER_ANVIL)
                    .add(MMEBlocks.CHIPPED_SILVER_ANVIL)
                    .add(MMEBlocks.DAMAGED_SILVER_ANVIL)
                    .add(MMEBlocks.GOLDEN_ANVIL)
                    .add(MMEBlocks.CHIPPED_GOLDEN_ANVIL)
                    .add(MMEBlocks.DAMAGED_GOLDEN_ANVIL)
                    .add(MMEBlocks.COPPER_ANVIL)
                    .add(MMEBlocks.CHIPPED_COPPER_ANVIL)
                    .add(MMEBlocks.DAMAGED_COPPER_ANVIL);
            getOrCreateTagBuilder(MMEBlockTags.INTACT_ANVIL)
                    .add(MMEBlocks.NETHERITE_ANVIL)
                    .add(MMEBlocks.ADAMANTIUM_ANVIL)
                    .add(MMEBlocks.MITHRIL_ANVIL)
                    .add(MMEBlocks.ANCIENT_METAL_ANVIL)
                    .add(MMEBlocks.SILVER_ANVIL)
                    .add(MMEBlocks.GOLDEN_ANVIL)
                    .add(MMEBlocks.COPPER_ANVIL);
            getOrCreateTagBuilder(MMEBlockTags.CHIPPED_ANVIL)
                    .add(MMEBlocks.CHIPPED_NETHERITE_ANVIL)
                    .add(MMEBlocks.CHIPPED_ADAMANTIUM_ANVIL)
                    .add(MMEBlocks.CHIPPED_MITHRIL_ANVIL)
                    .add(MMEBlocks.CHIPPED_ANCIENT_METAL_ANVIL)
                    .add(MMEBlocks.CHIPPED_SILVER_ANVIL)
                    .add(MMEBlocks.CHIPPED_GOLDEN_ANVIL)
                    .add(MMEBlocks.CHIPPED_COPPER_ANVIL);
            getOrCreateTagBuilder(MMEBlockTags.DAMAGED_ANVIL)
                    .add(MMEBlocks.DAMAGED_NETHERITE_ANVIL)
                    .add(MMEBlocks.DAMAGED_ADAMANTIUM_ANVIL)
                    .add(MMEBlocks.DAMAGED_MITHRIL_ANVIL)
                    .add(MMEBlocks.DAMAGED_ANCIENT_METAL_ANVIL)
                    .add(MMEBlocks.DAMAGED_SILVER_ANVIL)
                    .add(MMEBlocks.DAMAGED_GOLDEN_ANVIL)
                    .add(MMEBlocks.DAMAGED_COPPER_ANVIL);
            getOrCreateTagBuilder(MMEBlockTags.NETHERITE_ANVIL)
                    .add(MMEBlocks.NETHERITE_ANVIL)
                    .add(MMEBlocks.CHIPPED_NETHERITE_ANVIL)
                    .add(MMEBlocks.DAMAGED_NETHERITE_ANVIL);
            getOrCreateTagBuilder(MMEBlockTags.ADAMANTIUM_ANVIL)
                    .add(MMEBlocks.ADAMANTIUM_ANVIL)
                    .add(MMEBlocks.CHIPPED_ADAMANTIUM_ANVIL)
                    .add(MMEBlocks.DAMAGED_ADAMANTIUM_ANVIL);
            getOrCreateTagBuilder(MMEBlockTags.MITHRIL_ANVIL)
                    .add(MMEBlocks.MITHRIL_ANVIL)
                    .add(MMEBlocks.CHIPPED_MITHRIL_ANVIL)
                    .add(MMEBlocks.DAMAGED_MITHRIL_ANVIL);
            getOrCreateTagBuilder(MMEBlockTags.ANCIENT_METAL_ANVIL)
                    .add(MMEBlocks.ANCIENT_METAL_ANVIL)
                    .add(MMEBlocks.CHIPPED_ANCIENT_METAL_ANVIL)
                    .add(MMEBlocks.DAMAGED_ANCIENT_METAL_ANVIL);
            getOrCreateTagBuilder(MMEBlockTags.SILVER_ANVIL)
                    .add(MMEBlocks.SILVER_ANVIL)
                    .add(MMEBlocks.CHIPPED_SILVER_ANVIL)
                    .add(MMEBlocks.DAMAGED_SILVER_ANVIL);
            getOrCreateTagBuilder(MMEBlockTags.GOLDEN_ANVIL)
                    .add(MMEBlocks.GOLDEN_ANVIL)
                    .add(MMEBlocks.CHIPPED_GOLDEN_ANVIL)
                    .add(MMEBlocks.DAMAGED_GOLDEN_ANVIL);
            getOrCreateTagBuilder(MMEBlockTags.COPPER_ANVIL)
                    .add(MMEBlocks.COPPER_ANVIL)
                    .add(MMEBlocks.CHIPPED_COPPER_ANVIL)
                    .add(MMEBlocks.DAMAGED_COPPER_ANVIL);
            getOrCreateTagBuilder(MMEBlockTags.IRON_ANVIL)
                    .add(Blocks.ANVIL)
                    .add(Blocks.CHIPPED_ANVIL)
                    .add(Blocks.DAMAGED_ANVIL);
            getOrCreateTagBuilder(MMEBlockTags.PORTAL)
                    .add(MMEBlocks.UNDERGROUND_PORTAL)
                    .add(MMEBlocks.HOME_PORTAL)
                    .add(MMEBlocks.RUNE_PORTAL)
                    .add(Blocks.NETHER_PORTAL);
            getOrCreateTagBuilder(MMEBlockTags.MITHRIL_RUNESTORE)
                    .add(MMEBlocks.MITHRIL_NUL_RUNESTORE)
                    .add(MMEBlocks.MITHRIL_QUAS_RUNESTORE)
                    .add(MMEBlocks.MITHRIL_POR_RUNESTORE)
                    .add(MMEBlocks.MITHRIL_AN_RUNESTORE)
                    .add(MMEBlocks.MITHRIL_NOX_RUNESTORE)
                    .add(MMEBlocks.MITHRIL_FLAM_RUNESTORE)
                    .add(MMEBlocks.MITHRIL_VAS_RUNESTORE)
                    .add(MMEBlocks.MITHRIL_DES_RUNESTORE)
                    .add(MMEBlocks.MITHRIL_ORT_RUNESTORE)
                    .add(MMEBlocks.MITHRIL_TYM_RUNESTORE)
                    .add(MMEBlocks.MITHRIL_CORP_RUNESTORE)
                    .add(MMEBlocks.MITHRIL_LOR_RUNESTORE)
                    .add(MMEBlocks.MITHRIL_MANI_RUNESTORE)
                    .add(MMEBlocks.MITHRIL_JUX_RUNESTORE)
                    .add(MMEBlocks.MITHRIL_YLEM_RUNESTORE)
                    .add(MMEBlocks.MITHRIL_SANCT_RUNESTORE);
            getOrCreateTagBuilder(MMEBlockTags.ADAMANTIUM_RUNESTORE)
                    .add(MMEBlocks.ADAMANTIUM_NUL_RUNESTORE)
                    .add(MMEBlocks.ADAMANTIUM_QUAS_RUNESTORE)
                    .add(MMEBlocks.ADAMANTIUM_POR_RUNESTORE)
                    .add(MMEBlocks.ADAMANTIUM_AN_RUNESTORE)
                    .add(MMEBlocks.ADAMANTIUM_NOX_RUNESTORE)
                    .add(MMEBlocks.ADAMANTIUM_FLAM_RUNESTORE)
                    .add(MMEBlocks.ADAMANTIUM_VAS_RUNESTORE)
                    .add(MMEBlocks.ADAMANTIUM_DES_RUNESTORE)
                    .add(MMEBlocks.ADAMANTIUM_ORT_RUNESTORE)
                    .add(MMEBlocks.ADAMANTIUM_TYM_RUNESTORE)
                    .add(MMEBlocks.ADAMANTIUM_CORP_RUNESTORE)
                    .add(MMEBlocks.ADAMANTIUM_LOR_RUNESTORE)
                    .add(MMEBlocks.ADAMANTIUM_MANI_RUNESTORE)
                    .add(MMEBlocks.ADAMANTIUM_JUX_RUNESTORE)
                    .add(MMEBlocks.ADAMANTIUM_YLEM_RUNESTORE)
                    .add(MMEBlocks.ADAMANTIUM_SANCT_RUNESTORE);
            getOrCreateTagBuilder(MMEBlockTags.RUNESTORE)
                    .forceAddTag(MMEBlockTags.ADAMANTIUM_RUNESTORE)
                    .forceAddTag(MMEBlockTags.MITHRIL_RUNESTORE);
            getOrCreateTagBuilder(MMEBlockTags.CRAFTING_TABLE)
                    .add(MMEBlocks.ADAMANTIUM_CRAFTING_TABLE)
                    .add(MMEBlocks.MITHRIL_CRAFTING_TABLE)
                    .add(MMEBlocks.ANCIENT_METAL_CRAFTING_TABLE)
                    .add(MMEBlocks.IRON_CRAFTING_TABLE)
                    .add(MMEBlocks.GOLD_CRAFTING_TABLE)
                    .add(MMEBlocks.SILVER_CRAFTING_TABLE)
                    .add(MMEBlocks.COPPER_CRAFTING_TABLE)
                    .add(MMEBlocks.OBSIDIAN_CRAFTING_TABLE)
                    .add(MMEBlocks.FLINT_CRAFTING_TABLE);
            getOrCreateTagBuilder(MMEBlockTags.ENCHANTING_TABLE)
                    .add(Blocks.ENCHANTING_TABLE)
                    .add(MMEBlocks.EMERALD_ENCHANTING_TABLE);
            getOrCreateTagBuilder(MMEBlockTags.MINEABLE_WITH_MATTOCK)
                    .forceAddTag(BlockTags.MINEABLE_WITH_HOE)
                    .forceAddTag(BlockTags.MINEABLE_WITH_SHOVEL);

            getOrCreateTagBuilder(MMEBlockTags.NEEDS_ADAMANTIUM_TOOL)
                    .add(Blocks.ANCIENT_DEBRIS)
                    .add(Blocks.NETHERITE_BLOCK)
                    .add(MMEBlocks.ADAMANTIUM_BLOCK);
            getOrCreateTagBuilder(MMEBlockTags.NEEDS_MITHRIL_TOOL)
                    .add(MMEBlocks.MITHRIL_BLOCK)
                    .add(MMEBlocks.ADAMANTIUM_ORE)
                    .add(MMEBlocks.DEEPSLATE_ADAMANTIUM_ORE);
            getOrCreateTagBuilder(MMEBlockTags.NEEDS_ANCIENT_METAL_TOOL)
                    .add(MMEBlocks.ANCIENT_METAL_BLOCK)
                    .add(Blocks.DIAMOND_ORE)
                    .add(Blocks.DEEPSLATE_DIAMOND_ORE);
            getOrCreateTagBuilder(BlockTags.NEEDS_IRON_TOOL)
                    .add(MMEBlocks.MITHRIL_ORE)
                    .add(MMEBlocks.DEEPSLATE_MITHRIL_ORE);
            getOrCreateTagBuilder(MMEBlockTags.NEEDS_SILVER_OR_COPPER_TOOL)
                    .add(MMEBlocks.SILVER_BLOCK)
                    .add(Blocks.COPPER_BLOCK)
                    .forceAddTag(BlockTags.COPPER_ORES);

            getOrCreateTagBuilder(MMEBlockTags.INCORRECT_FOR_FLINT_OR_OBSIDIAN_TOOL)
                    .forceAddTag(MMEBlockTags.NEEDS_SILVER_OR_COPPER_TOOL)
                    .forceAddTag(MMEBlockTags.NEEDS_ANCIENT_METAL_TOOL)
                    .forceAddTag(MMEBlockTags.NEEDS_MITHRIL_TOOL)
                    .forceAddTag(MMEBlockTags.NEEDS_ADAMANTIUM_TOOL)
                    .forceAddTag(BlockTags.NEEDS_DIAMOND_TOOL)
                    .forceAddTag(BlockTags.NEEDS_IRON_TOOL)
                    .forceAddTag(BlockTags.NEEDS_STONE_TOOL);
            getOrCreateTagBuilder(MMEBlockTags.INCORRECT_FOR_COPPER_OR_SILVER_TOOL)
                    .forceAddTag(BlockTags.NEEDS_IRON_TOOL)
                    .forceAddTag(BlockTags.NEEDS_DIAMOND_TOOL)
                    .forceAddTag(MMEBlockTags.NEEDS_ANCIENT_METAL_TOOL)
                    .forceAddTag(MMEBlockTags.NEEDS_MITHRIL_TOOL)
                    .forceAddTag(MMEBlockTags.NEEDS_ADAMANTIUM_TOOL);
            getOrCreateTagBuilder(MMEBlockTags.INCORRECT_FOR_RUSTED_IRON_TOOL)
                    .forceAddTag(MMEBlockTags.NEEDS_ANCIENT_METAL_TOOL)
                    .forceAddTag(MMEBlockTags.NEEDS_MITHRIL_TOOL)
                    .forceAddTag(MMEBlockTags.NEEDS_ADAMANTIUM_TOOL);
            getOrCreateTagBuilder(MMEBlockTags.INCORRECT_FOR_ANCIENT_METAL_TOOL)
                    .forceAddTag(MMEBlockTags.NEEDS_MITHRIL_TOOL)
                    .forceAddTag(MMEBlockTags.NEEDS_ADAMANTIUM_TOOL);
            getOrCreateTagBuilder(MMEBlockTags.INCORRECT_FOR_MITHRIL_TOOL)
                    .forceAddTag(MMEBlockTags.NEEDS_ADAMANTIUM_TOOL);
            getOrCreateTagBuilder(MMEBlockTags.INCORRECT_FOR_ADAMANTIUM_TOOL);

            getOrCreateTagBuilder(BlockTags.MINEABLE_WITH_PICKAXE)
                    .addTag(MMEBlockTags.MITHRIL_RUNESTORE)
                    .addTag(MMEBlockTags.ADAMANTIUM_RUNESTORE)
                    .add(MMEBlocks.ADAMANTIUM_ORE)
                    .add(MMEBlocks.DEEPSLATE_ADAMANTIUM_ORE)
                    .add(MMEBlocks.MITHRIL_ORE)
                    .add(MMEBlocks.DEEPSLATE_MITHRIL_ORE)
                    .add(MMEBlocks.SILVER_ORE)
                    .add(MMEBlocks.DEEPSLATE_SILVER_ORE)
                    .add(MMEBlocks.ADAMANTIUM_BLOCK)
                    .add(MMEBlocks.ANCIENT_METAL_BLOCK)
                    .add(MMEBlocks.MITHRIL_BLOCK)
                    .add(MMEBlocks.SILVER_BLOCK);
            getOrCreateTagBuilder(BlockTags.BEE_GROWABLES)
                    .add(MMEBlocks.BLUE_BERRY_BUSH);
            getOrCreateTagBuilder(BlockTags.FALL_DAMAGE_RESETTING)
                    .add(MMEBlocks.BLUE_BERRY_BUSH);
            getOrCreateTagBuilder(MMEBlockTags.HERBACEOUS_PLANTS)
                    .add(Blocks.TALL_DRY_GRASS)
                    .add(Blocks.SHORT_GRASS)
                    .add(Blocks.FERN)
                    .add(Blocks.FLOWERING_AZALEA)
                    .add(Blocks.BUSH)
                    .add(Blocks.SUGAR_CANE)
                    .add(Blocks.TALL_GRASS)
                    .add(Blocks.LARGE_FERN)
                    .add(Blocks.TWISTING_VINES)
                    .add(Blocks.WEEPING_VINES)
                    .add(Blocks.DEAD_BUSH)
                    .add(Blocks.SHORT_DRY_GRASS);
            getOrCreateTagBuilder(BlockTags.SWORD_INSTANTLY_MINES)
                    .addTag(MMEBlockTags.HERBACEOUS_PLANTS)
                    .add(Blocks.KELP);
            getOrCreateTagBuilder(MMEBlockTags.MINEABLE_WITH_SCYTHE)
                    .addTag(MMEBlockTags.HERBACEOUS_PLANTS)
                    .add(Blocks.WHEAT)
                    .add(Blocks.KELP);
            getOrCreateTagBuilder(BlockTags.MINEABLE_WITH_HOE)
                    .add(Blocks.POTATOES)
                    .add(Blocks.CARROTS)
                    .add(Blocks.BEETROOTS)
                    .add(Blocks.MELON_STEM)
                    .add(Blocks.PUMPKIN_STEM)
                    .add(Blocks.NETHER_WART);
        }
    }

    public static class ItemTag extends FabricTagProvider.ItemTagProvider {
        public ItemTag(FabricDataOutput output, CompletableFuture<HolderLookup.Provider> completableFuture) {
            super(output, completableFuture);
        }
        @Override
        protected void addTags(HolderLookup.Provider wrapperLookup) {
            getOrCreateTagBuilder(ItemTags.HEAD_ARMOR)
                    .add(MMEItems.ADAMANTIUM_HELMET)
                    .add(MMEItems.ADAMANTIUM_CHAINMAIL_HELMET)
                    .add(MMEItems.ANCIENT_METAL_HELMET)
                    .add(MMEItems.ANCIENT_METAL_CHAINMAIL_HELMET)
                    .add(MMEItems.COPPER_HELMET)
                    .add(MMEItems.COPPER_CHAINMAIL_HELMET)
                    .add(MMEItems.MITHRIL_HELMET)
                    .add(MMEItems.MITHRIL_CHAINMAIL_HELMET)
                    .add(MMEItems.RUSTED_IRON_HELMET)
                    .add(MMEItems.RUSTED_IRON_CHAINMAIL_HELMET)
                    .add(MMEItems.SILVER_HELMET)
                    .add(MMEItems.SILVER_CHAINMAIL_HELMET)
                    .add(MMEItems.GOLDEN_CHAINMAIL_HELMET);
            getOrCreateTagBuilder(ItemTags.CHEST_ARMOR)
                    .add(MMEItems.ADAMANTIUM_CHESTPLATE)
                    .add(MMEItems.ADAMANTIUM_CHAINMAIL_CHESTPLATE)
                    .add(MMEItems.ANCIENT_METAL_CHESTPLATE)
                    .add(MMEItems.ANCIENT_METAL_CHAINMAIL_CHESTPLATE)
                    .add(MMEItems.COPPER_CHESTPLATE)
                    .add(MMEItems.COPPER_CHAINMAIL_CHESTPLATE)
                    .add(MMEItems.MITHRIL_CHESTPLATE)
                    .add(MMEItems.MITHRIL_CHAINMAIL_CHESTPLATE)
                    .add(MMEItems.RUSTED_IRON_CHESTPLATE)
                    .add(MMEItems.RUSTED_IRON_CHAINMAIL_CHESTPLATE)
                    .add(MMEItems.SILVER_CHESTPLATE)
                    .add(MMEItems.SILVER_CHAINMAIL_CHESTPLATE)
                    .add(MMEItems.GOLDEN_CHAINMAIL_CHESTPLATE);
            getOrCreateTagBuilder(ItemTags.LEG_ARMOR)
                    .add(MMEItems.ADAMANTIUM_LEGGINGS)
                    .add(MMEItems.ADAMANTIUM_CHAINMAIL_LEGGINGS)
                    .add(MMEItems.ANCIENT_METAL_LEGGINGS)
                    .add(MMEItems.ANCIENT_METAL_CHAINMAIL_LEGGINGS)
                    .add(MMEItems.COPPER_LEGGINGS)
                    .add(MMEItems.COPPER_CHAINMAIL_LEGGINGS)
                    .add(MMEItems.MITHRIL_LEGGINGS)
                    .add(MMEItems.MITHRIL_CHAINMAIL_LEGGINGS)
                    .add(MMEItems.RUSTED_IRON_LEGGINGS)
                    .add(MMEItems.RUSTED_IRON_CHAINMAIL_LEGGINGS)
                    .add(MMEItems.SILVER_LEGGINGS)
                    .add(MMEItems.SILVER_CHAINMAIL_LEGGINGS)
                    .add(MMEItems.GOLDEN_CHAINMAIL_LEGGINGS);
            getOrCreateTagBuilder(ItemTags.FOOT_ARMOR)
                    .add(MMEItems.ADAMANTIUM_BOOTS)
                    .add(MMEItems.ADAMANTIUM_CHAINMAIL_BOOTS)
                    .add(MMEItems.ANCIENT_METAL_BOOTS)
                    .add(MMEItems.ANCIENT_METAL_CHAINMAIL_BOOTS)
                    .add(MMEItems.COPPER_BOOTS)
                    .add(MMEItems.COPPER_CHAINMAIL_BOOTS)
                    .add(MMEItems.MITHRIL_BOOTS)
                    .add(MMEItems.MITHRIL_CHAINMAIL_BOOTS)
                    .add(MMEItems.RUSTED_IRON_BOOTS)
                    .add(MMEItems.RUSTED_IRON_CHAINMAIL_BOOTS)
                    .add(MMEItems.SILVER_BOOTS)
                    .add(MMEItems.SILVER_CHAINMAIL_BOOTS)
                    .add(MMEItems.GOLDEN_CHAINMAIL_BOOTS);
            getOrCreateTagBuilder(MMEItemTags.BUCKET)
                    .add(MMEItems.ADAMANTIUM_BUCKET)
                    .add(MMEItems.ANCIENT_METAL_BUCKET)
                    .add(MMEItems.COPPER_BUCKET)
                    .add(MMEItems.GOLD_BUCKET)
                    .add(MMEItems.MITHRIL_BUCKET)
                    .add(MMEItems.SILVER_BUCKET)
                    .add(MMEItems.NETHERITE_BUCKET)
                    .add(Items.BUCKET);
            getOrCreateTagBuilder(MMEItemTags.WATER_BUCKET)
                    .add(MMEItems.WATER_ADAMANTIUM_BUCKET)
                    .add(MMEItems.WATER_ANCIENT_METAL_BUCKET)
                    .add(MMEItems.WATER_COPPER_BUCKET)
                    .add(MMEItems.WATER_GOLD_BUCKET)
                    .add(MMEItems.WATER_MITHRIL_BUCKET)
                    .add(MMEItems.WATER_SILVER_BUCKET)
                    .add(MMEItems.WATER_NETHERITE_BUCKET)
                    .add(Items.WATER_BUCKET);
            getOrCreateTagBuilder(MMEItemTags.MILK_BUCKET)
                    .add(MMEItems.MILK_ADAMANTIUM_BUCKET)
                    .add(MMEItems.MILK_ANCIENT_METAL_BUCKET)
                    .add(MMEItems.MILK_COPPER_BUCKET)
                    .add(MMEItems.MILK_GOLD_BUCKET)
                    .add(MMEItems.MILK_MITHRIL_BUCKET)
                    .add(MMEItems.MILK_SILVER_BUCKET)
                    .add(MMEItems.MILK_NETHERITE_BUCKET)
                    .add(Items.MILK_BUCKET);
            getOrCreateTagBuilder(MMEItemTags.LAVA_BUCKET)
                    .add(MMEItems.LAVA_NETHERITE_BUCKET)
                    .add(MMEItems.LAVA_ADAMANTIUM_BUCKET)
                    .add(MMEItems.LAVA_MITHRIL_BUCKET)
                    .add(MMEItems.LAVA_ANCIENT_METAL_BUCKET)
                    .add(MMEItems.LAVA_COPPER_BUCKET)
                    .add(MMEItems.LAVA_SILVER_BUCKET)
                    .add(MMEItems.LAVA_GOLD_BUCKET)
                    .add(Items.LAVA_BUCKET);
            getOrCreateTagBuilder(MMEItemTags.FISHING_RODS)
                    .add(MMEItems.ADAMANTIUM_FISHING_ROD)
                    .add(MMEItems.ANCIENT_METAL_FISHING_ROD)
                    .add(MMEItems.COPPER_FISHING_ROD)
                    .add(MMEItems.MITHRIL_FISHING_ROD)
                    .add(MMEItems.GOLDEN_FISHING_ROD)
                    .add(MMEItems.IRON_FISHING_ROD)
                    .add(MMEItems.SILVER_FISHING_ROD)
                    .add(MMEItems.FLINT_FISHING_ROD)
                    .add(MMEItems.OBSIDIAN_FISHING_ROD)
                    .add(Items.FISHING_ROD);
            getOrCreateTagBuilder(MMEItemTags.NUGGET)
                    .add(Items.IRON_NUGGET)
                    .add(Items.GOLD_NUGGET)
                    .add(MMEItems.ADAMANTIUM_NUGGET)
                    .add(MMEItems.ANCIENT_METAL_NUGGET)
                    .add(MMEItems.MITHRIL_NUGGET)
                    .add(MMEItems.SILVER_NUGGET)
                    .add(MMEItems.COPPER_NUGGET);
            getOrCreateTagBuilder(MMEItemTags.SHARD)
                    .add(MMEItems.FLINT_SHARD)
                    .add(MMEItems.OBSIDIAN_SHARD);
            getOrCreateTagBuilder(MMEItemTags.INGOT)
                    .add(Items.IRON_INGOT)
                    .add(Items.GOLD_INGOT)
                    .add(Items.NETHERITE_INGOT)
                    .add(Items.COPPER_INGOT)
                    .add(MMEItems.ADAMANTIUM_INGOT)
                    .add(MMEItems.ANCIENT_METAL_INGOT)
                    .add(MMEItems.MITHRIL_INGOT)
                    .add(MMEItems.SILVER_INGOT);
            getOrCreateTagBuilder(MMEItemTags.CHAINS)
                    .add(MMEItems.ADAMANTIUM_CHAINS)
                    .add(MMEItems.ANCIENT_METAL_CHAINS)
                    .add(MMEItems.COPPER_CHAINS)
                    .add(MMEItems.MITHRIL_CHAINS)
                    .add(MMEItems.RUSTED_IRON_CHAINS)
                    .add(MMEItems.SILVER_CHAINS)
                    .add(MMEItems.GOLDEN_CHAINS)
                    .add(MMEItems.IRON_CHAINS);
            getOrCreateTagBuilder(MMEItemTags.COINS)
                    .add(MMEItems.ADAMANTIUM_COINS)
                    .add(MMEItems.ANCIENT_METAL_COINS)
                    .add(MMEItems.COPPER_COINS)
                    .add(MMEItems.MITHRIL_COINS)
                    .add(MMEItems.GOLD_COINS)
                    .add(MMEItems.SILVER_COINS)
                    .add(MMEItems.IRON_COINS);      
            getOrCreateTagBuilder(MMEItemTags.NETHERITE_TOOLS)
                    .add(Items.NETHERITE_AXE)
                    .add(MMEItems.NETHERITE_HATCHET)
                    .add(Items.NETHERITE_PICKAXE)
                    .add(Items.NETHERITE_SHOVEL)
                    .add(Items.NETHERITE_HOE)
                    .add(MMEItems.NETHERITE_MATTOCK)
                    .add(MMEItems.NETHERITE_SCYTHE)
                    .add(MMEItems.NETHERITE_SHEARS)
                    .add(MMEItems.NETHERITE_DAGGER)
                    .add(Items.NETHERITE_SWORD)
                    .add(MMEItems.NETHERITE_WAR_HAMMER)
                    .add(MMEItems.NETHERITE_BATTLE_AXE)
                    .add(Items.NETHERITE_HELMET)
                    .add(Items.NETHERITE_CHESTPLATE)
                    .add(Items.NETHERITE_LEGGINGS)
                    .add(Items.NETHERITE_BOOTS);
            getOrCreateTagBuilder(MMEItemTags.ADAMANTIUM_TOOLS)
                    .add(MMEItems.ADAMANTIUM_AXE)
                    .add(MMEItems.ADAMANTIUM_HATCHET)
                    .add(MMEItems.ADAMANTIUM_PICKAXE)
                    .add(MMEItems.ADAMANTIUM_SHOVEL)
                    .add(MMEItems.ADAMANTIUM_HOE)
                    .add(MMEItems.ADAMANTIUM_MATTOCK)
                    .add(MMEItems.ADAMANTIUM_SCYTHE)
                    .add(MMEItems.ADAMANTIUM_SHEARS)
                    .add(MMEItems.ADAMANTIUM_FISHING_ROD)
                    .add(MMEItems.ADAMANTIUM_DAGGER)
                    .add(MMEItems.ADAMANTIUM_SWORD)
                    .add(MMEItems.ADAMANTIUM_WAR_HAMMER)
                    .add(MMEItems.ADAMANTIUM_BATTLE_AXE)
                    .add(MMEItems.ADAMANTIUM_HELMET)
                    .add(MMEItems.ADAMANTIUM_CHAINMAIL_HELMET)
                    .add(MMEItems.ADAMANTIUM_CHESTPLATE)
                    .add(MMEItems.ADAMANTIUM_CHAINMAIL_CHESTPLATE)
                    .add(MMEItems.ADAMANTIUM_LEGGINGS)
                    .add(MMEItems.ADAMANTIUM_CHAINMAIL_LEGGINGS)
                    .add(MMEItems.ADAMANTIUM_BOOTS)
                    .add(MMEItems.ADAMANTIUM_CHAINMAIL_BOOTS);
            getOrCreateTagBuilder(MMEItemTags.MITHRIL_TOOLS)
                    .add(MMEItems.MITHRIL_AXE)
                    .add(MMEItems.MITHRIL_HATCHET)
                    .add(MMEItems.MITHRIL_PICKAXE)
                    .add(MMEItems.MITHRIL_SHOVEL)
                    .add(MMEItems.MITHRIL_HOE)
                    .add(MMEItems.MITHRIL_MATTOCK)
                    .add(MMEItems.MITHRIL_SCYTHE)
                    .add(MMEItems.MITHRIL_SHEARS)
                    .add(MMEItems.MITHRIL_FISHING_ROD)
                    .add(MMEItems.MITHRIL_DAGGER)
                    .add(MMEItems.MITHRIL_SWORD)
                    .add(MMEItems.MITHRIL_WAR_HAMMER)
                    .add(MMEItems.MITHRIL_BATTLE_AXE)
                    .add(MMEItems.MITHRIL_HELMET)
                    .add(MMEItems.MITHRIL_CHAINMAIL_HELMET)
                    .add(MMEItems.MITHRIL_CHESTPLATE)
                    .add(MMEItems.MITHRIL_CHAINMAIL_CHESTPLATE)
                    .add(MMEItems.MITHRIL_LEGGINGS)
                    .add(MMEItems.MITHRIL_CHAINMAIL_LEGGINGS)
                    .add(MMEItems.MITHRIL_BOOTS)
                    .add(MMEItems.MITHRIL_CHAINMAIL_BOOTS);
            getOrCreateTagBuilder(MMEItemTags.ANCIENT_METAL_TOOLS)
                    .add(MMEItems.ANCIENT_METAL_AXE)
                    .add(MMEItems.ANCIENT_METAL_HATCHET)
                    .add(MMEItems.ANCIENT_METAL_PICKAXE)
                    .add(MMEItems.ANCIENT_METAL_SHOVEL)
                    .add(MMEItems.ANCIENT_METAL_HOE)
                    .add(MMEItems.ANCIENT_METAL_MATTOCK)
                    .add(MMEItems.ANCIENT_METAL_SCYTHE)
                    .add(MMEItems.ANCIENT_METAL_SHEARS)
                    .add(MMEItems.ANCIENT_METAL_FISHING_ROD)
                    .add(MMEItems.ANCIENT_METAL_DAGGER)
                    .add(MMEItems.ANCIENT_METAL_SWORD)
                    .add(MMEItems.ANCIENT_METAL_WAR_HAMMER)
                    .add(MMEItems.ANCIENT_METAL_BATTLE_AXE)
                    .add(MMEItems.ANCIENT_METAL_HELMET)
                    .add(MMEItems.ANCIENT_METAL_CHAINMAIL_HELMET)
                    .add(MMEItems.ANCIENT_METAL_CHESTPLATE)
                    .add(MMEItems.ANCIENT_METAL_CHAINMAIL_CHESTPLATE)
                    .add(MMEItems.ANCIENT_METAL_LEGGINGS)
                    .add(MMEItems.ANCIENT_METAL_CHAINMAIL_LEGGINGS)
                    .add(MMEItems.ANCIENT_METAL_BOOTS)
                    .add(MMEItems.ANCIENT_METAL_CHAINMAIL_BOOTS);
            getOrCreateTagBuilder(MMEItemTags.GOLDEN_TOOLS)
                    .add(Items.GOLDEN_AXE)
                    .add(MMEItems.GOLDEN_HATCHET)
                    .add(Items.GOLDEN_PICKAXE)
                    .add(Items.GOLDEN_SHOVEL)
                    .add(Items.GOLDEN_HOE)
                    .add(MMEItems.GOLDEN_MATTOCK)
                    .add(MMEItems.GOLDEN_SCYTHE)
                    .add(MMEItems.GOLDEN_SHEARS)
                    .add(MMEItems.GOLDEN_FISHING_ROD)
                    .add(MMEItems.GOLDEN_DAGGER)
                    .add(Items.GOLDEN_SWORD)
                    .add(MMEItems.GOLDEN_WAR_HAMMER)
                    .add(MMEItems.GOLDEN_BATTLE_AXE)
                    .add(Items.GOLDEN_HELMET)
                    .add(MMEItems.GOLDEN_CHAINMAIL_HELMET)
                    .add(Items.GOLDEN_CHESTPLATE)
                    .add(MMEItems.GOLDEN_CHAINMAIL_CHESTPLATE)
                    .add(Items.GOLDEN_LEGGINGS)
                    .add(MMEItems.GOLDEN_CHAINMAIL_LEGGINGS)
                    .add(Items.GOLDEN_BOOTS)
                    .add(MMEItems.GOLDEN_CHAINMAIL_BOOTS);
            getOrCreateTagBuilder(MMEItemTags.IRON_TOOLS)
                    .add(Items.IRON_AXE)
                    .add(MMEItems.IRON_HATCHET)
                    .add(Items.IRON_PICKAXE)
                    .add(Items.IRON_SHOVEL)
                    .add(Items.IRON_HOE)
                    .add(MMEItems.IRON_MATTOCK)
                    .add(MMEItems.IRON_SCYTHE)
                    .add(Items.SHEARS)
                    .add(MMEItems.IRON_FISHING_ROD)
                    .add(MMEItems.IRON_DAGGER)
                    .add(Items.IRON_SWORD)
                    .add(MMEItems.IRON_WAR_HAMMER)
                    .add(MMEItems.IRON_BATTLE_AXE)
                    .add(Items.IRON_HELMET)
                    .add(Items.CHAINMAIL_HELMET)
                    .add(Items.IRON_CHESTPLATE)
                    .add(Items.CHAINMAIL_CHESTPLATE)
                    .add(Items.IRON_LEGGINGS)
                    .add(Items.CHAINMAIL_LEGGINGS)
                    .add(Items.IRON_BOOTS)
                    .add(Items.CHAINMAIL_BOOTS);
            getOrCreateTagBuilder(MMEItemTags.RUSTED_IRON_TOOLS)
                    .add(MMEItems.RUSTED_IRON_AXE)
                    .add(MMEItems.RUSTED_IRON_HATCHET)
                    .add(MMEItems.RUSTED_IRON_PICKAXE)
                    .add(MMEItems.RUSTED_IRON_SHOVEL)
                    .add(MMEItems.RUSTED_IRON_HOE)
                    .add(MMEItems.RUSTED_IRON_MATTOCK)
                    .add(MMEItems.RUSTED_IRON_SCYTHE)
                    .add(MMEItems.RUSTED_IRON_SHEARS)
                    .add(MMEItems.RUSTED_IRON_DAGGER)
                    .add(MMEItems.RUSTED_IRON_SWORD)
                    .add(MMEItems.RUSTED_IRON_WAR_HAMMER)
                    .add(MMEItems.RUSTED_IRON_BATTLE_AXE)
                    .add(MMEItems.RUSTED_IRON_HELMET)
                    .add(MMEItems.RUSTED_IRON_CHAINMAIL_HELMET)
                    .add(MMEItems.RUSTED_IRON_CHESTPLATE)
                    .add(MMEItems.RUSTED_IRON_CHAINMAIL_CHESTPLATE)
                    .add(MMEItems.RUSTED_IRON_LEGGINGS)
                    .add(MMEItems.RUSTED_IRON_CHAINMAIL_LEGGINGS)
                    .add(MMEItems.RUSTED_IRON_BOOTS)
                    .add(MMEItems.RUSTED_IRON_CHAINMAIL_BOOTS);
            getOrCreateTagBuilder(MMEItemTags.SILVER_TOOLS)
                    .add(MMEItems.SILVER_AXE)
                    .add(MMEItems.SILVER_HATCHET)
                    .add(MMEItems.SILVER_PICKAXE)
                    .add(MMEItems.SILVER_SHOVEL)
                    .add(MMEItems.SILVER_HOE)
                    .add(MMEItems.SILVER_MATTOCK)
                    .add(MMEItems.SILVER_SCYTHE)
                    .add(MMEItems.SILVER_SHEARS)
                    .add(MMEItems.SILVER_FISHING_ROD)
                    .add(MMEItems.SILVER_DAGGER)
                    .add(MMEItems.SILVER_SWORD)
                    .add(MMEItems.SILVER_WAR_HAMMER)
                    .add(MMEItems.SILVER_BATTLE_AXE)
                    .add(MMEItems.SILVER_HELMET)
                    .add(MMEItems.SILVER_CHAINMAIL_HELMET)
                    .add(MMEItems.SILVER_CHESTPLATE)
                    .add(MMEItems.SILVER_CHAINMAIL_CHESTPLATE)
                    .add(MMEItems.SILVER_LEGGINGS)
                    .add(MMEItems.SILVER_CHAINMAIL_LEGGINGS)
                    .add(MMEItems.SILVER_BOOTS)
                    .add(MMEItems.SILVER_CHAINMAIL_BOOTS);
            getOrCreateTagBuilder(MMEItemTags.COPPER_TOOLS)
                    .add(MMEItems.COPPER_AXE)
                    .add(MMEItems.COPPER_HATCHET)
                    .add(MMEItems.COPPER_PICKAXE)
                    .add(MMEItems.COPPER_SHOVEL)
                    .add(MMEItems.COPPER_HOE)
                    .add(MMEItems.COPPER_MATTOCK)
                    .add(MMEItems.COPPER_SCYTHE)
                    .add(MMEItems.COPPER_SHEARS)
                    .add(MMEItems.COPPER_FISHING_ROD)
                    .add(MMEItems.COPPER_DAGGER)
                    .add(MMEItems.COPPER_SWORD)
                    .add(MMEItems.COPPER_WAR_HAMMER)
                    .add(MMEItems.COPPER_BATTLE_AXE)
                    .add(MMEItems.COPPER_HELMET)
                    .add(MMEItems.COPPER_CHAINMAIL_HELMET)
                    .add(MMEItems.COPPER_CHESTPLATE)
                    .add(MMEItems.COPPER_CHAINMAIL_CHESTPLATE)
                    .add(MMEItems.COPPER_LEGGINGS)
                    .add(MMEItems.COPPER_CHAINMAIL_LEGGINGS)
                    .add(MMEItems.COPPER_BOOTS)
                    .add(MMEItems.COPPER_CHAINMAIL_BOOTS);
            getOrCreateTagBuilder(MMEItemTags.DESTRUCTIBLE_ENDCRYSTAL)
                    .addTag(MMEItemTags.NETHERITE_TOOLS)
                    .addTag(MMEItemTags.ADAMANTIUM_TOOLS);

            getOrCreateTagBuilder(MMEItemTags.ADAMANTIUM_TOOL_MATERIALS)
                    .add(MMEItems.ADAMANTIUM_INGOT)
                    .add(MMEBlocks.ADAMANTIUM_BLOCK.asItem())
                    .add(MMEItems.ADAMANTIUM_NUGGET);
            getOrCreateTagBuilder(MMEItemTags.MITHRIL_TOOL_MATERIALS)
                    .add(MMEItems.MITHRIL_INGOT)
                    .add(MMEBlocks.MITHRIL_BLOCK.asItem())
                    .add(MMEItems.MITHRIL_NUGGET);
            getOrCreateTagBuilder(MMEItemTags.ANCIENT_METAL_TOOL_MATERIALS)
                    .add(MMEItems.ANCIENT_METAL_INGOT)
                    .add(MMEBlocks.ANCIENT_METAL_BLOCK.asItem())
                    .add(MMEItems.ANCIENT_METAL_NUGGET);
            getOrCreateTagBuilder(MMEItemTags.SILVER_TOOL_MATERIALS)
                    .add(MMEItems.SILVER_INGOT)
                    .add(MMEBlocks.SILVER_BLOCK.asItem())
                    .add(MMEItems.SILVER_NUGGET);
            getOrCreateTagBuilder(MMEItemTags.COPPER_TOOL_MATERIALS)
                    .add(Items.COPPER_INGOT)
                    .add(Items.COPPER_BLOCK)
                    .add(MMEItems.COPPER_NUGGET);
            getOrCreateTagBuilder(ItemTags.IRON_TOOL_MATERIALS)
                    .add(Items.IRON_NUGGET)
                    .add(Items.IRON_BLOCK);

            getOrCreateTagBuilder(MMEItemTags.NETHERITE_NOT_ALLOWED_MATERIAL);
            getOrCreateTagBuilder(MMEItemTags.ADAMANTIUM_NOT_ALLOWED_MATERIAL)
                    .forceAddTag(ItemTags.NETHERITE_TOOL_MATERIALS);
            getOrCreateTagBuilder(MMEItemTags.MITHRIL_NOT_ALLOWED_MATERIAL)
                    .addTag(MMEItemTags.ADAMANTIUM_TOOL_MATERIALS);
            getOrCreateTagBuilder(MMEItemTags.ANCIENT_METAL_NOT_ALLOWED_MATERIAL)
                    .addTag(MMEItemTags.MITHRIL_TOOL_MATERIALS)
                    .addTag(MMEItemTags.MITHRIL_NOT_ALLOWED_MATERIAL);
            getOrCreateTagBuilder(MMEItemTags.IRON_NOT_ALLOWED_MATERIAL)
                    .addTag(MMEItemTags.ANCIENT_METAL_TOOL_MATERIALS)
                    .addTag(MMEItemTags.ANCIENT_METAL_NOT_ALLOWED_MATERIAL);
            getOrCreateTagBuilder(MMEItemTags.COPPER_OR_SILVER_NOT_ALLOWED_MATERIAL)
                    .addTag(ItemTags.IRON_TOOL_MATERIALS)
                    .addTag(MMEItemTags.IRON_NOT_ALLOWED_MATERIAL);
            getOrCreateTagBuilder(MMEItemTags.GOLD_NOT_ALLOWED_MATERIAL)
                    .addTag(ItemTags.IRON_TOOL_MATERIALS)
                    .addTag(MMEItemTags.IRON_NOT_ALLOWED_MATERIAL);


            getOrCreateTagBuilder(MMEItemTags.BATTLE_AXE)
                    .add(MMEItems.NETHERITE_BATTLE_AXE)
                    .add(MMEItems.ADAMANTIUM_BATTLE_AXE)
                    .add(MMEItems.MITHRIL_BATTLE_AXE)
                    .add(MMEItems.ANCIENT_METAL_BATTLE_AXE)
                    .add(MMEItems.IRON_BATTLE_AXE)
                    .add(MMEItems.RUSTED_IRON_BATTLE_AXE)
                    .add(MMEItems.GOLDEN_BATTLE_AXE)
                    .add(MMEItems.SILVER_BATTLE_AXE)
                    .add(MMEItems.COPPER_BATTLE_AXE);
            getOrCreateTagBuilder(MMEItemTags.HATCHET)
                    .add(MMEItems.NETHERITE_HATCHET)
                    .add(MMEItems.ADAMANTIUM_HATCHET)
                    .add(MMEItems.MITHRIL_HATCHET)
                    .add(MMEItems.ANCIENT_METAL_HATCHET)
                    .add(MMEItems.IRON_HATCHET)
                    .add(MMEItems.RUSTED_IRON_HATCHET)
                    .add(MMEItems.GOLDEN_HATCHET)
                    .add(MMEItems.SILVER_HATCHET)
                    .add(MMEItems.COPPER_HATCHET)
                    .add(MMEItems.FLINT_HATCHET)
                    .add(MMEItems.OBSIDIAN_HATCHET);
            getOrCreateTagBuilder(MMEItemTags.DAGGER)
                    .add(MMEItems.NETHERITE_DAGGER)
                    .add(MMEItems.ADAMANTIUM_DAGGER)
                    .add(MMEItems.MITHRIL_DAGGER)
                    .add(MMEItems.ANCIENT_METAL_DAGGER)
                    .add(MMEItems.IRON_DAGGER)
                    .add(MMEItems.RUSTED_IRON_DAGGER)
                    .add(MMEItems.GOLDEN_DAGGER)
                    .add(MMEItems.SILVER_DAGGER)
                    .add(MMEItems.COPPER_DAGGER);
            getOrCreateTagBuilder(MMEItemTags.DAGGER_ENCHANTABLE)
                    .addTag(MMEItemTags.DAGGER);
            getOrCreateTagBuilder(MMEItemTags.WAR_HAMMER)
                    .add(MMEItems.NETHERITE_WAR_HAMMER)
                    .add(MMEItems.ADAMANTIUM_WAR_HAMMER)
                    .add(MMEItems.MITHRIL_WAR_HAMMER)
                    .add(MMEItems.ANCIENT_METAL_WAR_HAMMER)
                    .add(MMEItems.IRON_WAR_HAMMER)
                    .add(MMEItems.RUSTED_IRON_WAR_HAMMER)
                    .add(MMEItems.GOLDEN_WAR_HAMMER)
                    .add(MMEItems.SILVER_WAR_HAMMER)
                    .add(MMEItems.COPPER_WAR_HAMMER);
            getOrCreateTagBuilder(MMEItemTags.MATTOCK)
                    .add(MMEItems.NETHERITE_MATTOCK)
                    .add(MMEItems.ADAMANTIUM_MATTOCK)
                    .add(MMEItems.MITHRIL_MATTOCK)
                    .add(MMEItems.ANCIENT_METAL_MATTOCK)
                    .add(MMEItems.IRON_MATTOCK)
                    .add(MMEItems.RUSTED_IRON_MATTOCK)
                    .add(MMEItems.GOLDEN_MATTOCK)
                    .add(MMEItems.SILVER_MATTOCK)
                    .add(MMEItems.COPPER_MATTOCK);
            getOrCreateTagBuilder(MMEItemTags.SCYTHE)
                    .add(MMEItems.NETHERITE_SCYTHE)
                    .add(MMEItems.ADAMANTIUM_SCYTHE)
                    .add(MMEItems.MITHRIL_SCYTHE)
                    .add(MMEItems.ANCIENT_METAL_SCYTHE)
                    .add(MMEItems.IRON_SCYTHE)
                    .add(MMEItems.RUSTED_IRON_SCYTHE)
                    .add(MMEItems.GOLDEN_SCYTHE)
                    .add(MMEItems.SILVER_SCYTHE)
                    .add(MMEItems.COPPER_SCYTHE);
            getOrCreateTagBuilder(MMEItemTags.SHEARS)
                    .add(MMEItems.NETHERITE_SHEARS)
                    .add(MMEItems.ADAMANTIUM_SHEARS)
                    .add(MMEItems.MITHRIL_SHEARS)
                    .add(MMEItems.ANCIENT_METAL_SHEARS)
                    .add(Items.SHEARS)
                    .add(MMEItems.RUSTED_IRON_SHEARS)
                    .add(MMEItems.GOLDEN_SHEARS)
                    .add(MMEItems.SILVER_SHEARS)
                    .add(MMEItems.COPPER_SHEARS);

            getOrCreateTagBuilder(ItemTags.SWORDS)
                    .addTag(MMEItemTags.DAGGER)
                    .add(MMEItems.ADAMANTIUM_SWORD)
                    .add(MMEItems.MITHRIL_SWORD)
                    .add(MMEItems.ANCIENT_METAL_SWORD)
                    .add(MMEItems.RUSTED_IRON_SWORD)
                    .add(MMEItems.SILVER_SWORD)
                    .add(MMEItems.COPPER_SWORD);
            getOrCreateTagBuilder(ItemTags.AXES)
                    .addTag(MMEItemTags.BATTLE_AXE)
                    .addTag(MMEItemTags.HATCHET)
                    .add(MMEItems.ADAMANTIUM_AXE)
                    .add(MMEItems.MITHRIL_AXE)
                    .add(MMEItems.ANCIENT_METAL_AXE)
                    .add(MMEItems.RUSTED_IRON_AXE)
                    .add(MMEItems.SILVER_AXE)
                    .add(MMEItems.COPPER_AXE)
                    .add(MMEItems.FLINT_AXE)
                    .add(MMEItems.OBSIDIAN_AXE);
            getOrCreateTagBuilder(ItemTags.PICKAXES)
                    .addTag(MMEItemTags.WAR_HAMMER)
                    .add(MMEItems.ADAMANTIUM_PICKAXE)
                    .add(MMEItems.MITHRIL_PICKAXE)
                    .add(MMEItems.ANCIENT_METAL_PICKAXE)
                    .add(MMEItems.RUSTED_IRON_PICKAXE)
                    .add(MMEItems.SILVER_PICKAXE)
                    .add(MMEItems.COPPER_PICKAXE);
            getOrCreateTagBuilder(ItemTags.SHOVELS)
                    .addTag(MMEItemTags.MATTOCK)
                    .add(MMEItems.ADAMANTIUM_SHOVEL)
                    .add(MMEItems.MITHRIL_SHOVEL)
                    .add(MMEItems.ANCIENT_METAL_SHOVEL)
                    .add(MMEItems.RUSTED_IRON_SHOVEL)
                    .add(MMEItems.SILVER_SHOVEL)
                    .add(MMEItems.COPPER_SHOVEL);
            getOrCreateTagBuilder(ItemTags.HOES)
                    .add(MMEItems.ADAMANTIUM_HOE)
                    .add(MMEItems.MITHRIL_HOE)
                    .add(MMEItems.ANCIENT_METAL_HOE)
                    .add(MMEItems.RUSTED_IRON_HOE)
                    .add(MMEItems.SILVER_HOE)
                    .add(MMEItems.COPPER_HOE);
            getOrCreateTagBuilder(ItemTags.FISHING_ENCHANTABLE)
                    .add(MMEItems.ADAMANTIUM_FISHING_ROD)
                    .add(MMEItems.MITHRIL_FISHING_ROD)
                    .add(MMEItems.ANCIENT_METAL_FISHING_ROD)
                    .add(MMEItems.IRON_FISHING_ROD)
                    .add(MMEItems.SILVER_FISHING_ROD)
                    .add(MMEItems.COPPER_FISHING_ROD)
                    .add(MMEItems.GOLDEN_FISHING_ROD)
                    .add(MMEItems.OBSIDIAN_FISHING_ROD)
                    .add(MMEItems.FLINT_FISHING_ROD);
            getOrCreateTagBuilder(ItemTags.DURABILITY_ENCHANTABLE)
                    .add(MMEItems.ADAMANTIUM_FISHING_ROD)
                    .add(MMEItems.MITHRIL_FISHING_ROD)
                    .add(MMEItems.ANCIENT_METAL_FISHING_ROD)
                    .add(MMEItems.IRON_FISHING_ROD)
                    .add(MMEItems.SILVER_FISHING_ROD)
                    .add(MMEItems.COPPER_FISHING_ROD)
                    .add(MMEItems.GOLDEN_FISHING_ROD)
                    .add(MMEItems.OBSIDIAN_FISHING_ROD)
                    .add(MMEItems.FLINT_FISHING_ROD);

            getOrCreateTagBuilder(ItemTags.DURABILITY_ENCHANTABLE)
                    .addTag(MMEItemTags.SHEARS);
            getOrCreateTagBuilder(ItemTags.MINING_ENCHANTABLE)
                    .addTag(MMEItemTags.SHEARS);

            getOrCreateTagBuilder(MMEItemTags.STRING)
                    .add(Items.STRING)
                    .add(MMEItems.SINEW);
            getOrCreateTagBuilder(MMEItemTags.HARVESTING_ENCHANTABLE)
                    .forceAddTag(ItemTags.HOES)
                    .addTag(MMEItemTags.MATTOCK)
                    .addTag(MMEItemTags.SCYTHE);
            getOrCreateTagBuilder(MMEItemTags.FERTILITY_ENCHANTABLE)
                    .forceAddTag(ItemTags.HOES)
                    .addTag(MMEItemTags.MATTOCK);
        }
    }
}
