package com.acuteterror233.mite.datagen;

import com.acuteterror233.mite.Mme;
import com.acuteterror233.mite.atinterface.BlockStateModelGeneratorExtension;
import com.acuteterror233.mite.atinterface.ItemModelGeneratorExtension;
import com.acuteterror233.mite.block.AtBlocks;
import com.acuteterror233.mite.item.AtItems;
import com.acuteterror233.mite.item.armor.AtArmorMaterials;
import net.fabricmc.fabric.api.client.datagen.v1.provider.FabricModelProvider;
import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.minecraft.client.data.BlockStateModelGenerator;
import net.minecraft.client.data.ItemModelGenerator;
import net.minecraft.client.data.Models;
import net.minecraft.client.data.TexturedModel;
import net.minecraft.item.Items;
import net.minecraft.util.Identifier;


public class ModelProvider extends FabricModelProvider {
    public ModelProvider(FabricDataOutput output) {
        super(output);
    }

    @Override
    public void generateBlockStateModels(BlockStateModelGenerator blockStateModelGenerator) {
        blockStateModelGenerator.registerSimpleCubeAll(AtBlocks.ADAMANTIUM_ORE);
        ((BlockStateModelGeneratorExtension)blockStateModelGenerator).registerBars(AtBlocks.ADAMANTIUM_BARS);
        blockStateModelGenerator.registerSimpleCubeAll(AtBlocks.ADAMANTIUM_BLOCK);
        ((BlockStateModelGeneratorExtension)blockStateModelGenerator).registerBars(AtBlocks.MITHRIL_BARS);
        blockStateModelGenerator.registerSimpleCubeAll(AtBlocks.MITHRIL_BLOCK);
        ((BlockStateModelGeneratorExtension)blockStateModelGenerator).registerBars(AtBlocks.SILVER_BARS);
        blockStateModelGenerator.registerSimpleCubeAll(AtBlocks.SILVER_BLOCK);
        ((BlockStateModelGeneratorExtension)blockStateModelGenerator).registerBars(AtBlocks.ANCIENT_METAL_BARS);
        blockStateModelGenerator.registerSimpleCubeAll(AtBlocks.ANCIENT_METAL_BLOCK);
        ((BlockStateModelGeneratorExtension)blockStateModelGenerator).registerBars(AtBlocks.GOLDEN_BARS);
        blockStateModelGenerator.registerSimpleCubeAll(AtBlocks.MANTLE);
        blockStateModelGenerator.registerSimpleCubeAll(AtBlocks.MITHRIL_ORE);
        blockStateModelGenerator.registerSimpleCubeAll(AtBlocks.SILVER_ORE);
        ((BlockStateModelGeneratorExtension) blockStateModelGenerator).registerBars(AtBlocks.COPPER_BARS);

        blockStateModelGenerator.registerDoor(AtBlocks.ADAMANTIUM_DOOR);
        blockStateModelGenerator.registerDoor(AtBlocks.GOLDEN_DOOR);
        blockStateModelGenerator.registerDoor(AtBlocks.SILVER_DOOR);
        blockStateModelGenerator.registerDoor(AtBlocks.ANCIENT_METAL_DOOR);
        blockStateModelGenerator.registerDoor(AtBlocks.MITHRIL_DOOR);
        ((BlockStateModelGeneratorExtension) blockStateModelGenerator).registerAnvil(AtBlocks.ADAMANTIUM_ANVIL, AtBlocks.CHIPPED_ADAMANTIUM_ANVIL, AtBlocks.DAMAGED_ADAMANTIUM_ANVIL);
        ((BlockStateModelGeneratorExtension) blockStateModelGenerator).registerAnvil(AtBlocks.MITHRIL_ANVIL, AtBlocks.CHIPPED_MITHRIL_ANVIL, AtBlocks.DAMAGED_MITHRIL_ANVIL);
        ((BlockStateModelGeneratorExtension) blockStateModelGenerator).registerAnvil(AtBlocks.ANCIENT_METAL_ANVIL, AtBlocks.CHIPPED_ANCIENT_METAL_ANVIL, AtBlocks.DAMAGED_ANCIENT_METAL_ANVIL);
        ((BlockStateModelGeneratorExtension) blockStateModelGenerator).registerAnvil(AtBlocks.GOLDEN_ANVIL, AtBlocks.CHIPPED_GOLDEN_ANVIL, AtBlocks.DAMAGED_GOLDEN_ANVIL);
        ((BlockStateModelGeneratorExtension) blockStateModelGenerator).registerAnvil(AtBlocks.SILVER_ANVIL, AtBlocks.CHIPPED_SILVER_ANVIL, AtBlocks.DAMAGED_SILVER_ANVIL);
        ((BlockStateModelGeneratorExtension) blockStateModelGenerator).registerAnvil(AtBlocks.COPPER_ANVIL, AtBlocks.CHIPPED_COPPER_ANVIL, AtBlocks.DAMAGED_COPPER_ANVIL);
        
        blockStateModelGenerator.registerCooker(AtBlocks.CLAY_FURNACE, TexturedModel.ORIENTABLE);
        blockStateModelGenerator.registerCooker(AtBlocks.HARDENED_CLAY_FURNACE, TexturedModel.ORIENTABLE);
        blockStateModelGenerator.registerCooker(AtBlocks.NETHERRACK_FURNACE, TexturedModel.ORIENTABLE);
        blockStateModelGenerator.registerCooker(AtBlocks.OBSIDIAN_FURNACE, TexturedModel.ORIENTABLE);
        blockStateModelGenerator.registerCooker(AtBlocks.SANDSTONE_FURNACE, TexturedModel.ORIENTABLE);

//        blockStateModelGenerator.registerSimpleCubeAll(AtBlocks.MITHRIL_NUL_RUNESTORE);
//        blockStateModelGenerator.registerSimpleCubeAll(AtBlocks.MITHRIL_QUAS_RUNESTORE);
//        blockStateModelGenerator.registerSimpleCubeAll(AtBlocks.MITHRIL_POR_RUNESTORE);
//        blockStateModelGenerator.registerSimpleCubeAll(AtBlocks.MITHRIL_AN_RUNESTORE);
//        blockStateModelGenerator.registerSimpleCubeAll(AtBlocks.MITHRIL_NOX_RUNESTORE);
//        blockStateModelGenerator.registerSimpleCubeAll(AtBlocks.MITHRIL_FLAM_RUNESTORE);
//        blockStateModelGenerator.registerSimpleCubeAll(AtBlocks.MITHRIL_VAS_RUNESTORE);
//        blockStateModelGenerator.registerSimpleCubeAll(AtBlocks.MITHRIL_DES_RUNESTORE);
//        blockStateModelGenerator.registerSimpleCubeAll(AtBlocks.MITHRIL_ORT_RUNESTORE);
//        blockStateModelGenerator.registerSimpleCubeAll(AtBlocks.MITHRIL_TYM_RUNESTORE);
//        blockStateModelGenerator.registerSimpleCubeAll(AtBlocks.MITHRIL_CORP_RUNESTORE);
//        blockStateModelGenerator.registerSimpleCubeAll(AtBlocks.MITHRIL_LOR_RUNESTORE);
//        blockStateModelGenerator.registerSimpleCubeAll(AtBlocks.MITHRIL_MANI_RUNESTORE);
//        blockStateModelGenerator.registerSimpleCubeAll(AtBlocks.MITHRIL_JUX_RUNESTORE);
//        blockStateModelGenerator.registerSimpleCubeAll(AtBlocks.MITHRIL_YLEM_RUNESTORE);
//        blockStateModelGenerator.registerSimpleCubeAll(AtBlocks.MITHRIL_SANCT_RUNESTORE);
//
//        blockStateModelGenerator.registerSimpleCubeAll(AtBlocks.ADAMANTIUM_NUL_RUNESTORE);
//        blockStateModelGenerator.registerSimpleCubeAll(AtBlocks.ADAMANTIUM_QUAS_RUNESTORE);
//        blockStateModelGenerator.registerSimpleCubeAll(AtBlocks.ADAMANTIUM_POR_RUNESTORE);
//        blockStateModelGenerator.registerSimpleCubeAll(AtBlocks.ADAMANTIUM_AN_RUNESTORE);
//        blockStateModelGenerator.registerSimpleCubeAll(AtBlocks.ADAMANTIUM_NOX_RUNESTORE);
//        blockStateModelGenerator.registerSimpleCubeAll(AtBlocks.ADAMANTIUM_FLAM_RUNESTORE);
//        blockStateModelGenerator.registerSimpleCubeAll(AtBlocks.ADAMANTIUM_VAS_RUNESTORE);
//        blockStateModelGenerator.registerSimpleCubeAll(AtBlocks.ADAMANTIUM_DES_RUNESTORE);
//        blockStateModelGenerator.registerSimpleCubeAll(AtBlocks.ADAMANTIUM_ORT_RUNESTORE);
//        blockStateModelGenerator.registerSimpleCubeAll(AtBlocks.ADAMANTIUM_TYM_RUNESTORE);
//        blockStateModelGenerator.registerSimpleCubeAll(AtBlocks.ADAMANTIUM_CORP_RUNESTORE);
//        blockStateModelGenerator.registerSimpleCubeAll(AtBlocks.ADAMANTIUM_LOR_RUNESTORE);
//        blockStateModelGenerator.registerSimpleCubeAll(AtBlocks.ADAMANTIUM_MANI_RUNESTORE);
//        blockStateModelGenerator.registerSimpleCubeAll(AtBlocks.ADAMANTIUM_JUX_RUNESTORE);
//        blockStateModelGenerator.registerSimpleCubeAll(AtBlocks.ADAMANTIUM_YLEM_RUNESTORE);
//        blockStateModelGenerator.registerSimpleCubeAll(AtBlocks.ADAMANTIUM_SANCT_RUNESTORE);
    }

    @Override
    public void generateItemModels(ItemModelGenerator itemModelGenerator) {
        //装备部分
        itemModelGenerator.registerArmor(AtItems.ADAMANTIUM_HELMET, AtArmorMaterials.ADAMANTIUM_ARMOR_MATERIAL_KEY, ItemModelGenerator.HELMET_TRIM_ID_PREFIX, false);
        itemModelGenerator.registerArmor(AtItems.ADAMANTIUM_CHESTPLATE, AtArmorMaterials.ADAMANTIUM_ARMOR_MATERIAL_KEY, ItemModelGenerator.CHESTPLATE_TRIM_ID_PREFIX, false);
        itemModelGenerator.registerArmor(AtItems.ADAMANTIUM_LEGGINGS, AtArmorMaterials.ADAMANTIUM_ARMOR_MATERIAL_KEY, ItemModelGenerator.LEGGINGS_TRIM_ID_PREFIX, false);
        itemModelGenerator.registerArmor(AtItems.ADAMANTIUM_BOOTS, AtArmorMaterials.ADAMANTIUM_ARMOR_MATERIAL_KEY, ItemModelGenerator.BOOTS_TRIM_ID_PREFIX, false);
        itemModelGenerator.registerArmor(AtItems.ADAMANTIUM_CHAINMAIL_HELMET, AtArmorMaterials.ADAMANTIUM_CHAINMAIL_ARMOR_MATERIAL_KEY, ItemModelGenerator.HELMET_TRIM_ID_PREFIX, false);
        itemModelGenerator.registerArmor(AtItems.ADAMANTIUM_CHAINMAIL_CHESTPLATE, AtArmorMaterials.ADAMANTIUM_CHAINMAIL_ARMOR_MATERIAL_KEY, ItemModelGenerator.CHESTPLATE_TRIM_ID_PREFIX, false);
        itemModelGenerator.registerArmor(AtItems.ADAMANTIUM_CHAINMAIL_LEGGINGS, AtArmorMaterials.ADAMANTIUM_CHAINMAIL_ARMOR_MATERIAL_KEY, ItemModelGenerator.LEGGINGS_TRIM_ID_PREFIX, false);
        itemModelGenerator.registerArmor(AtItems.ADAMANTIUM_CHAINMAIL_BOOTS, AtArmorMaterials.ADAMANTIUM_CHAINMAIL_ARMOR_MATERIAL_KEY, ItemModelGenerator.BOOTS_TRIM_ID_PREFIX, false);
        itemModelGenerator.registerArmor(AtItems.ANCIENT_METAL_HELMET, AtArmorMaterials.ANCIENT_METAL_ARMOR_MATERIAL_KEY, ItemModelGenerator.HELMET_TRIM_ID_PREFIX, false);
        itemModelGenerator.registerArmor(AtItems.ANCIENT_METAL_CHESTPLATE, AtArmorMaterials.ANCIENT_METAL_ARMOR_MATERIAL_KEY, ItemModelGenerator.CHESTPLATE_TRIM_ID_PREFIX, false);
        itemModelGenerator.registerArmor(AtItems.ANCIENT_METAL_LEGGINGS, AtArmorMaterials.ANCIENT_METAL_ARMOR_MATERIAL_KEY, ItemModelGenerator.LEGGINGS_TRIM_ID_PREFIX, false);
        itemModelGenerator.registerArmor(AtItems.ANCIENT_METAL_BOOTS, AtArmorMaterials.ANCIENT_METAL_ARMOR_MATERIAL_KEY, ItemModelGenerator.BOOTS_TRIM_ID_PREFIX, false);
        itemModelGenerator.registerArmor(AtItems.ANCIENT_METAL_CHAINMAIL_HELMET, AtArmorMaterials.ANCIENT_METAL_CHAINMAIL_ARMOR_MATERIAL_KEY, ItemModelGenerator.HELMET_TRIM_ID_PREFIX, false);
        itemModelGenerator.registerArmor(AtItems.ANCIENT_METAL_CHAINMAIL_CHESTPLATE, AtArmorMaterials.ANCIENT_METAL_CHAINMAIL_ARMOR_MATERIAL_KEY, ItemModelGenerator.CHESTPLATE_TRIM_ID_PREFIX, false);
        itemModelGenerator.registerArmor(AtItems.ANCIENT_METAL_CHAINMAIL_LEGGINGS, AtArmorMaterials.ANCIENT_METAL_CHAINMAIL_ARMOR_MATERIAL_KEY, ItemModelGenerator.LEGGINGS_TRIM_ID_PREFIX, false);
        itemModelGenerator.registerArmor(AtItems.ANCIENT_METAL_CHAINMAIL_BOOTS, AtArmorMaterials.ANCIENT_METAL_CHAINMAIL_ARMOR_MATERIAL_KEY, ItemModelGenerator.BOOTS_TRIM_ID_PREFIX, false);
        itemModelGenerator.registerArmor(AtItems.COPPER_HELMET, AtArmorMaterials.COPPER_ARMOR_MATERIAL_KEY, ItemModelGenerator.HELMET_TRIM_ID_PREFIX, false);
        itemModelGenerator.registerArmor(AtItems.COPPER_CHESTPLATE, AtArmorMaterials.COPPER_ARMOR_MATERIAL_KEY, ItemModelGenerator.CHESTPLATE_TRIM_ID_PREFIX, false);
        itemModelGenerator.registerArmor(AtItems.COPPER_LEGGINGS, AtArmorMaterials.COPPER_ARMOR_MATERIAL_KEY, ItemModelGenerator.LEGGINGS_TRIM_ID_PREFIX, false);
        itemModelGenerator.registerArmor(AtItems.COPPER_BOOTS, AtArmorMaterials.COPPER_ARMOR_MATERIAL_KEY, ItemModelGenerator.BOOTS_TRIM_ID_PREFIX, false);
        itemModelGenerator.registerArmor(AtItems.COPPER_CHAINMAIL_HELMET, AtArmorMaterials.COPPER_CHAINMAIL_ARMOR_MATERIAL_KEY, ItemModelGenerator.HELMET_TRIM_ID_PREFIX, false);
        itemModelGenerator.registerArmor(AtItems.COPPER_CHAINMAIL_CHESTPLATE, AtArmorMaterials.COPPER_CHAINMAIL_ARMOR_MATERIAL_KEY, ItemModelGenerator.CHESTPLATE_TRIM_ID_PREFIX, false);
        itemModelGenerator.registerArmor(AtItems.COPPER_CHAINMAIL_LEGGINGS, AtArmorMaterials.COPPER_CHAINMAIL_ARMOR_MATERIAL_KEY, ItemModelGenerator.LEGGINGS_TRIM_ID_PREFIX, false);
        itemModelGenerator.registerArmor(AtItems.COPPER_CHAINMAIL_BOOTS, AtArmorMaterials.COPPER_CHAINMAIL_ARMOR_MATERIAL_KEY, ItemModelGenerator.BOOTS_TRIM_ID_PREFIX, false);
        itemModelGenerator.registerArmor(AtItems.MITHRIL_HELMET, AtArmorMaterials.MITHRIL_ARMOR_MATERIAL_KEY, ItemModelGenerator.HELMET_TRIM_ID_PREFIX, false);
        itemModelGenerator.registerArmor(AtItems.MITHRIL_CHESTPLATE, AtArmorMaterials.MITHRIL_ARMOR_MATERIAL_KEY, ItemModelGenerator.CHESTPLATE_TRIM_ID_PREFIX, false);
        itemModelGenerator.registerArmor(AtItems.MITHRIL_LEGGINGS, AtArmorMaterials.MITHRIL_ARMOR_MATERIAL_KEY, ItemModelGenerator.LEGGINGS_TRIM_ID_PREFIX, false);
        itemModelGenerator.registerArmor(AtItems.MITHRIL_BOOTS, AtArmorMaterials.MITHRIL_ARMOR_MATERIAL_KEY, ItemModelGenerator.BOOTS_TRIM_ID_PREFIX, false);
        itemModelGenerator.registerArmor(AtItems.MITHRIL_CHAINMAIL_HELMET, AtArmorMaterials.MITHRIL_CHAINMAIL_ARMOR_MATERIAL_KEY, ItemModelGenerator.HELMET_TRIM_ID_PREFIX, false);
        itemModelGenerator.registerArmor(AtItems.MITHRIL_CHAINMAIL_CHESTPLATE, AtArmorMaterials.MITHRIL_CHAINMAIL_ARMOR_MATERIAL_KEY, ItemModelGenerator.CHESTPLATE_TRIM_ID_PREFIX, false);
        itemModelGenerator.registerArmor(AtItems.MITHRIL_CHAINMAIL_LEGGINGS, AtArmorMaterials.MITHRIL_CHAINMAIL_ARMOR_MATERIAL_KEY, ItemModelGenerator.LEGGINGS_TRIM_ID_PREFIX, false);
        itemModelGenerator.registerArmor(AtItems.MITHRIL_CHAINMAIL_BOOTS, AtArmorMaterials.MITHRIL_CHAINMAIL_ARMOR_MATERIAL_KEY, ItemModelGenerator.BOOTS_TRIM_ID_PREFIX, false);
        itemModelGenerator.registerArmor(AtItems.RUSTED_IRON_HELMET, AtArmorMaterials.RUSTED_IRON_ARMOR_MATERIAL_KEY, ItemModelGenerator.HELMET_TRIM_ID_PREFIX, false);
        itemModelGenerator.registerArmor(AtItems.RUSTED_IRON_CHESTPLATE, AtArmorMaterials.RUSTED_IRON_ARMOR_MATERIAL_KEY, ItemModelGenerator.CHESTPLATE_TRIM_ID_PREFIX, false);
        itemModelGenerator.registerArmor(AtItems.RUSTED_IRON_LEGGINGS, AtArmorMaterials.RUSTED_IRON_ARMOR_MATERIAL_KEY, ItemModelGenerator.LEGGINGS_TRIM_ID_PREFIX, false);
        itemModelGenerator.registerArmor(AtItems.RUSTED_IRON_BOOTS, AtArmorMaterials.RUSTED_IRON_ARMOR_MATERIAL_KEY, ItemModelGenerator.BOOTS_TRIM_ID_PREFIX, false);
        itemModelGenerator.registerArmor(AtItems.RUSTED_IRON_CHAINMAIL_HELMET, AtArmorMaterials.RUSTED_IRON_CHAINMAIL_ARMOR_MATERIAL_KEY, ItemModelGenerator.HELMET_TRIM_ID_PREFIX, false);
        itemModelGenerator.registerArmor(AtItems.RUSTED_IRON_CHAINMAIL_CHESTPLATE, AtArmorMaterials.RUSTED_IRON_CHAINMAIL_ARMOR_MATERIAL_KEY, ItemModelGenerator.CHESTPLATE_TRIM_ID_PREFIX, false);
        itemModelGenerator.registerArmor(AtItems.RUSTED_IRON_CHAINMAIL_LEGGINGS, AtArmorMaterials.RUSTED_IRON_CHAINMAIL_ARMOR_MATERIAL_KEY, ItemModelGenerator.LEGGINGS_TRIM_ID_PREFIX, false);
        itemModelGenerator.registerArmor(AtItems.RUSTED_IRON_CHAINMAIL_BOOTS, AtArmorMaterials.RUSTED_IRON_CHAINMAIL_ARMOR_MATERIAL_KEY, ItemModelGenerator.BOOTS_TRIM_ID_PREFIX, false);
        itemModelGenerator.registerArmor(AtItems.SILVER_HELMET, AtArmorMaterials.SILVER_ARMOR_MATERIAL_KEY, ItemModelGenerator.HELMET_TRIM_ID_PREFIX, false);
        itemModelGenerator.registerArmor(AtItems.SILVER_CHESTPLATE, AtArmorMaterials.SILVER_ARMOR_MATERIAL_KEY, ItemModelGenerator.CHESTPLATE_TRIM_ID_PREFIX, false);
        itemModelGenerator.registerArmor(AtItems.SILVER_LEGGINGS, AtArmorMaterials.SILVER_ARMOR_MATERIAL_KEY, ItemModelGenerator.LEGGINGS_TRIM_ID_PREFIX, false);
        itemModelGenerator.registerArmor(AtItems.SILVER_BOOTS, AtArmorMaterials.SILVER_ARMOR_MATERIAL_KEY, ItemModelGenerator.BOOTS_TRIM_ID_PREFIX, false);
        itemModelGenerator.registerArmor(AtItems.SILVER_CHAINMAIL_HELMET, AtArmorMaterials.SILVER_CHAINMAIL_ARMOR_MATERIAL_KEY, ItemModelGenerator.HELMET_TRIM_ID_PREFIX, false);
        itemModelGenerator.registerArmor(AtItems.SILVER_CHAINMAIL_CHESTPLATE, AtArmorMaterials.SILVER_CHAINMAIL_ARMOR_MATERIAL_KEY, ItemModelGenerator.CHESTPLATE_TRIM_ID_PREFIX, false);
        itemModelGenerator.registerArmor(AtItems.SILVER_CHAINMAIL_LEGGINGS, AtArmorMaterials.SILVER_CHAINMAIL_ARMOR_MATERIAL_KEY, ItemModelGenerator.LEGGINGS_TRIM_ID_PREFIX, false);
        itemModelGenerator.registerArmor(AtItems.SILVER_CHAINMAIL_BOOTS, AtArmorMaterials.SILVER_CHAINMAIL_ARMOR_MATERIAL_KEY, ItemModelGenerator.BOOTS_TRIM_ID_PREFIX, false);
        itemModelGenerator.registerArmor(AtItems.GOLDEN_CHAINMAIL_HELMET, AtArmorMaterials.GOLD_CHAINMAIL_ARMOR_MATERIAL_KEY, ItemModelGenerator.HELMET_TRIM_ID_PREFIX, false);
        itemModelGenerator.registerArmor(AtItems.GOLDEN_CHAINMAIL_CHESTPLATE, AtArmorMaterials.GOLD_CHAINMAIL_ARMOR_MATERIAL_KEY, ItemModelGenerator.CHESTPLATE_TRIM_ID_PREFIX, false);
        itemModelGenerator.registerArmor(AtItems.GOLDEN_CHAINMAIL_LEGGINGS, AtArmorMaterials.GOLD_CHAINMAIL_ARMOR_MATERIAL_KEY, ItemModelGenerator.LEGGINGS_TRIM_ID_PREFIX, false);
        itemModelGenerator.registerArmor(AtItems.GOLDEN_CHAINMAIL_BOOTS, AtArmorMaterials.GOLD_CHAINMAIL_ARMOR_MATERIAL_KEY, ItemModelGenerator.BOOTS_TRIM_ID_PREFIX, false);

        //食物部分
        itemModelGenerator.register(AtItems.BANANA, Models.GENERATED);
        itemModelGenerator.register(AtItems.BLUEBERRIE, Models.GENERATED);
        itemModelGenerator.register(AtItems.CHEESE, Models.GENERATED);
        itemModelGenerator.register(AtItems.CHOCOLATE, Models.GENERATED);
        itemModelGenerator.register(AtItems.DOUGH, Models.GENERATED);
        itemModelGenerator.register(AtItems.LEMON, Models.GENERATED);
        itemModelGenerator.register(AtItems.ONION, Models.GENERATED);
        itemModelGenerator.register(AtItems.ORANGE, Models.GENERATED);
        itemModelGenerator.register(AtItems.WORM_COOKED, Models.GENERATED);
        itemModelGenerator.register(AtItems.WORM_RAW, Models.GENERATED);
        itemModelGenerator.register(AtItems.BEEF_STEW, Models.GENERATED);
        itemModelGenerator.register(AtItems.BOWL_MILK, Models.GENERATED);
        itemModelGenerator.register(AtItems.BOWL_SALAD, Models.GENERATED);
        itemModelGenerator.register(AtItems.BOWL_WATER, Models.GENERATED);
        itemModelGenerator.register(AtItems.FLOUR, Models.GENERATED);
        itemModelGenerator.register(AtItems.CEREAL, Models.GENERATED);
        itemModelGenerator.register(AtItems.CHICKEN_SOUP, Models.GENERATED);
        itemModelGenerator.register(AtItems.CREAM_OF_MUSHROOM_SOUP, Models.GENERATED);
        itemModelGenerator.register(AtItems.CREAM_OF_VEGETABLE_SOUP, Models.GENERATED);
        itemModelGenerator.register(AtItems.ICE_CREAM, Models.GENERATED);
        itemModelGenerator.register(AtItems.MASHED_POTATO, Models.GENERATED);
        itemModelGenerator.register(AtItems.MUSHROOM_STEW, Models.GENERATED);
        itemModelGenerator.register(AtItems.PORRIDGE, Models.GENERATED);
        itemModelGenerator.register(AtItems.PUMPKIN_SOUP, Models.GENERATED);
        itemModelGenerator.register(AtItems.SORBET, Models.GENERATED);
        itemModelGenerator.register(AtItems.VEGETABLE_SOUP, Models.GENERATED);

        //币,锁链和箭
        itemModelGenerator.register(AtItems.ADAMANTIUM_ARROW, Models.GENERATED);
        itemModelGenerator.register(AtItems.ANCIENT_METAL_ARROW, Models.GENERATED);
        itemModelGenerator.register(AtItems.COPPER_ARROW, Models.GENERATED);
        itemModelGenerator.register(AtItems.MITHRIL_ARROW, Models.GENERATED);
        itemModelGenerator.register(AtItems.RUSTED_IRON_ARROW, Models.GENERATED);
        itemModelGenerator.register(AtItems.SILVER_ARROW, Models.GENERATED);
        itemModelGenerator.register(AtItems.FLINT_ARROW, Models.GENERATED);
        itemModelGenerator.register(AtItems.GOLDEN_ARROW, Models.GENERATED);
        itemModelGenerator.register(AtItems.IRON_ARROW, Models.GENERATED);
        itemModelGenerator.register(AtItems.OBSIDIAN_ARROW, Models.GENERATED);
        itemModelGenerator.register(AtItems.ADAMANTIUM_CHAINS, Models.GENERATED);
        itemModelGenerator.register(AtItems.ANCIENT_METAL_CHAINS, Models.GENERATED);
        itemModelGenerator.register(AtItems.COPPER_CHAINS, Models.GENERATED);
        itemModelGenerator.register(AtItems.MITHRIL_CHAINS, Models.GENERATED);
        itemModelGenerator.register(AtItems.RUSTED_IRON_CHAINS, Models.GENERATED);
        itemModelGenerator.register(AtItems.SILVER_CHAINS, Models.GENERATED);
        itemModelGenerator.register(AtItems.GOLDEN_CHAINS, Models.GENERATED);
        itemModelGenerator.register(AtItems.IRON_CHAINS, Models.GENERATED);
        itemModelGenerator.register(AtItems.ADAMANTIUM_COINS, Models.GENERATED);
        itemModelGenerator.register(AtItems.ANCIENT_METAL_COINS, Models.GENERATED);
        itemModelGenerator.register(AtItems.COPPER_COINS, Models.GENERATED);
        itemModelGenerator.register(AtItems.MITHRIL_COINS, Models.GENERATED);
        itemModelGenerator.register(AtItems.GOLDEN_COINS, Models.GENERATED);
        itemModelGenerator.register(AtItems.SILVER_COINS, Models.GENERATED);
        itemModelGenerator.register(AtItems.IRON_COINS, Models.GENERATED);

        //工具,武器
        itemModelGenerator.register(AtItems.ADAMANTIUM_AXE, Models.HANDHELD);
        itemModelGenerator.register(AtItems.ADAMANTIUM_BATTLE_AXE, Models.HANDHELD);
        itemModelGenerator.register(AtItems.ADAMANTIUM_DAGGER, Models.HANDHELD);
        itemModelGenerator.register(AtItems.ADAMANTIUM_HATCHET, Models.HANDHELD);
        itemModelGenerator.register(AtItems.ADAMANTIUM_HOE, Models.HANDHELD);
        itemModelGenerator.register(AtItems.ADAMANTIUM_KNIFE, Models.HANDHELD);
        itemModelGenerator.register(AtItems.ADAMANTIUM_MATTOCK, Models.HANDHELD);
        itemModelGenerator.register(AtItems.ADAMANTIUM_PICKAXE, Models.HANDHELD);
        itemModelGenerator.register(AtItems.ADAMANTIUM_SCYTHE, Models.HANDHELD);
        itemModelGenerator.register(AtItems.ADAMANTIUM_SHEARS, Models.HANDHELD);
        itemModelGenerator.register(AtItems.ADAMANTIUM_SHOVEL, Models.HANDHELD);
        itemModelGenerator.register(AtItems.ADAMANTIUM_SWORD, Models.HANDHELD);
        itemModelGenerator.register(AtItems.ADAMANTIUM_WAR_HAMMER, Models.HANDHELD);
        itemModelGenerator.register(AtItems.ANCIENT_METAL_AXE, Models.HANDHELD);
        itemModelGenerator.register(AtItems.ANCIENT_METAL_BATTLE_AXE, Models.HANDHELD);
        itemModelGenerator.register(AtItems.ANCIENT_METAL_DAGGER, Models.HANDHELD);
        itemModelGenerator.register(AtItems.ANCIENT_METAL_HATCHET, Models.HANDHELD);
        itemModelGenerator.register(AtItems.ANCIENT_METAL_HOE, Models.HANDHELD);
        itemModelGenerator.register(AtItems.ANCIENT_METAL_KNIFE, Models.HANDHELD);
        itemModelGenerator.register(AtItems.ANCIENT_METAL_MATTOCK, Models.HANDHELD);
        itemModelGenerator.register(AtItems.ANCIENT_METAL_PICKAXE, Models.HANDHELD);
        itemModelGenerator.register(AtItems.ANCIENT_METAL_SCYTHE, Models.HANDHELD);
        itemModelGenerator.register(AtItems.ANCIENT_METAL_SHEARS, Models.HANDHELD);
        itemModelGenerator.register(AtItems.ANCIENT_METAL_SHOVEL, Models.HANDHELD);
        itemModelGenerator.register(AtItems.ANCIENT_METAL_SWORD, Models.HANDHELD);
        itemModelGenerator.register(AtItems.ANCIENT_METAL_WAR_HAMMER, Models.HANDHELD);
        itemModelGenerator.register(AtItems.COPPER_AXE, Models.HANDHELD);
        itemModelGenerator.register(AtItems.COPPER_BATTLE_AXE, Models.HANDHELD);
        itemModelGenerator.register(AtItems.COPPER_DAGGER, Models.HANDHELD);
        itemModelGenerator.register(AtItems.COPPER_HATCHET, Models.HANDHELD);
        itemModelGenerator.register(AtItems.COPPER_HOE, Models.HANDHELD);
        itemModelGenerator.register(AtItems.COPPER_KNIFE, Models.HANDHELD);
        itemModelGenerator.register(AtItems.COPPER_MATTOCK, Models.HANDHELD);
        itemModelGenerator.register(AtItems.COPPER_PICKAXE, Models.HANDHELD);
        itemModelGenerator.register(AtItems.COPPER_SCYTHE, Models.HANDHELD);
        itemModelGenerator.register(AtItems.COPPER_SHEARS, Models.HANDHELD);
        itemModelGenerator.register(AtItems.COPPER_SHOVEL, Models.HANDHELD);
        itemModelGenerator.register(AtItems.COPPER_SWORD, Models.HANDHELD);
        itemModelGenerator.register(AtItems.COPPER_WAR_HAMMER, Models.HANDHELD);
        itemModelGenerator.register(AtItems.FLINT_AXE, Models.HANDHELD);
        itemModelGenerator.register(AtItems.FLINT_HATCHET, Models.HANDHELD);
        itemModelGenerator.register(AtItems.FLINT_KNIFE, Models.HANDHELD);
        itemModelGenerator.register(AtItems.FLINT_SHOVEL, Models.HANDHELD);
        itemModelGenerator.register(AtItems.GOLDEN_BATTLE_AXE, Models.HANDHELD);
        itemModelGenerator.register(AtItems.GOLDEN_DAGGER, Models.HANDHELD);
        itemModelGenerator.register(AtItems.GOLDEN_HATCHET, Models.HANDHELD);
        itemModelGenerator.register(AtItems.GOLDEN_KNIFE, Models.HANDHELD);
        itemModelGenerator.register(AtItems.GOLDEN_MATTOCK, Models.HANDHELD);
        itemModelGenerator.register(AtItems.GOLDEN_SCYTHE, Models.HANDHELD);
        itemModelGenerator.register(AtItems.GOLDEN_SHEARS, Models.HANDHELD);
        itemModelGenerator.register(AtItems.GOLDEN_WAR_HAMMER, Models.HANDHELD);
        itemModelGenerator.register(AtItems.IRON_BATTLE_AXE, Models.HANDHELD);
        itemModelGenerator.register(AtItems.IRON_DAGGER, Models.HANDHELD);
        itemModelGenerator.register(AtItems.IRON_HATCHET, Models.HANDHELD);
        itemModelGenerator.register(AtItems.IRON_KNIFE, Models.HANDHELD);
        itemModelGenerator.register(AtItems.IRON_MATTOCK, Models.HANDHELD);
        itemModelGenerator.register(AtItems.IRON_SCYTHE, Models.HANDHELD);
        itemModelGenerator.register(AtItems.IRON_WAR_HAMMER, Models.HANDHELD);
        itemModelGenerator.register(AtItems.MITHRIL_AXE, Models.HANDHELD);
        itemModelGenerator.register(AtItems.MITHRIL_BATTLE_AXE, Models.HANDHELD);
        itemModelGenerator.register(AtItems.MITHRIL_DAGGER, Models.HANDHELD);
        itemModelGenerator.register(AtItems.MITHRIL_HATCHET, Models.HANDHELD);
        itemModelGenerator.register(AtItems.MITHRIL_HOE, Models.HANDHELD);
        itemModelGenerator.register(AtItems.MITHRIL_KNIFE, Models.HANDHELD);
        itemModelGenerator.register(AtItems.MITHRIL_MATTOCK, Models.HANDHELD);
        itemModelGenerator.register(AtItems.MITHRIL_PICKAXE, Models.HANDHELD);
        itemModelGenerator.register(AtItems.MITHRIL_SCYTHE, Models.HANDHELD);
        itemModelGenerator.register(AtItems.MITHRIL_SHEARS, Models.HANDHELD);
        itemModelGenerator.register(AtItems.MITHRIL_SHOVEL, Models.HANDHELD);
        itemModelGenerator.register(AtItems.MITHRIL_SWORD, Models.HANDHELD);
        itemModelGenerator.register(AtItems.MITHRIL_WAR_HAMMER, Models.HANDHELD);
        itemModelGenerator.register(AtItems.OBSIDIAN_AXE, Models.HANDHELD);
        itemModelGenerator.register(AtItems.OBSIDIAN_HATCHET, Models.HANDHELD);
        itemModelGenerator.register(AtItems.OBSIDIAN_KNIFE, Models.HANDHELD);
        itemModelGenerator.register(AtItems.OBSIDIAN_SHOVEL, Models.HANDHELD);
        itemModelGenerator.register(AtItems.RUSTED_IRON_AXE, Models.HANDHELD);
        itemModelGenerator.register(AtItems.RUSTED_IRON_BATTLE_AXE, Models.HANDHELD);
        itemModelGenerator.register(AtItems.RUSTED_IRON_DAGGER, Models.HANDHELD);
        itemModelGenerator.register(AtItems.RUSTED_IRON_HATCHET, Models.HANDHELD);
        itemModelGenerator.register(AtItems.RUSTED_IRON_HOE, Models.HANDHELD);
        itemModelGenerator.register(AtItems.RUSTED_IRON_KNIFE, Models.HANDHELD);
        itemModelGenerator.register(AtItems.RUSTED_IRON_MATTOCK, Models.HANDHELD);
        itemModelGenerator.register(AtItems.RUSTED_IRON_PICKAXE, Models.HANDHELD);
        itemModelGenerator.register(AtItems.RUSTED_IRON_SCYTHE, Models.HANDHELD);
        itemModelGenerator.register(AtItems.RUSTED_IRON_SHEARS, Models.HANDHELD);
        itemModelGenerator.register(AtItems.RUSTED_IRON_SHOVEL, Models.HANDHELD);
        itemModelGenerator.register(AtItems.RUSTED_IRON_SWORD, Models.HANDHELD);
        itemModelGenerator.register(AtItems.RUSTED_IRON_WAR_HAMMER, Models.HANDHELD);
        itemModelGenerator.register(AtItems.SILVER_AXE, Models.HANDHELD);
        itemModelGenerator.register(AtItems.SILVER_BATTLE_AXE, Models.HANDHELD);
        itemModelGenerator.register(AtItems.SILVER_DAGGER, Models.HANDHELD);
        itemModelGenerator.register(AtItems.SILVER_HATCHET, Models.HANDHELD);
        itemModelGenerator.register(AtItems.SILVER_HOE, Models.HANDHELD);
        itemModelGenerator.register(AtItems.SILVER_KNIFE, Models.HANDHELD);
        itemModelGenerator.register(AtItems.SILVER_MATTOCK, Models.HANDHELD);
        itemModelGenerator.register(AtItems.SILVER_PICKAXE, Models.HANDHELD);
        itemModelGenerator.register(AtItems.SILVER_SCYTHE, Models.HANDHELD);
        itemModelGenerator.register(AtItems.SILVER_SHEARS, Models.HANDHELD);
        itemModelGenerator.register(AtItems.SILVER_SHOVEL, Models.HANDHELD);
        itemModelGenerator.register(AtItems.SILVER_SWORD, Models.HANDHELD);
        itemModelGenerator.register(AtItems.SILVER_WAR_HAMMER, Models.HANDHELD);
        itemModelGenerator.register(AtItems.STONE_DAGGER, Models.HANDHELD);
        itemModelGenerator.register(AtItems.WOOD_CLUB, Models.HANDHELD);
        itemModelGenerator.register(AtItems.WOOD_CUDGEL, Models.HANDHELD);

        Identifier AXOLOTL = Identifier.of(Mme.MOD_ID, "item/nobuckets/axolotl");
        Identifier COD = Identifier.of(Mme.MOD_ID, "item/nobuckets/cod");
        Identifier LAVA = Identifier.of(Mme.MOD_ID, "item/nobuckets/lava");
        Identifier MILK = Identifier.of(Mme.MOD_ID, "item/nobuckets/milk");
        Identifier POWDER_SNOW = Identifier.of(Mme.MOD_ID, "item/nobuckets/powder_snow");
        Identifier PUFFERFISH = Identifier.of(Mme.MOD_ID, "item/nobuckets/pufferfish");
        Identifier SALMON = Identifier.of(Mme.MOD_ID, "item/nobuckets/salmon");
        Identifier TADPOLE = Identifier.of(Mme.MOD_ID, "item/nobuckets/tadpole");
        Identifier TROPICAL_FISH = Identifier.of(Mme.MOD_ID, "item/nobuckets/tropical_fish");
        Identifier WATER = Identifier.of(Mme.MOD_ID, "item/nobuckets/water");

        ((ItemModelGeneratorExtension) itemModelGenerator).registerbucket(AtItems.ADAMANTIUM_BUCKET, null, AtItems.ADAMANTIUM_BUCKET);
        ((ItemModelGeneratorExtension) itemModelGenerator).registerbucket(AtItems.WATER_ADAMANTIUM_BUCKET, WATER, AtItems.ADAMANTIUM_BUCKET);
        ((ItemModelGeneratorExtension) itemModelGenerator).registerbucket(AtItems.LAVA_ADAMANTIUM_BUCKET, LAVA, AtItems.ADAMANTIUM_BUCKET);
        ((ItemModelGeneratorExtension) itemModelGenerator).registerbucket(AtItems.POWDER_SNOW_ADAMANTIUM_BUCKET, POWDER_SNOW, AtItems.ADAMANTIUM_BUCKET);
        ((ItemModelGeneratorExtension) itemModelGenerator).registerbucket(AtItems.MILK_ADAMANTIUM_BUCKET, MILK, AtItems.ADAMANTIUM_BUCKET);
        ((ItemModelGeneratorExtension) itemModelGenerator).registerbucket(AtItems.PUFFERFISH_ADAMANTIUM_BUCKET, PUFFERFISH, AtItems.ADAMANTIUM_BUCKET);
        ((ItemModelGeneratorExtension) itemModelGenerator).registerbucket(AtItems.SALMON_ADAMANTIUM_BUCKET, SALMON, AtItems.ADAMANTIUM_BUCKET);
        ((ItemModelGeneratorExtension) itemModelGenerator).registerbucket(AtItems.COD_ADAMANTIUM_BUCKET, COD, AtItems.ADAMANTIUM_BUCKET);
        ((ItemModelGeneratorExtension) itemModelGenerator).registerbucket(AtItems.TROPICAL_FISH_ADAMANTIUM_BUCKET, TROPICAL_FISH, AtItems.ADAMANTIUM_BUCKET);
        ((ItemModelGeneratorExtension) itemModelGenerator).registerbucket(AtItems.AXOLOTL_ADAMANTIUM_BUCKET, AXOLOTL, AtItems.ADAMANTIUM_BUCKET);
        ((ItemModelGeneratorExtension) itemModelGenerator).registerbucket(AtItems.TADPOLE_ADAMANTIUM_BUCKET, TADPOLE, AtItems.ADAMANTIUM_BUCKET);

        ((ItemModelGeneratorExtension) itemModelGenerator).registerbucket(AtItems.ANCIENT_METAL_BUCKET, null, AtItems.ANCIENT_METAL_BUCKET);
        ((ItemModelGeneratorExtension) itemModelGenerator).registerbucket(AtItems.WATER_ANCIENT_METAL_BUCKET, WATER, AtItems.ANCIENT_METAL_BUCKET);
        ((ItemModelGeneratorExtension) itemModelGenerator).registerbucket(AtItems.LAVA_ANCIENT_METAL_BUCKET, LAVA, AtItems.ANCIENT_METAL_BUCKET);
        ((ItemModelGeneratorExtension) itemModelGenerator).registerbucket(AtItems.POWDER_SNOW_ANCIENT_METAL_BUCKET, POWDER_SNOW, AtItems.ANCIENT_METAL_BUCKET);
        ((ItemModelGeneratorExtension) itemModelGenerator).registerbucket(AtItems.MILK_ANCIENT_METAL_BUCKET, MILK, AtItems.ANCIENT_METAL_BUCKET);
        ((ItemModelGeneratorExtension) itemModelGenerator).registerbucket(AtItems.PUFFERFISH_ANCIENT_METAL_BUCKET, PUFFERFISH, AtItems.ANCIENT_METAL_BUCKET);
        ((ItemModelGeneratorExtension) itemModelGenerator).registerbucket(AtItems.SALMON_ANCIENT_METAL_BUCKET, SALMON, AtItems.ANCIENT_METAL_BUCKET);
        ((ItemModelGeneratorExtension) itemModelGenerator).registerbucket(AtItems.COD_ANCIENT_METAL_BUCKET, COD, AtItems.ANCIENT_METAL_BUCKET);
        ((ItemModelGeneratorExtension) itemModelGenerator).registerbucket(AtItems.TROPICAL_FISH_ANCIENT_METAL_BUCKET, TROPICAL_FISH, AtItems.ANCIENT_METAL_BUCKET);
        ((ItemModelGeneratorExtension) itemModelGenerator).registerbucket(AtItems.AXOLOTL_ANCIENT_METAL_BUCKET, AXOLOTL, AtItems.ANCIENT_METAL_BUCKET);
        ((ItemModelGeneratorExtension) itemModelGenerator).registerbucket(AtItems.TADPOLE_ANCIENT_METAL_BUCKET, TADPOLE, AtItems.ANCIENT_METAL_BUCKET);

        ((ItemModelGeneratorExtension) itemModelGenerator).registerbucket(AtItems.COPPER_BUCKET, null, AtItems.COPPER_BUCKET);
        ((ItemModelGeneratorExtension) itemModelGenerator).registerbucket(AtItems.WATER_COPPER_BUCKET, WATER, AtItems.COPPER_BUCKET);
        ((ItemModelGeneratorExtension) itemModelGenerator).registerbucket(AtItems.LAVA_COPPER_BUCKET, LAVA, AtItems.COPPER_BUCKET);
        ((ItemModelGeneratorExtension) itemModelGenerator).registerbucket(AtItems.POWDER_SNOW_COPPER_BUCKET, POWDER_SNOW, AtItems.COPPER_BUCKET);
        ((ItemModelGeneratorExtension) itemModelGenerator).registerbucket(AtItems.MILK_COPPER_BUCKET, MILK, AtItems.COPPER_BUCKET);
        ((ItemModelGeneratorExtension) itemModelGenerator).registerbucket(AtItems.PUFFERFISH_COPPER_BUCKET, PUFFERFISH, AtItems.COPPER_BUCKET);
        ((ItemModelGeneratorExtension) itemModelGenerator).registerbucket(AtItems.SALMON_COPPER_BUCKET, SALMON, AtItems.COPPER_BUCKET);
        ((ItemModelGeneratorExtension) itemModelGenerator).registerbucket(AtItems.COD_COPPER_BUCKET, COD, AtItems.COPPER_BUCKET);
        ((ItemModelGeneratorExtension) itemModelGenerator).registerbucket(AtItems.TROPICAL_FISH_COPPER_BUCKET, TROPICAL_FISH, AtItems.COPPER_BUCKET);
        ((ItemModelGeneratorExtension) itemModelGenerator).registerbucket(AtItems.AXOLOTL_COPPER_BUCKET, AXOLOTL, AtItems.COPPER_BUCKET);
        ((ItemModelGeneratorExtension) itemModelGenerator).registerbucket(AtItems.TADPOLE_COPPER_BUCKET, TADPOLE, AtItems.COPPER_BUCKET);

        ((ItemModelGeneratorExtension) itemModelGenerator).registerbucket(AtItems.GOLD_BUCKET, null, AtItems.GOLD_BUCKET);
        ((ItemModelGeneratorExtension) itemModelGenerator).registerbucket(AtItems.WATER_GOLD_BUCKET, WATER, AtItems.GOLD_BUCKET);
        ((ItemModelGeneratorExtension) itemModelGenerator).registerbucket(AtItems.LAVA_GOLD_BUCKET, LAVA, AtItems.GOLD_BUCKET);
        ((ItemModelGeneratorExtension) itemModelGenerator).registerbucket(AtItems.POWDER_SNOW_GOLD_BUCKET, POWDER_SNOW, AtItems.GOLD_BUCKET);
        ((ItemModelGeneratorExtension) itemModelGenerator).registerbucket(AtItems.MILK_GOLD_BUCKET, MILK, AtItems.GOLD_BUCKET);
        ((ItemModelGeneratorExtension) itemModelGenerator).registerbucket(AtItems.PUFFERFISH_GOLD_BUCKET, PUFFERFISH, AtItems.GOLD_BUCKET);
        ((ItemModelGeneratorExtension) itemModelGenerator).registerbucket(AtItems.SALMON_GOLD_BUCKET, SALMON, AtItems.GOLD_BUCKET);
        ((ItemModelGeneratorExtension) itemModelGenerator).registerbucket(AtItems.COD_GOLD_BUCKET, COD, AtItems.GOLD_BUCKET);
        ((ItemModelGeneratorExtension) itemModelGenerator).registerbucket(AtItems.TROPICAL_FISH_GOLD_BUCKET, TROPICAL_FISH, AtItems.GOLD_BUCKET);
        ((ItemModelGeneratorExtension) itemModelGenerator).registerbucket(AtItems.AXOLOTL_GOLD_BUCKET, AXOLOTL, AtItems.GOLD_BUCKET);
        ((ItemModelGeneratorExtension) itemModelGenerator).registerbucket(AtItems.TADPOLE_GOLD_BUCKET, TADPOLE, AtItems.GOLD_BUCKET);

        ((ItemModelGeneratorExtension) itemModelGenerator).registerbucket(AtItems.MITHRIL_BUCKET, null, AtItems.MITHRIL_BUCKET);
        ((ItemModelGeneratorExtension) itemModelGenerator).registerbucket(AtItems.WATER_MITHRIL_BUCKET, WATER, AtItems.MITHRIL_BUCKET);
        ((ItemModelGeneratorExtension) itemModelGenerator).registerbucket(AtItems.LAVA_MITHRIL_BUCKET, LAVA, AtItems.MITHRIL_BUCKET);
        ((ItemModelGeneratorExtension) itemModelGenerator).registerbucket(AtItems.POWDER_SNOW_MITHRIL_BUCKET, POWDER_SNOW, AtItems.MITHRIL_BUCKET);
        ((ItemModelGeneratorExtension) itemModelGenerator).registerbucket(AtItems.MILK_MITHRIL_BUCKET, MILK, AtItems.MITHRIL_BUCKET);
        ((ItemModelGeneratorExtension) itemModelGenerator).registerbucket(AtItems.PUFFERFISH_MITHRIL_BUCKET, PUFFERFISH, AtItems.MITHRIL_BUCKET);
        ((ItemModelGeneratorExtension) itemModelGenerator).registerbucket(AtItems.SALMON_MITHRIL_BUCKET, SALMON, AtItems.MITHRIL_BUCKET);
        ((ItemModelGeneratorExtension) itemModelGenerator).registerbucket(AtItems.COD_MITHRIL_BUCKET, COD, AtItems.MITHRIL_BUCKET);
        ((ItemModelGeneratorExtension) itemModelGenerator).registerbucket(AtItems.TROPICAL_FISH_MITHRIL_BUCKET, TROPICAL_FISH, AtItems.MITHRIL_BUCKET);
        ((ItemModelGeneratorExtension) itemModelGenerator).registerbucket(AtItems.AXOLOTL_MITHRIL_BUCKET, AXOLOTL, AtItems.MITHRIL_BUCKET);
        ((ItemModelGeneratorExtension) itemModelGenerator).registerbucket(AtItems.TADPOLE_MITHRIL_BUCKET, TADPOLE, AtItems.MITHRIL_BUCKET);

        ((ItemModelGeneratorExtension) itemModelGenerator).registerbucket(AtItems.SILVER_BUCKET, null, AtItems.SILVER_BUCKET);
        ((ItemModelGeneratorExtension) itemModelGenerator).registerbucket(AtItems.WATER_SILVER_BUCKET, WATER, AtItems.SILVER_BUCKET);
        ((ItemModelGeneratorExtension) itemModelGenerator).registerbucket(AtItems.LAVA_SILVER_BUCKET, LAVA, AtItems.SILVER_BUCKET);
        ((ItemModelGeneratorExtension) itemModelGenerator).registerbucket(AtItems.POWDER_SNOW_SILVER_BUCKET, POWDER_SNOW, AtItems.SILVER_BUCKET);
        ((ItemModelGeneratorExtension) itemModelGenerator).registerbucket(AtItems.MILK_SILVER_BUCKET, MILK, AtItems.SILVER_BUCKET);
        ((ItemModelGeneratorExtension) itemModelGenerator).registerbucket(AtItems.PUFFERFISH_SILVER_BUCKET, PUFFERFISH, AtItems.SILVER_BUCKET);
        ((ItemModelGeneratorExtension) itemModelGenerator).registerbucket(AtItems.SALMON_SILVER_BUCKET, SALMON, AtItems.SILVER_BUCKET);
        ((ItemModelGeneratorExtension) itemModelGenerator).registerbucket(AtItems.COD_SILVER_BUCKET, COD, AtItems.SILVER_BUCKET);
        ((ItemModelGeneratorExtension) itemModelGenerator).registerbucket(AtItems.TROPICAL_FISH_SILVER_BUCKET, TROPICAL_FISH, AtItems.SILVER_BUCKET);
        ((ItemModelGeneratorExtension) itemModelGenerator).registerbucket(AtItems.AXOLOTL_SILVER_BUCKET, AXOLOTL, AtItems.SILVER_BUCKET);
        ((ItemModelGeneratorExtension) itemModelGenerator).registerbucket(AtItems.TADPOLE_SILVER_BUCKET, TADPOLE, AtItems.SILVER_BUCKET);

        ((ItemModelGeneratorExtension) itemModelGenerator).registerbucket(AtItems.NETHERITE_BUCKET, null, AtItems.NETHERITE_BUCKET);
        ((ItemModelGeneratorExtension) itemModelGenerator).registerbucket(AtItems.WATER_NETHERITE_BUCKET, WATER, AtItems.NETHERITE_BUCKET);
        ((ItemModelGeneratorExtension) itemModelGenerator).registerbucket(AtItems.LAVA_NETHERITE_BUCKET, LAVA, AtItems.NETHERITE_BUCKET);
        ((ItemModelGeneratorExtension) itemModelGenerator).registerbucket(AtItems.POWDER_SNOW_NETHERITE_BUCKET, POWDER_SNOW, AtItems.NETHERITE_BUCKET);
        ((ItemModelGeneratorExtension) itemModelGenerator).registerbucket(AtItems.MILK_NETHERITE_BUCKET, MILK, AtItems.NETHERITE_BUCKET);
        ((ItemModelGeneratorExtension) itemModelGenerator).registerbucket(AtItems.PUFFERFISH_NETHERITE_BUCKET, PUFFERFISH, AtItems.NETHERITE_BUCKET);
        ((ItemModelGeneratorExtension) itemModelGenerator).registerbucket(AtItems.SALMON_NETHERITE_BUCKET, SALMON, AtItems.NETHERITE_BUCKET);
        ((ItemModelGeneratorExtension) itemModelGenerator).registerbucket(AtItems.COD_NETHERITE_BUCKET, COD, AtItems.NETHERITE_BUCKET);
        ((ItemModelGeneratorExtension) itemModelGenerator).registerbucket(AtItems.TROPICAL_FISH_NETHERITE_BUCKET, TROPICAL_FISH, AtItems.NETHERITE_BUCKET);
        ((ItemModelGeneratorExtension) itemModelGenerator).registerbucket(AtItems.AXOLOTL_NETHERITE_BUCKET, AXOLOTL, AtItems.NETHERITE_BUCKET);
        ((ItemModelGeneratorExtension) itemModelGenerator).registerbucket(AtItems.TADPOLE_NETHERITE_BUCKET, TADPOLE, AtItems.NETHERITE_BUCKET);

        itemModelGenerator.registerBow(AtItems.MITHRIL_BOW);
        itemModelGenerator.registerBow(AtItems.ANCIENT_METAL_BOW);

        Identifier cast = itemModelGenerator.registerSubModel(Items.FISHING_ROD, "_cast", Models.HANDHELD_ROD);
        ((ItemModelGeneratorExtension) itemModelGenerator).registernewFishingRod(AtItems.ADAMANTIUM_FISHING_ROD, cast);
        ((ItemModelGeneratorExtension) itemModelGenerator).registernewFishingRod(AtItems.MITHRIL_FISHING_ROD, cast);
        ((ItemModelGeneratorExtension) itemModelGenerator).registernewFishingRod(AtItems.ANCIENT_METAL_FISHING_ROD, cast);
        ((ItemModelGeneratorExtension) itemModelGenerator).registernewFishingRod(AtItems.SILVER_FISHING_ROD, cast);
        ((ItemModelGeneratorExtension) itemModelGenerator).registernewFishingRod(AtItems.COPPER_FISHING_ROD, cast);
        ((ItemModelGeneratorExtension) itemModelGenerator).registernewFishingRod(AtItems.GOLDEN_FISHING_ROD, cast);
        ((ItemModelGeneratorExtension) itemModelGenerator).registernewFishingRod(AtItems.IRON_FISHING_ROD, cast);
        ((ItemModelGeneratorExtension) itemModelGenerator).registernewFishingRod(AtItems.FLINT_FISHING_ROD, cast);
        ((ItemModelGeneratorExtension) itemModelGenerator).registernewFishingRod(AtItems.OBSIDIAN_FISHING_ROD, cast);

        itemModelGenerator.register(AtItems.RAW_ADAMANTIUM, Models.GENERATED);
        itemModelGenerator.register(AtItems.RAW_MITHRIL, Models.GENERATED);
        itemModelGenerator.register(AtItems.RAW_SILVER, Models.GENERATED);

        itemModelGenerator.register(AtItems.ADAMANTIUM_INGOT, Models.GENERATED);
        itemModelGenerator.register(AtItems.MITHRIL_INGOT, Models.GENERATED);
        itemModelGenerator.register(AtItems.ANCIENT_METAL_INGOT, Models.GENERATED);
        itemModelGenerator.register(AtItems.SILVER_INGOT, Models.GENERATED);

        itemModelGenerator.register(AtItems.ADAMANTIUM_NUGGET, Models.GENERATED);
        itemModelGenerator.register(AtItems.MITHRIL_NUGGET, Models.GENERATED);
        itemModelGenerator.register(AtItems.ANCIENT_METAL_NUGGET, Models.GENERATED);
        itemModelGenerator.register(AtItems.SILVER_NUGGET, Models.GENERATED);
        itemModelGenerator.register(AtItems.COPPER_NUGGET, Models.GENERATED);

        itemModelGenerator.register(AtItems.DIAMOND_SHARD, Models.GENERATED);
        itemModelGenerator.register(AtItems.EMERALD_SHARD, Models.GENERATED);
        itemModelGenerator.register(AtItems.FLINT_SHARD, Models.GENERATED);
        itemModelGenerator.register(AtItems.GLASS_SHARD, Models.GENERATED);
        itemModelGenerator.register(AtItems.OBSIDIAN_SHARD, Models.GENERATED);
        itemModelGenerator.register(AtItems.QUARTZ_SHARD, Models.GENERATED);

        itemModelGenerator.register(AtItems.SINEW, Models.GENERATED);
    }
}
