package com.acuteterror233.mite.datagen;

import com.acuteterror233.mite.At_mite;
import com.acuteterror233.mite.atinterface.BlockStateModelGeneratorExtension;
import com.acuteterror233.mite.atinterface.ItemModelGeneratorExtension;
import com.acuteterror233.mite.block.At_Blocks;
import com.acuteterror233.mite.item.At_Items;
import com.acuteterror233.mite.item.armor.At_ArmorMaterials;
import net.fabricmc.fabric.api.client.datagen.v1.provider.FabricModelProvider;
import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.minecraft.client.data.BlockStateModelGenerator;
import net.minecraft.client.data.ItemModelGenerator;
import net.minecraft.client.data.Models;
import net.minecraft.util.Identifier;


public class ModelProvider extends FabricModelProvider {
    public ModelProvider(FabricDataOutput output) {
        super(output);
    }

    @Override
    public void generateBlockStateModels(BlockStateModelGenerator blockStateModelGenerator) {
        blockStateModelGenerator.registerSimpleCubeAll(At_Blocks.ADAMANTIUM_ORE);
        ((BlockStateModelGeneratorExtension)blockStateModelGenerator).registerBars(At_Blocks.ADAMANTIUM_BARS);
        blockStateModelGenerator.registerSimpleCubeAll(At_Blocks.ADAMANTIUM_BLOCK);
        ((BlockStateModelGeneratorExtension)blockStateModelGenerator).registerBars(At_Blocks.MITHRIL_BARS);
        blockStateModelGenerator.registerSimpleCubeAll(At_Blocks.MITHRIL_BLOCK);
        ((BlockStateModelGeneratorExtension)blockStateModelGenerator).registerBars(At_Blocks.SILVER_BARS);
        blockStateModelGenerator.registerSimpleCubeAll(At_Blocks.SILVER_BLOCK);
        ((BlockStateModelGeneratorExtension)blockStateModelGenerator).registerBars(At_Blocks.ANCIENT_METAL_BARS);
        blockStateModelGenerator.registerSimpleCubeAll(At_Blocks.ANCIENT_METAL_BLOCK);
        ((BlockStateModelGeneratorExtension)blockStateModelGenerator).registerBars(At_Blocks.GOLD_BARS);
        blockStateModelGenerator.registerSimpleCubeAll(At_Blocks.MANTLE);
        blockStateModelGenerator.registerSimpleCubeAll(At_Blocks.MITHRIL_ORE);
        blockStateModelGenerator.registerSimpleCubeAll(At_Blocks.SILVER_ORE);
        ((BlockStateModelGeneratorExtension) blockStateModelGenerator).registerBars(At_Blocks.COPPER_BARS);
    }

    @Override
    public void generateItemModels(ItemModelGenerator itemModelGenerator) {
        //装备部分
        itemModelGenerator.registerArmor(At_Items.ADAMANTIUM_HELMET, At_ArmorMaterials.ADAMANTIUM_ARMOR_MATERIAL_KEY, ItemModelGenerator.HELMET_TRIM_ID_PREFIX,false);
        itemModelGenerator.registerArmor(At_Items.ADAMANTIUM_CHESTPLATE, At_ArmorMaterials.ADAMANTIUM_ARMOR_MATERIAL_KEY, ItemModelGenerator.CHESTPLATE_TRIM_ID_PREFIX,false);
        itemModelGenerator.registerArmor(At_Items.ADAMANTIUM_LEGGINGS, At_ArmorMaterials.ADAMANTIUM_ARMOR_MATERIAL_KEY, ItemModelGenerator.LEGGINGS_TRIM_ID_PREFIX,false);
        itemModelGenerator.registerArmor(At_Items.ADAMANTIUM_BOOTS, At_ArmorMaterials.ADAMANTIUM_ARMOR_MATERIAL_KEY, ItemModelGenerator.BOOTS_TRIM_ID_PREFIX,false);
        itemModelGenerator.registerArmor(At_Items.ADAMANTIUM_CHAINMAIL_HELMET, At_ArmorMaterials.ADAMANTIUM_CHAINMAIL_ARMOR_MATERIAL_KEY, ItemModelGenerator.HELMET_TRIM_ID_PREFIX,false);
        itemModelGenerator.registerArmor(At_Items.ADAMANTIUM_CHAINMAIL_CHESTPLATE, At_ArmorMaterials.ADAMANTIUM_CHAINMAIL_ARMOR_MATERIAL_KEY, ItemModelGenerator.CHESTPLATE_TRIM_ID_PREFIX,false);
        itemModelGenerator.registerArmor(At_Items.ADAMANTIUM_CHAINMAIL_LEGGINGS, At_ArmorMaterials.ADAMANTIUM_CHAINMAIL_ARMOR_MATERIAL_KEY, ItemModelGenerator.LEGGINGS_TRIM_ID_PREFIX,false);
        itemModelGenerator.registerArmor(At_Items.ADAMANTIUM_CHAINMAIL_BOOTS, At_ArmorMaterials.ADAMANTIUM_CHAINMAIL_ARMOR_MATERIAL_KEY, ItemModelGenerator.BOOTS_TRIM_ID_PREFIX,false);
        itemModelGenerator.registerArmor(At_Items.ANCIENT_METAL_HELMET, At_ArmorMaterials.ANCIENT_METAL_ARMOR_MATERIAL_KEY, ItemModelGenerator.HELMET_TRIM_ID_PREFIX,false);
        itemModelGenerator.registerArmor(At_Items.ANCIENT_METAL_CHESTPLATE, At_ArmorMaterials.ANCIENT_METAL_ARMOR_MATERIAL_KEY, ItemModelGenerator.CHESTPLATE_TRIM_ID_PREFIX,false);
        itemModelGenerator.registerArmor(At_Items.ANCIENT_METAL_LEGGINGS, At_ArmorMaterials.ANCIENT_METAL_ARMOR_MATERIAL_KEY, ItemModelGenerator.LEGGINGS_TRIM_ID_PREFIX,false);
        itemModelGenerator.registerArmor(At_Items.ANCIENT_METAL_BOOTS, At_ArmorMaterials.ANCIENT_METAL_ARMOR_MATERIAL_KEY, ItemModelGenerator.BOOTS_TRIM_ID_PREFIX,false);
        itemModelGenerator.registerArmor(At_Items.ANCIENT_METAL_CHAINMAIL_HELMET, At_ArmorMaterials.ANCIENT_METAL_CHAINMAIL_ARMOR_MATERIAL_KEY, ItemModelGenerator.HELMET_TRIM_ID_PREFIX,false);
        itemModelGenerator.registerArmor(At_Items.ANCIENT_METAL_CHAINMAIL_CHESTPLATE, At_ArmorMaterials.ANCIENT_METAL_CHAINMAIL_ARMOR_MATERIAL_KEY, ItemModelGenerator.CHESTPLATE_TRIM_ID_PREFIX,false);
        itemModelGenerator.registerArmor(At_Items.ANCIENT_METAL_CHAINMAIL_LEGGINGS, At_ArmorMaterials.ANCIENT_METAL_CHAINMAIL_ARMOR_MATERIAL_KEY, ItemModelGenerator.LEGGINGS_TRIM_ID_PREFIX,false);
        itemModelGenerator.registerArmor(At_Items.ANCIENT_METAL_CHAINMAIL_BOOTS, At_ArmorMaterials.ANCIENT_METAL_CHAINMAIL_ARMOR_MATERIAL_KEY, ItemModelGenerator.BOOTS_TRIM_ID_PREFIX,false);
        itemModelGenerator.registerArmor(At_Items.COPPER_HELMET, At_ArmorMaterials.COPPER_ARMOR_MATERIAL_KEY, ItemModelGenerator.HELMET_TRIM_ID_PREFIX,false);
        itemModelGenerator.registerArmor(At_Items.COPPER_CHESTPLATE, At_ArmorMaterials.COPPER_ARMOR_MATERIAL_KEY, ItemModelGenerator.CHESTPLATE_TRIM_ID_PREFIX,false);
        itemModelGenerator.registerArmor(At_Items.COPPER_LEGGINGS, At_ArmorMaterials.COPPER_ARMOR_MATERIAL_KEY, ItemModelGenerator.LEGGINGS_TRIM_ID_PREFIX,false);
        itemModelGenerator.registerArmor(At_Items.COPPER_BOOTS, At_ArmorMaterials.COPPER_ARMOR_MATERIAL_KEY, ItemModelGenerator.BOOTS_TRIM_ID_PREFIX,false);
        itemModelGenerator.registerArmor(At_Items.COPPER_CHAINMAIL_HELMET, At_ArmorMaterials.COPPER_CHAINMAIL_ARMOR_MATERIAL_KEY, ItemModelGenerator.HELMET_TRIM_ID_PREFIX,false);
        itemModelGenerator.registerArmor(At_Items.COPPER_CHAINMAIL_CHESTPLATE, At_ArmorMaterials.COPPER_CHAINMAIL_ARMOR_MATERIAL_KEY, ItemModelGenerator.CHESTPLATE_TRIM_ID_PREFIX,false);
        itemModelGenerator.registerArmor(At_Items.COPPER_CHAINMAIL_LEGGINGS, At_ArmorMaterials.COPPER_CHAINMAIL_ARMOR_MATERIAL_KEY, ItemModelGenerator.LEGGINGS_TRIM_ID_PREFIX,false);
        itemModelGenerator.registerArmor(At_Items.COPPER_CHAINMAIL_BOOTS, At_ArmorMaterials.COPPER_CHAINMAIL_ARMOR_MATERIAL_KEY, ItemModelGenerator.BOOTS_TRIM_ID_PREFIX,false);
        itemModelGenerator.registerArmor(At_Items.MITHRIL_HELMET, At_ArmorMaterials.MITHRIL_ARMOR_MATERIAL_KEY, ItemModelGenerator.HELMET_TRIM_ID_PREFIX,false);
        itemModelGenerator.registerArmor(At_Items.MITHRIL_CHESTPLATE, At_ArmorMaterials.MITHRIL_ARMOR_MATERIAL_KEY, ItemModelGenerator.CHESTPLATE_TRIM_ID_PREFIX,false);
        itemModelGenerator.registerArmor(At_Items.MITHRIL_LEGGINGS, At_ArmorMaterials.MITHRIL_ARMOR_MATERIAL_KEY, ItemModelGenerator.LEGGINGS_TRIM_ID_PREFIX,false);
        itemModelGenerator.registerArmor(At_Items.MITHRIL_BOOTS, At_ArmorMaterials.MITHRIL_ARMOR_MATERIAL_KEY, ItemModelGenerator.BOOTS_TRIM_ID_PREFIX,false);
        itemModelGenerator.registerArmor(At_Items.MITHRIL_CHAINMAIL_HELMET, At_ArmorMaterials.MITHRIL_CHAINMAIL_ARMOR_MATERIAL_KEY, ItemModelGenerator.HELMET_TRIM_ID_PREFIX,false);
        itemModelGenerator.registerArmor(At_Items.MITHRIL_CHAINMAIL_CHESTPLATE, At_ArmorMaterials.MITHRIL_CHAINMAIL_ARMOR_MATERIAL_KEY, ItemModelGenerator.CHESTPLATE_TRIM_ID_PREFIX,false);
        itemModelGenerator.registerArmor(At_Items.MITHRIL_CHAINMAIL_LEGGINGS, At_ArmorMaterials.MITHRIL_CHAINMAIL_ARMOR_MATERIAL_KEY, ItemModelGenerator.LEGGINGS_TRIM_ID_PREFIX,false);
        itemModelGenerator.registerArmor(At_Items.MITHRIL_CHAINMAIL_BOOTS, At_ArmorMaterials.MITHRIL_CHAINMAIL_ARMOR_MATERIAL_KEY, ItemModelGenerator.BOOTS_TRIM_ID_PREFIX,false);
        itemModelGenerator.registerArmor(At_Items.RUSTED_IRON_HELMET,  At_ArmorMaterials.RUSTED_IRON_ARMOR_MATERIAL_KEY, ItemModelGenerator.HELMET_TRIM_ID_PREFIX,false);
        itemModelGenerator.registerArmor(At_Items.RUSTED_IRON_CHESTPLATE, At_ArmorMaterials.RUSTED_IRON_ARMOR_MATERIAL_KEY, ItemModelGenerator.CHESTPLATE_TRIM_ID_PREFIX,false);
        itemModelGenerator.registerArmor(At_Items.RUSTED_IRON_LEGGINGS, At_ArmorMaterials.RUSTED_IRON_ARMOR_MATERIAL_KEY, ItemModelGenerator.LEGGINGS_TRIM_ID_PREFIX,false);
        itemModelGenerator.registerArmor(At_Items.RUSTED_IRON_BOOTS, At_ArmorMaterials.RUSTED_IRON_ARMOR_MATERIAL_KEY, ItemModelGenerator.BOOTS_TRIM_ID_PREFIX,false);
        itemModelGenerator.registerArmor(At_Items.RUSTED_IRON_CHAINMAIL_HELMET, At_ArmorMaterials.RUSTED_IRON_CHAINMAIL_ARMOR_MATERIAL_KEY, ItemModelGenerator.HELMET_TRIM_ID_PREFIX,false);
        itemModelGenerator.registerArmor(At_Items.RUSTED_IRON_CHAINMAIL_CHESTPLATE, At_ArmorMaterials.RUSTED_IRON_CHAINMAIL_ARMOR_MATERIAL_KEY, ItemModelGenerator.CHESTPLATE_TRIM_ID_PREFIX,false);
        itemModelGenerator.registerArmor(At_Items.RUSTED_IRON_CHAINMAIL_LEGGINGS, At_ArmorMaterials.RUSTED_IRON_CHAINMAIL_ARMOR_MATERIAL_KEY, ItemModelGenerator.LEGGINGS_TRIM_ID_PREFIX,false);
        itemModelGenerator.registerArmor(At_Items.RUSTED_IRON_CHAINMAIL_BOOTS, At_ArmorMaterials.RUSTED_IRON_CHAINMAIL_ARMOR_MATERIAL_KEY, ItemModelGenerator.BOOTS_TRIM_ID_PREFIX,false);
        itemModelGenerator.registerArmor(At_Items.SILVER_HELMET, At_ArmorMaterials.SILVER_ARMOR_MATERIAL_KEY, ItemModelGenerator.HELMET_TRIM_ID_PREFIX,false);
        itemModelGenerator.registerArmor(At_Items.SILVER_CHESTPLATE, At_ArmorMaterials.SILVER_ARMOR_MATERIAL_KEY, ItemModelGenerator.CHESTPLATE_TRIM_ID_PREFIX,false);
        itemModelGenerator.registerArmor(At_Items.SILVER_LEGGINGS, At_ArmorMaterials.SILVER_ARMOR_MATERIAL_KEY, ItemModelGenerator.LEGGINGS_TRIM_ID_PREFIX,false);
        itemModelGenerator.registerArmor(At_Items.SILVER_BOOTS, At_ArmorMaterials.SILVER_ARMOR_MATERIAL_KEY, ItemModelGenerator.BOOTS_TRIM_ID_PREFIX,false);
        itemModelGenerator.registerArmor(At_Items.SILVER_CHAINMAIL_HELMET, At_ArmorMaterials.SILVER_CHAINMAIL_ARMOR_MATERIAL_KEY, ItemModelGenerator.HELMET_TRIM_ID_PREFIX,false);
        itemModelGenerator.registerArmor(At_Items.SILVER_CHAINMAIL_CHESTPLATE, At_ArmorMaterials.SILVER_CHAINMAIL_ARMOR_MATERIAL_KEY, ItemModelGenerator.CHESTPLATE_TRIM_ID_PREFIX,false);
        itemModelGenerator.registerArmor(At_Items.SILVER_CHAINMAIL_LEGGINGS, At_ArmorMaterials.SILVER_CHAINMAIL_ARMOR_MATERIAL_KEY, ItemModelGenerator.LEGGINGS_TRIM_ID_PREFIX,false);
        itemModelGenerator.registerArmor(At_Items.SILVER_CHAINMAIL_BOOTS, At_ArmorMaterials.SILVER_CHAINMAIL_ARMOR_MATERIAL_KEY, ItemModelGenerator.BOOTS_TRIM_ID_PREFIX,false);

        //食物部分
        itemModelGenerator.register(At_Items.BANANA, Models.GENERATED);
        itemModelGenerator.register(At_Items.BLUEBERRIE, Models.GENERATED);
        itemModelGenerator.register(At_Items.CHEESE, Models.GENERATED);
        itemModelGenerator.register(At_Items.CHOCOLATE, Models.GENERATED);
        itemModelGenerator.register(At_Items.DOUGH, Models.GENERATED);
        itemModelGenerator.register(At_Items.LEMON, Models.GENERATED);
        itemModelGenerator.register(At_Items.ONION, Models.GENERATED);
        itemModelGenerator.register(At_Items.ORANGE, Models.GENERATED);
        itemModelGenerator.register(At_Items.WORM_COOKED, Models.GENERATED);
        itemModelGenerator.register(At_Items.WORM_RAW, Models.GENERATED);
        itemModelGenerator.register(At_Items.BEEF_STEW, Models.GENERATED);
        itemModelGenerator.register(At_Items.BOWL_MILK, Models.GENERATED);
        itemModelGenerator.register(At_Items.BOWL_SALAD, Models.GENERATED);
        itemModelGenerator.register(At_Items.BOWL_WATER, Models.GENERATED);
        itemModelGenerator.register(At_Items.CEREAL, Models.GENERATED);
        itemModelGenerator.register(At_Items.CHICKEN_SOUP, Models.GENERATED);
        itemModelGenerator.register(At_Items.CREAM_OF_MUSHROOM_SOUP, Models.GENERATED);
        itemModelGenerator.register(At_Items.CREAM_OF_VEGETABLE_SOUP, Models.GENERATED);
        itemModelGenerator.register(At_Items.ICE_CREAM, Models.GENERATED);
        itemModelGenerator.register(At_Items.MASHED_POTATO, Models.GENERATED);
        itemModelGenerator.register(At_Items.MUSHROOM_STEW, Models.GENERATED);
        itemModelGenerator.register(At_Items.PORRIDGE, Models.GENERATED);
        itemModelGenerator.register(At_Items.PUMPKIN_SOUP, Models.GENERATED);
        itemModelGenerator.register(At_Items.SORBET, Models.GENERATED);
        itemModelGenerator.register(At_Items.VEGETABLE_SOUP, Models.GENERATED);

        //币,锁链和箭
        itemModelGenerator.register(At_Items.ADAMANTIUM_ARROW, Models.GENERATED);
        itemModelGenerator.register(At_Items.ANCIENT_METAL_ARROW, Models.GENERATED);
        itemModelGenerator.register(At_Items.COPPER_ARROW, Models.GENERATED);
        itemModelGenerator.register(At_Items.MITHRIL_ARROW, Models.GENERATED);
        itemModelGenerator.register(At_Items.RUSTED_IRON_ARROW, Models.GENERATED);
        itemModelGenerator.register(At_Items.SILVER_ARROW, Models.GENERATED);
        itemModelGenerator.register(At_Items.FLINT_ARROW, Models.GENERATED);
        itemModelGenerator.register(At_Items.GOLD_ARROW, Models.GENERATED);
        itemModelGenerator.register(At_Items.IRON_ARROW, Models.GENERATED);
        itemModelGenerator.register(At_Items.OBSIDIAN_ARROW, Models.GENERATED);
        itemModelGenerator.register(At_Items.ADAMANTIUM_CHAINS, Models.GENERATED);
        itemModelGenerator.register(At_Items.ANCIENT_METAL_CHAINS, Models.GENERATED);
        itemModelGenerator.register(At_Items.COPPER_CHAINS, Models.GENERATED);
        itemModelGenerator.register(At_Items.MITHRIL_CHAINS, Models.GENERATED);
        itemModelGenerator.register(At_Items.RUSTED_IRON_CHAINS, Models.GENERATED);
        itemModelGenerator.register(At_Items.SILVER_CHAINS, Models.GENERATED);
        itemModelGenerator.register(At_Items.GOLD_CHAINS, Models.GENERATED);
        itemModelGenerator.register(At_Items.IRON_CHAINS, Models.GENERATED);
        itemModelGenerator.register(At_Items.ADAMANTIUM_COINS, Models.GENERATED);
        itemModelGenerator.register(At_Items.ANCIENT_METAL_COINS, Models.GENERATED);
        itemModelGenerator.register(At_Items.COPPER_COINS, Models.GENERATED);
        itemModelGenerator.register(At_Items.MITHRIL_COINS, Models.GENERATED);
        itemModelGenerator.register(At_Items.GOLD_COINS, Models.GENERATED);
        itemModelGenerator.register(At_Items.SILVER_COINS, Models.GENERATED);
        itemModelGenerator.register(At_Items.IRON_COINS, Models.GENERATED);

        //工具,武器
        itemModelGenerator.register(At_Items.ADAMANTIUM_AXE, Models.HANDHELD);
        itemModelGenerator.register(At_Items.ADAMANTIUM_BATTLE_AXE, Models.HANDHELD);
        itemModelGenerator.register(At_Items.ADAMANTIUM_DAGGER, Models.HANDHELD);
        itemModelGenerator.register(At_Items.ADAMANTIUM_HATCHET, Models.HANDHELD);
        itemModelGenerator.register(At_Items.ADAMANTIUM_HOE, Models.HANDHELD);
        itemModelGenerator.register(At_Items.ADAMANTIUM_KNIFE, Models.HANDHELD);
        itemModelGenerator.register(At_Items.ADAMANTIUM_MATTOCK, Models.HANDHELD);
        itemModelGenerator.register(At_Items.ADAMANTIUM_PICKAXE, Models.HANDHELD);
        itemModelGenerator.register(At_Items.ADAMANTIUM_SCYTHE, Models.HANDHELD);
        itemModelGenerator.register(At_Items.ADAMANTIUM_SHEARS, Models.HANDHELD);
        itemModelGenerator.register(At_Items.ADAMANTIUM_SHOVEL, Models.HANDHELD);
        itemModelGenerator.register(At_Items.ADAMANTIUM_SWORD, Models.HANDHELD);
        itemModelGenerator.register(At_Items.ADAMANTIUM_WAR_HAMMER, Models.HANDHELD);
        itemModelGenerator.register(At_Items.ANCIENT_METAL_AXE, Models.HANDHELD);
        itemModelGenerator.register(At_Items.ANCIENT_METAL_BATTLE_AXE, Models.HANDHELD);
        itemModelGenerator.register(At_Items.ANCIENT_METAL_DAGGER, Models.HANDHELD);
        itemModelGenerator.register(At_Items.ANCIENT_METAL_HATCHET, Models.HANDHELD);
        itemModelGenerator.register(At_Items.ANCIENT_METAL_HOE, Models.HANDHELD);
        itemModelGenerator.register(At_Items.ANCIENT_METAL_KNIFE, Models.HANDHELD);
        itemModelGenerator.register(At_Items.ANCIENT_METAL_MATTOCK, Models.HANDHELD);
        itemModelGenerator.register(At_Items.ANCIENT_METAL_PICKAXE, Models.HANDHELD);
        itemModelGenerator.register(At_Items.ANCIENT_METAL_SCYTHE, Models.HANDHELD);
        itemModelGenerator.register(At_Items.ANCIENT_METAL_SHEARS, Models.HANDHELD);
        itemModelGenerator.register(At_Items.ANCIENT_METAL_SHOVEL, Models.HANDHELD);
        itemModelGenerator.register(At_Items.ANCIENT_METAL_SWORD, Models.HANDHELD);
        itemModelGenerator.register(At_Items.ANCIENT_METAL_WAR_HAMMER, Models.HANDHELD);
        itemModelGenerator.register(At_Items.COPPER_AXE, Models.HANDHELD);
        itemModelGenerator.register(At_Items.COPPER_BATTLE_AXE, Models.HANDHELD);
        itemModelGenerator.register(At_Items.COPPER_DAGGER, Models.HANDHELD);
        itemModelGenerator.register(At_Items.COPPER_HATCHET, Models.HANDHELD);
        itemModelGenerator.register(At_Items.COPPER_HOE, Models.HANDHELD);
        itemModelGenerator.register(At_Items.COPPER_KNIFE, Models.HANDHELD);
        itemModelGenerator.register(At_Items.COPPER_MATTOCK, Models.HANDHELD);
        itemModelGenerator.register(At_Items.COPPER_PICKAXE, Models.HANDHELD);
        itemModelGenerator.register(At_Items.COPPER_SCYTHE, Models.HANDHELD);
        itemModelGenerator.register(At_Items.COPPER_SHEARS, Models.HANDHELD);
        itemModelGenerator.register(At_Items.COPPER_SHOVEL, Models.HANDHELD);
        itemModelGenerator.register(At_Items.COPPER_SWORD, Models.HANDHELD);
        itemModelGenerator.register(At_Items.COPPER_WAR_HAMMER, Models.HANDHELD);
        itemModelGenerator.register(At_Items.FLINT_AXE, Models.HANDHELD);
        itemModelGenerator.register(At_Items.FLINT_HATCHET, Models.HANDHELD);
        itemModelGenerator.register(At_Items.FLINT_KNIFE, Models.HANDHELD);
        itemModelGenerator.register(At_Items.FLINT_SHOVEL, Models.HANDHELD);
        itemModelGenerator.register(At_Items.GOLD_AXE, Models.HANDHELD);
        itemModelGenerator.register(At_Items.GOLD_BATTLE_AXE, Models.HANDHELD);
        itemModelGenerator.register(At_Items.GOLD_DAGGER, Models.HANDHELD);
        itemModelGenerator.register(At_Items.GOLD_HATCHET, Models.HANDHELD);
        itemModelGenerator.register(At_Items.GOLD_HOE, Models.HANDHELD);
        itemModelGenerator.register(At_Items.GOLD_KNIFE, Models.HANDHELD);
        itemModelGenerator.register(At_Items.GOLD_MATTOCK, Models.HANDHELD);
        itemModelGenerator.register(At_Items.GOLD_PICKAXE, Models.HANDHELD);
        itemModelGenerator.register(At_Items.GOLD_SCYTHE, Models.HANDHELD);
        itemModelGenerator.register(At_Items.GOLD_SHEARS, Models.HANDHELD);
        itemModelGenerator.register(At_Items.GOLD_SHOVEL, Models.HANDHELD);
        itemModelGenerator.register(At_Items.GOLD_SWORD, Models.HANDHELD);
        itemModelGenerator.register(At_Items.GOLD_WAR_HAMMER, Models.HANDHELD);
        itemModelGenerator.register(At_Items.IRON_BATTLE_AXE, Models.HANDHELD);
        itemModelGenerator.register(At_Items.IRON_DAGGER, Models.HANDHELD);
        itemModelGenerator.register(At_Items.IRON_HATCHET, Models.HANDHELD);
        itemModelGenerator.register(At_Items.IRON_KNIFE, Models.HANDHELD);
        itemModelGenerator.register(At_Items.IRON_MATTOCK, Models.HANDHELD);
        itemModelGenerator.register(At_Items.IRON_SCYTHE, Models.HANDHELD);
        itemModelGenerator.register(At_Items.IRON_WAR_HAMMER, Models.HANDHELD);
        itemModelGenerator.register(At_Items.MITHRIL_AXE, Models.HANDHELD);
        itemModelGenerator.register(At_Items.MITHRIL_BATTLE_AXE, Models.HANDHELD);
        itemModelGenerator.register(At_Items.MITHRIL_DAGGER, Models.HANDHELD);
        itemModelGenerator.register(At_Items.MITHRIL_HATCHET, Models.HANDHELD);
        itemModelGenerator.register(At_Items.MITHRIL_HOE, Models.HANDHELD);
        itemModelGenerator.register(At_Items.MITHRIL_KNIFE, Models.HANDHELD);
        itemModelGenerator.register(At_Items.MITHRIL_MATTOCK, Models.HANDHELD);
        itemModelGenerator.register(At_Items.MITHRIL_PICKAXE, Models.HANDHELD);
        itemModelGenerator.register(At_Items.MITHRIL_SCYTHE, Models.HANDHELD);
        itemModelGenerator.register(At_Items.MITHRIL_SHEARS, Models.HANDHELD);
        itemModelGenerator.register(At_Items.MITHRIL_SHOVEL, Models.HANDHELD);
        itemModelGenerator.register(At_Items.MITHRIL_SWORD, Models.HANDHELD);
        itemModelGenerator.register(At_Items.MITHRIL_WAR_HAMMER, Models.HANDHELD);
        itemModelGenerator.register(At_Items.OBSIDIAN_AXE, Models.HANDHELD);
        itemModelGenerator.register(At_Items.OBSIDIAN_HATCHET, Models.HANDHELD);
        itemModelGenerator.register(At_Items.OBSIDIAN_KNIFE, Models.HANDHELD);
        itemModelGenerator.register(At_Items.OBSIDIAN_SHOVEL, Models.HANDHELD);
        itemModelGenerator.register(At_Items.RUSTED_IRON_AXE, Models.HANDHELD);
        itemModelGenerator.register(At_Items.RUSTED_IRON_BATTLE_AXE, Models.HANDHELD);
        itemModelGenerator.register(At_Items.RUSTED_IRON_DAGGER, Models.HANDHELD);
        itemModelGenerator.register(At_Items.RUSTED_IRON_HATCHET, Models.HANDHELD);
        itemModelGenerator.register(At_Items.RUSTED_IRON_HOE, Models.HANDHELD);
        itemModelGenerator.register(At_Items.RUSTED_IRON_KNIFE, Models.HANDHELD);
        itemModelGenerator.register(At_Items.RUSTED_IRON_MATTOCK, Models.HANDHELD);
        itemModelGenerator.register(At_Items.RUSTED_IRON_PICKAXE, Models.HANDHELD);
        itemModelGenerator.register(At_Items.RUSTED_IRON_SCYTHE, Models.HANDHELD);
        itemModelGenerator.register(At_Items.RUSTED_IRON_SHEARS, Models.HANDHELD);
        itemModelGenerator.register(At_Items.RUSTED_IRON_SHOVEL, Models.HANDHELD);
        itemModelGenerator.register(At_Items.RUSTED_IRON_SWORD, Models.HANDHELD);
        itemModelGenerator.register(At_Items.RUSTED_IRON_WAR_HAMMER, Models.HANDHELD);
        itemModelGenerator.register(At_Items.SILVER_AXE, Models.HANDHELD);
        itemModelGenerator.register(At_Items.SILVER_BATTLE_AXE, Models.HANDHELD);
        itemModelGenerator.register(At_Items.SILVER_DAGGER, Models.HANDHELD);
        itemModelGenerator.register(At_Items.SILVER_HATCHET, Models.HANDHELD);
        itemModelGenerator.register(At_Items.SILVER_HOE, Models.HANDHELD);
        itemModelGenerator.register(At_Items.SILVER_KNIFE, Models.HANDHELD);
        itemModelGenerator.register(At_Items.SILVER_MATTOCK, Models.HANDHELD);
        itemModelGenerator.register(At_Items.SILVER_PICKAXE, Models.HANDHELD);
        itemModelGenerator.register(At_Items.SILVER_SCYTHE, Models.HANDHELD);
        itemModelGenerator.register(At_Items.SILVER_SHEARS, Models.HANDHELD);
        itemModelGenerator.register(At_Items.SILVER_SHOVEL, Models.HANDHELD);
        itemModelGenerator.register(At_Items.SILVER_SWORD, Models.HANDHELD);
        itemModelGenerator.register(At_Items.SILVER_WAR_HAMMER, Models.HANDHELD);
        itemModelGenerator.register(At_Items.STONE_DAGGER, Models.HANDHELD);
        itemModelGenerator.register(At_Items.WOOD_CLUB, Models.HANDHELD);
        itemModelGenerator.register(At_Items.WOOD_CUDGEL, Models.HANDHELD);

        Identifier axolotl = Identifier.of(At_mite.MOD_ID, "item/nobuckets/axolotl");
        Identifier cod = Identifier.of(At_mite.MOD_ID, "item/nobuckets/cod");
        Identifier lava = Identifier.of(At_mite.MOD_ID, "item/nobuckets/lava");
        Identifier milk = Identifier.of(At_mite.MOD_ID, "item/nobuckets/milk");
        Identifier powder_snow = Identifier.of(At_mite.MOD_ID, "item/nobuckets/powder_snow");
        Identifier pufferfish = Identifier.of(At_mite.MOD_ID, "item/nobuckets/pufferfish");
        Identifier salmon = Identifier.of(At_mite.MOD_ID, "item/nobuckets/salmon");
        Identifier tadpole = Identifier.of(At_mite.MOD_ID, "item/nobuckets/tadpole");
        Identifier tropical_fish = Identifier.of(At_mite.MOD_ID, "item/nobuckets/tropical_fish");
        Identifier water = Identifier.of(At_mite.MOD_ID, "item/nobuckets/water");

        ((ItemModelGeneratorExtension)itemModelGenerator).registerbucket(At_Items.ADAMANTIUM_BUCKET,null,At_Items.ADAMANTIUM_BUCKET);
        ((ItemModelGeneratorExtension)itemModelGenerator).registerbucket(At_Items.WATER_ADAMANTIUM_BUCKET,water,At_Items.ADAMANTIUM_BUCKET);
        ((ItemModelGeneratorExtension)itemModelGenerator).registerbucket(At_Items.LAVA_ADAMANTIUM_BUCKET,lava,At_Items.ADAMANTIUM_BUCKET);
        ((ItemModelGeneratorExtension)itemModelGenerator).registerbucket(At_Items.POWDER_SNOW_ADAMANTIUM_BUCKET,powder_snow,At_Items.ADAMANTIUM_BUCKET);
        ((ItemModelGeneratorExtension)itemModelGenerator).registerbucket(At_Items.MILK_ADAMANTIUM_BUCKET,milk,At_Items.ADAMANTIUM_BUCKET);
        ((ItemModelGeneratorExtension)itemModelGenerator).registerbucket(At_Items.PUFFERFISH_ADAMANTIUM_BUCKET,pufferfish,At_Items.ADAMANTIUM_BUCKET);
        ((ItemModelGeneratorExtension)itemModelGenerator).registerbucket(At_Items.SALMON_ADAMANTIUM_BUCKET,salmon,At_Items.ADAMANTIUM_BUCKET);
        ((ItemModelGeneratorExtension)itemModelGenerator).registerbucket(At_Items.COD_ADAMANTIUM_BUCKET,cod,At_Items.ADAMANTIUM_BUCKET);
        ((ItemModelGeneratorExtension)itemModelGenerator).registerbucket(At_Items.TROPICAL_FISH_ADAMANTIUM_BUCKET,tropical_fish,At_Items.ADAMANTIUM_BUCKET);
        ((ItemModelGeneratorExtension)itemModelGenerator).registerbucket(At_Items.AXOLOTL_ADAMANTIUM_BUCKET,axolotl,At_Items.ADAMANTIUM_BUCKET);
        ((ItemModelGeneratorExtension)itemModelGenerator).registerbucket(At_Items.TADPOLE_ADAMANTIUM_BUCKET,tadpole,At_Items.ADAMANTIUM_BUCKET);
    }
}
