package com.acuteterror233.mite.datagen;

import com.acuteterror233.mite.block.AtBlocks;
import com.acuteterror233.mite.item.AtItems;
import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricLanguageProvider;
import net.minecraft.registry.RegistryWrapper;

import java.util.concurrent.CompletableFuture;

public class Zh_cnLanguageProvider extends FabricLanguageProvider {

    public Zh_cnLanguageProvider(FabricDataOutput dataOutput, CompletableFuture<RegistryWrapper.WrapperLookup> registryLookup) {
        super(dataOutput, "zh_cn", registryLookup);
    }

    @Override
    public void generateTranslations(RegistryWrapper.WrapperLookup wrapperLookup, TranslationBuilder translationBuilder) {
        translationBuilder.add("itemGroup.at_mite.item_group","Minecraft实在是太简单了!");
        translationBuilder.add(AtItems.ADAMANTIUM_HELMET,"艾德曼头盔");
        translationBuilder.add(AtItems.ADAMANTIUM_CHESTPLATE,"艾德曼胸甲");
        translationBuilder.add(AtItems.ADAMANTIUM_LEGGINGS,"艾德曼护腿");
        translationBuilder.add(AtItems.ADAMANTIUM_BOOTS,"艾德曼靴子");
        translationBuilder.add(AtItems.ADAMANTIUM_CHAINMAIL_HELMET,"艾德曼锁链头盔");
        translationBuilder.add(AtItems.ADAMANTIUM_CHAINMAIL_CHESTPLATE,"艾德曼锁链胸甲");
        translationBuilder.add(AtItems.ADAMANTIUM_CHAINMAIL_LEGGINGS,"艾德曼锁链护腿");
        translationBuilder.add(AtItems.ADAMANTIUM_CHAINMAIL_BOOTS,"艾德曼锁链靴子");
        translationBuilder.add(AtItems.ANCIENT_METAL_HELMET,"远古金属头盔");
        translationBuilder.add(AtItems.ANCIENT_METAL_CHESTPLATE,"远古金属胸甲");
        translationBuilder.add(AtItems.ANCIENT_METAL_LEGGINGS,"远古金属护腿");
        translationBuilder.add(AtItems.ANCIENT_METAL_BOOTS,"远古金属靴子");
        translationBuilder.add(AtItems.ANCIENT_METAL_CHAINMAIL_HELMET,"远古金属锁链头盔");
        translationBuilder.add(AtItems.ANCIENT_METAL_CHAINMAIL_CHESTPLATE,"远古金属锁链胸甲");
        translationBuilder.add(AtItems.ANCIENT_METAL_CHAINMAIL_LEGGINGS,"远古金属锁链护腿");
        translationBuilder.add(AtItems.ANCIENT_METAL_CHAINMAIL_BOOTS,"远古金属锁链靴子");
        translationBuilder.add(AtItems.COPPER_HELMET,"铜头盔");
        translationBuilder.add(AtItems.COPPER_CHESTPLATE,"铜胸甲");
        translationBuilder.add(AtItems.COPPER_LEGGINGS,"铜护腿");
        translationBuilder.add(AtItems.COPPER_BOOTS,"铜靴子");
        translationBuilder.add(AtItems.COPPER_CHAINMAIL_HELMET,"铜锁链头盔");
        translationBuilder.add(AtItems.COPPER_CHAINMAIL_CHESTPLATE,"铜锁链胸甲");
        translationBuilder.add(AtItems.COPPER_CHAINMAIL_LEGGINGS,"铜锁链护腿");
        translationBuilder.add(AtItems.COPPER_CHAINMAIL_BOOTS,"铜锁链靴子");
        translationBuilder.add(AtItems.MITHRIL_HELMET,"秘银头盔");
        translationBuilder.add(AtItems.MITHRIL_CHESTPLATE,"秘银胸甲");
        translationBuilder.add(AtItems.MITHRIL_LEGGINGS,"秘银护腿");
        translationBuilder.add(AtItems.MITHRIL_BOOTS,"秘银靴子");
        translationBuilder.add(AtItems.MITHRIL_CHAINMAIL_HELMET,"秘银锁链头盔");
        translationBuilder.add(AtItems.MITHRIL_CHAINMAIL_CHESTPLATE,"秘银锁链胸甲");
        translationBuilder.add(AtItems.MITHRIL_CHAINMAIL_LEGGINGS,"秘银锁链护腿");
        translationBuilder.add(AtItems.MITHRIL_CHAINMAIL_BOOTS,"秘银锁链靴子");
        translationBuilder.add(AtItems.RUSTED_IRON_HELMET, "锈铁头盔");
        translationBuilder.add(AtItems.RUSTED_IRON_CHESTPLATE, "锈铁胸甲");
        translationBuilder.add(AtItems.RUSTED_IRON_LEGGINGS, "锈铁护腿");
        translationBuilder.add(AtItems.RUSTED_IRON_BOOTS, "锈铁靴子");
        translationBuilder.add(AtItems.RUSTED_IRON_CHAINMAIL_HELMET, "锈铁锁链头盔");
        translationBuilder.add(AtItems.RUSTED_IRON_CHAINMAIL_CHESTPLATE, "锈铁锁链胸甲");
        translationBuilder.add(AtItems.RUSTED_IRON_CHAINMAIL_LEGGINGS, "锈铁锁链护腿");
        translationBuilder.add(AtItems.RUSTED_IRON_CHAINMAIL_BOOTS, "锈铁锁链靴子");
        translationBuilder.add(AtItems.SILVER_HELMET, "银头盔");
        translationBuilder.add(AtItems.SILVER_CHESTPLATE, "银胸甲");
        translationBuilder.add(AtItems.SILVER_LEGGINGS, "银护腿");
        translationBuilder.add(AtItems.SILVER_BOOTS, "银靴子");
        translationBuilder.add(AtItems.SILVER_CHAINMAIL_HELMET, "银锁链头盔");
        translationBuilder.add(AtItems.SILVER_CHAINMAIL_CHESTPLATE, "银锁链胸甲");
        translationBuilder.add(AtItems.SILVER_CHAINMAIL_LEGGINGS, "银锁链护腿");
        translationBuilder.add(AtItems.SILVER_CHAINMAIL_BOOTS, "银锁链靴子");

        translationBuilder.add(AtItems.BANANA, "香蕉");
        translationBuilder.add(AtItems.BLUEBERRIE, "蓝莓");
        translationBuilder.add(AtItems.CHEESE, "奶酪");
        translationBuilder.add(AtItems.CHOCOLATE, "巧克力");
        translationBuilder.add(AtItems.DOUGH, "面团");
        translationBuilder.add(AtItems.ONION, "洋葱");
        translationBuilder.add(AtItems.LEMON, "柠檬");
        translationBuilder.add(AtItems.ORANGE, "橘子");
        translationBuilder.add(AtItems.WORM_COOKED, "烤熟的虫子");
        translationBuilder.add(AtItems.WORM_RAW, "生的虫子");
        translationBuilder.add(AtItems.BEEF_STEW, "炖牛肉");
        translationBuilder.add(AtItems.BOWL_MILK, "一碗牛奶");
        translationBuilder.add(AtItems.BOWL_SALAD, "一碗沙拉");
        translationBuilder.add(AtItems.BOWL_WATER, "一碗水");
        translationBuilder.add(AtItems.CEREAL, "麦片");
        translationBuilder.add(AtItems.CHICKEN_SOUP, "鸡汤");
        translationBuilder.add(AtItems.CREAM_OF_MUSHROOM_SOUP, "奶油蘑菇汤");
        translationBuilder.add(AtItems.CREAM_OF_VEGETABLE_SOUP, "奶油蔬菜汤");
        translationBuilder.add(AtItems.ICE_CREAM, "冰淇淋");
        translationBuilder.add(AtItems.MASHED_POTATO, "土豆泥");
        translationBuilder.add(AtItems.MUSHROOM_STEW, "蘑菇炖汤");
        translationBuilder.add(AtItems.PORRIDGE, "粥");
        translationBuilder.add(AtItems.PUMPKIN_SOUP, "南瓜汤");
        translationBuilder.add(AtItems.SORBET, "雪糕");
        translationBuilder.add(AtItems.VEGETABLE_SOUP, "蔬菜汤");

        translationBuilder.add(AtItems.ADAMANTIUM_ARROW, "艾德曼箭");
        translationBuilder.add(AtItems.ANCIENT_METAL_ARROW, "远古金属箭");
        translationBuilder.add(AtItems.COPPER_ARROW, "铜箭");
        translationBuilder.add(AtItems.MITHRIL_ARROW, "秘银箭");
        translationBuilder.add(AtItems.RUSTED_IRON_ARROW, "锈铁箭");
        translationBuilder.add(AtItems.SILVER_ARROW, "银箭");
        translationBuilder.add(AtItems.FLINT_ARROW, "燧石箭");
        translationBuilder.add(AtItems.GOLD_ARROW, "金箭");
        translationBuilder.add(AtItems.IRON_ARROW, "铁箭");
        translationBuilder.add(AtItems.OBSIDIAN_ARROW, "黑曜石箭");
        translationBuilder.add(AtItems.ADAMANTIUM_CHAINS, "艾德曼锁链");
        translationBuilder.add(AtItems.ANCIENT_METAL_CHAINS, "远古金属链");
        translationBuilder.add(AtItems.COPPER_CHAINS, "铜链");
        translationBuilder.add(AtItems.MITHRIL_CHAINS, "秘银链");
        translationBuilder.add(AtItems.RUSTED_IRON_CHAINS, "锈铁链");
        translationBuilder.add(AtItems.SILVER_CHAINS, "银链");
        translationBuilder.add(AtItems.GOLD_CHAINS, "钢链");
        translationBuilder.add(AtItems.IRON_CHAINS, "铁链");
        translationBuilder.add(AtItems.ADAMANTIUM_COINS, "艾德曼币");
        translationBuilder.add(AtItems.ANCIENT_METAL_COINS, "远古金属币");
        translationBuilder.add(AtItems.COPPER_COINS, "铜币");
        translationBuilder.add(AtItems.MITHRIL_COINS, "秘银币");
        translationBuilder.add(AtItems.GOLD_COINS, "锈铁币");
        translationBuilder.add(AtItems.SILVER_COINS, "银币");
        translationBuilder.add(AtItems.IRON_COINS, "铁币");

        translationBuilder.add(AtItems.ADAMANTIUM_AXE, "艾德曼斧");
        translationBuilder.add(AtItems.ADAMANTIUM_BATTLE_AXE, "艾德曼战斧");
        translationBuilder.add(AtItems.ADAMANTIUM_DAGGER, "艾德曼匕首");
        translationBuilder.add(AtItems.ADAMANTIUM_HATCHET, "艾德曼短斧");
        translationBuilder.add(AtItems.ADAMANTIUM_HOE, "艾德曼锄头");
        translationBuilder.add(AtItems.ADAMANTIUM_KNIFE, "艾德曼小刀");
        translationBuilder.add(AtItems.ADAMANTIUM_MATTOCK, "艾德曼鹤嘴锄");
        translationBuilder.add(AtItems.ADAMANTIUM_PICKAXE, "艾德曼镐");
        translationBuilder.add(AtItems.ADAMANTIUM_SCYTHE, "艾德曼镰刀");
        translationBuilder.add(AtItems.ADAMANTIUM_SHEARS, "艾德曼剪刀");
        translationBuilder.add(AtItems.ADAMANTIUM_SHOVEL, "艾德曼铲子");
        translationBuilder.add(AtItems.ADAMANTIUM_SWORD, "艾德曼剑");
        translationBuilder.add(AtItems.ADAMANTIUM_WAR_HAMMER, "艾德曼战锤");
        translationBuilder.add(AtItems.ANCIENT_METAL_AXE, "远古金属斧");
        translationBuilder.add(AtItems.ANCIENT_METAL_BATTLE_AXE, "远古金属战斧");
        translationBuilder.add(AtItems.ANCIENT_METAL_DAGGER, "远古金属匕首");
        translationBuilder.add(AtItems.ANCIENT_METAL_HATCHET, "远古金属短斧");
        translationBuilder.add(AtItems.ANCIENT_METAL_HOE, "远古金属锄头");
        translationBuilder.add(AtItems.ANCIENT_METAL_KNIFE, "远古金属小刀");
        translationBuilder.add(AtItems.ANCIENT_METAL_MATTOCK, "远古金属鹤嘴锄");
        translationBuilder.add(AtItems.ANCIENT_METAL_PICKAXE, "远古金属镐");
        translationBuilder.add(AtItems.ANCIENT_METAL_SCYTHE, "远古金属镰刀");
        translationBuilder.add(AtItems.ANCIENT_METAL_SHEARS, "远古金属剪刀");
        translationBuilder.add(AtItems.ANCIENT_METAL_SHOVEL, "远古金属铲子");
        translationBuilder.add(AtItems.ANCIENT_METAL_SWORD, "远古金属剑");
        translationBuilder.add(AtItems.ANCIENT_METAL_WAR_HAMMER, "远古金属战锤");
        translationBuilder.add(AtItems.COPPER_AXE, "铜斧");
        translationBuilder.add(AtItems.COPPER_BATTLE_AXE, "铜战斧");
        translationBuilder.add(AtItems.COPPER_DAGGER, "铜匕首");
        translationBuilder.add(AtItems.COPPER_HATCHET, "铜短斧");
        translationBuilder.add(AtItems.COPPER_HOE, "铜锄头");
        translationBuilder.add(AtItems.COPPER_KNIFE, "铜小刀");
        translationBuilder.add(AtItems.COPPER_MATTOCK, "铜鹤嘴锄");
        translationBuilder.add(AtItems.COPPER_PICKAXE, "铜镐");
        translationBuilder.add(AtItems.COPPER_SCYTHE, "铜镰刀");
        translationBuilder.add(AtItems.COPPER_SHEARS, "铜剪刀");
        translationBuilder.add(AtItems.COPPER_SHOVEL, "铜铲子");
        translationBuilder.add(AtItems.COPPER_SWORD, "铜剑");
        translationBuilder.add(AtItems.COPPER_WAR_HAMMER, "铜战锤");
        translationBuilder.add(AtItems.FLINT_AXE, "燧石斧");
        translationBuilder.add(AtItems.FLINT_HATCHET, "燧石短斧");
        translationBuilder.add(AtItems.FLINT_KNIFE, "燧石小刀");
        translationBuilder.add(AtItems.FLINT_SHOVEL, "燧石铲子");
        translationBuilder.add(AtItems.GOLD_AXE, "金斧");
        translationBuilder.add(AtItems.GOLD_BATTLE_AXE, "金战斧");
        translationBuilder.add(AtItems.GOLD_DAGGER, "金匕首");
        translationBuilder.add(AtItems.GOLD_HATCHET, "金短斧");
        translationBuilder.add(AtItems.GOLD_HOE, "金锄头");
        translationBuilder.add(AtItems.GOLD_KNIFE, "金小刀");
        translationBuilder.add(AtItems.GOLD_MATTOCK, "金鹤嘴锄");
        translationBuilder.add(AtItems.GOLD_PICKAXE, "金镐");
        translationBuilder.add(AtItems.GOLD_SCYTHE, "金镰刀");
        translationBuilder.add(AtItems.GOLD_SHEARS, "金剪刀");
        translationBuilder.add(AtItems.GOLD_SHOVEL, "金铲子");
        translationBuilder.add(AtItems.GOLD_SWORD, "金剑");
        translationBuilder.add(AtItems.GOLD_WAR_HAMMER, "金战锤");
        translationBuilder.add(AtItems.IRON_BATTLE_AXE, "铁战斧");
        translationBuilder.add(AtItems.IRON_DAGGER, "铁匕首");
        translationBuilder.add(AtItems.IRON_HATCHET, "铁短斧");
        translationBuilder.add(AtItems.IRON_KNIFE, "铁小刀");
        translationBuilder.add(AtItems.IRON_MATTOCK, "铁鹤嘴锄");
        translationBuilder.add(AtItems.IRON_SCYTHE, "铁镰刀");
        translationBuilder.add(AtItems.IRON_WAR_HAMMER, "铁战锤");
        translationBuilder.add(AtItems.MITHRIL_AXE, "秘银斧");
        translationBuilder.add(AtItems.MITHRIL_BATTLE_AXE, "秘银战斧");
        translationBuilder.add(AtItems.MITHRIL_DAGGER, "秘银匕首");
        translationBuilder.add(AtItems.MITHRIL_HATCHET, "秘银短斧");
        translationBuilder.add(AtItems.MITHRIL_HOE, "秘银锄头");
        translationBuilder.add(AtItems.MITHRIL_KNIFE, "秘银小刀");
        translationBuilder.add(AtItems.MITHRIL_MATTOCK, "秘银鹤嘴锄");
        translationBuilder.add(AtItems.MITHRIL_PICKAXE, "秘银镐");
        translationBuilder.add(AtItems.MITHRIL_SCYTHE, "秘银镰刀");
        translationBuilder.add(AtItems.MITHRIL_SHEARS, "秘银剪刀");
        translationBuilder.add(AtItems.MITHRIL_SHOVEL, "秘银铲子");
        translationBuilder.add(AtItems.MITHRIL_SWORD, "秘银剑");
        translationBuilder.add(AtItems.MITHRIL_WAR_HAMMER, "秘银战锤");
        translationBuilder.add(AtItems.OBSIDIAN_AXE, "黑曜石斧");
        translationBuilder.add(AtItems.OBSIDIAN_HATCHET, "黑曜石短斧");
        translationBuilder.add(AtItems.OBSIDIAN_KNIFE, "黑曜石小刀");
        translationBuilder.add(AtItems.OBSIDIAN_SHOVEL, "黑曜石铲子");
        translationBuilder.add(AtItems.RUSTED_IRON_AXE, "锈铁斧");
        translationBuilder.add(AtItems.RUSTED_IRON_BATTLE_AXE, "锈铁战斧");
        translationBuilder.add(AtItems.RUSTED_IRON_DAGGER, "锈铁匕首");
        translationBuilder.add(AtItems.RUSTED_IRON_HATCHET, "锈铁短斧");
        translationBuilder.add(AtItems.RUSTED_IRON_HOE, "锈铁锄头");
        translationBuilder.add(AtItems.RUSTED_IRON_KNIFE, "锈铁小刀");
        translationBuilder.add(AtItems.RUSTED_IRON_MATTOCK, "锈铁鹤嘴锄");
        translationBuilder.add(AtItems.RUSTED_IRON_PICKAXE, "锈铁镐");
        translationBuilder.add(AtItems.RUSTED_IRON_SCYTHE, "锈铁镰刀");
        translationBuilder.add(AtItems.RUSTED_IRON_SHEARS, "锈铁剪刀");
        translationBuilder.add(AtItems.RUSTED_IRON_SHOVEL, "锈铁铲子");
        translationBuilder.add(AtItems.RUSTED_IRON_SWORD, "锈铁剑");
        translationBuilder.add(AtItems.RUSTED_IRON_WAR_HAMMER, "锈铁战锤");
        translationBuilder.add(AtItems.SILVER_AXE, "银斧");
        translationBuilder.add(AtItems.SILVER_BATTLE_AXE, "银战斧");
        translationBuilder.add(AtItems.SILVER_DAGGER, "银匕首");
        translationBuilder.add(AtItems.SILVER_HATCHET, "银短斧");
        translationBuilder.add(AtItems.SILVER_HOE, "银锄头");
        translationBuilder.add(AtItems.SILVER_KNIFE, "银小刀");
        translationBuilder.add(AtItems.SILVER_MATTOCK, "银鹤嘴锄");
        translationBuilder.add(AtItems.SILVER_PICKAXE, "银镐");
        translationBuilder.add(AtItems.SILVER_SCYTHE, "银镰刀");
        translationBuilder.add(AtItems.SILVER_SHEARS, "银剪刀");
        translationBuilder.add(AtItems.SILVER_SHOVEL, "银铲子");
        translationBuilder.add(AtItems.SILVER_SWORD, "银剑");
        translationBuilder.add(AtItems.SILVER_WAR_HAMMER, "银战锤");
        translationBuilder.add(AtItems.STONE_DAGGER, "石匕首");
        translationBuilder.add(AtItems.WOOD_CLUB, "木棒");
        translationBuilder.add(AtItems.WOOD_CUDGEL,"小木棒");

        translationBuilder.add(AtBlocks.ADAMANTIUM_ORE, "艾德曼矿");
        translationBuilder.add(AtBlocks.ADAMANTIUM_BARS, "艾德曼栏杆");
        translationBuilder.add(AtBlocks.ADAMANTIUM_BLOCK, "艾德曼块");
        translationBuilder.add(AtBlocks.ANCIENT_METAL_BARS, "古代金属栏杆");
        translationBuilder.add(AtBlocks.ANCIENT_METAL_BLOCK, "古代金属块");
        translationBuilder.add(AtBlocks.GOLD_BARS, "金栏杆");
        translationBuilder.add(AtBlocks.MITHRIL_BARS, "秘银栏杆");
        translationBuilder.add(AtBlocks.MITHRIL_BLOCK, "秘银块");
        translationBuilder.add(AtBlocks.MITHRIL_ORE, "秘银矿");
        translationBuilder.add(AtBlocks.SILVER_BARS, "银栏杆");
        translationBuilder.add(AtBlocks.SILVER_BLOCK, "银块");
        translationBuilder.add(AtBlocks.SILVER_ORE, "银矿");
        translationBuilder.add(AtBlocks.MANTLE, "地幔");
        translationBuilder.add(AtBlocks.COPPER_BARS, "铜栏杆");

        translationBuilder.add(AtItems.ADAMANTIUM_BUCKET,"艾德曼桶");
        translationBuilder.add(AtItems.LAVA_ADAMANTIUM_BUCKET, "装满熔岩的艾德曼桶");
        translationBuilder.add(AtItems.WATER_ADAMANTIUM_BUCKET, "装满水的艾德曼桶");
        translationBuilder.add(AtItems.POWDER_SNOW_ADAMANTIUM_BUCKET, "装满细雪的艾德曼桶");
        translationBuilder.add(AtItems.MILK_ADAMANTIUM_BUCKET, "装满牛奶的艾德曼桶");
        translationBuilder.add(AtItems.PUFFERFISH_ADAMANTIUM_BUCKET, "装有河豚的艾德曼桶");
        translationBuilder.add(AtItems.SALMON_ADAMANTIUM_BUCKET, "装有鲑鱼的艾德曼桶");
        translationBuilder.add(AtItems.COD_ADAMANTIUM_BUCKET, "装有鳕鱼的艾德曼桶");
        translationBuilder.add(AtItems.TROPICAL_FISH_ADAMANTIUM_BUCKET, "装有热带鱼的艾德曼桶");
        translationBuilder.add(AtItems.AXOLOTL_ADAMANTIUM_BUCKET, "装有美西螈的艾德曼桶");
        translationBuilder.add(AtItems.TADPOLE_ADAMANTIUM_BUCKET, "装有蝌蚪的艾德曼桶");

        translationBuilder.add(AtItems.ANCIENT_METAL_BUCKET,"远古金属桶");
        translationBuilder.add(AtItems.LAVA_ANCIENT_METAL_BUCKET, "装满熔岩的远古金属桶");
        translationBuilder.add(AtItems.WATER_ANCIENT_METAL_BUCKET, "装满水的远古金属桶");
        translationBuilder.add(AtItems.POWDER_SNOW_ANCIENT_METAL_BUCKET, "装满细雪的远古金属桶");
        translationBuilder.add(AtItems.MILK_ANCIENT_METAL_BUCKET, "装满牛奶的远古金属桶");
        translationBuilder.add(AtItems.PUFFERFISH_ANCIENT_METAL_BUCKET, "装有河豚的远古金属桶");
        translationBuilder.add(AtItems.SALMON_ANCIENT_METAL_BUCKET, "装有鲑鱼的远古金属桶");
        translationBuilder.add(AtItems.COD_ANCIENT_METAL_BUCKET, "装有鳕鱼的远古金属桶");
        translationBuilder.add(AtItems.TROPICAL_FISH_ANCIENT_METAL_BUCKET, "装有热带鱼的远古金属桶");
        translationBuilder.add(AtItems.AXOLOTL_ANCIENT_METAL_BUCKET, "装有美西螈的远古金属桶");
        translationBuilder.add(AtItems.TADPOLE_ANCIENT_METAL_BUCKET, "装有蝌蚪的远古金属桶");

        translationBuilder.add(AtItems.COPPER_BUCKET,"铜桶");
        translationBuilder.add(AtItems.LAVA_COPPER_BUCKET, "装满熔岩的铜桶");
        translationBuilder.add(AtItems.WATER_COPPER_BUCKET, "装满水的铜桶");
        translationBuilder.add(AtItems.POWDER_SNOW_COPPER_BUCKET, "装满细雪的铜桶");
        translationBuilder.add(AtItems.MILK_COPPER_BUCKET, "装满牛奶的铜桶");
        translationBuilder.add(AtItems.PUFFERFISH_COPPER_BUCKET, "装有河豚的铜桶");
        translationBuilder.add(AtItems.SALMON_COPPER_BUCKET, "装有鲑鱼的铜桶");
        translationBuilder.add(AtItems.COD_COPPER_BUCKET, "装有鳕鱼的铜桶");
        translationBuilder.add(AtItems.TROPICAL_FISH_COPPER_BUCKET, "装有热带鱼的铜桶");
        translationBuilder.add(AtItems.AXOLOTL_COPPER_BUCKET, "装有美西螈的铜桶");
        translationBuilder.add(AtItems.TADPOLE_COPPER_BUCKET, "装有蝌蚪的铜桶");

        translationBuilder.add(AtItems.GOLD_BUCKET,"金桶");
        translationBuilder.add(AtItems.LAVA_GOLD_BUCKET, "装满熔岩的金桶");
        translationBuilder.add(AtItems.WATER_GOLD_BUCKET, "装满水的金桶");
        translationBuilder.add(AtItems.POWDER_SNOW_GOLD_BUCKET, "装满细雪的金桶");
        translationBuilder.add(AtItems.MILK_GOLD_BUCKET, "装满牛奶的金桶");
        translationBuilder.add(AtItems.PUFFERFISH_GOLD_BUCKET, "装有河豚的金桶");
        translationBuilder.add(AtItems.SALMON_GOLD_BUCKET, "装有鲑鱼的金桶");
        translationBuilder.add(AtItems.COD_GOLD_BUCKET, "装有鳕鱼的金桶");
        translationBuilder.add(AtItems.TROPICAL_FISH_GOLD_BUCKET, "装有热带鱼的金桶");
        translationBuilder.add(AtItems.AXOLOTL_GOLD_BUCKET, "装有美西螈的金桶");
        translationBuilder.add(AtItems.TADPOLE_GOLD_BUCKET, "装有蝌蚪的金桶");

        translationBuilder.add(AtItems.MITHRIL_BUCKET,"秘银桶");
        translationBuilder.add(AtItems.LAVA_MITHRIL_BUCKET, "装满熔岩的秘银桶");
        translationBuilder.add(AtItems.WATER_MITHRIL_BUCKET, "装满水的秘银桶");
        translationBuilder.add(AtItems.POWDER_SNOW_MITHRIL_BUCKET, "装满细雪的秘银桶");
        translationBuilder.add(AtItems.MILK_MITHRIL_BUCKET, "装满牛奶的秘银桶");
        translationBuilder.add(AtItems.PUFFERFISH_MITHRIL_BUCKET, "装有河豚的秘银桶");
        translationBuilder.add(AtItems.SALMON_MITHRIL_BUCKET, "装有鲑鱼的秘银桶");
        translationBuilder.add(AtItems.COD_MITHRIL_BUCKET, "装有鳕鱼的秘银桶");
        translationBuilder.add(AtItems.TROPICAL_FISH_MITHRIL_BUCKET, "装有热带鱼的秘银桶");
        translationBuilder.add(AtItems.AXOLOTL_MITHRIL_BUCKET, "装有美西螈的秘银桶");
        translationBuilder.add(AtItems.TADPOLE_MITHRIL_BUCKET, "装有蝌蚪的秘银桶");

        translationBuilder.add(AtItems.SILVER_BUCKET,"银桶");
        translationBuilder.add(AtItems.LAVA_SILVER_BUCKET, "装满熔岩的银桶");
        translationBuilder.add(AtItems.WATER_SILVER_BUCKET, "装满水的银桶");
        translationBuilder.add(AtItems.POWDER_SNOW_SILVER_BUCKET, "装满细雪的银桶");
        translationBuilder.add(AtItems.MILK_SILVER_BUCKET, "装满牛奶的银桶");
        translationBuilder.add(AtItems.PUFFERFISH_SILVER_BUCKET, "装有河豚的银桶");
        translationBuilder.add(AtItems.SALMON_SILVER_BUCKET, "装有鲑鱼的银桶");
        translationBuilder.add(AtItems.COD_SILVER_BUCKET, "装有鳕鱼的银桶");
        translationBuilder.add(AtItems.TROPICAL_FISH_SILVER_BUCKET, "装有热带鱼的银桶");
        translationBuilder.add(AtItems.AXOLOTL_SILVER_BUCKET, "装有美西螈的银桶");
        translationBuilder.add(AtItems.TADPOLE_SILVER_BUCKET, "装有蝌蚪的银桶");

        translationBuilder.add(AtItems.NETHERITE_BUCKET,"下界合金桶");
        translationBuilder.add(AtItems.LAVA_NETHERITE_BUCKET, "装满熔岩的下界合金桶");
        translationBuilder.add(AtItems.WATER_NETHERITE_BUCKET, "装满水的下界合金桶");
        translationBuilder.add(AtItems.POWDER_SNOW_NETHERITE_BUCKET, "装满细雪的下界合金桶");
        translationBuilder.add(AtItems.MILK_NETHERITE_BUCKET, "装满牛奶的下界合金桶");
        translationBuilder.add(AtItems.PUFFERFISH_NETHERITE_BUCKET, "装有河豚的下界合金桶");
        translationBuilder.add(AtItems.SALMON_NETHERITE_BUCKET, "装有鲑鱼的下界合金桶");
        translationBuilder.add(AtItems.COD_NETHERITE_BUCKET, "装有鳕鱼的下界合金桶");
        translationBuilder.add(AtItems.TROPICAL_FISH_NETHERITE_BUCKET, "装有热带鱼的下界合金桶");
        translationBuilder.add(AtItems.AXOLOTL_NETHERITE_BUCKET, "装有美西螈的下界合金桶");
        translationBuilder.add(AtItems.TADPOLE_NETHERITE_BUCKET, "装有蝌蚪的下界合金桶");

        translationBuilder.add(AtItems.MITHRIL_BOW,"秘银弓");
        translationBuilder.add(AtItems.ANCIENT_METAL_BOW,"远古金属弓");

        translationBuilder.add(AtBlocks.ADAMANTIUM_DOOR, "艾德曼门");
        translationBuilder.add(AtBlocks.ANCIENT_METAL_DOOR, "远古金属门");
        translationBuilder.add(AtBlocks.MITHRIL_DOOR, "秘银门");
        translationBuilder.add(AtBlocks.SILVER_DOOR, "银门");
        translationBuilder.add(AtBlocks.GOLD_DOOR, "金门");

        translationBuilder.add(AtItems.ADAMANTIUM_FISHING_ROD, "艾德曼鱼竿");
        translationBuilder.add(AtItems.ANCIENT_METAL_FISHING_ROD, "远古金属鱼竿");
        translationBuilder.add(AtItems.MITHRIL_FISHING_ROD, "秘银鱼竿");
        translationBuilder.add(AtItems.SILVER_FISHING_ROD, "银鱼竿");
        translationBuilder.add(AtItems.GOLD_FISHING_ROD, "金鱼竿");
        translationBuilder.add(AtItems.COPPER_FISHING_ROD, "铜鱼竿");
        translationBuilder.add(AtItems.IRON_FISHING_ROD, "铁鱼竿");
        translationBuilder.add(AtItems.FLINT_FISHING_ROD, "燧石鱼竿");
        translationBuilder.add(AtItems.OBSIDIAN_FISHING_ROD, "黑曜石鱼竿");

        translationBuilder.add(AtItems.ADAMANTIUM_INGOT, "艾德曼锭");
        translationBuilder.add(AtItems.ANCIENT_METAL_INGOT, "远古金属锭");
        translationBuilder.add(AtItems.MITHRIL_INGOT, "秘银锭");
        translationBuilder.add(AtItems.SILVER_INGOT, "银锭");

        translationBuilder.add(AtItems.ADAMANTIUM_NUGGET, "艾德曼粒");
        translationBuilder.add(AtItems.ANCIENT_METAL_NUGGET, "远古金属粒");
        translationBuilder.add(AtItems.MITHRIL_NUGGET, "秘银粒");
        translationBuilder.add(AtItems.SILVER_NUGGET, "银粒");

        translationBuilder.add(AtItems.DIAMOND_SHARD, "钻石碎片");
        translationBuilder.add(AtItems.EMERALD_SHARD, "绿宝石碎片");
        translationBuilder.add(AtItems.FLINT_SHARD, "燧石碎片");
        translationBuilder.add(AtItems.GLASS_SHARD, "玻璃碎片");
        translationBuilder.add(AtItems.OBSIDIAN_SHARD, "黑曜石碎片");
        translationBuilder.add(AtItems.QUARTZ_SHARD, "石英碎片");

        translationBuilder.add(AtBlocks.ADAMANTIUM_ANVIL,"艾德曼砧");
        translationBuilder.add(AtBlocks.CHIPPED_ADAMANTIUM_ANVIL,"开裂的艾德曼砧");
        translationBuilder.add(AtBlocks.DAMAGED_ADAMANTIUM_ANVIL,"损坏的艾德曼砧");
    }
}
