package com.acuteterror233.mite.datagen;

import com.acuteterror233.mite.item.At_Items;
import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricLanguageProvider;
import net.minecraft.registry.RegistryWrapper;

import java.util.concurrent.CompletableFuture;

public class Zh_cnLanguageProvider extends FabricLanguageProvider {

    public Zh_cnLanguageProvider(FabricDataOutput dataOutput, CompletableFuture<RegistryWrapper.WrapperLookup> registryLookup) {
        super(dataOutput, "zh_cn", registryLookup);
    }

    @Override
    public void generateTranslations(RegistryWrapper.WrapperLookup wrapperLookup, TranslationBuilder translationBuilder) {
        translationBuilder.add("itemGroup.at_mite.item_group","Minecraft实在是太简单了!");
        translationBuilder.add(At_Items.ADAMANTIUM_HELMET,"艾德曼头盔");
        translationBuilder.add(At_Items.ADAMANTIUM_CHESTPLATE,"艾德曼胸甲");
        translationBuilder.add(At_Items.ADAMANTIUM_LEGGINGS,"艾德曼护腿");
        translationBuilder.add(At_Items.ADAMANTIUM_BOOTS,"艾德曼靴子");
        translationBuilder.add(At_Items.ADAMANTIUM_CHAINMAIL_HELMET,"艾德曼锁链头盔");
        translationBuilder.add(At_Items.ADAMANTIUM_CHAINMAIL_CHESTPLATE,"艾德曼锁链胸甲");
        translationBuilder.add(At_Items.ADAMANTIUM_CHAINMAIL_LEGGINGS,"艾德曼锁链护腿");
        translationBuilder.add(At_Items.ADAMANTIUM_CHAINMAIL_BOOTS,"艾德曼锁链靴子");
        translationBuilder.add(At_Items.ANCIENT_METAL_HELMET,"远古金属头盔");
        translationBuilder.add(At_Items.ANCIENT_METAL_CHESTPLATE,"远古金属胸甲");
        translationBuilder.add(At_Items.ANCIENT_METAL_LEGGINGS,"远古金属护腿");
        translationBuilder.add(At_Items.ANCIENT_METAL_BOOTS,"远古金属靴子");
        translationBuilder.add(At_Items.ANCIENT_METAL_CHAINMAIL_HELMET,"远古金属锁链头盔");
        translationBuilder.add(At_Items.ANCIENT_METAL_CHAINMAIL_CHESTPLATE,"远古金属锁链胸甲");
        translationBuilder.add(At_Items.ANCIENT_METAL_CHAINMAIL_LEGGINGS,"远古金属锁链护腿");
        translationBuilder.add(At_Items.ANCIENT_METAL_CHAINMAIL_BOOTS,"远古金属锁链靴子");
        translationBuilder.add(At_Items.COPPER_HELMET,"铜头盔");
        translationBuilder.add(At_Items.COPPER_CHESTPLATE,"铜胸甲");
        translationBuilder.add(At_Items.COPPER_LEGGINGS,"铜护腿");
        translationBuilder.add(At_Items.COPPER_BOOTS,"铜靴子");
        translationBuilder.add(At_Items.COPPER_CHAINMAIL_HELMET,"铜锁链头盔");
        translationBuilder.add(At_Items.COPPER_CHAINMAIL_CHESTPLATE,"铜锁链胸甲");
        translationBuilder.add(At_Items.COPPER_CHAINMAIL_LEGGINGS,"铜锁链护腿");
        translationBuilder.add(At_Items.COPPER_CHAINMAIL_BOOTS,"铜锁链靴子");
        translationBuilder.add(At_Items.MITHRIL_HELMET,"秘银头盔");
        translationBuilder.add(At_Items.MITHRIL_CHESTPLATE,"秘银胸甲");
        translationBuilder.add(At_Items.MITHRIL_LEGGINGS,"秘银护腿");
        translationBuilder.add(At_Items.MITHRIL_BOOTS,"秘银靴子");
        translationBuilder.add(At_Items.MITHRIL_CHAINMAIL_HELMET,"秘银锁链头盔");
        translationBuilder.add(At_Items.MITHRIL_CHAINMAIL_CHESTPLATE,"秘银锁链胸甲");
        translationBuilder.add(At_Items.MITHRIL_CHAINMAIL_LEGGINGS,"秘银锁链护腿");
        translationBuilder.add(At_Items.MITHRIL_CHAINMAIL_BOOTS,"秘银锁链靴子");
        translationBuilder.add(At_Items.RUSTED_IRON_HELMET, "锈铁头盔");
        translationBuilder.add(At_Items.RUSTED_IRON_CHESTPLATE, "锈铁胸甲");
        translationBuilder.add(At_Items.RUSTED_IRON_LEGGINGS, "锈铁护腿");
        translationBuilder.add(At_Items.RUSTED_IRON_BOOTS, "锈铁靴子");
        translationBuilder.add(At_Items.RUSTED_IRON_CHAINMAIL_HELMET, "锈铁锁链头盔");
        translationBuilder.add(At_Items.RUSTED_IRON_CHAINMAIL_CHESTPLATE, "锈铁锁链胸甲");
        translationBuilder.add(At_Items.RUSTED_IRON_CHAINMAIL_LEGGINGS, "锈铁锁链护腿");
        translationBuilder.add(At_Items.RUSTED_IRON_CHAINMAIL_BOOTS, "锈铁锁链靴子");
        translationBuilder.add(At_Items.SILVER_HELMET, "银头盔");
        translationBuilder.add(At_Items.SILVER_CHESTPLATE, "银胸甲");
        translationBuilder.add(At_Items.SILVER_LEGGINGS, "银护腿");
        translationBuilder.add(At_Items.SILVER_BOOTS, "银靴子");
        translationBuilder.add(At_Items.SILVER_CHAINMAIL_HELMET, "银锁链头盔");
        translationBuilder.add(At_Items.SILVER_CHAINMAIL_CHESTPLATE, "银锁链胸甲");
        translationBuilder.add(At_Items.SILVER_CHAINMAIL_LEGGINGS, "银锁链护腿");
        translationBuilder.add(At_Items.SILVER_CHAINMAIL_BOOTS, "银锁链靴子");

        translationBuilder.add(At_Items.BANANA, "香蕉");
        translationBuilder.add(At_Items.BLUEBERRIE, "蓝莓");
        translationBuilder.add(At_Items.CHEESE, "奶酪");
        translationBuilder.add(At_Items.CHOCOLATE, "巧克力");
        translationBuilder.add(At_Items.DOUGH, "面团");
        translationBuilder.add(At_Items.ONION, "洋葱");
        translationBuilder.add(At_Items.LEMON, "柠檬");
        translationBuilder.add(At_Items.ORANGE, "橘子");
        translationBuilder.add(At_Items.WORM_COOKED, "烤熟的虫子");
        translationBuilder.add(At_Items.WORM_RAW, "生的虫子");
        translationBuilder.add(At_Items.BEEF_STEW, "炖牛肉");
        translationBuilder.add(At_Items.BOWL_MILK, "一碗牛奶");
        translationBuilder.add(At_Items.BOWL_SALAD, "一碗沙拉");
        translationBuilder.add(At_Items.BOWL_WATER, "一碗水");
        translationBuilder.add(At_Items.CEREAL, "麦片");
        translationBuilder.add(At_Items.CHICKEN_SOUP, "鸡汤");
        translationBuilder.add(At_Items.CREAM_OF_MUSHROOM_SOUP, "奶油蘑菇汤");
        translationBuilder.add(At_Items.CREAM_OF_VEGETABLE_SOUP, "奶油蔬菜汤");
        translationBuilder.add(At_Items.ICE_CREAM, "冰淇淋");
        translationBuilder.add(At_Items.MASHED_POTATO, "土豆泥");
        translationBuilder.add(At_Items.MUSHROOM_STEW, "蘑菇炖汤");
        translationBuilder.add(At_Items.PORRIDGE, "粥");
        translationBuilder.add(At_Items.PUMPKIN_SOUP, "南瓜汤");
        translationBuilder.add(At_Items.SORBET, "雪糕");
        translationBuilder.add(At_Items.VEGETABLE_SOUP, "蔬菜汤");


        translationBuilder.add(At_Items.ADAMANTIUM_ARROW, "艾德曼箭");
        translationBuilder.add(At_Items.ANCIENT_METAL_ARROW, "远古金属箭");
        translationBuilder.add(At_Items.COPPER_ARROW, "铜箭");
        translationBuilder.add(At_Items.MITHRIL_ARROW, "秘银箭");
        translationBuilder.add(At_Items.RUSTED_IRON_ARROW, "锈铁箭");
        translationBuilder.add(At_Items.SILVER_ARROW, "银箭");
        translationBuilder.add(At_Items.FLINT_ARROW, "燧石箭");
        translationBuilder.add(At_Items.GOLD_ARROW, "金箭");
        translationBuilder.add(At_Items.IRON_ARROW, "铁箭");
        translationBuilder.add(At_Items.OBSIDIAN_ARROW, "黑曜石箭");

        translationBuilder.add(At_Items.ADAMANTIUM_AXE, "艾德曼斧");
        translationBuilder.add(At_Items.ADAMANTIUM_BATTLE_AXE, "艾德曼战斧");
        translationBuilder.add(At_Items.ADAMANTIUM_DAGGER, "艾德曼匕首");
        translationBuilder.add(At_Items.ADAMANTIUM_HATCHET, "艾德曼短斧");
        translationBuilder.add(At_Items.ADAMANTIUM_HOE, "艾德曼锄头");
        translationBuilder.add(At_Items.ADAMANTIUM_KNIFE, "艾德曼小刀");
        translationBuilder.add(At_Items.ADAMANTIUM_MATTOCK, "艾德曼鹤嘴锄");
        translationBuilder.add(At_Items.ADAMANTIUM_PICKAXE, "艾德曼镐");
        translationBuilder.add(At_Items.ADAMANTIUM_SCYTHE, "艾德曼镰刀");
        translationBuilder.add(At_Items.ADAMANTIUM_SHEARS, "艾德曼剪刀");
        translationBuilder.add(At_Items.ADAMANTIUM_SHOVEL, "艾德曼铲子");
        translationBuilder.add(At_Items.ADAMANTIUM_SWORD, "艾德曼剑");
        translationBuilder.add(At_Items.ADAMANTIUM_WAR_HAMMER, "艾德曼战锤");
        translationBuilder.add(At_Items.ANCIENT_METAL_AXE, "远古金属斧");
        translationBuilder.add(At_Items.ANCIENT_METAL_BATTLE_AXE, "远古金属战斧");
        translationBuilder.add(At_Items.ANCIENT_METAL_DAGGER, "远古金属匕首");
        translationBuilder.add(At_Items.ANCIENT_METAL_HATCHET, "远古金属短斧");
        translationBuilder.add(At_Items.ANCIENT_METAL_HOE, "远古金属锄头");
        translationBuilder.add(At_Items.ANCIENT_METAL_KNIFE, "远古金属小刀");
        translationBuilder.add(At_Items.ANCIENT_METAL_MATTOCK, "远古金属鹤嘴锄");
        translationBuilder.add(At_Items.ANCIENT_METAL_PICKAXE, "远古金属镐");
        translationBuilder.add(At_Items.ANCIENT_METAL_SCYTHE, "远古金属镰刀");
        translationBuilder.add(At_Items.ANCIENT_METAL_SHEARS, "远古金属剪刀");
        translationBuilder.add(At_Items.ANCIENT_METAL_SHOVEL, "远古金属铲子");
        translationBuilder.add(At_Items.ANCIENT_METAL_SWORD, "远古金属剑");
        translationBuilder.add(At_Items.ANCIENT_METAL_WAR_HAMMER, "远古金属战锤");
        translationBuilder.add(At_Items.COPPER_AXE, "铜斧");
        translationBuilder.add(At_Items.COPPER_BATTLE_AXE, "铜战斧");
        translationBuilder.add(At_Items.COPPER_DAGER, "铜匕首");
        translationBuilder.add(At_Items.COPPER_HATCHET, "铜短斧");
        translationBuilder.add(At_Items.COPPER_HOE, "铜锄头");
        translationBuilder.add(At_Items.COPPER_KNIFE, "铜小刀");
        translationBuilder.add(At_Items.COPPER_MATTOCK, "铜鹤嘴锄");
        translationBuilder.add(At_Items.COPPER_PICKAXE, "铜镐");
        translationBuilder.add(At_Items.COPPER_SCYTHE, "铜镰刀");
        translationBuilder.add(At_Items.COPPER_SHEARS, "铜剪刀");
        translationBuilder.add(At_Items.COPPER_SHOVEL, "铜铲子");
        translationBuilder.add(At_Items.COPPER_SWORD, "铜剑");
        translationBuilder.add(At_Items.COPPER_WAR_HAMMER, "铜战锤");
        translationBuilder.add(At_Items.FLINT_AXE, "燧石斧");
        translationBuilder.add(At_Items.FLINT_HATCHET, "燧石短斧");
        translationBuilder.add(At_Items.FLINT_KNIFE, "燧石小刀");
        translationBuilder.add(At_Items.FLINT_SHOVEL, "燧石铲子");
        translationBuilder.add(At_Items.GOLD_AXE, "金斧");
        translationBuilder.add(At_Items.GOLD_BATTLE_AXE, "金战斧");
        translationBuilder.add(At_Items.GOLD_DAGER, "金匕首");
        translationBuilder.add(At_Items.GOLD_HATCHET, "金短斧");
        translationBuilder.add(At_Items.GOLD_HOE, "金锄头");
        translationBuilder.add(At_Items.GOLD_KNIFE, "金小刀");
        translationBuilder.add(At_Items.GOLD_MATTOCK, "金鹤嘴锄");
        translationBuilder.add(At_Items.GOLD_PICKAXE, "金镐");
        translationBuilder.add(At_Items.GOLD_SCYTHE, "金镰刀");
        translationBuilder.add(At_Items.GOLD_SHEARS, "金剪刀");
        translationBuilder.add(At_Items.GOLD_SHOVEL, "金铲子");
        translationBuilder.add(At_Items.GOLD_SWORD, "金剑");
        translationBuilder.add(At_Items.GOLD_WAR_HAMMER, "金战锤");
        translationBuilder.add(At_Items.IRON_BATTLE_AXE, "铁战斧");
        translationBuilder.add(At_Items.IRON_DAGER, "铁匕首");
        translationBuilder.add(At_Items.IRON_HATCHET, "铁短斧");
        translationBuilder.add(At_Items.IRON_KNIFE, "铁小刀");
        translationBuilder.add(At_Items.IRON_MATTOCK, "铁鹤嘴锄");
        translationBuilder.add(At_Items.IRON_SCYTHE, "铁镰刀");
        translationBuilder.add(At_Items.IRON_WAR_HAMMER, "铁战锤");
        translationBuilder.add(At_Items.MITHRIL_AXE, "秘银斧");
        translationBuilder.add(At_Items.MITHRIL_BATTLE_AXE, "秘银战斧");
        translationBuilder.add(At_Items.MITHRIL_DAGER, "秘银匕首");
        translationBuilder.add(At_Items.MITHRIL_HATCHET, "秘银短斧");
        translationBuilder.add(At_Items.MITHRIL_HOE, "秘银锄头");
        translationBuilder.add(At_Items.MITHRIL_KNIFE, "秘银小刀");
        translationBuilder.add(At_Items.MITHRIL_MATTOCK, "秘银鹤嘴锄");
        translationBuilder.add(At_Items.MITHRIL_PICKAXE, "秘银镐");
        translationBuilder.add(At_Items.MITHRIL_SCYTHE, "秘银镰刀");
        translationBuilder.add(At_Items.MITHRIL_SHEARS, "秘银剪刀");
        translationBuilder.add(At_Items.MITHRIL_SHOVEL, "秘银铲子");
        translationBuilder.add(At_Items.MITHRIL_SWORD, "秘银剑");
        translationBuilder.add(At_Items.MITHRIL_WAR_HAMMER, "秘银战锤");
        translationBuilder.add(At_Items.OBSIDIAN_AXE, "黑曜石斧");
        translationBuilder.add(At_Items.OBSIDIAN_HATCHET, "黑曜石短斧");
        translationBuilder.add(At_Items.OBSIDIAN_KNIFE, "黑曜石小刀");
        translationBuilder.add(At_Items.OBSIDIAN_SHOVEL, "黑曜石铲子");
        translationBuilder.add(At_Items.RUSTED_IRON_AXE, "锈铁斧");
        translationBuilder.add(At_Items.RUSTED_IRON_BATTLE_AXE, "锈铁战斧");
        translationBuilder.add(At_Items.RUSTED_IRON_DAGER, "锈铁匕首");
        translationBuilder.add(At_Items.RUSTED_IRON_HATCHET, "锈铁短斧");
        translationBuilder.add(At_Items.RUSTED_IRON_HOE, "锈铁锄头");
        translationBuilder.add(At_Items.RUSTED_IRON_KNIFE, "锈铁小刀");
        translationBuilder.add(At_Items.RUSTED_IRON_MATTOCK, "锈铁鹤嘴锄");
        translationBuilder.add(At_Items.RUSTED_IRON_PICKAXE, "锈铁镐");
        translationBuilder.add(At_Items.RUSTED_IRON_SCYTHE, "锈铁镰刀");
        translationBuilder.add(At_Items.RUSTED_IRON_SHEARS, "锈铁剪刀");
        translationBuilder.add(At_Items.RUSTED_IRON_SHOVEL, "锈铁铲子");
        translationBuilder.add(At_Items.RUSTED_IRON_SWORD, "锈铁剑");
        translationBuilder.add(At_Items.RUSTED_IRON_WAR_HAMMER, "锈铁战锤");
        translationBuilder.add(At_Items.SILVER_AXE, "银斧");
        translationBuilder.add(At_Items.SILVER_BATTLE_AXE, "银战斧");
        translationBuilder.add(At_Items.SILVER_DAGER, "银匕首");
        translationBuilder.add(At_Items.SILVER_HATCHET, "银短斧");
        translationBuilder.add(At_Items.SILVER_HOE, "银锄头");
        translationBuilder.add(At_Items.SILVER_KNIFE, "银小刀");
        translationBuilder.add(At_Items.SILVER_MATTOCK, "银鹤嘴锄");
        translationBuilder.add(At_Items.SILVER_PICKAXE, "银镐");
        translationBuilder.add(At_Items.SILVER_SCYTHE, "银镰刀");
        translationBuilder.add(At_Items.SILVER_SHEARS, "银剪刀");
        translationBuilder.add(At_Items.SILVER_SHOVEL, "银铲子");
        translationBuilder.add(At_Items.SILVER_SWORD, "银剑");
        translationBuilder.add(At_Items.SILVER_WAR_HAMMER, "银战锤");
        translationBuilder.add(At_Items.STONE_DAGER, "石匕首");
        translationBuilder.add(At_Items.WOOD_CLUB, "木棒");
        translationBuilder.add(At_Items.WOOD_CUDGEL,"小木棒");
    }

}
